### ISSUE TITLE
syclcompat/memory/memory_async.cpp failed in post-commit

### ISSUE THREAD

**Issue by KornevNikita** [intel/llvm#13636] opened 2024-05-02 10:34 UTC
### Describe the bug

see: https://github.com/intel/llvm/actions/runs/8921355161/job/24501752365?pr=13601
```
FAIL: SYCL :: syclcompat/memory/memory_async.cpp (2007 of 2020)
******************** TEST 'SYCL :: syclcompat/memory/memory_async.cpp' FAILED ********************
Exit Code: -11

Command Output (stdout):
--
# RUN: at line 33
/__w/llvm/llvm/toolchain/bin//clang++   -std=c++20 -fsycl -fsycl-targets=spir64 /__w/llvm/llvm/llvm/sycl/test-e2e/syclcompat/memory/memory_async.cpp -o /__w/llvm/llvm/build-e2e/syclcompat/memory/Output/memory_async.cpp.tmp.out
# executed command: /__w/llvm/llvm/toolchain/bin//clang++ -std=c++20 -fsycl -fsycl-targets=spir64 /__w/llvm/llvm/llvm/sycl/test-e2e/syclcompat/memory/memory_async.cpp -o /__w/llvm/llvm/build-e2e/syclcompat/memory/Output/memory_async.cpp.tmp.out
# .---command stderr------------
# | In file included from /__w/llvm/llvm/llvm/sycl/test-e2e/syclcompat/memory/memory_async.cpp:42:
# | In file included from /__w/llvm/llvm/toolchain/bin/../include/syclcompat/memory.hpp:53:
# | /__w/llvm/llvm/toolchain/bin/../include/syclcompat/device.hpp:348:2: warning: "Querying the number of bytes of free memory is not supported" [-W#warnings]
# |   348 | #warning "Querying the number of bytes of free memory is not supported"
# |       |  ^
# | 1 warning generated.
# | In file included from /__w/llvm/llvm/llvm/sycl/test-e2e/syclcompat/memory/memory_async.cpp:42:
# | In file included from /__w/llvm/llvm/toolchain/bin/../include/syclcompat/memory.hpp:53:
# | /__w/llvm/llvm/toolchain/bin/../include/syclcompat/device.hpp:348:2: warning: "Querying the number of bytes of free memory is not supported" [-W#warnings]
# |   348 | #warning "Querying the number of bytes of free memory is not supported"
# |       |  ^
# | /__w/llvm/llvm/toolchain/bin/../include/syclcompat/device.hpp:406:2: warning: "get_device_info: querying memory_clock_rate and memory_bus_width are not supported by the compiler used. Use [32](https://github.com/intel/llvm/actions/runs/8921355161/job/24501752365?pr=13601#step:21:33)00000 kHz as memory_clock_rate default value. Use 64 bits as memory_bus_width default value." [-W#warnings]
# |   406 | #warning "get_device_info: querying memory_clock_rate and \
# |       |  ^
# | 2 warnings generated.
# `-----------------------------
# RUN: at line [34](https://github.com/intel/llvm/actions/runs/8921355161/job/24501752365?pr=13601#step:21:35)
env ONEAPI_DEVICE_SELECTOR=level_zero:gpu  /__w/llvm/llvm/build-e2e/syclcompat/memory/Output/memory_async.cpp.tmp.out
# executed command: env ONEAPI_DEVICE_SELECTOR=level_zero:gpu /__w/llvm/llvm/build-e2e/syclcompat/memory/Output/memory_async.cpp.tmp.out
# .---command stdout------------
# | void test_free_async()
# | void test_memcpy_async1()
# | void test_memcpy_async2()
# | void test_memcpy_async3()
# | void test_memset_async1()
# `-----------------------------
# error: command failed with exit status: -11
```

**Comment by joeatodd** [comment] 2024-05-03 10:37
We've been investigating this. None of these tests have been touched recently, so I expect we are exposing an issue in UR or L0. I've been unable to reproduce the failure locally on our Arc A770.

It also seems like the failure has stopped occurring :crossed_fingers: though given it's intermittent we can't yet be sure.

For now I'd suggest we wait and see if it continues to occur. If so we will need to look deeper.

**Comment by sarnex** [comment] 2024-07-29 19:50
@joeatodd This is failing again https://github.com/intel/llvm/actions/runs/10150284793/job/28067414470

**Comment by sarnex** [comment] 2024-07-29 19:50
@intel/syclcompat-lib-reviewers FYI

**Comment by joeatodd** [comment] 2024-07-31 10:42
Sorry for delay @sarnex, here's a [PR](https://github.com/intel/llvm/pull/14855) which disables these tests for now, until we can get to the root cause.

**Comment by Alcpz** [comment] 2024-07-31 13:27
Tests disabled for now.

**Comment by joeatodd** [comment] 2024-10-16 09:30
Re-enabled in this [PR](https://github.com/intel/llvm/pull/15683/) (awaiting review)

**Comment by joeatodd** [comment] 2024-10-23 08:55
PR merged, tests passing.

**Closed by joeatodd** 2024-10-23 08:55 UTC
Labels: bug, confirmed, syclcompat
