### ISSUE TITLE
oneMKL open source interfaces: warning with LLVM compiler

### ISSUE THREAD

**Issue by mmeterel** [intel/llvm#5055] opened 2021-11-30 17:57 UTC
**Describe the bug**
When we compile oneMKL open source interfaces repo with LLVM compiler, we see the below warning. We don't see the same warning with DPC++ compiler. 

**warning: Could not determine extension for archivemembers, using ".o"**

**To Reproduce**
Please compile oneMKL open source interfaces with LLVM compiler. 
https://github.com/oneapi-src/oneMKL

We expect to see no warnings. 

**Environment (please complete the following information):**
- OS: Linux. 
- Target device and vendor: Intel GEN9

**Comment by sndmitriev** [comment] 2021-12-01 08:23
This warning as added by the following change https://reviews.llvm.org/D105191 in the upstream llvm. I have prepared a patch to remove it https://reviews.llvm.org/D114776.

**Comment by alexbatashev** [comment] 2022-01-31 18:43
The differential in question was merged. I'm going to close this issue. @mmeterel please, reopen if the issue is not gone.

**Closed by alexbatashev** 2022-01-31 18:43 UTC
Labels: bug
