### ISSUE TITLE
[SYCL] getDeviceLambdaManglingNumber() const: Assertion `isLambda() && "Not a lambda closure type!"' failed.

### ISSUE THREAD

**Issue by zjin-lcf** [intel/llvm#7360] opened 2022-11-10 20:24 UTC
Building the example below using the SYCL compiler with Cuda support shows the error:

/path/to/clang/lib/AST/DeclCXX.cpp:1613: unsigned int clang::CXXRecordDecl::getDeviceLambdaManglingNumber() const: Assertion `isLambda() && "Not a lambda closure type!"'

https://github.com/zjin-lcf/HeCBench/tree/master/vmc-sycl

**Comment by dm-vodopyanov** [comment] 2022-11-30 13:39
Reproduced even on SYCL compiler without CUDA support.

**Comment by Fznamznon** [comment] 2023-01-05 11:30
I have created a fix in #7927, although, it still won't help to compile example. This is because the example passes unnamed struct to `handler::copy` here https://github.com/zjin-lcf/HeCBench/blob/master/vmc-sycl/vmc2.cpp#L310 . Under the hood `handler::copy` creates a kernel and it is implemented in a way so the type of destination pointer ends up being a part of kernel name. Unnamed struct causes this name to be invalid and triggers the following error:
```
llvm/build/bin/../include/sycl/handler.hpp:1279:59: error: unnamed type '__copyAcc2Ptr<float, (unnamed struct at vmc2.cpp:306:5), 1, sycl::ac
cess::mode::read, sycl::access::target::global_buffer, sycl::access::placeholder::false_t>' is invalid; provide a kernel name, or use '-fsycl-unnamed-lambda' to enable unna
med kernel lambdas
      h->kernel_parallel_for<TypesToForward..., Props...>(Args...);
                                                          ^
llvm/build/bin/../include/sycl/handler.hpp:1356:29: note: in instantiation of function template specialization 'sycl::handler::KernelProperti
esUnpackerImpl<>::kernel_parallel_for_unpack<__copyAcc2Ptr<float, (unnamed struct at vmc2.cpp:306:5), 1, sycl::access::mode::read, sycl::access::target::global_buffer, sycl
::access::placeholder::false_t>, sycl::item<1, true>, (lambda at llvm/build/bin/../include/sycl/handler.hpp:797:16), (lambda at /iusers/mpodc
his/source/syclos/llvm/build/bin/../include/sycl/handler.hpp:797:16)>' requested here
          Unpacker.template kernel_parallel_for_unpack<KernelName, ElementType,
                            ^
llvm/build/bin/../include/sycl/handler.hpp:1352:5: note: in instantiation of function template specialization 'sycl::handler::unpack<(lambda
at llvm/build/bin/../include/sycl/handler.hpp:797:16), sycl::ext::oneapi::experimental::properties<std::tuple<>>, false, (lambda at /iusers/m
podchis/source/syclos/llvm/build/bin/../include/sycl/handler.hpp:1355:21)>' requested here
    unpack<KernelType, PropertiesT,
    ^
llvm/build/bin/../include/sycl/handler.hpp:1004:7: note: in instantiation of function template specialization 'sycl::handler::kernel_parallel
_for_wrapper<__copyAcc2Ptr<float, (unnamed struct at vmc2.cpp:306:5), 1, sycl::access::mode::read, sycl::access::target::global_buffer, sycl::access::placeholder::false_t>,
 sycl::item<1, true>, (lambda at llvm/build/bin/../include/sycl/handler.hpp:797:16), sycl::ext::oneapi::experimental::properties<std::tuple<>
>>' requested here
      kernel_parallel_for_wrapper<NameT, TransformedArgType, KernelType,
      ^
llvm/build/bin/../include/sycl/handler.hpp:1996:5: note: in instantiation of function template specialization 'sycl::handler::parallel_for_la
mbda_impl<__copyAcc2Ptr<float, (unnamed struct at vmc2.cpp:306:5), 1, sycl::access::mode::read, sycl::access::target::global_buffer, sycl::access::placeholder::false_t>, (l
ambda at llvm/build/bin/../include/sycl/handler.hpp:797:16), 1, sycl::ext::oneapi::experimental::properties<std::tuple<>>>' requested here
    parallel_for_lambda_impl<KernelName, KernelType, 1, PropertiesT>(
    ^
llvm/build/bin/../include/sycl/handler.hpp:2046:5: note: in instantiation of function template specialization 'sycl::handler::parallel_for<__
copyAcc2Ptr<float, (unnamed struct at vmc2.cpp:306:5), 1, sycl::access::mode::read, sycl::access::target::global_buffer, sycl::access::placeholder::false_t>, (lambda at /iu
sers/mpodchis/source/syclos/llvm/build/bin/../include/sycl/handler.hpp:797:16), sycl::ext::oneapi::experimental::properties<std::tuple<>>>' requested here
    parallel_for<KernelName>(
    ^
llvm/build/bin/../include/sycl/handler.hpp:795:5: note: in instantiation of function template specialization 'sycl::handler::parallel_for<__c
opyAcc2Ptr<float, (unnamed struct at vmc2.cpp:306:5), 1, sycl::access::mode::read, sycl::access::target::global_buffer, sycl::access::placeholder::false_t>, 1, (lambda at /
iusers/mpodchis/source/syclos/llvm/build/bin/../include/sycl/handler.hpp:797:16)>' requested here
    parallel_for<
    ^
```
The obvious w/a is to not use unnamed struct.
The proper solution lays inside SYCL headers implementation, I believe. I suggest filing a separate issue for that.

**Comment by zjin-lcf** [comment] 2023-01-05 14:54
Thank you for explaining the error and your suggestion. 
"The proper solution lays inside SYCL headers implementation, I believe". Is it right the proper solution is to define a named struct ?

**Comment by Fznamznon** [comment] 2023-01-05 15:00
@zjin-lcf , yes, you can use a named struct and that will likely make successful compilation. Even before #7927 is merged.
However there is nothing wrong with example code in general. I believe it cannot be compiled after assertion fix due to a problem in SYCL headers implementation.

**Closed** 2023-01-05 16:07 UTC
Labels: bug, confirmed
