### ISSUE TITLE
buildbot/compile.py does not respect configured build directory

### ISSUE THREAD

**Issue by cgleggett** [intel/llvm#1595] opened 2020-04-27 15:58 UTC
if a build directory is specified via "-o DIR" to the buildbot/configure.py, it is not remembered by the buildbot/compile.py stage, which will try to build in $DPCPP_ROOT/build. The "-o" option must be passed to compile.py as well as configure.py

**Comment by alexbatashev** [comment] 2020-04-28 06:53
@cgleggett isn't it an expected behaviour? For example, one may want to generate both debug and release builds out of the same source tree. You need to specify which one you need to compile right now, and for that reason `-o` is passed to `compile.py`. However, the documentation does not mention `compile.py` options at all, and that is something we can improve.

**Comment by cgleggett** [comment] 2020-04-28 17:47
well, either way, as long as it's consistent ;-}

**Comment by AlexeySachkov** [comment] 2020-12-25 13:52
@cgleggett, @alexbatashev, I've tried to address this documentation issue in #2956 - please take a look and provide your feedback

**Comment by cgleggett** [comment] 2020-12-25 18:57
works for me.

**Comment by AlexeySachkov** [comment] 2020-12-28 08:33
Closing this, since documentation was updated in #2956

**Closed by AlexeySachkov** 2020-12-28 08:33 UTC
