### ISSUE TITLE
[SYCL] Build error with element-wise operation for vector class

### ISSUE THREAD

**Issue by abagusetty** [intel/llvm#6158] opened 2022-05-16 23:40 UTC
**Describe the bug**
Element-wise operations between two different sycl::vec class data-types

**To Reproduce**
```c++
#include <sycl/sycl.hpp>
int main()
{
    sycl::int3 a = {1, 2, 3};
    sycl::double3 b = {3.0, 2.5, 1.2};

    sycl::double3 result_add, result_sub, result_mul, result_div;

    result_add = a + b;
    result_sub = a - b;
    result_mul = a * b;
    result_div = a / b;    

    // WORKS!!
    // result.x() = a.x() * b.x();
    // result.y() = a.y() * b.y();
    // result.z() = a.z() * b.z();    

    std::cout << "Result (add) : " << result_add.x() << ", " << result_add.y() << ", " << result_add.z() << std::endl;
    std::cout << "Result (sub) : " << result_sub.x() << ", " << result_sub.y() << ", " << result_sub.z() << std::endl;    
    std::cout << "Result (mul) : " << result_mul.x() << ", " << result_mul.y() << ", " << result_mul.z() << std::endl;    
    std::cout << "Result (div) : " << result_div.x() << ", " << result_div.y() << ", " << result_div.z() << std::endl;
    
    return 0;
}
```
**Errors**
```bash
abagusetty@iris09:~/soft/sycl_vectorn$ dpcpp sycl_operatorx.cpp
sycl_operatorx.cpp:10:20: error: cannot convert between vector values of different size ('sycl::vec<int, 3>::vector_t' (aka 'int __attribute__((ext_vector_type(3)))') and 'sycl::vec<double, 3>::vector_t' (aka 'double __attribute__((ext_vector_type(3)))'))
    result_add = a + b;
                 ~ ^ ~
sycl_operatorx.cpp:11:20: error: cannot convert between vector values of different size ('sycl::vec<int, 3>::vector_t' (aka 'int __attribute__((ext_vector_type(3)))') and 'sycl::vec<double, 3>::vector_t' (aka 'double __attribute__((ext_vector_type(3)))'))
    result_sub = a - b;
                 ~ ^ ~
sycl_operatorx.cpp:12:20: error: cannot convert between vector values of different size ('sycl::vec<int, 3>::vector_t' (aka 'int __attribute__((ext_vector_type(3)))') and 'sycl::vec<double, 3>::vector_t' (aka 'double __attribute__((ext_vector_type(3)))'))
    result_mul = a * b;
                 ~ ^ ~
sycl_operatorx.cpp:13:20: error: cannot convert between vector values of different size ('sycl::vec<int, 3>::vector_t' (aka 'int __attribute__((ext_vector_type(3)))') and 'sycl::vec<double, 3>::vector_t' (aka 'double __attribute__((ext_vector_type(3)))'))
    result_div = a / b;    
                 ~ ^ ~
4 errors generated.
```

**Environment (please complete the following information):**
- Target device and vendor: Intel Gen9
- DPC++ version: Intel(R) oneAPI DPC++/C++ Compiler 2022.1.0 (2022.x.0.20211027)

**Comment by zjin-lcf** [comment] 2022-05-26 02:04
Does OpenCL support vector operations with different data types ?

**Comment by AlexeySachkov** [comment] 2022-08-17 16:16
Hi, @abagusetty,

> Element-wise operations between two different sycl::vec class data-types

I doubt that this is really a bug, it seems to me that this is SYCL spec not being clear about what is supported and what is not. [Table 144](https://registry.khronos.org/SYCL/specs/sycl-2020/html/sycl-2020.html#table.functions.vec) defines those operators as:
```
vec operatorOP(const vec &lhs, const vec &rhs)
```

Even though it is not clearly stated, I believe that the idea is that both argument and return value have the same type, i.e. the same amount of elements and element type. Tagging @gmlueck here to comment as well.

@zjin-lcf,

> Does OpenCL support vector operations with different data types ?

AFAIK, no

**Comment by gmlueck** [comment] 2022-08-17 16:58
> Even though it is not clearly stated, I believe that the idea is that both argument and return value have the same type, i.e. the same amount of elements and element type. Tagging @gmlueck here to comment as well.

I think this is clear in the spec.  Here is what it says:

```
template <typename DataT, int NumElements>
class vec {
  // ...
  friend vec operatorOP(const vec &lhs, const vec &rhs)
};
```

By standard C++ rules `vec` in this context represents the instantiated class type `vec`, which includes the specific template parameters.  Therefore, both parameters have the same type, and this is the same as the return type.

**Comment by AlexeySachkov** [comment] 2022-08-18 11:26
> By standard C++ rules vec in this context represents the instantiated class type vec, which includes the specific template parameters. Therefore, both parameters have the same type, and this is the same as the return type.

Thanks, @gmlueck, I just wasn't aware of that.

@abagusetty, I'm closing this one as not a bug. If you think that SYCL spec should support operations on vectors of different types, please open an issue against the spec itself here: [KhronosGroup/SYCL-Docs](https://github.com/KhronosGroup/SYCL-Docs)

**Closed by AlexeySachkov** 2022-08-18 11:26 UTC
Labels: bug
