### ISSUE TITLE
Ptxas: unresolved extern function __spirv_AtomicLoad(long long const*...)

### ISSUE THREAD

**Issue by 12VIP** [intel/llvm#7658] opened 2022-12-06 13:28 UTC
Issue (ptxas error) observed while building sample application(after dpct migration) 

In this case :
During  compilation phase object file TestFluxBC.cpp.dp.o is generated then ,during linking phase : 
**command :** 
dpcpp_compiler/bin/clang++ -fsycl -fsycl-targets=nvptx64-nvidia-cuda -o TestFluxBC tests/TestFluxBC.cpp.dp.o liblbpm-wia.a -L/usr/lib/x86_64-linux-gnu/openmpi/lib -lmpi_cxx -lmpi

**Error Reported:** 
ptxas fatal   : Unresolved extern function '_Z18__spirv_AtomicLoadPKxN5__spv5Scope4FlagENS_19MemorySemanticsMask4FlagE'
llvm-foreach: 
ptxas fatal   : Unresolved extern function '_Z18__spirv_AtomicLoadPKxN5__spv5Scope4FlagENS_19MemorySemanticsMask4FlagE'
llvm-foreach: 
clang++: error: ptxas command failed with exit code 255 (use -v to see invocation)
clang version 16.0.0 (/netbatch/donb3373736_00/runDir/jenkins-dir/workspace/Tools_SH/SYCLOS_Nightly/RHEL/llvm.src/clang 2359d948b3f3589c87637f07875e8a01c8438594)
Target: x86_64-unknown-linux-gnu
Thread model: posix
InstalledDir: sycl_nightly_20221203/dpcpp_compiler/bin
clang++: note: diagnostic msg: Error generating preprocessed source(s).

**Function :** 
c++filt '_Z18__spirv_AtomicLoadPKxN5__spv5Scope4FlagENS_19MemorySemanticsMask4FlagE'
__spirv_AtomicLoad(long long const*, __spv::Scope::Flag, long long const::MemorySemanticsMask::Flag)

- OS: Linux(Ubuntu)
- DPC++ version: 16.0.0(2359d948b3f3589c87637f07875e8a01c8438594)
- Dependencies : openmpi

Will try to check on the reproducer steps(as lots of steps prerequisite) .Want to check if this is some known issue .

**Comment by mmoadeli** [comment] 2022-12-06 14:27
Hi @12VIP  thanks for reporting this issue. We will look into this and get back to you shortly. Would you be helpful if you could share the related code to reproduce the issue.

**Comment by dm-vodopyanov** [comment] 2022-12-06 14:31
Quick look on the error message: the reason the compilation failed is that CUDA doesn't support SPIR-V.

**Comment by bader** [comment] 2022-12-06 16:27
> Quick look on the error message: the reason the compilation failed is that CUDA doesn't support SPIR-V.

CUDA doesn't use SPIR-V, so I don't think this is the right guess. I suppose it has something to do with the libclc implementation, which is supposed to implement this function. The reason why this function definition is missing might be that `long long` type is not supported by OpenCL. @AerialMantis, could you assign someone to investigate, please?

**Comment by 12VIP** [comment] 2022-12-07 09:24
[files.zip](https://github.com/intel/llvm/files/10174605/files.zip)  : Attached cpp file & headers if required.

**Comment by zjin-lcf** [comment] 2022-12-08 19:28
@12VIP 
Do your files contain DPC++ codes ?

**Comment by 12VIP** [comment] 2022-12-09 05:29
@zjin-lcf  , Original code : https://github.com/OPM/LBPM/blob/master/tests/TestFluxBC.cpp 
Attached earlier(files.zip with dpct) : TestFluxBC.cpp.dp.cpp .Both files are same only ,no dpc++ code as such .

**Comment by jchlanda** [comment] 2022-12-13 12:46
@12VIP I wasn't able to build your example (as attached in files.zip) due to broken dependencies, it would be great if you could provide us with a minimal SYCL example that exhibits the same issue. Recently we have merged in fixes to re-mangler, which might be of help in that case (as long long would likely be requiring re-mangline), further more I suggest you try this PR: https://github.com/intel/llvm/pull/7391 as it introduces more support for generic address space atomics.

**Comment by jchlanda** [comment] 2022-12-13 12:48
In fact I've just had a look in the generated libclc files (from that PR I've mentioned above) and indeed it contains the function in question:

```
remangled-l32-signed_char.libspirv-nvptx64--nvidiacl.ll

479632:declare dso_local i64 @_Z18__spirv_AtomicLoadPKxN5__spv5Scope4FlagENS_19MemorySemanticsMask4FlagE(i64* noundef, i32 noundef, i32 noundef) local_unnamed_addr #50
```

**Closed** 2022-12-14 09:34 UTC
Labels: bug, cuda
