### ISSUE TITLE
Missed diagnostic about function pointers usage

### ISSUE THREAD

**Issue by AlexeySachkov** [intel/llvm#659] opened 2019-09-19 17:28 UTC
Reproducer:
```c++
#include <CL/sycl.hpp>

typedef void(*fp_t)(struct Desc *);

struct Type;

struct Desc {
  int B;
  Type *Ptr;
};

struct Type {
  int A;
  fp_t FP;
};

int main() {
  cl::sycl::queue Q;

  Q.submit([&](cl::sycl::handler &cgh) {
    cgh.single_task<class K>([=]() {
      Type t;
    });
  });

  return 0;
}
```

Instead of emitting an error about incorrect usage of function pointers in the device code, compiler crashes in llvm-spirv:
```
$ bin/clang++ fp-in-struct.cpp -fsycl -std=c++11 -fsycl-device-only -fno-sycl-use-bitcode -o fp-in-struct.spv
llvm-spirv: /data/from-github/SYCL/otcshare/llvm-spirv/lib/SPIRV/libSPIRV/SPIRVModule.cpp:701: virtual SPIRV::SPIRVEntry* SPIRV::SPIRVMod
uleImpl::getEntry(SPIRV::SPIRVId) const: Assertion `Loc != IdEntryMap.end() && "Id is not in map"' failed.
```

**Comment by Fznamznon** [comment] 2019-09-20 12:01
It looks like we diagnose function pointers usage only if call through a function pointer was made. Diagnosing declaring of function pointers just is not implemented.
It think function pointers declaring also should be diagnosed too, since function pointer types fall into a device module even if call wasn't made which can make SPIRV invalid for CPU back-ends.
The problem can be reproduced with the simplest code:
```
#include <CL/sycl.hpp>

typedef void(*fp_t)();

int main() {
  cl::sycl::queue Q;

  Q.submit([&](cl::sycl::handler &cgh) {
    cgh.single_task<class K>([=]() {
        fp_t FP;
    });
  });

  return 0;
}
```
It compiles without any diagnostics!

**Comment by keryell** [comment] 2019-09-27 00:59
The problem when we are too pedantic is that it becomes difficult to compile real C++ code that contains some features that should disappear anyway when compiled with some level of optimization.
For example the function pointer above should be removed by at least `-O2`.
So what about an options such as `-fsycl-best-effort` :-) to generate some LLVM IR even if this is not strictly compliant SYCL code for some forgiving back-ends?

**Comment by romanovvlad** [comment] 2022-09-07 13:35
It doesn't crash anymore. On attempt to actually call thru function pointer the clang emits an error.
So, closing the tracker, @AlexeySachkov please, feel free to reopen if there are any concerns.

**Closed by romanovvlad** 2022-09-07 13:35 UTC
Labels: bug
