### ISSUE TITLE
[CUDA] Support CUDA 11.5 in compiler

### ISSUE THREAD

**Issue by yuxianch** [intel/llvm#4872] opened 2021-11-02 07:14 UTC
CUDA 11.5 has been released(See https://docs.nvidia.com/cuda/cuda-toolkit-release-notes/index.html ) but compiler doesn't support it on Windows for now. Therefore, when running tests on a Windows machine with CUDA 11.5 installed, it will show error "cannot find libdevice" like below.
```
ksh-3.2$ clang-cl -fsycl -Xsycl-target-backend --cuda-gpu-arch=sm_50 -fsycl-targets=nvptx64-nvidia-cuda test.cpp -v
clang version 14.0.0 (https://github.com/intel/llvm.git a0342b313592143345ab3367e2ed6f6926a79a98)
Target: x86_64-pc-windows-msvc
Thread model: posix
InstalledDir: \path\to\build\win_prod\bin
clang-cl: error: cannot find libdevice for sm_50; provide path to different CUDA installation via '--cuda-path', or pass '-nocudalib' to build without linking with libdevice
clang-cl: error: cannot find libdevice for sm_50; provide path to different CUDA installation via '--cuda-path', or pass '-nocudalib' to build without linking with libdevice
```
```
ksh-3.2$ nvcc --version
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2021 NVIDIA Corporation
Built on Mon_Sep_13_20:11:50_Pacific_Daylight_Time_2021
Cuda compilation tools, release 11.5, V11.5.50
Build cuda_11.5.r11.5/compiler.30411180_0
```

**Comment by alexbatashev** [comment] 2021-11-02 07:22
@yuxianch I think the support should first come to the upstream clang, and only then it can be utilized in DPC++.

**Comment by pvchupin** [comment] 2021-11-02 20:01
@alexbatashev, @yuxianch it doesn't look like this has anything to do with clang upstream. The problem is probably that sm_50 is deprecated based on https://docs.nvidia.com/cuda/cuda-toolkit-release-notes/index.html#title-new-cuda-libraries
Where this switch (--cuda-gpu-arch=sm_50) is coming from? Can we try to move forward?

Matching the machine where this test is run would be the best approach I think.
See: https://docs.nvidia.com/cuda/cuda-compiler-driver-nvcc/index.html#gpu-feature-list

**Comment by yuxianch** [comment] 2021-11-03 01:11
Add more info.
1) This issue only exists on Windows. We don't meet it on Linux with CUDA 11.5.
```
# Works well on Linux(--cuda-gpu-arch=sm_50 works well too):
$ touch test.cpp ; clang++ -fsycl -Xsycl-target-backend --cuda-gpu-arch=sm_86 -fsycl-targets=nvptx64-nvidia-cuda test.cpp -c
clang++: warning: CUDA version is newer than the latest supported version 11.4 [-Wunknown-cuda-version]
warning: linking module '/path/to/build/linux_prod/lib/clang/14.0.0/../../clc/remangled-l64-signed_char.libspirv-nvptx64--nvidiacl.bc': Linking two modules of different target triples: '/path/to/build/linux_prod/lib/clang/14.0.0/../../clc/remangled-l64-signed_char.libspirv-nvptx64--nvidiacl.bc' is 'nvptx64-unknown-nvidiacl' whereas 'test.cpp' is 'nvptx64-nvidia-cuda'
 [-Wlinker-warnings]
1 warning generated.
```
2) Looks like it's not related with cuda-gpu-arch switch. We meet the same error for both --cuda-gpu-arch=sm_50 and --cuda-gpu-arch=sm_86 on Windows. Both clang-cl and clang++ have the same output.

**Comment by pvchupin** [comment] 2021-11-03 01:33
@yuxianch, what's the latest CUDA toolkit version on windows that's confirmed to be OK?

**Comment by yuxianch** [comment] 2021-11-03 01:38
> @yuxianch, what's the latest CUDA toolkit version on windows that's confirmed to be OK?

It's 11.4

**Comment by pvchupin** [comment] 2021-11-03 01:44
Tagging @AerialMantis

**Comment by steffenlarsen** [comment] 2021-11-17 10:11
@alexbatashev is right that this issue is normally something we rely on from upstream as this problem is in how the CUDA driver toolchain looks for libdevice. Currently it only supports up to 11.4 and does not search in the default installation folder of CUDA 11.5 (see [clang/lib/Driver/ToolChains/Cuda.cpp#L128](https://github.com/intel/llvm/blob/sycl/clang/lib/Driver/ToolChains/Cuda.cpp#L128))

**Comment by pvchupin** [comment] 2021-11-18 01:02
@steffenlarsen, is it a matter of adding one more number to the list? :)
Any ideas how 11.5 works on Linux?

**Comment by steffenlarsen** [comment] 2021-11-18 09:56
> @steffenlarsen, is it a matter of adding one more number to the list? :) 

It's not far from it at least. I actually think intel/llvm is ahead of upstream with this anyway, as of https://github.com/intel/llvm/commit/8aa3513c8224b0f4c1f4d0f405f0facd955bd7f5. I actually tried to get it into upstream, but the patch grew stale (https://reviews.llvm.org/D107054)

> Any ideas how 11.5 works on Linux?

No idea, but I suspect it's little different from the previous minor releases.

**Comment by steffenlarsen** [comment] 2021-11-18 22:46
It appears that 11.5 support was added to upstream recently: https://reviews.llvm.org/D113249 (thanks @bader for pinging 😄 )

We should see it with next pulldown.

**Comment by AerialMantis** [comment] 2021-12-07 00:05
We believe this issue to be resolved now so we're closing this, if the issue is seen again we can re-open the ticket.

**Closed by AerialMantis** 2021-12-07 00:05 UTC
Labels: bug, cuda, compiler
