### ISSUE TITLE
Re-enable CUDA tests

### ISSUE THREAD

**Issue by erichkeane** [intel/llvm#1542] opened 2020-04-17 13:18 UTC
In 7a9a4251 Alexander disabled quite a few SYCL tests for CUDA with XFAIL:CUDA in order to get the commit in.  These all need to be re-enabled.  This likely can be handled by a few different people, but Alexander should own re-enabling that which he disabled.

Note that most have a TODO associated with them.

The following test all have XFAIL:cuda in them, so they need to be analyzed and fixed:
usm/queue_wait.cpp
usm/allocator_vector_fail.cpp
usm/math.cpp
usm/mixed2template.cpp
usm/smemll.cpp
usm/depends_on.cpp
usm/memset.cpp
usm/mixed_queue.cpp
usm/dmemll.cpp
usm/memcpy.cpp
usm/allocator_vector.cpp
usm/allocatorll.cpp
usm/hmemll.cpp
usm/memadvise.cpp
usm/badmalloc.cpp
usm/mixed2.cpp
usm/mixed.cpp
device-code-split/aot-gpu.cpp
device-code-split/split-per-kernel.cpp
device-code-split/split-per-source-main.cpp
regression/kernel_name_class.cpp
regression/kernel_unnamed.cpp
separate-compile/sycl-external.cpp
ordered_queue/oq_kernels.cpp
ordered_queue/ordered_buffs.cpp
basic_tests/buffer/subbuffer.cpp
basic_tests/buffer/buffer.cpp
basic_tests/parallel_for_range.cpp
basic_tests/scalar_vec_access.cpp
basic_tests/vec_op.cpp
basic_tests/image.cpp
basic_tests/compare_exchange_strong.cpp
basic_tests/image_array.cpp
basic_tests/stream/stream.cpp
basic_tests/stream/auto_flush.cpp
basic_tests/parallel_for_indexers.cpp
built-ins/vector_common.cpp
built-ins/scalar_geometric.cpp
built-ins/vector_integer.cpp
built-ins/vector_geometric.cpp
built-ins/scalar_relational.cpp
built-ins/vector_math.cpp
built-ins/vector_relational.cpp
built-ins/nan.cpp
built-ins/scalar_common.cpp
built-ins/scalar_integer.cpp
built-ins/scalar_math.cpp
built-ins/printf.cpp
scheduler/ReleaseResourcesTest.cpp
scheduler/DataMovement.cpp

**Comment by bjoernknafla** [comment] 2020-04-20 12:50
A lot of work of the community and us went into fixing LIT testing to work as expected for CUDA - without marking tests as XFAIL it would have taken longer with more breakage slipping through. Without a lot of visible and invisible work of Alexander there would to this time be no reliable and deterministic LIT testing.

Sometimes I mark tests as XFAIL that we expect to pass in the future. This way the tests will automatically show up as unexpected passes when running tests after adding features.

We have a roadmap for many of the CUDA related LIT XFAILs (and UNSUPPORTEDs) and our whole team takes responsibility for these and is actively working on them. Some XFAILS will be fixed soon, some later, some are not part of what we plan to achieve and we will not work on them.

Tests we are aware off and are tracking will have a TODO or comment added to them about the problem.

Tests without any comment typicall fall into the following categories:
* Added upstream without testing CUDA while we prepared open sourcing.
* Updated upstream since open sourcing while features got added or changed upstream without updating or running CUDA tests.

**Comment by erichkeane** [comment] 2020-04-20 12:57
That is fine, we just need a bug/series of bugs to track these. So, this is here to track them.  

At least one is disabled because of design implementation details of __builtin_unique_stable_name, which is how this came up.  It is disappointing that it was never brought up via bug/etc, since we could have fixed this trivially immediately (I've since fixed it in the upstream, so we're awaiting the pulldown).

We need to analyze the changes that will need to happen to make sure they do not have ABI implications, otherwise they might never be able to be fixed.

**Comment by bader** [comment] 2020-04-20 14:07
@erichkeane, it looks like @vladimirlaz has some problems with pulldown, so if `__builtin_unique_stable_name` fix is required soon, it can be cherry-picked manually.

**Comment by erichkeane** [comment] 2020-04-20 14:10
I don't know if it necessarily IS required soon, just before we hit a release that locks us into ABI.  Presumably, we could have these problems with some of the things that CUDA disabled as well, so I just want to make sure we have a plan for HOW to fix these before a release locks us into not being able to make said change.

**Comment by keryell** [comment] 2020-04-22 03:53
ABI, ABI... Ahem... Is it a proof of success when we end up into ABI stability discussion? :-)

**Comment by erichkeane** [comment] 2020-04-22 04:17
> ABI, ABI... Ahem... Is it a proof of success when we end up into ABI stability discussion? :-)

Any language worth using has to end up in an ABI discussion eventually. As a person shipping a compiler frontend, ABI compatibility between versions and compilers is a constant headache.

**Comment by bjoernknafla** [comment] 2020-04-22 13:01
Fix of tests for `basic_tests/buffer/buffer.cpp`: https://github.com/intel/llvm/pull/1570

**Comment by bjoernknafla** [comment] 2020-04-22 16:50
PR including fix for `scheduler/DataMovement.cpp`: https://github.com/intel/llvm/pull/1543

**Comment by bjoernknafla** [comment] 2020-05-07 09:59
PR by @fwyzard to fix many of the USM XFAILs: #1577

**Comment by bjoernknafla** [comment] 2020-05-07 11:28
The following (merged) PR triaged most LIT tests to mark missing features or features that cannot be supported by CUDA as `UNSUPPORTED: cuda` and added a comment: https://github.com/intel/llvm/pull/1620

* SYCL 1.2.1 image spec cannot be implemented with HW support in CUDA.
* Fixed tests (by passing the required compilation target) to work with CUDA.
* printf is not supported by CUDA
* Device code splitting is not supported by CUDA.
* Unnamed lambdas are not supported by CUDA.

**Comment by bjoernknafla** [comment] 2020-05-07 11:29
`scheduler/ReleaseResourcesTest.cpp` fails due to an unexpected trace when running with CUDA as CUDA does not support SPIR.

**Comment by bjoernknafla** [comment] 2020-05-07 11:30
That leaves xfails due to missing builtins - and we are actively working on them.

**Comment by bjoernknafla** [comment] 2020-05-07 11:34
`basic_tests/buffer/subbuffer.cpp` this test needs to be fixed to handle sub-buffer alignment requirements correctly before knowing if it works with CUDA.

**Comment by bjoernknafla** [comment] 2020-05-07 11:34
`basic_tests/parallel_for_range.cpp` needs investigation.

**Comment by bjoernknafla** [comment] 2020-05-07 11:37
`parallel_for_indexers.cpp` is under investigation (fail is related to global offset handling).

**Comment by erichkeane** [comment] 2020-05-07 12:49
> 
> 
> The following (merged) PR triaged most LIT tests to mark missing features or features that cannot be supported by CUDA as `UNSUPPORTED: cuda` and added a comment: #1620
> 
>     * SYCL 1.2.1 image spec cannot be implemented with HW support in CUDA.
> 
>     * Fixed tests (by passing the required compilation target) to work with CUDA.
> 
>     * printf is not supported by CUDA
> 
>     * Device code splitting is not supported by CUDA.
> 
>     * Unnamed lambdas are not supported by CUDA.

Unnamed Lambdas should now be supported for CUDA I changed the text format so that it should now work, if you're still having a problem, please let me know!

**Comment by bjoernknafla** [comment] 2020-05-07 15:59
Both unnamed lambda tests use USM and require the fix by @fwyzard : https://github.com/intel/llvm/pull/1577 to then pass.

One of them passes but creates an (ignored) error output due to event handling. The fix for this planned on top of https://github.com/intel/llvm/pull/1471

**Comment by erichkeane** [comment] 2020-05-07 16:16
I see, thanks!  So nothing to do with the mangling anymore.  Not sure how the USM matters here (other than perhaps it is used in the test?).

**Comment by bjoernknafla** [comment] 2020-05-07 16:20
Both tests (`sycl/test/usm/pfor_flatten.cpp`, `
`) trigger USM allocations and the mentioned PR fixes an issue with `0` alignment values to be handled spec-conform.

**Comment by erichkeane** [comment] 2020-05-07 16:21
Great, thanks for clarifying.

**Comment by bjoernknafla** [comment] 2020-06-09 16:27
Many of the builtin-related tests will be fixed by the following PRs:
* https://github.com/intel/llvm/pull/1827
* https://github.com/intel/llvm/pull/1828

**Comment by bjoernknafla** [comment] 2020-06-09 17:01
usm/queue_wait.cpp - PR https://github.com/intel/llvm/pull/1577
usm/allocator_vector_fail.cpp - PR https://github.com/intel/llvm/pull/1577
usm/math.cpp - PR https://github.com/intel/llvm/pull/1577
usm/mixed2template.cpp - PR https://github.com/intel/llvm/pull/1577
usm/smemll.cpp - PR https://github.com/intel/llvm/pull/1577
usm/depends_on.cpp - PR https://github.com/intel/llvm/pull/1577
usm/memset.cpp - PR https://github.com/intel/llvm/pull/1577
usm/mixed_queue.cpp - PR https://github.com/intel/llvm/pull/1577
usm/dmemll.cpp - PR https://github.com/intel/llvm/pull/1577
usm/memcpy.cpp - PR https://github.com/intel/llvm/pull/1577
usm/allocator_vector.cpp - PR https://github.com/intel/llvm/pull/1577
usm/allocatorll.cpp - PR https://github.com/intel/llvm/pull/1577
usm/hmemll.cpp - PR https://github.com/intel/llvm/pull/1577
usm/memadvise.cpp - PR https://github.com/intel/llvm/pull/1577
usm/badmalloc.cpp - PR https://github.com/intel/llvm/pull/1577
usm/mixed2.cpp - PR https://github.com/intel/llvm/pull/1577
usm/mixed.cpp - PR https://github.com/intel/llvm/pull/1577
~~device-code-split/aot-gpu.cpp~~ - unsupported device code splitting and SPIR
~~device-code-split/split-per-kernel.cpp~~ - unsupported device code splitting and SPIR
~~device-code-split/split-per-source-main.cpp~~ - unsupported device code splitting and SPIR
~~regression/kernel_name_class.cpp~~ fixed
~~regression/kernel_unnamed.cpp~~ fixed
~~separate-compile/sycl-external.cpp~~ fixed
~~ordered_queue/oq_kernels.cpp~~ test got removed
~~ordered_queue/ordered_buffs.cpp~~ test got removed
basic_tests/buffer/subbuffer.cpp - PR outstanding, test needs fixing for alignment handling
~~basic_tests/buffer/buffer.cpp~~ fixed
basic_tests/parallel_for_range.cpp - PR https://github.com/intel/llvm/pull/1654
basic_tests/scalar_vec_access.cpp
basic_tests/vec_op.cpp
~~basic_tests/image.cpp~~ - unsupported images
basic_tests/compare_exchange_strong.cpp
~~basic_tests/image_array.cpp~~ - unsupported images
basic_tests/stream/stream.cpp
~~basic_tests/stream/auto_flush.cpp~~ fixed
basic_tests/parallel_for_indexers.cpp - under investigation
built-ins/vector_common.cpp
built-ins/scalar_geometric.cpp
built-ins/vector_integer.cpp - PR https://github.com/intel/llvm/pull/1828
built-ins/vector_geometric.cpp
built-ins/scalar_relational.cpp
built-ins/vector_math.cpp
built-ins/vector_relational.cpp
built-ins/nan.cpp
built-ins/scalar_common.cpp
built-ins/scalar_integer.cpp - PR https://github.com/intel/llvm/pull/1828
built-ins/scalar_math.cpp - PR https://github.com/intel/llvm/pull/1827
~~built-ins/printf.cpp~~ printf unsupported
~~scheduler/ReleaseResourcesTest.cpp~~ SPIR-V unsupported
~~scheduler/DataMovement.cpp~~ fixed

**Comment by bader** [comment] 2020-10-13 16:56
SYCL :: basic_tests/image/image_write.cpp fails on CUDA device.
https://github.com/intel/llvm/pull/2627 - Log: http://ci.llvm.intel.com:8010/#/builders/37/builds/3715
https://github.com/intel/llvm/pull/2628 - Log: http://ci.llvm.intel.com:8010/#/builders/37/builds/3716
I'm going to disable it and use use issue to track the status. At first glance it looks like some UB triggered by random changes.

**Comment by steffenlarsen** [comment] 2021-04-21 11:47
@erichkeane @bader 

I don't see any more `XFAIL: cuda` in intel/llvm. Can we close this?

**Comment by bader** [comment] 2021-04-21 11:53
+@vladimirlaz, I think we should check https://github.com/intel/llvm-test-suite/tree/intel/SYCL as most of these tests moved from `intel/llvm` there.

**Comment by steffenlarsen** [comment] 2021-04-21 11:55
I think there are a handful of xfails left in there, but would it make sense to open a new ticket on that repo for tracking those?

**Comment by vladimirlaz** [comment] 2021-04-21 12:03
Simple grepping showed that there are some:
It looks like tests in Regression and USM are inherited, the other may be new:
```
llvm-test-suite/build$ grep -r XFAIL ../SYCL/ | grep cuda
../SYCL/Regression/atomic_load.cpp:// XFAIL: cuda
../SYCL/Regression/implicit_offset_debug_info.cpp:// XFAIL: cuda
../SYCL/Sampler/normalized-clamp-linear-float.cpp:// XFAIL: cuda
../SYCL/Sampler/normalized-mirror-linear-float.cpp:// XFAIL: cuda
../SYCL/Sampler/unnormalized-none-linear-float.cpp:// XFAIL: cuda
../SYCL/Sampler/normalized-repeat-nearest.cpp:// XFAIL: cuda
../SYCL/Sampler/normalized-mirror-nearest.cpp:// XFAIL: cuda
../SYCL/Sampler/normalized-repeat-linear-float.cpp:// XFAIL: cuda
../SYCL/Sampler/unnormalized-clampedge-linear-float.cpp:// XFAIL: cuda
../SYCL/Sampler/normalized-none-linear-float.cpp:// XFAIL: cuda
../SYCL/Sampler/normalized-clampedge-linear-float.cpp:// XFAIL: cuda
../SYCL/Sampler/unnormalized-clamp-linear-float.cpp:// XFAIL: cuda
../SYCL/Config/select_device.cpp:// XFAIL: cuda
../SYCL/Basic/reqd_work_group_size.cpp:// XFAIL: cuda
../SYCL/Scheduler/CommandCleanupThreadSafety.cpp:// XFAIL: cuda
../SYCL/Scheduler/MemObjRemapping.cpp:// XFAIL: cuda
../SYCL/KernelAndProgram/build-log.cpp:// XFAIL: cuda
../SYCL/KernelAndProgram/basic-program.cpp:// XFAIL: cuda
../SYCL/KernelAndProgram/kernel-and-program.cpp:// XFAIL: cuda
../SYCL/KernelAndProgram/cache-build-result.cpp:// XFAIL: cuda
../SYCL/KernelAndProgram/get-options.cpp:// XFAIL: cuda
../SYCL/USM/dmem_varied.cpp:// XFAIL: cuda
../SYCL/USM/smem_concurrent.cpp:// XFAIL: cuda
../SYCL/USM/math.cpp:// XFAIL: cuda
../SYCL/USM/pointer_query.cpp:// XFAIL: cuda
../SYCL/USM/smem_varied.cpp:// XFAIL: cuda
../SYCL/USM/prefetch.cpp:// XFAIL: cuda
```

**Comment by steffenlarsen** [comment] 2021-04-21 12:06
To my knowledge, some of them have both `XFAIL: cuda` and `REQUIRES: level-zero`, such as SYCL/USM/smem_concurrent.cpp. Am I right in assuming the latter makes lit ignore the former?

**Comment by vladimirlaz** [comment] 2021-04-21 12:07
> To my knowledge, some of them have both `XFAIL: cuda` and `REQUIRES: level-zero`, such as SYCL/USM/smem_concurrent.cpp. Am I right in assuming the latter makes lit ignore the former?

You are right.

**Comment by bader** [comment] 2021-04-22 06:08
> I think there are a handful of xfails left in there, but would it make sense to open a new ticket on that repo for tracking those?

I'm okay with that.
I can even [transfer this issue](https://docs.github.com/en/github/managing-your-work-on-github/transferring-an-issue-to-another-repository) to llvm-test-suite if you are okay with it.

**Comment by steffenlarsen** [comment] 2021-04-22 09:40
> I can even transfer this issue to llvm-test-suite if you are okay with it.

I think it may be cleaner to just restart it and link. That way people who read it won't have to go through all the previous discussions on fixed issues to get to the relevant information. Thank you though!

If you are okay with that solution, I will go find the relevant XFAILs and list them in a new issue on llvm-test-suite. I'll leave out the ones with `REQUIRES: level-zero` and make a PR to remove `XFAIL: cuda` from them.

**Comment by bader** [comment] 2021-04-22 09:47
Sounds good to me. Thanks!

**Comment by steffenlarsen** [comment] 2021-04-22 12:15
I have opened the continuation issue here: https://github.com/intel/llvm-test-suite/issues/249

**Comment by AlexeySachkov** [comment] 2022-02-07 14:42
Closing this one, because we have a more up-to-date tracker for those issues here: intel/llvm-test-suite#249

**Closed by AlexeySachkov** 2022-02-07 14:42 UTC
Labels: cuda
