### ISSUE TITLE
annotated_arg fail on Windows in CI

### ISSUE THREAD

**Issue by sarnex** [intel/llvm#11224] opened 2023-09-19 20:11 UTC
See https://github.com/intel/llvm/actions/runs/6224435385/job/16906814653?pr=11171

**Comment by aelovikov-intel** [comment] 2023-09-26 15:10
It seems that whenever these fail, other tests hang and entire run isn't finished (terminated by timeout). When that happens, some zombie processes from the hanging tests remain on the runner and affect subsequent CI tasks. I've disabled the tests in the PR mentioned above.

**Comment by aelovikov-intel** [comment] 2023-09-27 17:30
Tagging @broxigarchen , @tiwaria1 , @jessicadavies-intel , @GarveyJoe as they seem to be active in that area.

**Comment by broxigarchen** [comment] 2023-09-28 15:14
Hi @aelovikov-intel  the error msg from the annotated_arg_ptr test does not seem meaningful to me.

Are they hanging? Does this only happen on windows?

**Comment by aelovikov-intel** [comment] 2023-09-28 16:33
We only saw that on Windows. Whenever those tests failed, we saw a bunch of *other* tests hanging affecting subsequent CI tasks.

> I am not familiar with the runtime that is used in the e2e test. If I want to reproduce it offline, which runtime should I use?

I'm not sure I fully understand the question. Using any task from https://github.com/intel/llvm/actions/workflows/sycl_precommit_windows.yml, you'd be interested in the following commands:

![image](https://github.com/intel/llvm/assets/55163882/e466c6d3-37d5-4c3d-9610-e669025ed635)
![image](https://github.com/intel/llvm/assets/55163882/a01fd56f-7afb-4037-857e-9e0accfa8060)
![image](https://github.com/intel/llvm/assets/55163882/67e782ee-ec96-4a82-9612-37284966b53d)
![image](https://github.com/intel/llvm/assets/55163882/0a1a1e56-dd30-4b91-b02a-529349563e9d)

**Comment by broxigarchen** [comment] 2023-10-03 15:14
Hi @aelovikov-intel, it seems I cannot reproduce with FPGA runtime locally. The log shows CI are failed with GPU runtime which is not available to me.

I tried to reenable these test here and seems the CI are passing on windows e2e test? Can you help teo take a look? https://github.com/intel/llvm/pull/11386

**Comment by broxigarchen** [comment] 2023-10-03 16:37
It seems the annotated_arg_ptr test is failing intermittently on windows GPU platform

Since this feature is introduced for FPGA runtime and it's only used by FPGA runtime currently, the failing on GPU might not be a big problem.

I don't have the GPU runtime to reproduce this issue so I will keep this as it is right now.

**Comment by broxigarchen** [comment] 2023-11-02 21:13
Hi @aelovikov-intel  can you evaluate if this PR can get in https://github.com/intel/llvm/pull/11731 ? I am no sure how to prove that if this issue has gone since you mentioned that it's flaky. Shall we get it in and see how does it looks like?

**Comment by steffenlarsen** [comment] 2024-05-08 07:28
Tests were reenabled with https://github.com/intel/llvm/pull/11731. Closing this as fixed.

**Closed by steffenlarsen** 2024-05-08 07:28 UTC
Labels: bug
