### ISSUE TITLE
[CUDA] Inefficient code generation around the barrier

### ISSUE THREAD

**Issue by anton-v-gorshkov** [intel/llvm#4504] opened 2021-09-07 13:07 UTC
**Describe the bug**
Similar kernel compiled with DPC++ shows ~10% overhead comparing with CUDA due to ~20% additional instructions generated.

**To Reproduce**
[test.zip](https://github.com/intel/llvm/files/7121301/test.zip)

$ unzip test.zip
$ cd cuda
$ ./build.sh
$ nvprof ./cholesky
```
Rows: 16 Matricies:  1176 Min:   0.0988 Avg:   0.0993 Max:   0.1004 [ms]
==384516== Profiling result:
            Type  Time(%)      Time     Calls       Avg       Min       Max  Name
 GPU activities:   39.80%  1.0077ms        17  59.277us  59.043us  59.812us  void CholeskyDecompositionImpl<int=128, int=16, int=16>(float*, int)
                   10.98%  278.03us        17  16.354us  16.225us  16.545us  void SolveForwardImpl<TTransposedSystem, int=256>(float const *, int, int, int, float*)
                   10.63%  269.14us        17  15.831us  15.681us  15.969us  void SolveForwardImpl<TDirectSystem, int=256>(float const *, int, int, int, float*)
```

$ cd ../dpcpp
$ ./build.sh
$ SYCL_DEVICE_FILTER=cuda ./cholesky
```
Target device: NVIDIA GeForce RTX 2070
Rows: 16 Matricies:  1176 Min:   0.1014 Avg:   0.1022 Max:   0.1042 [ms]
==384490== Profiling result:
            Type  Time(%)      Time     Calls       Avg       Min       Max  Name
 GPU activities:   38.89%  971.07us        34  28.560us  6.7840us  50.723us  [CUDA memcpy HtoD]
                   36.33%  907.09us        17  53.358us  52.707us  58.051us  _ZTSZZ17RunCholeskySolverILi128ELi256ELi0EEvPfS0_iiN2cl4sycl5queueEENKUlRNS2_7handlerEE4_clES5_E31CholeskyDecompositionUnrolled16
                   12.36%  308.59us        17  18.152us  17.857us  18.369us  _ZTSZZ17RunCholeskySolverILi128ELi256ELi0EEvPfS0_iiN2cl4sycl5queueEENKUlRNS2_7handlerEE15_clES5_E21SolveForwardTranspose
                   12.15%  303.51us        17  17.853us  17.633us  18.434us  _ZTSZZ17RunCholeskySolverILi128ELi256ELi0EEvPfS0_iiN2cl4sycl5queueEENKUlRNS2_7handlerEE14_clES5_E18SolveForwardDirect
```
**Environment (please complete the following information):**

- OS: Ubuntu 20.04
- Target device and vendor:  NVIDIA GeForce RTX 2070
- DPC++ version: clang version 14.0.0 (https://github.com/intel/llvm 29a1f167060e69d4d90d1e6a15d4998fd4556c4d)
- Dependencies version: CUDA 11.4

**Additional context**

After deeper dive into the problem I've come to the assumption the redundant instructions are located in WarpReduce function and connected to the difference in thread mask calculation for barrier.

LLVM IR for CUDA looks like this:
```
_Z10WarpReduceIf8TCudaAddIfEET_iPVS2_iT0_.exit.i: ; preds = %if.then.i.i, %for.cond.cleanup.i.i
  tail call void @llvm.nvvm.bar.warp.sync(i32 -1) #7, !dbg !1145
  br label %_Z17FastInBlockReduceIf8TCudaAddIfEET_iPVS2_i.exit, !dbg !1147
```
LLVM IR for DPC++ code looks like this:
```
_Z10WarpReduceIf8TCudaAddIfEET_iPVS2_iN2cl4sycl7nd_itemILi1EEET0_.exit.i.i.i: ; preds = %if.then.i.i.i.i, %for.cond.cleanup.i.i.i.i
  %25 = tail call i32 @llvm.nvvm.read.ptx.sreg.tid.y() #10, !dbg !2599, !range !64
  %26 = tail call i32 @llvm.nvvm.read.ptx.sreg.tid.z() #10, !dbg !2599, !range !87
  %27 = tail call i32 @llvm.nvvm.read.ptx.sreg.ntid.y() #10, !dbg !2599, !range !48
  %mul.i.i.i.i.i.i.i.i = mul nuw nsw i32 %27, %26, !dbg !2599
  %mul719.i.i.i.i.i.i.i.i = add nuw nsw i32 %mul.i.i.i.i.i.i.i.i, %25, !dbg !2599
  %add.i.i.i.i.i.i.i.i = mul nuw nsw i32 %mul719.i.i.i.i.i.i.i.i, %0, !dbg !2599
  %add9.i.i.i.i.i.i.i.i = add nuw nsw i32 %add.i.i.i.i.i.i.i.i, %3, !dbg !2599
  %div.i.i.i.i.i.i.i.i = lshr i32 %add9.i.i.i.i.i.i.i.i, 5, !dbg !2599
  %28 = tail call i32 @llvm.nvvm.read.ptx.sreg.ntid.z() #10, !dbg !2599, !range !88
  %mul.i3.i.i.i.i.i.i.i = mul nuw nsw i32 %27, %0, !dbg !2599
  %mul4.i4.i.i.i.i.i.i.i = mul nuw nsw i32 %mul.i3.i.i.i.i.i.i.i, %28, !dbg !2599
  %sub.i5.i.i.i.i.i.i.i = add nuw nsw i32 %mul4.i4.i.i.i.i.i.i.i, 31, !dbg !2599
  %div.i6.i.i.i.i.i.i.i = lshr i32 %sub.i5.i.i.i.i.i.i.i, 5, !dbg !2599
  %sub.i.i.i.i.i.i.i = add nsw i32 %div.i6.i.i.i.i.i.i.i, -1, !dbg !2599
  %cmp.not.i.i.i.i.i.i.i = icmp eq i32 %div.i.i.i.i.i.i.i.i, %sub.i.i.i.i.i.i.i, !dbg !2599
  %sub11.i.neg.i.i.i.i.i.i = sub nsw i32 0, %mul4.i4.i.i.i.i.i.i.i, !dbg !2599
  %sub11.i.neg.op.i.i.i.i.i.i = and i32 %sub11.i.neg.i.i.i.i.i.i, 31, !dbg !2599
  %sub11.i.neg.op.op.i.i.i.i.i.i = lshr i32 -1, %sub11.i.neg.op.i.i.i.i.i.i, !dbg !2599
  %shr.i.i.i.i.i.i = select i1 %cmp.not.i.i.i.i.i.i.i, i32 %sub11.i.neg.op.op.i.i.i.i.i.i, i32 -1, !dbg !2599
  tail call void @llvm.nvvm.bar.warp.sync(i32 %shr.i.i.i.i.i.i) #10, !dbg !2599
  br label %_Z17FastInBlockReduceIf8TCudaAddIfEET_iPVS2_iN2cl4sycl7nd_itemILi1EEE.exit.i.i, !dbg !2601
```
As one may notice, DPC++ code computes thread mask with the help of quite many additional instructions while CUDA just uses -1 value.

**Comment by Pennycook** [comment] 2021-09-13 18:55
You can see where the mask is being generated here: https://github.com/intel/llvm/blob/f26492503ad4aa66404b138db12a2cdec4577d8a/sycl/include/CL/sycl/detail/spirv.hpp#L496-L503

Used here:
https://github.com/intel/llvm/blob/f26492503ad4aa66404b138db12a2cdec4577d8a/sycl/include/CL/sycl/detail/spirv.hpp#L527-L536

The max sub-group size is always 32, but the sub-group size may be less than that (in the last sub-group of each work-group).  Most of the extra instructions here are computing `__spirv_SubgroupSize()` -- the chain of multiplications computes the work-group's linear size, which is used to compute the remainder modulo 32 (see [here](https://github.com/intel/llvm/blob/sycl/libclc/ptx-nvidiacl/libspirv/workitem/get_sub_group_size.cl)).

There are two potential fixes here, but I don't know enough about CUDA's architecture to say which is best (or even possible).  Leaving my thoughts here in the hopes somebody else can shed some light on things.

1. Find a smarter way to compute the number of work-items in the last sub-group (or a mask representing that).
    
2. Always use `0xFFFFFFFF` as the mask.
    This would be equivalent to what the CUDA code is doing.  I didn't write things this way initially because I couldn't convince myself it was safe.  I was concerned because the NVIDIA documentation [here](https://docs.nvidia.com/cuda/nvvm-ir-spec/index.html#nvvm-intrin-warp-level-datamove) says: "For `compute_62` or below, all threads in `%membermask` must call the same `@llvm.nvvm.shfl.sync.i32()` in convergence, and only threads belonging to the `%membermask` can be active when the intrinsic is called. Otherwise, the behavior is undefined."

**Comment by anton-v-gorshkov** [comment] 2021-09-14 12:10
Thanks, @Pennycook! Can we simply leave existing solution for compute_62- and use 0xFFFFFFFF mask for compute_70+?

**Comment by bader** [comment] 2021-09-14 14:26
> It's possible that using `0xFFFFFFFF` here is safe because we know (from the SYCL spec) that all active CUDA threads will hit the barrier and the others are exited (or never existed?), but I'm really just guessing. If all the tests pass with `0xFFFFFFFF` and @bader thinks that's acceptable we could give it a go -- otherwise I'd feel much more comfortable if somebody from Codeplay could weigh in on what they think is safe.

@AerialMantis, does it sounds reasonable to you?

**Comment by npmiller** [comment] 2021-11-25 19:02
Hello,

So I've been looking into this, I'm currently trying to get clarifications on if using `0xFFFFFFFF` for the mask would be valid so hopefully we'll have an answer on that soon.

However I've been experimenting with a hack/patch to do that:
* [membermask-hack.txt](https://github.com/intel/llvm/files/7604848/membermask-hack.txt)

I'm not seeing any new failures in the lit tests or `llvm-test-suite` with it, but I'm not sure how well this is exercised.

However running the benchmark with it I'm actually not seeing significant performance difference between the version with `0xFFFFFFFF` and the version computing the mask, looking at the assembly it looks like the compiler is smart enough to optimize the mask computation and only compute it once in the function and re-use it so the impact is a lot more negligible.

In addition I'm also not really able to reproduce the performance difference you're seeing with the latest `dpcpp`, with or without the membermask patch, however I don't have exactly the same setup available.

Here's the different configurations I tried:

|Configuration|CholeskyDecomposition|ForwardTranspose|ForwardDirect
|--|--|--|--
|Titan RTX NVCC 11.2|1.0041ms|308.99us|303.78us
|Titan RTX DPCPP mask|868.57us|312.90us|303.23us
|Titan RTX DPCPP 0xFFFFFFFF|867.17us|313.02us|302.21us
|GTX 1050 Ti NVCC 11.4|4.4138ms|924.19us|912.16us
|GTX 1050 Ti DPCPP mask|3.6245ms|937.47us|911.97us
|GTX 1050 Ti DPCPP 0xFFFFFFFF|3.6253ms|937.47us|913.98us

It does look like we're still a little bit slower than NVCC for `ForwardTranspose` and `ForwardDirect` but not by much, and especially changing the mask doesn't seem to have any effect.

I'll try to rollback my DPCPP build to the revision mentioned and see if I can reproduce the performance difference with an older compiler.

However, if you can, it would be interesting to see numbers on your specific setup with the latest compiler, and maybe also with the patch attached, just in case the performance issue has been resolved since then, and to try and confirm if the masking is actually the issue.

Thanks!

**Comment by anton-v-gorshkov** [comment] 2021-11-26 10:39
Thanks, @npmiller! Yes, I can confirm that somewhere in between of 7dcb4042e3d583d9c8c88ca11ab1c9d287a3034d and 626682032ac4f711cea9c73715b474c739b99b38 commit compiler starts to work faster for this case. Performance degradation over CUDA for the kernel drops from ~20% to ~5%.
Despite this, it may still be valuable to use FULL_MASK instead of doing its computation (if legitimate) since in other cases compiler may behave differently.

**Comment by npmiller** [comment] 2021-11-29 09:46
> Thanks, @npmiller! Yes, I can confirm that somewhere in between of [7dcb404](https://github.com/intel/llvm/commit/7dcb4042e3d583d9c8c88ca11ab1c9d287a3034d) and [6266820](https://github.com/intel/llvm/commit/626682032ac4f711cea9c73715b474c739b99b38) commit compiler starts to work faster for this case. Performance degradation over CUDA for the kernel drops from ~20% to ~5%.

That's great news!

> Despite this, it may still be valuable to use FULL_MASK instead of doing its computation (if legitimate) since in other cases compiler may behave differently.

Agreed, I'm trying to get clarifications from Nvidia on whether what we discussed here would be a valid use of these instructions, I'll update here, and potentially the code when I know more.

**Comment by npmiller** [comment] 2021-12-03 11:33
Hello @Pennycook,

I was able to get some clarification on this and it is actually valid to have exited or inactive threads in the membermask, the NVVM IR documentation suggesting otherwise is incorrect, and hopefully will be fixed in the future. 

So given that the SYCL built-ins are required to be convergent and that it is safe to have inactive threads in the membermask, I believe it should then be safe to just use the `FULL_MASK` in libclc.

Do you agree with this or can you think of any other scenarios where this could cause issues?

**Comment by Pennycook** [comment] 2021-12-03 15:51
> Do you agree with this or can you think of any other scenarios where this could cause issues?

I agree.  The only way we can encounter these primitives today is via sub-groups, which carry the convergence requirements you mentioned.  I do think we'll want to introduce support for more interesting cases in the future, but I think we'll want to keep all of that functionality separate anyway, and should introduce separate implementations of the primitives that are mask-aware.

Thanks again for chasing this up and driving it to a conclusion!

**Comment by AerialMantis** [comment] 2021-12-07 00:11
With the past change that has improved the performance and https://github.com/intel/llvm/pull/5079 being merged, we think this ticket could be closed. @anton-v-gorshkov @Pennycook what do you think?

**Comment by anton-v-gorshkov** [comment] 2021-12-07 05:50
Fine for me.

**Comment by Pennycook** [comment] 2021-12-07 15:00
> With the past change that has improved the performance and #5079 being merged, we think this ticket could be closed.

I also agree, so closing this now.

**Closed by Pennycook** 2021-12-07 15:00 UTC
Labels: bug, performance, cuda, blocker
