### ISSUE TITLE
[CUDA] unable to compile tip of sycl branch

### ISSUE THREAD

**Issue by cgleggett** [intel/llvm#1590] opened 2020-04-27 05:38 UTC
using gcc 8.4.0, cmake 3.14.7 and ninja 1.7.2
llvm git hash: cece82e63f6

```
> python $DPCPP_HOME/llvm/buildbot/configure.py --cuda --shared-libs --cmake-opt=-DCMAKE_INSTALL_PREFIX=/opt/dpcpp/2020.04.26-cuda-cece82e63f6

> python $DPCPP_HOME/llvm/buildbot/compile.py


[455/2747] Building CXX object tools/sycl/sour...CMakeFiles/sycl_object.dir/detail/config.cpp.o
FAILED: tools/sycl/source/CMakeFiles/sycl_object.dir/detail/config.cpp.o 
/opt/gcc/8.4.0/bin/g++  -DUSE_PI_CUDA -DXPTI_ENABLE_INSTRUMENTATION -DXPTI_STATIC_LIBRARY -D_DEBUG -D_GNU_SOURCE -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS -Itools/sycl/source -I/bld4/home/leggett/intel/git/llvm/sycl/source -Iinclude -I/bld4/home/leggett/intel/git/llvm/llvm/include -I/bld4/home/leggett/intel/git/llvm/xpti/include -I/bld4/home/leggett/intel/git/llvm/sycl/include -Itools/sycl/OpenCL/inc -fPIC -fvisibility-inlines-hidden -Werror=date-time -Wall -Wextra -Wno-unused-parameter -Wwrite-strings -Wcast-qual -Wno-missing-field-initializers -pedantic -Wno-long-long -Wimplicit-fallthrough -Wno-maybe-uninitialized -Wno-class-memaccess -Wno-noexcept-type -Wdelete-non-virtual-dtor -Wno-comment -fdiagnostics-color -ffunction-sections -fdata-sections -Wall -Wextra -Wno-deprecated-declarations -Werror -O2    -UNDEBUG -fvisibility=hidden -fvisibility-inlines-hidden -std=c++11 -MD -MT tools/sycl/source/CMakeFiles/sycl_object.dir/detail/config.cpp.o -MF tools/sycl/source/CMakeFiles/sycl_object.dir/detail/config.cpp.o.d -o tools/sycl/source/CMakeFiles/sycl_object.dir/detail/config.cpp.o -c /bld4/home/leggett/intel/git/llvm/sycl/source/detail/config.cpp
In function ‘void cl::sycl::detail::initValue(const char*, const char*)’,
    inlined from ‘void cl::sycl::detail::readConfig()’ at /bld4/home/leggett/intel/git/llvm/sycl/source/detail/config.cpp:96:16:
/bld4/home/leggett/intel/git/llvm/sycl/source/detail/config.cpp:42:12: error: ‘char* strncpy(char*, const char*, size_t)’ output may be truncated copying 16 bytes from a string of length 255 [-Werror=stringop-truncation]
     strncpy(SYCLConfigBase<Name>::MStorage, Value, MaxSize);                   \
     ~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/bld4/home/leggett/intel/git/llvm/sycl/source/detail/config.def:17:1: note: in expansion of macro ‘CONFIG’
 CONFIG(SYCL_PI_TRACE, 16, __SYCL_PI_TRACE)
 ^~~~~~
/bld4/home/leggett/intel/git/llvm/sycl/source/detail/config.cpp:42:12: error: ‘char* strncpy(char*, const char*, size_t)’ output may be truncated copying 16 bytes from a string of length 255 [-Werror=stringop-truncation]
     strncpy(SYCLConfigBase<Name>::MStorage, Value, MaxSize);                   \
     ~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/bld4/home/leggett/intel/git/llvm/sycl/source/detail/config.def:16:1: note: in expansion of macro ‘CONFIG’
 CONFIG(SYCL_BE, 16, __SYCL_BE)
 ^~~~~~
/bld4/home/leggett/intel/git/llvm/sycl/source/detail/config.cpp:42:12: error: ‘char* strncpy(char*, const char*, size_t)’ output may be truncated copying 1 byte from a string of length 255 [-Werror=stringop-truncation]
     strncpy(SYCLConfigBase<Name>::MStorage, Value, MaxSize);                   \
     ~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/bld4/home/leggett/intel/git/llvm/sycl/source/detail/config.def:14:1: note: in expansion of macro ‘CONFIG’
 CONFIG(SYCL_DISABLE_EXECUTION_GRAPH_CLEANUP, 1, __SYCL_DISABLE_EXECUTION_GRAPH_CLEANUP)
 ^~~~~~
/bld4/home/leggett/intel/git/llvm/sycl/source/detail/config.cpp:42:12: error: ‘char* strncpy(char*, const char*, size_t)’ output may be truncated copying 32 bytes from a string of length 255 [-Werror=stringop-truncation]
     strncpy(SYCLConfigBase<Name>::MStorage, Value, MaxSize);                   \
     ~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/bld4/home/leggett/intel/git/llvm/sycl/source/detail/config.def:13:1: note: in expansion of macro ‘CONFIG’
 CONFIG(SYCL_PRINT_EXECUTION_GRAPH, 32, __SYCL_PRINT_EXECUTION_GRAPH)
 ^~~~~~
cc1plus: all warnings being treated as errors
[467/2747] Building CXX object tools/sycl/plug...pencl/CMakeFiles/pi_opencl.dir/pi_opencl.cpp.o
In file included from tools/sycl/OpenCL/inc/CL/cl.h:20,
                 from tools/sycl/OpenCL/inc/CL/opencl.h:24,
                 from /bld4/home/leggett/intel/git/llvm/sycl/plugins/opencl/pi_opencl.cpp:17:
tools/sycl/OpenCL/inc/CL/cl_version.h:22:104: note: #pragma message: cl_version.h: CL_TARGET_OPENCL_VERSION is not defined. Defaulting to 220 (OpenCL 2.2)
 #pragma message("cl_version.h: CL_TARGET_OPENCL_VERSION is not defined. Defaulting to 220 (OpenCL 2.2)")
                                                                                                        ^
[476/2747] Building CXX object tools/sycl/sour...Files/sycl_object.dir/detail/buffer_impl.cpp.o
In file included from tools/sycl/OpenCL/inc/CL/cl.h:20,
                 from /bld4/home/leggett/intel/git/llvm/sycl/include/CL/sycl/detail/buffer_impl.hpp:11,
                 from /bld4/home/leggett/intel/git/llvm/sycl/source/detail/buffer_impl.cpp:9:
tools/sycl/OpenCL/inc/CL/cl_version.h:22:104: note: #pragma message: cl_version.h: CL_TARGET_OPENCL_VERSION is not defined. Defaulting to 220 (OpenCL 2.2)
 #pragma message("cl_version.h: CL_TARGET_OPENCL_VERSION is not defined. Defaulting to 220 (OpenCL 2.2)")
                                                                                                        ^
[480/2747] Building CXX object tools/sycl/sour...es/sycl_object.dir/detail/sycl_mem_obj_t.cpp.o
In file included from tools/sycl/OpenCL/inc/CL/cl.h:20,
                 from /bld4/home/leggett/intel/git/llvm/sycl/include/CL/sycl/detail/memory_manager.hpp:11,
                 from /bld4/home/leggett/intel/git/llvm/sycl/source/detail/sycl_mem_obj_t.cpp:9:
tools/sycl/OpenCL/inc/CL/cl_version.h:22:104: note: #pragma message: cl_version.h: CL_TARGET_OPENCL_VERSION is not defined. Defaulting to 220 (OpenCL 2.2)
 #pragma message("cl_version.h: CL_TARGET_OPENCL_VERSION is not defined. Defaulting to 220 (OpenCL 2.2)")
                                                                                                        ^
[490/2747] Building CXX object tools/sycl/sour...eFiles/sycl_object.dir/detail/image_impl.cpp.o
In file included from tools/sycl/OpenCL/inc/CL/cl.h:20,
                 from /bld4/home/leggett/intel/git/llvm/sycl/include/CL/sycl/detail/aligned_allocator.hpp:11,
                 from /bld4/home/leggett/intel/git/llvm/sycl/include/CL/sycl/detail/image_impl.hpp:11,
                 from /bld4/home/leggett/intel/git/llvm/sycl/source/detail/image_impl.cpp:9:
tools/sycl/OpenCL/inc/CL/cl_version.h:22:104: note: #pragma message: cl_version.h: CL_TARGET_OPENCL_VERSION is not defined. Defaulting to 220 (OpenCL 2.2)
 #pragma message("cl_version.h: CL_TARGET_OPENCL_VERSION is not defined. Defaulting to 220 (OpenCL 2.2)")
                                                                                                        ^
[495/2747] Building CXX object tools/sycl/sour...es/sycl_object.dir/detail/memory_manager.cpp.o
In file included from tools/sycl/OpenCL/inc/CL/cl.h:20,
                 from /bld4/home/leggett/intel/git/llvm/sycl/include/CL/sycl/detail/memory_manager.hpp:11,
                 from /bld4/home/leggett/intel/git/llvm/sycl/source/detail/memory_manager.cpp:9:
tools/sycl/OpenCL/inc/CL/cl_version.h:22:104: note: #pragma message: cl_version.h: CL_TARGET_OPENCL_VERSION is not defined. Defaulting to 220 (OpenCL 2.2)
 #pragma message("cl_version.h: CL_TARGET_OPENCL_VERSION is not defined. Defaulting to 220 (OpenCL 2.2)")
                                                                                                        ^
[505/2747] Building CXX object tools/sycl/sour...les/sycl_object.dir/detail/builtins_math.cpp.o
ninja: build stopped: subcommand failed.
Traceback (most recent call last):
  File "/bld4/home/leggett/intel/git/llvm/buildbot/compile.py", line 63, in <module>
    ret = main()
  File "/bld4/home/leggett/intel/git/llvm/buildbot/compile.py", line 59, in main
    return do_compile(args)
  File "/bld4/home/leggett/intel/git/llvm/buildbot/compile.py", line 37, in do_compile
    subprocess.check_call(cmake_cmd, cwd=abs_obj_dir)
  File "/usr/lib64/python2.7/subprocess.py", line 542, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['cmake', '--build', '/bld4/home/leggett/intel/git/llvm/build', '--', 'deploy-sycl-toolchain', 'deploy-opencl-aot', '-j', '72']' returned non-zero exit status 1


```

**Comment by bader** [comment] 2020-04-27 07:40
This seems to be a duplicate of https://github.com/intel/llvm/issues/1572. Particularly these warnings are reported here: https://github.com/intel/llvm/issues/1572#issuecomment-617842987.
@cgleggett, you can try this [fix](https://github.com/intel/llvm/issues/1572#issuecomment-617852979).

**Closed** 2020-04-27 07:40 UTC
Labels: cuda, duplicate
