### ISSUE TITLE
[L0] Plugin/level_zero_imm_cmdlist_per_thread.cpp fails in CI for unrelated changes

### ISSUE THREAD

**Issue by steffenlarsen** [intel/llvm#8753] opened 2023-03-23 13:46 UTC
The test Plugin/level_zero_imm_cmdlist_per_thread.cpp has been seen to fail on Windows pre-commit CI with the output:

```

******************** TEST 'SYCL :: Plugin/level_zero_imm_cmdlist_per_thread.cpp' FAILED ********************
Script:
--
: 'RUN: at line 3';    clang-cl.exe /EHsc     -fsycl -fsycl-targets=spir64  ze_loader.lib /Iinstall\include  llvm-test-suite\SYCL\Plugin\level_zero_imm_cmdlist_per_thread.cpp -o build\SYCL\Plugin\Output\level_zero_imm_cmdlist_per_thread.cpp.tmp.out
: 'RUN: at line 4';   env SYCL_PI_LEVEL_ZERO_USE_IMMEDIATE_COMMANDLISTS=1 ZE_DEBUG=4  env ONEAPI_DEVICE_SELECTOR=ext_oneapi_level_zero:gpu  build\SYCL\Plugin\Output\level_zero_imm_cmdlist_per_thread.cpp.tmp.out 2>&1 | FileCheck --check-prefixes=CHECK-ONE-CMDLIST llvm-test-suite\SYCL\Plugin\level_zero_imm_cmdlist_per_thread.cpp
: 'RUN: at line 5';   env SYCL_PI_LEVEL_ZERO_USE_IMMEDIATE_COMMANDLISTS=2 ZE_DEBUG=4  env ONEAPI_DEVICE_SELECTOR=ext_oneapi_level_zero:gpu  build\SYCL\Plugin\Output\level_zero_imm_cmdlist_per_thread.cpp.tmp.out 2>&1 | FileCheck --check-prefixes=CHECK-PER-THREAD-CMDLIST llvm-test-suite\SYCL\Plugin\level_zero_imm_cmdlist_per_thread.cpp
--
Exit Code: 3221226505

Command Output (stdout):
--
$ ":" "RUN: at line 3"
note: command had no output on stdout or stderr
$ "clang-cl.exe" "/EHsc" "-fsycl" "-fsycl-targets=spir64" "ze_loader.lib" "/Iinstall\include" "llvm-test-suite\SYCL\Plugin\level_zero_imm_cmdlist_per_thread.cpp" "-o" "build\SYCL\Plugin\Output\level_zero_imm_cmdlist_per_thread.cpp.tmp.out"
note: command had no output on stdout or stderr
$ ":" "RUN: at line 4"
note: command had no output on stdout or stderr
$ "env" "SYCL_PI_LEVEL_ZERO_USE_IMMEDIATE_COMMANDLISTS=1" "ZE_DEBUG=4" "env" "ONEAPI_DEVICE_SELECTOR=ext_oneapi_level_zero:gpu" "build\SYCL\Plugin\Output\level_zero_imm_cmdlist_per_thread.cpp.tmp.out"
note: command had no output on stdout or stderr
error: command failed with exit status: 0xc0000409
$ "FileCheck" "--check-prefixes=CHECK-ONE-CMDLIST" "llvm-test-suite\SYCL\Plugin\level_zero_imm_cmdlist_per_thread.cpp"
note: command had no output on stdout or stderr

--
```

Failure seen on https://github.com/intel/llvm/pull/8682.

**Comment by rdeodhar** [comment] 2023-03-23 16:30
For a brief period the compilation command was missing the %threads_lib reference. That has been corrected.

**Comment by sarnex** [comment] 2023-05-03 13:39
Dupe of https://github.com/intel/llvm/issues/9117 and that one has more discussion, so closing this one

**Closed by sarnex** 2023-05-03 13:39 UTC
Labels: bug, confirmed
