### ISSUE TITLE
[SYCL] the values read in a callee do not match the values passed from a caller  

### ISSUE THREAD

**Issue by zjin-lcf** [intel/llvm#4875] opened 2021-11-02 15:08 UTC
For the sycl program https://github.com/zjin-lcf/HeCBench/blob/master/fluidSim-sycl/

Verification fails because calling the device function "double ced(double rho, double weight, double2 dir, double2 u)" in kernels.cpp does not pass the values of the type "double2" correctly for the function parameter "double2 dir". 

Thanks.

To reproduce on a GPU:
make 
./main 1

**Comment by zjin-lcf** [comment] 2021-11-06 17:01
Please confirm.

**Comment by romanovvlad** [comment] 2022-02-09 13:58
@zjin-lcf 
Reproduced the issue and it indeed seems to be related to how `double2` is passed to `ced`. So far, I tend to say that it's a product issue, but more debugging is required.
It would be great if there was a small reproducer.

**Comment by zjin-lcf** [comment] 2022-02-09 14:34
Thank you for running the example. This is a great example developed by AMD with codes and documentation. I hope it is a good reproducer for you.

**Comment by psamolysov-intel** [comment] 2022-02-17 10:48
Can be reproduced on Windows too on GPU (both drivers, level zero as well as OpenCL) and on CPU.

To build the demo application for CPU and test:

```
> clang++ -O3 -fsycl -I..\include -DVERIFY -o main.exe main.cpp reference.cpp kernels.cpp
> set SYCL_DEVICE_FILTER=opencl:cpu
> main.exe 1
FAIL
```

To build the demo application for GPU and test:

```
> clang++ -O3 -fsycl -I..\include -DVERIFY -DUSE_GPU -o main.exe main.cpp reference.cpp kernels.cpp
> set SYCL_DEVICE_FILTER=opencl:gpu
> main.exe 1
FAIL
> set SYCL_DEVICE_FILTER=ext_oneapi_level_zero:gpu
> main.exe 1
FAIL
```

After I've changed the code a bit, replacing this in `kernels.cpp` starting from line 97:

```c++
    e0            = ced(rho, weight[0], (double2)(0), u);
    e1234.x() = ced(rho, weight[1], double2{dirX.s0(), dirY.s0()}, u);
    e1234.y() = ced(rho, weight[2], (double2)(dirX.s1(), dirY.s1()), u);
    e1234.z() = ced(rho, weight[3], (double2)(dirX.s2(), dirY.s2()), u);
    e1234.w() = ced(rho, weight[4], (double2)(dirX.s3(), dirY.s3()), u);
    e5678.x() = ced(rho, weight[5], (double2)(dirX.s4(), dirY.s4()), u);
    e5678.y() = ced(rho, weight[6], (double2)(dirX.s5(), dirY.s5()), u);
    e5678.z() = ced(rho, weight[7], (double2)(dirX.s6(), dirY.s6()), u);
    e5678.w() = ced(rho, weight[8], (double2)(dirX.s7(), dirY.s7()), u);
```

with this:

```c++
    e0            = ced(rho, weight[0], {0, 0}, u);
    e1234.x() = ced(rho, weight[1], {dirX.s0(), dirY.s0()}, u);
    e1234.y() = ced(rho, weight[2], {dirX.s1(), dirY.s1()}, u);
    e1234.z() = ced(rho, weight[3], {dirX.s2(), dirY.s2()}, u);
    e1234.w() = ced(rho, weight[4], {dirX.s3(), dirY.s3()}, u);
    e5678.x() = ced(rho, weight[5], {dirX.s4(), dirY.s4()}, u);
    e5678.y() = ced(rho, weight[6], {dirX.s5(), dirY.s5()}, u);
    e5678.z() = ced(rho, weight[7], {dirX.s6(), dirY.s6()}, u);
    e5678.w() = ced(rho, weight[8], {dirX.s7(), dirY.s7()}, u);
```

(manually creating temporary `double2` objects instead of just using type casting), the test started passing on GPU (L0 and OpenCL) as well as on CPU.

It looks like clang treats the expression `(dirX.s0(), dirY.s0())` as the comma operator and just casting `dirY.s0()` to `double2`.

The following small reproducer was developed:

```c++
#include <sycl/sycl.hpp>
#include <iostream>

using namespace sycl;

int main() {
  const double8 dirX = {0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8};
  const double8 dirY = {1.1, 1.2, 1.3, 1.4, 1.5, 1.6, 1.7, 1.8};

  const double2 dbl1 = (double2)(dirX.s1(), dirY.s1());
  const double2 dbl2 = {dirX.s1(), dirY.s1()};

  std::cout << "first  double2: (" << dbl1.x() << ", " << dbl1.y() << ")\n";
  std::cout << "second double2: (" << dbl2.x() << ", " << dbl2.y() << ")\n";

  return 0;
}
```

And it outputs the following:

```
first  double2: (1.2, 1.2) ; so, only the second "operand" does matter!
second double2: (0.2, 1.2)
```

and If constants used in the type casting operator:

```
const double2 dbl1 = (double2)(0.5, 25.3);
```

... clang agrees with me:

```
vectors-demo.cpp:10:34: warning: left operand of comma operator has no effect [-Wunused-value]
  const double2 dbl1 = (double2)(0.5, 25.3);
```

@zjin-lcf I'm not sure this is a bug, it looks like a problem in the code of the test. I'm closing the issue but if you disagree, you always are welcome to re-open it.

**Closed by psamolysov-intel** 2022-02-17 10:48 UTC
Labels: bug, confirmed

**Comment by keryell** [comment] 2022-02-18 06:31
This is an interesting example showing that SYCL is pure C++ while OpenCL has its own life.
