### ISSUE TITLE
Clang LoopVectorizePass crashes with -march=native

### ISSUE THREAD

**Issue by ianayl** [intel/llvm#14288] opened 2024-06-25 15:20 UTC
### Describe the bug

The following snippet of code causes intel/llvm's `clang` to crash when compiled with `-O2` and `-march=native`:
```cpp
// vectorizer_bug.cpp:
#include <sycl/sycl.hpp>

int main() {
    sycl::queue Q;
    std::vector<sycl::event> events;

    events.push_back(Q.submit([&](sycl::handler& cgh) { /* Could be anything, or nothing */ }));
}
```
The full command I am using is:
```sh
$DPCPP_HOME/build/bin/clang++ -I$DPCPP_HOME/build/include/ -I$DPCPP_HOME/build/include/sycl/ -O2 -march=native -S -emit-llvm ~/vectorizer_bug.cpp
```
Please see the `clang` stack dump below. Although I am not using `-fsycl` here and manually adding the include paths, using `-fsycl` produces the same crash. Note that this example _does_ work just fine on `clang` 18.1.0, although I have not been able to confirm yet if this is an issue on `clang` 19.0.0, as some of the syntax used in `include/sycl` no longer works with `clang` 19.0.0.

This specific example can be seen in [unisa-hpc/sycl-bench](https://github.com/unisa-hpc/sycl-bench/blob/ae02405d99d58c9364552129af7396bfcf8895ee/micro/arith.cpp#L50), thus causing the benchmarks to fail on dpc++.

### To reproduce

1. Create `vectorizer_bug.cpp` from the code snippet above
2. Use the following command to compile:
    ```sh
    $DPCPP_HOME/build/bin/clang++ -I$DPCPP_HOME/build/include/ -I$DPCPP_HOME/build/include/sycl/ -O2 -march=native ./vectorizer_bug.cpp
    ```

### Environment

This seems to be a problem with `clang`, I don't think my environment matters.
- OS: Linux
- Target device: Intel CPU
- DPC++ version: clang version 19.0.0git (https://github.com/intel/llvm f38bd93546e74197dacbda8740f85826fdf14e63)

### Additional context

Here is the snippet of the crash trace most relevant to the crash:
```
[...]
Unknown type!
UNREACHABLE executed at .../syclos-ws/upstream/llvm/lib/CodeGen/ValueTypes.cpp:592!
PLEASE submit a bug report to https://github.com/intel/llvm/issues and include the crash backtrace, preprocessed source, and associated run script.
Stack dump:
0.      Program arguments: build/bin/clang++ -I.../syclos-ws/upstream/build/include/ -I.../syclos-ws/upstream/build/include/sycl/ -O2 -march=native -S -emit-llvm .../vectorizer_bug.cpp
1.      <eof> parser at end of file
2.      Optimizer
 #0 0x000055d3bfa47ac0 llvm::sys::PrintStackTrace(llvm::raw_ostream&, int) (build/bin/clang+++0x2244ac0)
 #1 0x000055d3bfa44ecf llvm::sys::RunSignalHandlers() (build/bin/clang+++0x2241ecf)
 #2 0x000055d3bf99c9c8 CrashRecoverySignalHandler(int) CrashRecoveryContext.cpp:0:0
 #3 0x00007f8fb3524520 (/lib/x86_64-linux-gnu/libc.so.6+0x42520)
 #4 0x00007f8fb3578a7c __pthread_kill_implementation ./nptl/./nptl/pthread_kill.c:44:76
 #5 0x00007f8fb3578a7c __pthread_kill_internal ./nptl/./nptl/pthread_kill.c:78:10
 #6 0x00007f8fb3578a7c pthread_kill ./nptl/./nptl/pthread_kill.c:89:10
 #7 0x00007f8fb3524476 gsignal ./signal/../sysdeps/posix/raise.c:27:6
 #8 0x00007f8fb350a7f3 abort ./stdlib/./stdlib/abort.c:81:7
 #9 0x000055d3bf9a6c8e (build/bin/clang+++0x21a3c8e)
#10 0x000055d3bf0461c5 (build/bin/clang+++0x18431c5)
#11 0x000055d3be647cb2 llvm::X86TTIImpl::getInterleavedMemoryOpCostAVX512(unsigned int, llvm::FixedVectorType*, unsigned int, llvm::ArrayRef<unsigned int>, llvm::Align, unsigned int, llvm::TargetTransformInfo::TargetCostKind, bool, bool) (build/bin/clang+++0xe44cb2)
#12 0x000055d3bebe35e6 llvm::TargetTransformInfo::getInterleavedMemoryOpCost(unsigned int, llvm::Type*, unsigned int, llvm::ArrayRef<unsigned int>, llvm::Align, unsigned int, llvm::TargetTransformInfo::TargetCostKind, bool, bool) const (build/bin/clang+++0x13e05e6)
#13 0x000055d3c1417e71 llvm::LoopVectorizationCostModel::getInterleaveGroupCost(llvm::Instruction*, llvm::ElementCount) (build/bin/clang+++0x3c14e71)
#14 0x000055d3c1436063 llvm::LoopVectorizationCostModel::setCostBasedWideningDecision(llvm::ElementCount) (build/bin/clang+++0x3c33063)
#15 0x000055d3c1454b82 llvm::LoopVectorizationPlanner::plan(llvm::ElementCount, unsigned int) (build/bin/clang+++0x3c51b82)
#16 0x000055d3c14581e5 llvm::LoopVectorizePass::processLoop(llvm::Loop*) (build/bin/clang+++0x3c551e5)
#17 0x000055d3c145b23e llvm::LoopVectorizePass::runImpl(llvm::Function&, llvm::ScalarEvolution&, llvm::LoopInfo&, llvm::TargetTransformInfo&, llvm::DominatorTree&, llvm::BlockFrequencyInfo*, llvm::TargetLibraryInfo*, llvm::DemandedBits&, llvm::AssumptionCache&, llvm::LoopAccessInfoManager&, llvm::OptimizationRemarkEmitter&, llvm::ProfileSummaryInfo*) (build/bin/clang+++0x3c5823e)
#18 0x000055d3c145c38d llvm::LoopVectorizePass::run(llvm::Function&, llvm::AnalysisManager<llvm::Function>&) (build/bin/clang+++0x3c5938d)
#19 0x000055d3c0e6f146 llvm::detail::PassModel<llvm::Function, llvm::LoopVectorizePass, llvm::AnalysisManager<llvm::Function> >::run(llvm::Function&, llvm::AnalysisManager<llvm::Function>&) (build/bin/clang+++0x366c146)
[...]
```

**Comment by dm-vodopyanov** [comment] 2024-06-25 15:44
@ianayl thanks for the detailed report.

From the log
```
Unknown type!
UNREACHABLE executed at /sources/llvm/lib/CodeGen/ValueTypes.cpp:592!
```
it looks like the root cause should be the same as in https://github.com/intel/llvm/issues/14276. I'm closing the current issue to track the progress on fixing the crash in https://github.com/intel/llvm/issues/14276

**Closed by dm-vodopyanov** 2024-06-25 15:44 UTC
Labels: bug
