### ISSUE TITLE
[SYCL] ICE: Instruction Combining seems stuck in an infinite loop after 1000 iterations.

### ISSUE THREAD

**Issue by Vsevolod-Livinskij** [intel/llvm#1896] opened 2020-06-15 22:34 UTC
Error:
>\>$ clang++ -fsycl -O3 small.cpp && ./a.out
**Internal compiler error** Instruction Combining seems stuck in an infinite loop after 1000 iterations.

Reproducer:
```c++
#include <CL/sycl.hpp>

unsigned int app_var_8 = 1626891678U;
int app_var_12 = 1865482409;
short app_var_17 = 14858;

int main() {
    using namespace cl::sycl;
    {
        queue myQueue;
        buffer<unsigned int, 1> var_8_buf { &app_var_8, range<1>(1) };
        buffer<int, 1> var_12_buf { &app_var_12, range<1>(1) };
        buffer<short, 1> var_17_buf { &app_var_17, range<1>(1) };
        myQueue.submit([&](handler & cgh) {
            auto var_8 = var_8_buf.get_access<access::mode::read>(cgh);
            auto var_12 = var_12_buf.get_access<access::mode::read>(cgh);
            auto var_17 = var_17_buf.get_access<access::mode::write>(cgh);
            cgh.single_task<class test_func>([=] ()
            {
                var_17[0] = var_8[0] - (~var_12[0] != 0);
            }
            );
        });
    }
}
```

Clang version:
clang version 11.0.0 (https://github.com/intel/llvm 4fdd0ab88440deb7842778275faadb7892069640)

**Comment by dbabokin** [comment] 2020-06-16 00:48
Would be useful to check if it's same as https://bugs.llvm.org/show_bug.cgi?id=46271 or not.

**Comment by AlexeySachkov** [comment] 2022-01-31 17:39
Using clang version 14.0.0 (git@github.com:intel/llvm.git 21a31428985dabdf76dd4fd76a3b22d77f8916f7) I'm not able to reproduce this issue anymore, closing it.

**Closed by AlexeySachkov** 2022-01-31 17:39 UTC
Labels: bug
