### ISSUE TITLE
Compile fail in sycl_span.hpp 150 42 error: SIZE_MAX not declared

### ISSUE THREAD

**Issue by MaxwellDupre** [intel/llvm#9348] opened 2023-05-06 08:49 UTC
Compiling on linux:
/home/me/sycl_workspace/llvm/build/include/sycl/sycl_span.hpp:150:42: error: ‘SIZE_MAX’ was not declared in this scope
  150 | inline constexpr size_t dynamic_extent = SIZE_MAX;
      |                                          ^~~~~~~~
/home/me/sycl_workspace/llvm/build/include/sycl/sycl_span.hpp:131:1: note: ‘SIZE_MAX’ is defined in header ‘<cstdint>’; did you forget to ‘#include <cstdint>’?
  130 | #include <iterator>    // for iterators
  +++ |+#include <cstdint>
  131 | #include <type_traits> // for remove_cv, etc
/home/me/sycl_workspace/llvm/build/include/sycl/sycl_span.hpp:629:23: error: trailing return type ‘<type error>’ of deduction guide is not a specialization of ‘sycl::_V1::span<_Tp, _Extent>’
  629 | span(_Container &) -> span<typename _Container::value_type>;
      |                       ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/me/sycl_workspace/llvm/build/include/sycl/sycl_span.hpp:632:29: error: trailing return type ‘<type error>’ of deduction guide is not a specialization of ‘sycl::_V1::span<_Tp, _Extent>’
  632 | span(const _Container &) -> span<const typename _Container::value_type>;
      |                             ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[2805/3077] Building CXX object tools/sycl/source/...cl_object.dir/detail/scheduler/graph_builder.cpp.o
ninja: build stopped: subcommand failed.
Traceback (most recent call last):
  File "/home/me/sycl_workspace/llvm/buildbot/compile.py", line 71, in <module>
    ret = main()
          ^^^^^^
  File "/home/me/sycl_workspace/llvm/buildbot/compile.py", line 67, in main
    return do_compile(args)
           ^^^^^^^^^^^^^^^^
  File "/home/me/sycl_workspace/llvm/buildbot/compile.py", line 42, in do_compile
    subprocess.check_call(cmake_cmd, cwd=abs_obj_dir)
  File "/usr/lib64/python3.11/subprocess.py", line 413, in check_call
    raise CalledProcessError(retcode, cmd)

**To Reproduce**
Followed https://github.com/intel/llvm/blob/sycl/sycl/doc/GetStartedGuide.md#build-dpc-toolchain-with-support-for-nvidia-cuda

At python $DPCPP_HOME/llvm/buildbot/compile.py 

- OS: Fedora 38 Linux 6.2.14-300.fc38. x86_64 #1 SMP PREEMPT_DYNAMIC 
- Target: nVidia GPU
- DPC++ version:  ?
- Dependencies version:

**Comment by dm-vodopyanov** [comment] 2023-05-28 09:57
The problem should be fixed by https://github.com/intel/llvm/pull/9363, closing the issue, feel free re-open if the problem is still here.

**Closed by dm-vodopyanov** 2023-05-28 09:57 UTC
Labels: bug
