### ISSUE TITLE
[sycl-post-link] Handle SYCL_EXTERNAL functions in sycl-post-link

### ISSUE THREAD

**Issue by DenisBakhvalov** [intel/llvm#3239] opened 2021-02-21 22:30 UTC
Currently, the `sycl-post-link` tool only processes kernel functions and skips `SYCL_EXTERNAL` functions. So, for example, if splitting of the device code takes place, we would lose SYCL_EXTERNAL functions.

I think, most of the time we use `sycl-post-link`, all external functions are already resolved, however, I'm not 100% sure there no use case when sycl-post-link must handle those.

**Comment by KornevNikita** [comment] 2024-05-17 11:36
Hi! There have been no updates for at least the last 60 days, though the ticket has assignee(s).

      @AlexeySachkov @Fznamznon, could I ask you to take one of the following actions? :)
      - Please provide an update if you have any (or just a small comment if you don't have any yet).
      - OR mark this issue with the 'confirmed' label if you have confirmed the problem/request and our team should work on it.
      - OR close the issue if it has been resolved.
      - OR take any other suitable action.

      Thanks!

**Comment by Fznamznon** [comment] 2024-05-21 08:31
No updates from my side, and reassigning myself since I won't be having bandwidth to work on this one.

PS Doesn't https://github.com/intel/llvm/pull/3793 implement what the issue suggests?

**Comment by KornevNikita** [comment] 2024-05-21 08:35
> This PR is supposed to fix https://github.com/intel/llvm/issues/3239.

Yep, looks so. Then closing the issue. @AlexeySachkov please re-open if needed.

**Closed by KornevNikita** 2024-05-21 08:35 UTC
Labels: enhancement
