### ISSUE TITLE
[SYCL] Poor Performance - Low bandwidth of SYCL kernel for Eltwise Primitive

### ISSUE THREAD

**Issue by AvijitBag** [intel/llvm#8050] opened 2023-01-19 05:58 UTC
**Describe the bug**
This reproducer is created for enhancing the performance, to achieve  higher bandwidth for the SYCL implementation of
Eltwise primitive on Nvidia.
This reproducer computes the Eltwise abs algorithm with post ops for forward and then the memory bandwidth is calculated. Similarly, for backward propagation relu algorithm is computed and memory bandwidth is calculated. 

**Reproduce**

For the reproducer code, refer the attachments setup.sh, eltwise.cpp, eltwise_kernels.hpp and sycl_post_ops.hpp

1. Go to the directory having the reproducer files and run the below script to setup the environment.
  source setup.sh

2. To compile, run.
  clang++ -O2 -fsycl -fsycl-targets=nvptx64-nvidia-cuda eltwise.cpp

3. The above generates the output file. To see the output bandwidth, run
   ./a.out

**Observed behaviour**

For, N = 16, C = 64, D = 1, H = 56, W = 56
Propagation : Forward 
Alg : Abs 
Post-ops: binary : Add

Result,
Total time  = 0.004545 s 
Total bandwidth = 19.783365 Gb/s 

_________________________________

For, N = 50, C = 10, D = 10, H = 10, W = 10 and Alpha = 0.00, Beta = 4.00
Propagation : Backward 
Alg : Relu

Result,
Total time  = 0.000398 s 
Total bandwidth  = 15.075377 Gb/s 

__________________________________________

**Expected behavior**
The ideal behavior is to attain the maximum bandwidth (i.e., CLPeak value for Float16 = 251.94 GBPS) for any input size.
For the current reproducer higher bandwidth is expected i.e., a minimum of 100 GBPS is expected.

**Environment :**

- OS: Ubuntu 22.04.1 LTS
- Target device and vendor: Nvidia, Tesla T4
- DPC++ version: clang version 15.0.0 (https://github.com/intel/llvm.git https://github.com/intel/llvm/commit/0c7a1e18978754451f5c2c95129721297e2c2411)
- Dependencies version: Driver Version: 495.29.05 CUDA Version: 11.5

**Additional context**
Note: The inputs dimension for the primitives are hard code and all tensor values are automatically filled. 
Currently, for forward abs alg with binary post add is implemented and for backward relu alg is implemented.
 
The reproducer can be tested by switching the flag forward or backward and changing the dimensions values(N,C,D,H,W) in eltwise.cpp as illustrated below.

In reproducer for Forward, only the N,C,D,H & W values need to be changed in line 29 -33 inside forward function 
    int64_t N = 16;
    int64_t C = 64;
    int64_t D = 1;
    int64_t H = 56;
    int64_t W = 56; 

Similar for Backward, only the N,C,D,H & W values need to be changed in line 162 -166 inside backward function 
    int64_t N = 50;
    int64_t C = 10;
    int64_t D = 10;
    int64_t H = 10;
    int64_t W = 10;

And, For Forward & Backward a flag is there, by changing it we can switch forward to backward or vice-versa.(line no :273)

    isForward= true; 

**Source Files**

[eltwise_reproducer.zip](https://github.com/intel/llvm/files/10453889/eltwise_reproducer.zip)

**Comment by JackAKirk** [comment] 2023-01-20 15:17
I'm betting this is another inline issue looking at the source code it. Basically the inline threshold is not high enough related to the inlining cost in the nvptx backend, and this affects both sycl cuda backend and clang cuda. I am currently benchmarking an improved value and an upstream patch will be made shortly to solve this.

**Comment by JackAKirk** [comment] 2023-01-20 17:18
FYI I think this small patch will fix your performance issue: https://reviews.llvm.org/D142232

**Comment by AvijitBag** [comment] 2023-01-24 07:24
We modified the code as per instruction. As attached below
![llvm_source_diff](https://user-images.githubusercontent.com/90190061/214233038-4bee511c-5e01-4130-8afc-0381a70642a0.png)


After testing with modified clang++ we found performance is similar to previous.

![image](https://user-images.githubusercontent.com/90190061/214233699-b78b21b5-5801-4a21-9ab4-9dadfc24d7e1.png)

**Comment by zjin-lcf** [comment] 2023-01-24 15:54
@AvijitBag 
I have a question. Does a CUDA version of the primitive meet your expectation ? Thanks.
" higher bandwidth is expected i.e., a minimum of 100 GBPS is expected."

**Comment by AvijitBag** [comment] 2023-01-25 05:42
We tested cudnn version  code on same hardware, we got performance above 200 GBPS as attached below

![image](https://user-images.githubusercontent.com/90190061/214488354-b4127c3b-84f5-42b2-accd-21c713988178.png)

**Comment by AvijitBag** [comment] 2023-01-25 11:41
We tested the cuda version of same primitive and found performance is slightly improved than sycl .

**Example:**
----------------------------
Total time  = 0.135804 s 
Total bandwidth = 82.762100 Gb/s

-------------------------------------- 

**Build process :**
nvcc -O3 eltwise.cu

---------------------------------------------
**Run process:**
./a.out

[eltwise_reproducer_cuda.zip](https://github.com/intel/llvm/files/10498873/eltwise_reproducer_cuda.zip)

**Comment by JackAKirk** [comment] 2023-01-25 11:49
You compiled the sycl version with -O2 according to the above:

```
clang++ -O2 -fsycl -fsycl-targets=nvptx64-nvidia-cuda eltwise.cpp
```

and used -O3 with nvcc. Can you please compare like for like?

There could well be more things at play than the inlining issue. But we find that is the go-to thing to fix first atm.

**Comment by AvijitBag** [comment] 2023-01-30 10:21
This is comparsion result Sycl vs Cuda
-------------------------------------------------------------------------
clang++ -O3  -fsycl -fsycl-targets=nvptx64-nvidia-cuda eltwise.cpp 

Total time  = 0.002901 s 
Total bandwidth = 19.371638 Gb/s 

-------------------------------------------------------------------------
nvcc -O3 eltwise.cu 

Total time  = 0.000910 s 
Total bandwidth = 61.755077 Gb/s 

-------------------------------------------------------------------------
clang++ -O2  -fsycl -fsycl-targets=nvptx64-nvidia-cuda eltwise.cpp 

Total time  = 0.002849 s 
Total bandwidth = 19.725209 Gb/s 

-------------------------------------------------------------------------
nvcc -O2 eltwise.cu 

Total time  = 0.000914 s 
Total bandwidth = 61.484816 Gb/s 

-------------------------------------------------------------------------
We have tried, couldnt able to find the proper reason about performance degradation of sycl part
Please do help, if you know anything about it.

**Comment by zjin-lcf** [comment] 2023-02-07 01:28
Can you please update your cuda program (reproducer) to fix illegal memory accesses ?

CUDA Exception: Warp Illegal Address

Another question is the header file. Do you include `#include <bits/stdc++.h>`  for calling some functions ?

**Comment by AvijitBag** [comment] 2023-02-07 06:51
For Cuda, can you please share me the exact inputs with the files which you are using for testing.

Currently we are not getting any exception in our enviroment.

#include <bits/stdc++.h> is header file that includes standard library of c++. For ex:- std::cout ,etc

**Comment by zjin-lcf** [comment] 2023-02-07 12:53
nvcc -arch=sm_70 -O3 eltwise.cu
compute-sanitizer ./a.out   
Could you reproduce the issue ?

**Comment by AvijitBag** [comment] 2023-02-08 07:28
Changed few things,
In Kernel file, I used **int64_t** instead of **int**  and Instead of **#include <bits/stdc++.h>** I used `#include <iostream> #include <vector>"`

Now, please check if the exception is occurring or not
I checked now the exception is not occurring . 

Please find new modified cuda files
[Cuda_release.zip](https://github.com/intel/llvm/files/10682853/Cuda_release.zip)

**Comment by zjin-lcf** [comment] 2023-02-08 20:02
Thank you for your updates. I converted the cuda program to sycl using the DPCT tool, and then tried to browse the assembly instructions generated by the two compilers. The performance gap between the sycl and cuda is significant on an Nvidia v100 GPU.

```
    for (int64_t blk_idx = 0; blk_idx < 16; blk_idx++) {
        int64_t idx = base_idx + blk_idx;
        if (idx < wk_size) {

            Operation(idx);
        }
    }
```

for the `Operation` in each loop iteration, the cuda compiler can load one of the two operands using the address with an offset of 20 directly :

```
        ld.global.nc.f32        %f1, [%rd2];
        neg.f32         %f2, %f1;
        setp.gt.f32     %p2, %f1, 0f00000000;
        selp.f32        %f3, %f1, %f2, %p2;
        ld.global.nc.f32        %f4, [%rd3+16];
        add.f32         %f5, %f3, %f4; 
        st.global.f32   [%rd4], %f5;

$L__BB0_2:
        add.s64         %rd19, %rd1, 1;
        setp.ge.s64     %p3, %rd19, %rd5;
        @%p3 bra        $L__BB0_4;

        ld.global.nc.f32        %f6, [%rd2+4];
        neg.f32         %f7, %f6;
        setp.gt.f32     %p4, %f6, 0f00000000;
        selp.f32        %f8, %f6, %f7, %p4;
        ld.global.nc.f32        %f9, [%rd3+36];   // offset: 36 - 16 = 20
        add.f32         %f10, %f8, %f9;   // add two numbers  - the "calculate" function in sycl_post_ops.hpp
        st.global.f32   [%rd4+4], %f10;
```

for the `Operation` in each loop iteration, the sycl compiler needs to compute the offset and then load one of the two operands:
```
        or.b64          %rd3, %rd2, 1;
        setp.ge.s64     %p3, %rd3, %rd18;
        @%p3 bra        $L__BB5_4;
        add.s64         %rd33, %rd19, %rd121;
        ld.global.f32   %f6, [%rd33+4];
        add.s64         %rd34, %rd20, %rd121;
        mul.lo.s64      %rd35, %rd3, 20;       // compute the offset 20 using a multiply instruction
        add.s64         %rd36, %rd21, %rd35;
        ld.global.f32   %f7, [%rd36+16];
        setp.gt.f32     %p4, %f6, 0f00000000;
        neg.f32         %f8, %f6;
        selp.f32        %f9, %f6, %f8, %p4;
        add.rn.f32      %f10, %f7, %f9;
        st.global.f32   [%rd34+4], %f10;
```

I tried to explain the difference without proposing a solution. There may be other issues.  Hope it helps for others.

**Comment by AvijitBag** [comment] 2023-02-09 13:24
Thank you for your response. One thing i have observed in the Eltwise SYCL code is that if we comment out the post op operation there is a chance for increase in performance but post op operation is required to completed the functional feature too. Can you help on these part ?

**Comment by JackAKirk** [comment] 2023-02-16 16:16
The CUDA version is using the texture cache and the SYCL version isn't. Performance could be significantly improved by using this extension: https://github.com/intel/llvm/pull/7397.

**Comment by zjin-lcf** [comment] 2023-02-16 16:46
@JackAKirk  Thank you for the improvement!   Since your improvement has not been merged, your instructions would help application developers know what to do to see the significant performance improvement.

1. clone your repository
   git clone https://github.com/JackAKirk/llvm.git -b ext-ldg

2. build your repository
   
3. change the SYCL program with your proposed cache read function

**Comment by zjin-lcf** [comment] 2023-02-20 23:33
the bandwidth increases from 75 GB/s to 110 GB/s on a v100 GPU.

**Comment by leikinman** [comment] 2023-02-21 06:25
> the bandwidth increases from 75 GB/s to 110 GB/s on a v100 GPU.

Can you explain how to improve the performance by using ld.global.nc.f32 in above SYCL program? Thanks!

**Comment by zjin-lcf** [comment] 2023-02-21 12:01
I quote some explanation about the idea and texture cache.

```
This PR makes advantage of this information to generates the llvm.noalias and llvm.readonly attributes to CUDA kernel function parameters. If an argument is not readonly, it still set llvm.noalias because the ranges used within the bindings are guaranteed not to alias.

This is crucial for two reasons. When the downstream compiler detects that it can better schedule the load instructions. It typically schedules them together that utilized bandwith better. Second, it generates 'non-coherent cache loads' (nc prefix to ld.global instruction in PTX). What PTX models say about it is as follows (this part gives room for experimentation):

The texture cache is larger, has higher bandwidth, and longer latency than the global memory cache.
For applications with sufficient parallelism to cover the longer latency, ld.global.nc should offer 
better performance than ld.global.

``` 

Here is an example

https://github.com/intel/llvm/pull/7397/files#diff-eaab55a0a42373052dbc2f4808f25198db229c06c334bf3ffe993417d203e45c

**Comment by leikinman** [comment] 2023-02-21 12:11
Thank you for your response. I followed the example you mentioned, compiled that version of DPC++ and updated the code, but I didn't get any performance gain, can you share me the updated SYCL code?

**Comment by leikinman** [comment] 2023-02-21 12:13
Thank you for your response. I followed the example you mentioned, compiled that version of DPC++ and updated the code, but I didn't get any performance improvement, can you share me the updated eltwise code?

**Comment by zjin-lcf** [comment] 2023-02-21 15:34
Thank you for the comments. Could you copy/paste your SYCL program ?

**Comment by JackAKirk** [comment] 2023-02-21 16:08
> > Changed few things, In Kernel file, I used **int64_t** instead of **int** and Instead of **#include <bits/stdc++.h>** I used `#include <iostream> #include <vector>"`
> > Now, please check if the exception is occurring or not I checked now the exception is not occurring .
> > Please find new modified cuda files [Cuda_release.zip](https://github.com/intel/llvm/files/10682853/Cuda_release.zip)
> 
> I just converted the above cuda program to sycl using the DPCT tool.
> 
> then change the code `post_po_sr[4] = *(post_op_src+ idx*5 + 4);` to `post_po_sr[4] = sycl::ext::oneapi::experimental::cuda::ldg(post_op_src+ idx*5 + 4);` in `eltwise_fwd_kernel_vec_t` function.
> 
> I'm not sure is it correct but i see ld.global.nc.f32 is used in PTX code.

nice, that at least probably rules out `.nc` as the offender. It is not surprising if it isn't used that much. Could you post the updated ptx for the sycl version? It should now be closer the the cuda version but we can investigate the remaining differences.

**Comment by leikinman** [comment] 2023-02-21 16:26
Here is the ptx code [eltwise.dp-sycl-nvptx64-nvidia-cuda-sm_70.txt](https://github.com/intel/llvm/files/10795494/eltwise.dp-sycl-nvptx64-nvidia-cuda-sm_70.txt) .
 The performance is about 80 Gb/s on v100.

**Comment by JackAKirk** [comment] 2023-02-21 16:31
> Here is the ptx code [eltwise.dp-sycl-nvptx64-nvidia-cuda-sm_70.txt](https://github.com/intel/llvm/files/10795494/eltwise.dp-sycl-nvptx64-nvidia-cuda-sm_70.txt) . The performance is about 80 Gb/s on v100.

And this is with the inline multiplier patch that you mentioned above applied? it still looks like there are some register spills. But otherwise I don't see anything else immediately obvious without comparing it to the nvcc generated ptx. If you can post the full cuda ptx we could make a proper comparison. Thanks.

**Comment by leikinman** [comment] 2023-02-22 03:37
Thanks. Here is the nvcc generated ptx code [eltwise_cuda.txt](https://github.com/intel/llvm/files/10799789/eltwise_cuda.txt)

The performance is about 138 Gb/s on v100.

**Comment by leikinman** [comment] 2023-02-22 08:37
After I compared the ptx code and updated `auto src_ = *(src+ idx);` in the SYCL code to `auto src_ = sycl::ext::oneapi::experimental::cuda::ldg(src+ idx);`, I observed improvements. Thanks.

**Closed** 2024-09-25 13:32 UTC
Labels: bug, cuda
