### ISSUE TITLE
[CUDA][Gromacs] Suboptimal code generation for templated kernel

### ISSUE THREAD

**Issue by anton-v-gorshkov** [intel/llvm#5117] opened 2021-12-10 07:15 UTC
**Describe the bug**
In case of using templates + constexpr approach for defining SYCL kernels compiler may generate suboptimal (LLVM) code for PTX backend. Such an approach is using in Gromacs to SYCL version.

Performance impact is ~30% of kernel slowdown and ~20% of total benchmark slowdown for Gromacs SYCL version on NVidia GPUs (tested on RTX 2070).

**To Reproduce**
Reproducer is in attachment: [reproducer.zip](https://github.com/intel/llvm/files/7690762/reproducer.zip)
```
$ source <compiler>
$ unzip reproducer.zip
$ cd reproducer
$ ./build.sh
$ SYCL_DEVICE_FILTER=cuda ./reproducer
With template:    0.00357528
Without template: 0.000897871
```
Performance difference for the test is ~4x.

**Environment (please complete the following information):**

- OS: Linux
- Target device and vendor: NVidia RTX2070
- DPC++ version: clang version 14.0.0 (https://github.com/intel/llvm 626682032ac4f711cea9c73715b474c739b99b38)
- Dependencies version: CUDA 11.4

**Additional context**
Workaround for the problem is to declare function as `static`.

**Comment by rolandschulz** [comment] 2021-12-10 07:45
Because it is a template it is inline. Because it is inline it is linkonce_odr (both the function and the lambda inside the function). Based on the fact that linkonce_odr is the only difference between the fast and slow version, it seems that linkonce_odr causes inlining to fail. What isn't clear is why linkonce_odr makes the inlining fail.

**Comment by zjin-lcf** [comment] 2021-12-10 12:39
Is there a cuda version that is similar to your reproducer in SYCL ?

**Comment by anton-v-gorshkov** [comment] 2021-12-10 12:41
@zjin-lcf no, we don't have such a version in CUDA.

**Comment by Naghasan** [comment] 2021-12-13 09:55
> What isn't clear is why linkonce_odr makes the inlining fail

Probably because this causes a penalty (haven't look at the heuristics) as the compiler thinks it don't see the whole graph. It most probably not the case in this build scenario (as it operates in a LTO mode).

The NVPTX backend is already has a biais making calls expensive to promote inlining but I often saw it not being enough for SYCL. As a workaround, you could try to set `-fgpu-inline-threshold` to some high value (we often use 1000) to force the inliner to be less conservative.

**Comment by zjin-lcf** [comment] 2021-12-22 14:57
There is no performance drop for the cuda version; this may be already known.

I have a question for @Naghasan 
Will you recommend an inline threshold of 1000 by default for DPC++/ComputeCpp ?  Is it good that the option is 1000 by default without user's manual setting ? 

Thanks

**Comment by Naghasan** [comment] 2022-01-03 10:00
I'm not too sure TBH, personally I'm more in favour of making that flag know to users so they can set their own value (simply so that they are aware they can play with this value).
ComputeCpp sdk's cmake set it by default. It serves either to improve perf in some places or work around driver bugs.

The way  DPC++/ComputeCpp lowers the SYCL kernel into an SPIR-V/PTX/HIP kernel makes inlining very important so that SROA and DAE works properly. And those 2 are critically important (in some case kernels will simply not compile otherwise).

**Comment by Michoumichmich** [comment] 2022-01-05 18:15
Got the same issue, however using templates inside the kernel works fine, it's when the kernel is submitted through a function template that it blows up. Furthermore it happened while I didn't had the templates definitions in a header, but in a separate source (and using `extern template` in the headers). `-fgpu-inline-threshold` solves it. 

For GPUs especially, oneAPI could emit an optional *hint* saying that the stack frame*usage is huge and that increasing the inlining threshold could improve your kernel by using more registers (but with the drawbacks, etc).

**Comment by npmiller** [comment] 2023-07-03 13:43
Closing this now, as it seems solved, please feel free to re-open or open a new ticket if the issue persists.

**Closed by npmiller** 2023-07-03 13:43 UTC
Labels: bug, performance, cuda
