### ISSUE TITLE
AtomicRef/max_generic.cpp failed on HIP/AMD with unrelated changes

### ISSUE THREAD

**Issue by YuriPlyakhin** [intel/llvm#11033] opened 2023-08-31 14:41 UTC
test-e2e/AtomicRef/max_generic.cpp failed on HIP/AMD with unrelated test changes:
https://github.com/intel/llvm/actions/runs/6032515893/job/16367933301
PR: https://github.com/intel/llvm/pull/11022
```
******************** TEST 'SYCL :: AtomicRef/max_generic.cpp' FAILED ********************
Script:
--
: 'RUN: at line 1';    /__w/llvm/llvm/toolchain/bin//clang++  -Xsycl-target-backend=amdgcn-amd-amdhsa --offload-arch=gfx1031 -fsycl -fsycl-targets=amdgcn-amd-amdhsa /__w/llvm/llvm/llvm/sycl/test-e2e/AtomicRef/max_generic.cpp -o /__w/llvm/llvm/build-e2e/AtomicRef/Output/max_generic.cpp.tmp.out
: 'RUN: at line 2';   env ONEAPI_DEVICE_SELECTOR=ext_oneapi_hip:gpu  /__w/llvm/llvm/build-e2e/AtomicRef/Output/max_generic.cpp.tmp.out
--
Exit Code: -6

Command Output (stdout):
--
$ ":" "RUN: at line 1"
note: command had no output on stdout or stderr
$ "/__w/llvm/llvm/toolchain/bin//clang++" "-Xsycl-target-backend=amdgcn-amd-amdhsa" "--offload-arch=gfx1031" "-fsycl" "-fsycl-targets=amdgcn-amd-amdhsa" "/__w/llvm/llvm/llvm/sycl/test-e2e/AtomicRef/max_generic.cpp" "-o" "/__w/llvm/llvm/build-e2e/AtomicRef/Output/max_generic.cpp.tmp.out"
note: command had no output on stdout or stderr
$ ":" "RUN: at line 2"
note: command had no output on stdout or stderr
$ "env" "ONEAPI_DEVICE_SELECTOR=ext_oneapi_hip:gpu" "/__w/llvm/llvm/build-e2e/AtomicRef/Output/max_generic.cpp.tmp.out"
# command stderr:
Memory access fault by GPU node-1 (Agent handle: 0x[23](https://github.com/intel/llvm/actions/runs/6032515893/job/16367933301#step:21:24)1c7a0) on address 0x7f3e3ba00000. Reason: Page not present or supervisor privilege.

error: command failed with exit status: -6
```

**Comment by steffenlarsen** [comment] 2023-08-31 14:47
Issue is a duplicate of https://github.com/intel/llvm/issues/10460.

**Closed by steffenlarsen** 2023-08-31 14:47 UTC
Labels: bug
