### ISSUE TITLE
UR CUDA ERROR Runtime error: CUDA_ERROR_INVALID_VALUE, unified runtime error

### ISSUE THREAD

**Issue by vidyalatha-badde** [intel/llvm#10976] opened 2023-08-25 18:04 UTC
Hi,

```
UR CUDA ERROR:
        Value:           1
        Name:            CUDA_ERROR_INVALID_VALUE
        Description:     invalid argument
        Function:        urEnqueueKernelLaunch
        Source Location: sycl_workspace/llvm/sycl/plugins/unified_runtime/ur/adapters/cuda/enqueue.cpp:418

terminate called after throwing an instance of 'sycl::_V1::runtime_error'
  what():  Native API failed. Native API returns: -30 (PI_ERROR_INVALID_VALUE) -30 (PI_ERROR_INVALID_VALUE)
Aborted (core dumped) 
```

Has anyone encountered a similar runtime error during the execution of migrated sycl code on NVIDIA as the backend? what could be the cause of the error?

**Comment by vidyalatha-badde** [comment] 2023-08-28 04:51
Could someone help me out here?

**Comment by mmoadeli** [comment] 2023-08-28 09:06
Hi @vidyalatha-badde 
would you please be able to provide more details on how to produce the error?

**Comment by vidyalatha-badde** [comment] 2023-08-28 17:41
Hi @mmoadeli 

Thanks for looking into the issue.
I have a cuda code that got migrated and when trying to run on NVIDIA A100 GPU it is giving the above runtime error. Below are the code snippets 
```
([&]() { dpct::get_default_queue().submit([&](sycl::handler &cgh) {
        sycl::local_accessor<half, 2> dpct_local_acc_ct1(
            sycl::range<2>(SHMEM_SZ, CHUNK_K * K + SKEW_HALF) , cgh);
        cgh.parallel_for(
            sycl::nd_range<3>(
                sycl::range<3>(1, 1, deviceProp.get_max_compute_units()) *
                    sycl::range<3>(1, 1, THREADS_PER_BLOCK),
                sycl::range<3>(1, 1, THREADS_PER_BLOCK)),
            [=](sycl::nd_item<3> item_ct1) {
            sycl::sub_group sg = item_ct1.get_sub_group();
             func1( A, B, C, D, alpha, beta, item_ct1, dpct_local_acc_ct1, sg);
            });
```
But in the function definition, the migrated code contains pointer to dpct_local accessor variable

```
void func1( const sycl::half *A, const sycl::half *B, const float *C,
                  float *D, float alpha, float beta,
                  const sycl::nd_item<3> &item_ct1, sycl::half* dpct_local, sycl::sub_group sg) {

auto shmem = (sycl::half (*)[CHUNK_K * K + SKEW_HALF])dpct_local;
```
Compiling the above code gives an error as 

```
 no matching function for call to 'func1'
  263 |              func1( A, B, C, D, alpha, beta, item_ct1, dpct_local_acc_ct1, sg);
      |              ^~~~~~~~~~~~
local_acc_repro.cpp:106:6: note: candidate function not viable: no known conversion from 'const sycl::local_accessor<half, 2>' (aka 'const local_accessor<sycl::detail::half_impl::half, 2>') to 'sycl::half *' (aka 'sycl::detail::half_impl::half *') for 8th argument
  106 | void func1( const sycl::half *A, const sycl::half *B, const float *C,
      |      ^
```
Hence I added .get_pointer() to dpct_local_acc_ct1 as `dpct_local_acc_ct1.get_pointer()` during the function call and that removed the compile time error and now I'm getting the CUDA_ERROR_INVALID_VALUE.

Could you please let me know if I'm following the correct syntax for dpct_local accessor pointer here? Please let me know if you require any additional details.

Thanks,
Vidya.

**Comment by vidyalathabadde** [comment] 2023-08-30 02:12
Hi @mmoadeli,
Any idea so far?

**Comment by mmoadeli** [comment] 2023-09-04 21:02
Apologies @vidyalathabadde for late reply.
I haven't been able to find out the reason for the above error using the provided information. Having the source code, if possible, should help to further investigate.

**Comment by vidyalathabadde** [comment] 2023-09-05 10:01
Hi @mmoadeli,

Thanks for getting back to me.
Please find the attached reproducer code (test-case.zip) which helps in reproducing the runtime error that I'm getting on NVIDIA hardware (A100).

To compile: 
` clang++ -fsycl -fsycl-targets=nvptx64-nvidia-cuda test.cpp -o repro -I include/ -I Common/`

To Run:
`./repro`

Output:
```
Preparing data for GPU...

UR CUDA ERROR:
        Value:           1
        Name:            CUDA_ERROR_INVALID_VALUE
        Description:     invalid argument
        Function:        urEnqueueKernelLaunch
        Source Location: sycl_workspace/llvm/sycl/plugins/unified_runtime/ur/adapters/cuda/enqueue.cpp:418

terminate called after throwing an instance of 'sycl::_V1::runtime_error'
  what():  Native API failed. Native API returns: -30 (PI_ERROR_INVALID_VALUE) -30 (PI_ERROR_INVALID_VALUE)
Aborted (core dumped)

```
Clang version:
```
clang version 17.0.0 (https://github.com/intel/llvm c1d3d7ce2e4a3b05f70b0b2d8f6d7621ea0595aa)
Target: x86_64-unknown-linux-gnu
Thread model: posix
```

Could you please take a look at this issue and let me know what is the cause of the runtime error?

[test-case.zip](https://github.com/intel/llvm/files/12521929/test-case.zip)

**Comment by vidyalathabadde** [comment] 2023-09-11 06:43
Hi @mmoadeli ,

Did you get a chance to reproduce the issue? Please let me know if it is an issue with the code or if is it a bug.

Thanks,
Vidya.

**Comment by mmoadeli** [comment] 2023-09-12 20:40
Hi @vidyalathabadde
Sorry for late reply. 
I have been able to re-produce the issue. It is going to be investigated shortly.

**Comment by abagusetty** [comment] 2023-09-12 23:59
Apparently the issue is related to the size of local memory. The requested local memory is for this 2D array `(73728, 144)`. So `73728 * 144 * sizeof(sycl::half)` certainly exceeds `q.get_device().get_info<sycl::info::device::local_mem_size>()` 

The error code seems not be the right one.

**Comment by vidyalathabadde** [comment] 2023-09-13 13:14
Thanks for looking into this issue. Could you please let me know how can i resolve it?

**Comment by vidyalathabadde** [comment] 2023-09-13 15:02
> The error code seems not be the right one.

Do you think the error code should be changed then? I could not interpret the error message initially hence I posted the issue here. Also, I'll check with a smaller size and get back to you if I see similar error. Will that be fine?

**Comment by abagusetty** [comment] 2023-09-13 15:19
> > The error code seems not be the right one.
> 
> Do you think the error code should be changed then? I could not interpret the error message initially hence I posted the issue here. Also, I'll check with a smaller size and get back to you if I see similar error. Will that be fine?

If you set the following env variables: `export UR_CUDA_MAX_LOCAL_MEM_SIZE=49000`  & `export SYCL_RT_WARNING_LEVEL=2` 
https://github.com/intel/llvm/blob/2744b41ec202264ebf8db8e5553a842616d75ffe/sycl/doc/EnvironmentVariables.md?plain=1#L165

and run the executable again, hopefully you should see an error like the one below:
```
The program was built for 1 devices
Build program log for 'NVIDIA A100 80GB PCIe':

Too much local memory allocated for device
terminate called after throwing an instance of 'sycl::_V1::runtime_error'
  what():  Native API failed. Native API returns: -996 (The plugin has emitted a backend specific error)
Too much local memory allocated for device
 -996 (The plugin has emitted a backend specific error)
Aborted (core dumped)
```

**Comment by vidyalathabadde** [comment] 2023-09-14 09:41
Hi @abagusetty ,

> Apparently the issue is related to the size of local memory. The requested local memory is for this 2D array `(73728, 144)`. So `73728 * 144 * sizeof(sycl::half)` certainly exceeds `q.get_device().get_info<sycl::info::device::local_mem_size>()`
> 
> The error code seems not be the right one.

How did you get that number (73728,144) is it related to a specific hardware? Because as for the size, the local accessor 
 ```
sycl::local_accessor<half, 2> dpct_local_acc_ct1(
            sycl::range<2>(SHMEM_SZ, CHUNK_K * K + SKEW_HALF) , cgh);
```
that is present in the code is SHMEM_SZ 65536 and CHUNK_K * K + SKEW_HALF is 80 ?

**Comment by vidyalathabadde** [comment] 2023-09-14 09:56
> > > The error code seems not be the right one.
> > 
> > 
> > Do you think the error code should be changed then? I could not interpret the error message initially hence I posted the issue here. Also, I'll check with a smaller size and get back to you if I see similar error. Will that be fine?
> 
> If you set the following env variables: `export UR_CUDA_MAX_LOCAL_MEM_SIZE=49000` & `export SYCL_RT_WARNING_LEVEL=2`
> 
> https://github.com/intel/llvm/blob/2744b41ec202264ebf8db8e5553a842616d75ffe/sycl/doc/EnvironmentVariables.md?plain=1#L165
> 
> and run the executable again, hopefully you should see an error like the one below:
> 
> ```
> The program was built for 1 devices
> Build program log for 'NVIDIA A100 80GB PCIe':
> 
> Too much local memory allocated for device
> terminate called after throwing an instance of 'sycl::_V1::runtime_error'
>   what():  Native API failed. Native API returns: -996 (The plugin has emitted a backend specific error)
> Too much local memory allocated for device
>  -996 (The plugin has emitted a backend specific error)
> Aborted (core dumped)
> ```

This is how I get when I tried exporting the 2 variables
```
The program was built for 1 devices
Build program log for 'NVIDIA A100 80GB PCIe':


UR CUDA ERROR:
        Value:           1
        Name:            CUDA_ERROR_INVALID_VALUE
        Description:     invalid argument
        Function:        urEnqueueKernelLaunch
        Source Location: sycl_workspace/llvm/sycl/plugins/unified_runtime/ur/adapters/cuda/enqueue.cpp:418

terminate called after throwing an instance of 'sycl::_V1::runtime_error'
  what():  Native API failed. Native API returns: -30 (PI_ERROR_INVALID_VALUE) -30 (PI_ERROR_INVALID_VALUE)
Aborted (core dumped)

```
Could you please let me know why can't i see the complete message as yours?

**Comment by abagusetty** [comment] 2023-09-14 16:12
It is certainly because the compiler is bit old. Always a good practice to include the git hash in the issues (i.e., `clang++ -V`)

**Comment by vidyalathabadde** [comment] 2023-09-15 06:28
I already included the clang++ -V in my previous post in which i used 17.0.0 and i just tried with another version but still could not get the complete output as yours. 

```
clang version 18.0.0 (https://github.com/intel/llvm ad973f3383e265a1e209b61559e24cec37c5d111)
Target: x86_64-unknown-linux-gnu
Thread model: posix
```

What is the version of clang++ that you have used in this case?

**Comment by maarquitos14** [comment] 2023-12-12 17:06
@vidyalathabadde were you able to resolve the issue with the commit pointed out by @abagusetty? If so, please, let us know so that we can close the issue. Thanks in advance.

**Comment by vidyalathabadde** [comment] 2023-12-13 07:20
I reported this issue and got the fix from the concerned team. Thanks @mmoadeli @abagusetty for your help in this issue.

**Closed** 2023-12-13 08:00 UTC
Labels: cuda
