### ISSUE TITLE
Installation failure - supported accelerator?

### ISSUE THREAD

**Issue by DGASUK** [intel/llvm#795] opened 2019-11-06 16:06 UTC
My installation of llvm sycl on Windows just failed to complete.
I have had OpenGL and Vulkan working fine with my AMD Tonga-based FirePro GPU on this computer.
Is there an issue with this acceleration target for llvm sycl?
The problem seems to be around building icd/loader:-
[last lines of Ninja script output]...

[23/28] Building C object CMakeFiles/OpenCL.dir/loader/windows/icd_windows_hkr.c.obj
FAILED: CMakeFiles/OpenCL.dir/loader/windows/icd_windows_hkr.c.obj
C:\mingw-w64\x86_64-8.1.0-win32-seh-rt_v6-rev0\mingw64\bin\gcc.exe -DCL_TARGET_OPENCL_VERSION=220 -DOpenCL_EXPORTS -IC:/Users/David/sycl_workspace/build/tools/sycl/OpenCL/inc -I. -IC:/Users/David/sycl_workspace/build/tools/sycl/OpenCL/icd/loader -O3 -DNDEBUG -MD -MT CMakeFiles/OpenCL.dir/loader/windows/icd_windows_hkr.c.obj -MF CMakeFiles\OpenCL.dir\loader\windows\icd_windows_hkr.c.obj.d -o CMakeFiles/OpenCL.dir/loader/windows/icd_windows_hkr.c.obj   -c C:/Users/David/sycl_workspace/build/tools/sycl/OpenCL/icd/loader/windows/icd_windows_hkr.c
C:/Users/David/sycl_workspace/build/tools/sycl/OpenCL/icd/loader/windows/icd_windows_hkr.c: In function 'khrIcdOsVendorsEnumerateHKR':
C:/Users/David/sycl_workspace/build/tools/sycl/OpenCL/icd/loader/windows/icd_windows_hkr.c:210:21: error: 'CM_GETIDLIST_FILTER_CLASS' undeclared (first use in this function); did you mean 'CM_GETIDLIST_FILTER_BITS'?
     ULONG ulFlags = CM_GETIDLIST_FILTER_CLASS |
                     ^~~~~~~~~~~~~~~~~~~~~~~~~
                     CM_GETIDLIST_FILTER_BITS
C:/Users/David/sycl_workspace/build/tools/sycl/OpenCL/icd/loader/windows/icd_windows_hkr.c:210:21: note: each undeclared identifier is reported only once for each function it appears in
C:/Users/David/sycl_workspace/build/tools/sycl/OpenCL/icd/loader/windows/icd_windows_hkr.c:211:21: error: 'CM_GETIDLIST_FILTER_PRESENT' undeclared (first use in this function); did you mean 'CM_GETIDLIST_FILTER_BITS'?
                     CM_GETIDLIST_FILTER_PRESENT;
                     ^~~~~~~~~~~~~~~~~~~~~~~~~~~
                     CM_GETIDLIST_FILTER_BITS
C:/Users/David/sycl_workspace/build/tools/sycl/OpenCL/icd/loader/windows/icd_windows_hkr.c:271:9: error: unknown type name 'DEVPROPTYPE'; did you mean 'EPROTOTYPE'?
         DEVPROPTYPE devpropType;
         ^~~~~~~~~~~
         EPROTOTYPE
C:/Users/David/sycl_workspace/build/tools/sycl/OpenCL/icd/loader/windows/icd_windows_hkr.c:334:23: warning: implicit declaration of function 'CM_Get_DevNode_PropertyW'; did you mean 'CM_Set_DevNode_Problem'? [-Wimplicit-function-declaration]
                 ret = CM_Get_DevNode_PropertyW(
                       ^~~~~~~~~~~~~~~~~~~~~~~~
                       CM_Set_DevNode_Problem
C:/Users/David/sycl_workspace/build/tools/sycl/OpenCL/icd/loader/windows/icd_windows_hkr.c:336:22: error: 'DEVPKEY_Device_ClassGuid' undeclared (first use in this function)
                     &DEVPKEY_Device_ClassGuid,
                      ^~~~~~~~~~~~~~~~~~~~~~~~
[24/28] Building C object CMakeFiles/OpenCL.dir/loader/windows/icd_windows.c.obj
C:/Users/David/sycl_workspace/build/tools/sycl/OpenCL/icd/loader/windows/icd_windows.c: In function 'khrIcdOsVendorsEnumerate':
C:/Users/David/sycl_workspace/build/tools/sycl/OpenCL/icd/loader/windows/icd_windows.c:192:64: warning: passing argument 2 of 'pCreateDXGIFactory' from incompatible pointer type [-Wincompatible-pointer-types]
             HRESULT hr = pCreateDXGIFactory(&IID_IDXGIFactory, &pFactory);
                                                                ^~~~~~~~~
C:/Users/David/sycl_workspace/build/tools/sycl/OpenCL/icd/loader/windows/icd_windows.c:192:64: note: expected 'void **' but argument is of type 'IDXGIFactory **' {aka 'struct IDXGIFactory **'}
C:/Users/David/sycl_workspace/build/tools/sycl/OpenCL/icd/loader/windows/icd_windows.c: In function 'khrIcdOsVendorsEnumerateOnce':
C:/Users/David/sycl_workspace/build/tools/sycl/OpenCL/icd/loader/windows/icd_windows.c:244:5: warning: implicit declaration of function 'InitOnceExecuteOnce' [-Wimplicit-function-declaration]
     InitOnceExecuteOnce(&initialized, khrIcdOsVendorsEnumerate, NULL, NULL);
     ^~~~~~~~~~~~~~~~~~~
[25/28] Building C object CMakeFiles/OpenCL.dir/loader/icd.c.obj
[26/28] Building C object CMakeFiles/OpenCL.dir/loader/icd_dispatch.c.obj
ninja: build stopped: subcommand failed.
ninja: build stopped: subcommand failed.

**Comment by alexbatashev** [comment] 2019-11-06 18:38
@DGASUK I think, the problem is this line
```
C:\mingw-w64\x86_64-8.1.0-win32-seh-rt_v6-rev0\mingw64\bin\gcc.exe
```

I have faced a very similar problem recently. Can you please try cherry-picking https://github.com/intel/llvm/pull/792 and see if it resolves the issue?

Also, please note that we require SPIR-V support for SYCL offload targets. I'm not sure if your device supports it.

**Comment by DGASUK** [comment] 2019-11-08 03:59
Thanks @alexbatashev for pointing me in the right direction, SYCL build problem was with compiler selection from environment info. Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\ folder was before mingw entry in path variable but version sub-folder was incorrect - had not been changed in line with recent update 14.16.27023.
SYCL built successfully after correcting this!

However, SYCl software not working correctly - issue with support for my Tonga-based AMD GPU? You mentioned SPIR-V support for SYCL offload targets - if I can run Vulkan does this imply SPIR-V ingestion capability also?

Initial output from installation check below - does this help identify issue?
 
C:\Users\David\sycl_workspace\build>ninja check-all
[3/17] Performing update step for 'ocl-headers'
HEAD is up to date.
[8/17] Performing update step for 'ocl-icd'
HEAD is up to date.
[9/17] Performing configure step for 'ocl-icd'
-- Configuring done
-- Generating done
-- Build files have been written to: C:/Users/David/sycl_workspace/build/tools/sycl/icd_build
[10/17] Performing build step for 'ocl-icd'
ninja: no work to do.
[11/13] Performing install step for 'ocl-icd'
[0/1] Install the project...
-- Install configuration: "Release"
-- Up-to-date: C:/Users/David/sycl_workspace/build/lib/OpenCL.lib
-- Up-to-date: C:/Users/David/sycl_workspace/build/bin/OpenCL.dll
[12/13] Running all regression tests
llvm-lit.py: C:/Users/David/sycl_workspace/llvm/llvm\utils\lit\lit\llvm\config.py:342: note: using clang: c:\users\david\sycl_workspace\build\bin\clang.exe
llvm-lit.py: C:/Users/David/sycl_workspace/llvm/llvm\utils\lit\lit\llvm\config.py:342: note: using clang: c:\users\david\sycl_workspace\build\bin\clang.exe
getDeviceCount cpu:
Found available CPU device
getDeviceCount gpu:
Found available GPU device
getDeviceCount accelerator:
Could not find AOT device compiler ioc64
Could not find AOT device compiler ocloc
Could not find AOT device compiler aoc
llvm-lit.py: C:/Users/David/sycl_workspace/build/utils/lit/tests/lit.cfg:73: warning: Setting a timeout per test not supported. Requires the Python psutil module but it could not be found. Try installing it via pip or via your operating system's package manager. Some tests will be skipped and the --timeout command line argument will not work.
-- Testing: 50899 tests, 8 workers --
llvm-lit.py: C:/Users/David/sycl_workspace/llvm/llvm\utils\lit\lit\run.py:173: warning: Failed to raise process limit: No module named 'resource'
Testing:  0..
FAIL: Clang :: ARCMT/GC-check-warn-nsalloc.m (4169 of 50899)
******************** TEST 'Clang :: ARCMT/GC-check-warn-nsalloc.m' FAILED ********************
Script:
--
: 'RUN: at line 1';   c:\users\david\sycl_workspace\build\bin\clang.exe -cc1 -internal-isystem c:\users\david\sycl_workspace\build\lib\clang\10.0.0\include -nostdsysteminc -arcmt-check -no-ns-alloc-error -triple x86_64-apple-darwin10 -fobjc-gc-only C:\Users\David\sycl_workspace\llvm\clang\test\ARCMT\GC-check-warn-nsalloc.m 2>&1 | grep 'warning: \[rewriter\] call returns pointer to GC managed memory'
: 'RUN: at line 2';   c:\users\david\sycl_workspace\build\bin\clang.exe -cc1 -internal-isystem c:\users\david\sycl_workspace\build\lib\clang\10.0.0\include -nostdsysteminc -arcmt-check -no-ns-alloc-error -triple x86_64-apple-darwin10 -fobjc-gc-only -x objective-c++ C:\Users\David\sycl_workspace\llvm\clang\test\ARCMT\GC-check-warn-nsalloc.m 2>&1 | grep 'warning: \[rewriter\] call returns pointer to GC managed memory'
--
Exit Code: 127

Command Output (stdout):
--
$ ":" "RUN: at line 1"
$ "grep" "warning: \[rewriter\] call returns pointer to GC managed memory"
# command stderr:
'grep': command not found
error: command failed with exit status: 127

--

********************
Testing:  0..
FAIL: Clang :: ARCMT/GC-no-finalize-removal.m (4173 of 50899)
******************** TEST 'Clang :: ARCMT/GC-no-finalize-removal.m' FAILED ********************
Script:
--
: 'RUN: at line 1';   c:\users\david\sycl_workspace\build\bin\clang.exe -cc1 -internal-isystem c:\users\david\sycl_workspace\build\lib\clang\10.0.0\include -nostdsysteminc -triple x86_64-apple-macosx10.7 -fsyntax-only -fobjc-runtime-has-weak -fobjc-arc -x objective-c C:\Users\David\sycl_workspace\llvm\clang\test\ARCMT\GC-no-finalize-removal.m.result
: 'RUN: at line 2';   arcmt-test --args -triple x86_64-apple-macosx10.7 -fsyntax-only -fobjc-gc-only -no-finalize-removal -x objective-c C:\Users\David\sycl_workspace\llvm\clang\test\ARCMT\GC-no-finalize-removal.m > C:\Users\David\sycl_workspace\build\tools\clang\test\ARCMT\Output\GC-no-finalize-removal.m.tmp
: 'RUN: at line 3';   diff C:\Users\David\sycl_workspace\build\tools\clang\test\ARCMT\Output\GC-no-finalize-removal.m.tmp C:\Users\David\sycl_workspace\llvm\clang\test\ARCMT\GC-no-finalize-removal.m.result
: 'RUN: at line 4';   arcmt-test --args -triple x86_64-apple-macosx10.7 -fsyntax-only -fobjc-gc-only -no-finalize-removal -x objective-c++ C:\Users\David\sycl_workspace\llvm\clang\test\ARCMT\GC-no-finalize-removal.m > C:\Users\David\sycl_workspace\build\tools\clang\test\ARCMT\Output\GC-no-finalize-removal.m.tmp
: 'RUN: at line 5';   diff C:\Users\David\sycl_workspace\build\tools\clang\test\ARCMT\Output\GC-no-finalize-removal.m.tmp C:\Users\David\sycl_workspace\llvm\clang\test\ARCMT\GC-no-finalize-removal.m.result
--
Exit Code: 1

Command Output (stdout):
--
$ ":" "RUN: at line 1"
$ "c:\users\david\sycl_workspace\build\bin\clang.exe" "-cc1" "-internal-isystem" "c:\users\david\sycl_workspace\build\lib\clang\10.0.0\include" "-nostdsysteminc" "-triple" "x86_64-apple-macosx10.7" "-fsyntax-only" "-fobjc-runtime-has-weak" "-fobjc-arc" "-x" "objective-c" "C:\Users\David\sycl_workspace\llvm\clang\test\ARCMT\GC-no-finalize-removal.m.result"
# command stderr:
In file included from C:\Users\David\sycl_workspace\llvm\clang\test\ARCMT\GC-no-finalize-removal.m.result:8:
C:\Users\David\sycl_workspace\llvm\clang\test\ARCMT/GC.h:4:3: warning: '__strong' only applies to Objective-C object or block pointer types; type here is 'void *'
  __strong void *gcVar;
  ^
C:\Users\David\sycl_workspace\llvm\clang\test\ARCMT\GC-no-finalize-removal.m.result:14:12: warning: class 'I1' defined without specifying a base class
@interface I1
           ^
C:\Users\David\sycl_workspace\llvm\clang\test\ARCMT\GC-no-finalize-removal.m.result:14:14: note: add a super class to fix this problem
@interface I1
             ^
              : NSObject
C:\Users\David\sycl_workspace\llvm\clang\test\ARCMT\GC-no-finalize-removal.m.result:31:12: warning: class 'I2' defined without specifying a base class
@interface I2
           ^
C:\Users\David\sycl_workspace\llvm\clang\test\ARCMT\GC-no-finalize-removal.m.result:31:14: note: add a super class to fix this problem
@interface I2
             ^
              : NSObject
C:\Users\David\sycl_workspace\llvm\clang\test\ARCMT\GC-no-finalize-removal.m.result:64:12: warning: class 'I4Impl' defined without specifying a base class
@interface I4Impl {
           ^
C:\Users\David\sycl_workspace\llvm\clang\test\ARCMT\GC-no-finalize-removal.m.result:64:18: note: add a super class to fix this problem
@interface I4Impl {
                 ^
                  : NSObject
C:\Users\David\sycl_workspace\llvm\clang\test\ARCMT\GC-no-finalize-removal.m.result:89:12: warning: class 'rdar10532449' defined without specifying a base class
@interface rdar10532449
           ^
C:\Users\David\sycl_workspace\llvm\clang\test\ARCMT\GC-no-finalize-removal.m.result:89:24: note: add a super class to fix this problem
@interface rdar10532449
                       ^
                        : NSObject
5 warnings generated.

$ ":" "RUN: at line 2"
$ "arcmt-test" "--args" "-triple" "x86_64-apple-macosx10.7" "-fsyntax-only" "-fobjc-gc-only" "-no-finalize-removal" "-x" "objective-c" "C:\Users\David\sycl_workspace\llvm\clang\test\ARCMT\GC-no-finalize-removal.m"
$ ":" "RUN: at line 3"
$ "diff" "C:\Users\David\sycl_workspace\build\tools\clang\test\ARCMT\Output\GC-no-finalize-removal.m.tmp" "C:\Users\David\sycl_workspace\llvm\clang\test\ARCMT\GC-no-finalize-removal.m.result"
# command output:
*** C:\Users\David\sycl_workspace\build\tools\clang\test\ARCMT\Output\GC-no-finalize-removal.m.tmp
--- C:\Users\David\sycl_workspace\llvm\clang\test\ARCMT\GC-no-finalize-removal.m.result
***************
*** 20,31 ****
    test1(0);
  }

! #if !__has_feature(objc_arc)
  -(void)finalize {
    // finalize
    test1(0);
! }
! #endif
  @end

  @interface I2
--- 20,31 ----
    test1(0);
  }

! #if !__has_feature(objc_arc)
  -(void)finalize {
    // finalize
    test1(0);
! }
! #endif
  @end

  @interface I2
***************
*** 35,47 ****
  @implementation I2
  @synthesize prop;

! #if !__has_feature(objc_arc)
  -(void)finalize {
    self.prop = 0;
    // finalize
    test1(0);
! }
! #endif
  -(void)dealloc {
    // finalize
    test1(0);
--- 35,47 ----
  @implementation I2
  @synthesize prop;

! #if !__has_feature(objc_arc)
  -(void)finalize {
    self.prop = 0;
    // finalize
    test1(0);
! }
! #endif
  -(void)dealloc {
    // finalize
    test1(0);

error: command failed with exit status: 1

--

**Comment by alexbatashev** [comment] 2019-11-08 04:11
>  if I can run Vulkan does this imply SPIR-V ingestion capability also?

No, it does not. SPIR-V for Vulkan/OpenGL and OpenCL use different capabilities. To run SYCL applications, your graphics driver must support OpenCL-flavoured SPIR-V. 

As for your error message. From what I see, it is not related to SYCL at all. Apple’s Objective C tests have failed. Try running `cmake --build . --target check-sycl` in your build directory. This will only run SYCL tests.

**Comment by fodinabor** [comment] 2019-11-08 19:41
Do you btw. know a way to convert the OpenCL-flavored SPIR-V to Vulkan SPIR-V?
Or is it possible to add a modified backend to generate Vulkan compatible SPIR-V?

**Comment by alexbatashev** [comment] 2019-11-08 19:43
@fodinabor AFAIK there's no such tool. SPIR-V LLVM translator only supports OpenCL-flavoured SPIR-V and crashes (I think) if you try to process shaders.

**Comment by fodinabor** [comment] 2019-11-08 19:45
I see ;-)

**Comment by DGASUK** [comment] 2019-11-10 01:41
OK @alexbatashev, ran check-syscl rather than check-all - results output from first few errors below.

The tests fail from number 7 onwards with Exit Code: 3221225477 and 'LLVM ERROR: SPIR-V not supported on legacy compiler lib' seems clear enough but I wasn't sure if it was from line 3 "env" "SYCL_DEVICE_TYPE=CPU" or line 4 "env" "SYCL_DEVICE_TYPE=GPU"?

...
[9/16] Performing build step for 'ocl-icd'
ninja: no work to do.
[10/12] Performing install step for 'ocl-icd'
[0/1] Install the project...
-- Install configuration: "Release"
-- Up-to-date: C:/Users/David/sycl_workspace/build/lib/OpenCL.lib
-- Up-to-date: C:/Users/David/sycl_workspace/build/bin/OpenCL.dll
[11/12] Running the SYCL regression tests
getDeviceCount cpu:
Found available CPU device
getDeviceCount gpu:
Found available GPU device
getDeviceCount accelerator:
Could not find AOT device compiler ioc64
Could not find AOT device compiler ocloc
Could not find AOT device compiler aoc
-- Testing: 148 tests, 8 workers --
llvm-lit.py: C:/Users/David/sycl_workspace/llvm/llvm\utils\lit\lit\run.py:173: warning: Failed to raise process limit: No module named 'resource'
Testing:  0
FAIL: SYCL :: basic_tests/access_to_subset.cpp (7 of 148)
******************** TEST 'SYCL :: basic_tests/access_to_subset.cpp' FAILED ********************
Script:
--
: 'RUN: at line 1';    C:/Users/David/sycl_workspace/build/bin/clang++ -IC:/Users/David/sycl_workspace/build/tools/sycl/OpenCL/inc -fsycl C:\Users\David\sycl_workspace\llvm\sycl\test\basic_tests\access_to_subset.cpp -o C:\Users\David\sycl_workspace\build\tools\sycl\test\basic_tests\Output\access_to_subset.cpp.tmp.out
: 'RUN: at line 2';   env SYCL_DEVICE_TYPE=HOST C:\Users\David\sycl_workspace\build\tools\sycl\test\basic_tests\Output\access_to_subset.cpp.tmp.out
: 'RUN: at line 3';   env SYCL_DEVICE_TYPE=CPU  C:\Users\David\sycl_workspace\build\tools\sycl\test\basic_tests\Output\access_to_subset.cpp.tmp.out
: 'RUN: at line 4';    env SYCL_DEVICE_TYPE=GPU  C:\Users\David\sycl_workspace\build\tools\sycl\test\basic_tests\Output\access_to_subset.cpp.tmp.out
: 'RUN: at line 5';   echo C:\Users\David\sycl_workspace\build\tools\sycl\test\basic_tests\Output\access_to_subset.cpp.tmp.out
--
Exit Code: 3221225477

Command Output (stdout):
--
$ ":" "RUN: at line 1"
$ "C:/Users/David/sycl_workspace/build/bin/clang++" "-IC:/Users/David/sycl_workspace/build/tools/sycl/OpenCL/inc" "-fsycl" "C:\Users\David\sycl_workspace\llvm\sycl\test\basic_tests\access_to_subset.cpp" "-o" "C:\Users\David\sycl_workspace\build\tools\sycl\test\basic_tests\Output\access_to_subset.cpp.tmp.out"
$ ":" "RUN: at line 2"
$ "env" "SYCL_DEVICE_TYPE=HOST" "C:\Users\David\sycl_workspace\build\tools\sycl\test\basic_tests\Output\access_to_subset.cpp.tmp.out"
$ ":" "RUN: at line 3"
$ "env" "SYCL_DEVICE_TYPE=CPU" "C:\Users\David\sycl_workspace\build\tools\sycl\test\basic_tests\Output\access_to_subset.cpp.tmp.out"
# command stderr:
LLVM ERROR: SPIR-V not supported on legacy compiler lib

error: command failed with exit status: 3221225477

**Comment by alexbatashev** [comment] 2019-11-10 04:55
@DGASUK from this extract it looks like CPU is failing. You can check for sure by running single test:

```
set SYCL_DEVICE_TYPE=GPU
C:\Users\David\sycl_workspace\build\tools\sycl\test\basic_tests\Output\access_to_subset.cpp.tmp.out
```

You may also need to add bin to `PATH` and lib to `LIB`.

**Comment by DGASUK** [comment] 2019-11-12 02:14
Not clear from your suggestion on the command line needed to run single test from the .out file and the relevance of lib?

**Comment by alexbatashev** [comment] 2019-11-12 05:34
@DGASUK sorry for confusion. LIT tests compile simple SYCL programs to test both compiler and runtime. *.out file is just a SYCL executable. You may run it as any other exe file. The only thing you have to keep in mind is the location of SYCL Runtime library. Test infrastructure usually takes care of this for you, but since you're going to run a standalone test, you need to tell operating system where to look for `sycl.dll`. That's why you need compiler's bin in your `PATH`. And `LIB` is only needed to compile SYCL applications.

**Comment by AlexeySachkov** [comment] 2019-12-18 19:49
Hi @DGASUK,

Do you experience any other issues with building/using SYCL compiler and runtime? Can we close this issue?

**Closed** 2020-07-18 20:00 UTC
