### ISSUE TITLE
handler2.hpp:573:14: error: no matching member function for call to 'set'

### ISSUE THREAD

**Issue by jeffhammond** [intel/llvm#163] opened 2019-05-24 07:38 UTC
# Reproducer
```
git clone --depth 1 https://github.com/ParRes/Kernels.git PRK
cd PRK/common && cp make.defs.llvm make.defs
# edit make.defs appropriately (see below for suggestions)
cd ../Cxx11 && make stencil-sycl
```

## `make.defs` hint
```
#
# SYCL flags
#
SYCLDIR=/opt/sycl
SYCLCXX=${SYCLDIR}/bin/clang++
SYCLFLAG=-fsycl -lsycl -lOpenCL -Wl,-rpath=${SYCLDIR}/lib
SYCLFLAG+=-std=c++17 -O3
```

# Compiler
Freshly built within the past few hours...
```
jrhammon@jrhammon-nuc:~/PRK/Cxx11$ /opt/sycl/bin/clang++  -v
clang version 9.0.0 (https://github.com/intel/llvm 8a95712bcc9a2a6d34ce66b6b5948c24204fa846)
Target: x86_64-unknown-linux-gnu
Thread model: posix
InstalledDir: /opt/sycl/bin
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/8
Selected GCC installation: /usr/lib/gcc/x86_64-linux-gnu/8
Candidate multilib: .;@m64
Candidate multilib: 32;@m32
Candidate multilib: x32;@mx32
Selected multilib: .;@m64
```

# Error
This code compiles just fine with CodePlay and triSYCL.
```
jrhammon@jrhammon-nuc:~/PRK/Cxx11$ make stencil-sycl
/opt/sycl/bin/clang++ -DPRKVERSION="2.16" -fsycl -lsycl -lOpenCL -Wl,-rpath=/opt/sycl/lib -std=c++17 -O3 -DUSE_SYCL -DUSE_2D_INDEXING=0 -DUSE_BOOST_IRANGE  -DUSE_RANGES stencil-sycl.cc -o stencil-sycl
In file included from stencil-sycl.cc:63:
In file included from /opt/sycl/lib/clang/9.0.0/include/CL/sycl.hpp:15:
In file included from /opt/sycl/lib/clang/9.0.0/include/CL/sycl/accessor.hpp:11:
In file included from /opt/sycl/lib/clang/9.0.0/include/CL/sycl/accessor2.hpp:12:
In file included from /opt/sycl/lib/clang/9.0.0/include/CL/sycl/buffer.hpp:11:
In file included from /opt/sycl/lib/clang/9.0.0/include/CL/sycl/detail/buffer_impl2.hpp:20:
In file included from /opt/sycl/lib/clang/9.0.0/include/CL/sycl/handler.hpp:10:
/opt/sycl/lib/clang/9.0.0/include/CL/sycl/handler2.hpp:573:14: error: no matching member function for call to 'set'
    MNDRDesc.set(std::move(NumWorkItems), std::move(WorkItemOffset));
    ~~~~~~~~~^~~
./stencil_sycl.hpp:10:7: note: in instantiation of function template specialization 'cl::sycl::handler::parallel_for<star1_1d<float>, (lambda at ./stencil_sycl.hpp:10:92), 2>'
      requested here
    h.parallel_for<class star1_1d<T>>(cl::sycl::range<2> {n-2,n-2}, cl::sycl::id<2> {1,1}, [=] (cl::sycl::item<2> it) {
      ^
stencil-sycl.cc:91:29: note: in instantiation of function template specialization 'star1<float>' requested here
          case 1: stencil = star1; break;
                            ^
stencil-sycl.cc:323:9: note: in instantiation of function template specialization 'run<float>' requested here
        run<float>(host, iterations, n, tile_size, star, radius);
        ^
/opt/sycl/lib/clang/9.0.0/include/CL/sycl/detail/cg.hpp:59:29: note: candidate function template not viable: requires single argument 'NumWorkItems', but 2 arguments were
      provided
  template <int Dims_> void set(sycl::range<Dims_> NumWorkItems) {
                            ^
/opt/sycl/lib/clang/9.0.0/include/CL/sycl/detail/cg.hpp:70:29: note: candidate function template not viable: requires single argument 'ExecutionRange', but 2 arguments were
      provided
  template <int Dims_> void set(sycl::nd_range<Dims_> ExecutionRange) {
                            ^
In file included from stencil-sycl.cc:63:
In file included from /opt/sycl/lib/clang/9.0.0/include/CL/sycl.hpp:15:
In file included from /opt/sycl/lib/clang/9.0.0/include/CL/sycl/accessor.hpp:11:
In file included from /opt/sycl/lib/clang/9.0.0/include/CL/sycl/accessor2.hpp:12:
In file included from /opt/sycl/lib/clang/9.0.0/include/CL/sycl/buffer.hpp:11:
In file included from /opt/sycl/lib/clang/9.0.0/include/CL/sycl/detail/buffer_impl2.hpp:20:
In file included from /opt/sycl/lib/clang/9.0.0/include/CL/sycl/handler.hpp:10:
/opt/sycl/lib/clang/9.0.0/include/CL/sycl/handler2.hpp:573:14: error: no matching member function for call to 'set'
    MNDRDesc.set(std::move(NumWorkItems), std::move(WorkItemOffset));
    ~~~~~~~~~^~~
./stencil_sycl.hpp:49:7: note: in instantiation of function template specialization 'cl::sycl::handler::parallel_for<star2_1d<float>, (lambda at ./stencil_sycl.hpp:49:92), 2>'
      requested here
    h.parallel_for<class star2_1d<T>>(cl::sycl::range<2> {n-4,n-4}, cl::sycl::id<2> {2,2}, [=] (cl::sycl::item<2> it) {
      ^
stencil-sycl.cc:92:29: note: in instantiation of function template specialization 'star2<float>' requested here
          case 2: stencil = star2; break;
                            ^
stencil-sycl.cc:323:9: note: in instantiation of function template specialization 'run<float>' requested here
        run<float>(host, iterations, n, tile_size, star, radius);
        ^
/opt/sycl/lib/clang/9.0.0/include/CL/sycl/detail/cg.hpp:59:29: note: candidate function template not viable: requires single argument 'NumWorkItems', but 2 arguments were
      provided
  template <int Dims_> void set(sycl::range<Dims_> NumWorkItems) {
                            ^
/opt/sycl/lib/clang/9.0.0/include/CL/sycl/detail/cg.hpp:70:29: note: candidate function template not viable: requires single argument 'ExecutionRange', but 2 arguments were
      provided
  template <int Dims_> void set(sycl::nd_range<Dims_> ExecutionRange) {
                            ^
In file included from stencil-sycl.cc:63:
In file included from /opt/sycl/lib/clang/9.0.0/include/CL/sycl.hpp:15:
In file included from /opt/sycl/lib/clang/9.0.0/include/CL/sycl/accessor.hpp:11:
In file included from /opt/sycl/lib/clang/9.0.0/include/CL/sycl/accessor2.hpp:12:
In file included from /opt/sycl/lib/clang/9.0.0/include/CL/sycl/buffer.hpp:11:
In file included from /opt/sycl/lib/clang/9.0.0/include/CL/sycl/detail/buffer_impl2.hpp:20:
In file included from /opt/sycl/lib/clang/9.0.0/include/CL/sycl/handler.hpp:10:
/opt/sycl/lib/clang/9.0.0/include/CL/sycl/handler2.hpp:573:14: error: no matching member function for call to 'set'
    MNDRDesc.set(std::move(NumWorkItems), std::move(WorkItemOffset));
    ~~~~~~~~~^~~
./stencil_sycl.hpp:98:7: note: in instantiation of function template specialization 'cl::sycl::handler::parallel_for<star3_1d<float>, (lambda at ./stencil_sycl.hpp:98:92), 2>'
      requested here
    h.parallel_for<class star3_1d<T>>(cl::sycl::range<2> {n-6,n-6}, cl::sycl::id<2> {3,3}, [=] (cl::sycl::item<2> it) {
      ^
stencil-sycl.cc:93:29: note: in instantiation of function template specialization 'star3<float>' requested here
          case 3: stencil = star3; break;
                            ^
stencil-sycl.cc:323:9: note: in instantiation of function template specialization 'run<float>' requested here
        run<float>(host, iterations, n, tile_size, star, radius);
        ^
/opt/sycl/lib/clang/9.0.0/include/CL/sycl/detail/cg.hpp:59:29: note: candidate function template not viable: requires single argument 'NumWorkItems', but 2 arguments were
      provided
  template <int Dims_> void set(sycl::range<Dims_> NumWorkItems) {
                            ^
/opt/sycl/lib/clang/9.0.0/include/CL/sycl/detail/cg.hpp:70:29: note: candidate function template not viable: requires single argument 'ExecutionRange', but 2 arguments were
      provided
  template <int Dims_> void set(sycl::nd_range<Dims_> ExecutionRange) {
                            ^
In file included from stencil-sycl.cc:63:
In file included from /opt/sycl/lib/clang/9.0.0/include/CL/sycl.hpp:15:
In file included from /opt/sycl/lib/clang/9.0.0/include/CL/sycl/accessor.hpp:11:
In file included from /opt/sycl/lib/clang/9.0.0/include/CL/sycl/accessor2.hpp:12:
In file included from /opt/sycl/lib/clang/9.0.0/include/CL/sycl/buffer.hpp:11:
In file included from /opt/sycl/lib/clang/9.0.0/include/CL/sycl/detail/buffer_impl2.hpp:20:
In file included from /opt/sycl/lib/clang/9.0.0/include/CL/sycl/handler.hpp:10:
/opt/sycl/lib/clang/9.0.0/include/CL/sycl/handler2.hpp:573:14: error: no matching member function for call to 'set'
    MNDRDesc.set(std::move(NumWorkItems), std::move(WorkItemOffset));
    ~~~~~~~~~^~~
./stencil_sycl.hpp:157:7: note: in instantiation of function template specialization 'cl::sycl::handler::parallel_for<star4_1d<float>, (lambda at ./stencil_sycl.hpp:157:92), 2>'
      requested here
    h.parallel_for<class star4_1d<T>>(cl::sycl::range<2> {n-8,n-8}, cl::sycl::id<2> {4,4}, [=] (cl::sycl::item<2> it) {
      ^
stencil-sycl.cc:94:29: note: in instantiation of function template specialization 'star4<float>' requested here
          case 4: stencil = star4; break;
                            ^
stencil-sycl.cc:323:9: note: in instantiation of function template specialization 'run<float>' requested here
        run<float>(host, iterations, n, tile_size, star, radius);
        ^
/opt/sycl/lib/clang/9.0.0/include/CL/sycl/detail/cg.hpp:59:29: note: candidate function template not viable: requires single argument 'NumWorkItems', but 2 arguments were
      provided
  template <int Dims_> void set(sycl::range<Dims_> NumWorkItems) {
                            ^
/opt/sycl/lib/clang/9.0.0/include/CL/sycl/detail/cg.hpp:70:29: note: candidate function template not viable: requires single argument 'ExecutionRange', but 2 arguments were
      provided
  template <int Dims_> void set(sycl::nd_range<Dims_> ExecutionRange) {
                            ^
In file included from stencil-sycl.cc:63:
In file included from /opt/sycl/lib/clang/9.0.0/include/CL/sycl.hpp:15:
In file included from /opt/sycl/lib/clang/9.0.0/include/CL/sycl/accessor.hpp:11:
In file included from /opt/sycl/lib/clang/9.0.0/include/CL/sycl/accessor2.hpp:12:
In file included from /opt/sycl/lib/clang/9.0.0/include/CL/sycl/buffer.hpp:11:
In file included from /opt/sycl/lib/clang/9.0.0/include/CL/sycl/detail/buffer_impl2.hpp:20:
In file included from /opt/sycl/lib/clang/9.0.0/include/CL/sycl/handler.hpp:10:
/opt/sycl/lib/clang/9.0.0/include/CL/sycl/handler2.hpp:573:14: error: no matching member function for call to 'set'
    MNDRDesc.set(std::move(NumWorkItems), std::move(WorkItemOffset));
    ~~~~~~~~~^~~
./stencil_sycl.hpp:226:7: note: in instantiation of function template specialization 'cl::sycl::handler::parallel_for<star5_1d<float>, (lambda at ./stencil_sycl.hpp:226:94), 2>'
      requested here
    h.parallel_for<class star5_1d<T>>(cl::sycl::range<2> {n-10,n-10}, cl::sycl::id<2> {5,5}, [=] (cl::sycl::item<2> it) {
      ^
stencil-sycl.cc:95:29: note: in instantiation of function template specialization 'star5<float>' requested here
          case 5: stencil = star5; break;
                            ^
stencil-sycl.cc:323:9: note: in instantiation of function template specialization 'run<float>' requested here
        run<float>(host, iterations, n, tile_size, star, radius);
        ^
/opt/sycl/lib/clang/9.0.0/include/CL/sycl/detail/cg.hpp:59:29: note: candidate function template not viable: requires single argument 'NumWorkItems', but 2 arguments were
      provided
  template <int Dims_> void set(sycl::range<Dims_> NumWorkItems) {
                            ^
/opt/sycl/lib/clang/9.0.0/include/CL/sycl/detail/cg.hpp:70:29: note: candidate function template not viable: requires single argument 'ExecutionRange', but 2 arguments were
      provided
  template <int Dims_> void set(sycl::nd_range<Dims_> ExecutionRange) {
                            ^
In file included from stencil-sycl.cc:63:
In file included from /opt/sycl/lib/clang/9.0.0/include/CL/sycl.hpp:15:
In file included from /opt/sycl/lib/clang/9.0.0/include/CL/sycl/accessor.hpp:11:
In file included from /opt/sycl/lib/clang/9.0.0/include/CL/sycl/accessor2.hpp:12:
In file included from /opt/sycl/lib/clang/9.0.0/include/CL/sycl/buffer.hpp:11:
In file included from /opt/sycl/lib/clang/9.0.0/include/CL/sycl/detail/buffer_impl2.hpp:20:
In file included from /opt/sycl/lib/clang/9.0.0/include/CL/sycl/handler.hpp:10:
/opt/sycl/lib/clang/9.0.0/include/CL/sycl/handler2.hpp:573:14: error: no matching member function for call to 'set'
    MNDRDesc.set(std::move(NumWorkItems), std::move(WorkItemOffset));
    ~~~~~~~~~^~~
stencil-sycl.cc:167:11: note: in instantiation of function template specialization 'cl::sycl::handler::parallel_for<add<float>, (lambda at stencil-sycl.cc:168:35), 2>' requested
      here
        h.parallel_for<class add<T>>(cl::sycl::range<2> {n, n}, cl::sycl::id<2> {0, 0},
          ^
stencil-sycl.cc:323:9: note: in instantiation of function template specialization 'run<float>' requested here
        run<float>(host, iterations, n, tile_size, star, radius);
        ^
/opt/sycl/lib/clang/9.0.0/include/CL/sycl/detail/cg.hpp:59:29: note: candidate function template not viable: requires single argument 'NumWorkItems', but 2 arguments were
      provided
  template <int Dims_> void set(sycl::range<Dims_> NumWorkItems) {
                            ^
/opt/sycl/lib/clang/9.0.0/include/CL/sycl/detail/cg.hpp:70:29: note: candidate function template not viable: requires single argument 'ExecutionRange', but 2 arguments were
      provided
  template <int Dims_> void set(sycl::nd_range<Dims_> ExecutionRange) {
                            ^
In file included from stencil-sycl.cc:63:
In file included from /opt/sycl/lib/clang/9.0.0/include/CL/sycl.hpp:15:
In file included from /opt/sycl/lib/clang/9.0.0/include/CL/sycl/accessor.hpp:11:
In file included from /opt/sycl/lib/clang/9.0.0/include/CL/sycl/accessor2.hpp:12:
In file included from /opt/sycl/lib/clang/9.0.0/include/CL/sycl/buffer.hpp:11:
In file included from /opt/sycl/lib/clang/9.0.0/include/CL/sycl/detail/buffer_impl2.hpp:20:
In file included from /opt/sycl/lib/clang/9.0.0/include/CL/sycl/handler.hpp:10:
/opt/sycl/lib/clang/9.0.0/include/CL/sycl/handler2.hpp:573:14: error: no matching member function for call to 'set'
    MNDRDesc.set(std::move(NumWorkItems), std::move(WorkItemOffset));
    ~~~~~~~~~^~~
./stencil_sycl.hpp:10:7: note: in instantiation of function template specialization 'cl::sycl::handler::parallel_for<star1_1d<double>, (lambda at ./stencil_sycl.hpp:10:92), 2>'
      requested here
    h.parallel_for<class star1_1d<T>>(cl::sycl::range<2> {n-2,n-2}, cl::sycl::id<2> {1,1}, [=] (cl::sycl::item<2> it) {
      ^
stencil-sycl.cc:91:29: note: in instantiation of function template specialization 'star1<double>' requested here
          case 1: stencil = star1; break;
                            ^
stencil-sycl.cc:324:9: note: in instantiation of function template specialization 'run<double>' requested here
        run<double>(host, iterations, n, tile_size, star, radius);
        ^
/opt/sycl/lib/clang/9.0.0/include/CL/sycl/detail/cg.hpp:59:29: note: candidate function template not viable: requires single argument 'NumWorkItems', but 2 arguments were
      provided
  template <int Dims_> void set(sycl::range<Dims_> NumWorkItems) {
                            ^
/opt/sycl/lib/clang/9.0.0/include/CL/sycl/detail/cg.hpp:70:29: note: candidate function template not viable: requires single argument 'ExecutionRange', but 2 arguments were
      provided
  template <int Dims_> void set(sycl::nd_range<Dims_> ExecutionRange) {
                            ^
In file included from stencil-sycl.cc:63:
In file included from /opt/sycl/lib/clang/9.0.0/include/CL/sycl.hpp:15:
In file included from /opt/sycl/lib/clang/9.0.0/include/CL/sycl/accessor.hpp:11:
In file included from /opt/sycl/lib/clang/9.0.0/include/CL/sycl/accessor2.hpp:12:
In file included from /opt/sycl/lib/clang/9.0.0/include/CL/sycl/buffer.hpp:11:
In file included from /opt/sycl/lib/clang/9.0.0/include/CL/sycl/detail/buffer_impl2.hpp:20:
In file included from /opt/sycl/lib/clang/9.0.0/include/CL/sycl/handler.hpp:10:
/opt/sycl/lib/clang/9.0.0/include/CL/sycl/handler2.hpp:573:14: error: no matching member function for call to 'set'
    MNDRDesc.set(std::move(NumWorkItems), std::move(WorkItemOffset));
    ~~~~~~~~~^~~
./stencil_sycl.hpp:49:7: note: in instantiation of function template specialization 'cl::sycl::handler::parallel_for<star2_1d<double>, (lambda at ./stencil_sycl.hpp:49:92), 2>'
      requested here
    h.parallel_for<class star2_1d<T>>(cl::sycl::range<2> {n-4,n-4}, cl::sycl::id<2> {2,2}, [=] (cl::sycl::item<2> it) {
      ^
stencil-sycl.cc:92:29: note: in instantiation of function template specialization 'star2<double>' requested here
          case 2: stencil = star2; break;
                            ^
stencil-sycl.cc:324:9: note: in instantiation of function template specialization 'run<double>' requested here
        run<double>(host, iterations, n, tile_size, star, radius);
        ^
/opt/sycl/lib/clang/9.0.0/include/CL/sycl/detail/cg.hpp:59:29: note: candidate function template not viable: requires single argument 'NumWorkItems', but 2 arguments were
      provided
  template <int Dims_> void set(sycl::range<Dims_> NumWorkItems) {
                            ^
/opt/sycl/lib/clang/9.0.0/include/CL/sycl/detail/cg.hpp:70:29: note: candidate function template not viable: requires single argument 'ExecutionRange', but 2 arguments were
      provided
  template <int Dims_> void set(sycl::nd_range<Dims_> ExecutionRange) {
                            ^
In file included from stencil-sycl.cc:63:
In file included from /opt/sycl/lib/clang/9.0.0/include/CL/sycl.hpp:15:
In file included from /opt/sycl/lib/clang/9.0.0/include/CL/sycl/accessor.hpp:11:
In file included from /opt/sycl/lib/clang/9.0.0/include/CL/sycl/accessor2.hpp:12:
In file included from /opt/sycl/lib/clang/9.0.0/include/CL/sycl/buffer.hpp:11:
In file included from /opt/sycl/lib/clang/9.0.0/include/CL/sycl/detail/buffer_impl2.hpp:20:
In file included from /opt/sycl/lib/clang/9.0.0/include/CL/sycl/handler.hpp:10:
/opt/sycl/lib/clang/9.0.0/include/CL/sycl/handler2.hpp:573:14: error: no matching member function for call to 'set'
    MNDRDesc.set(std::move(NumWorkItems), std::move(WorkItemOffset));
    ~~~~~~~~~^~~
./stencil_sycl.hpp:98:7: note: in instantiation of function template specialization 'cl::sycl::handler::parallel_for<star3_1d<double>, (lambda at ./stencil_sycl.hpp:98:92), 2>'
      requested here
    h.parallel_for<class star3_1d<T>>(cl::sycl::range<2> {n-6,n-6}, cl::sycl::id<2> {3,3}, [=] (cl::sycl::item<2> it) {
      ^
stencil-sycl.cc:93:29: note: in instantiation of function template specialization 'star3<double>' requested here
          case 3: stencil = star3; break;
                            ^
stencil-sycl.cc:324:9: note: in instantiation of function template specialization 'run<double>' requested here
        run<double>(host, iterations, n, tile_size, star, radius);
        ^
/opt/sycl/lib/clang/9.0.0/include/CL/sycl/detail/cg.hpp:59:29: note: candidate function template not viable: requires single argument 'NumWorkItems', but 2 arguments were
      provided
  template <int Dims_> void set(sycl::range<Dims_> NumWorkItems) {
                            ^
/opt/sycl/lib/clang/9.0.0/include/CL/sycl/detail/cg.hpp:70:29: note: candidate function template not viable: requires single argument 'ExecutionRange', but 2 arguments were
      provided
  template <int Dims_> void set(sycl::nd_range<Dims_> ExecutionRange) {
                            ^
In file included from stencil-sycl.cc:63:
In file included from /opt/sycl/lib/clang/9.0.0/include/CL/sycl.hpp:15:
In file included from /opt/sycl/lib/clang/9.0.0/include/CL/sycl/accessor.hpp:11:
In file included from /opt/sycl/lib/clang/9.0.0/include/CL/sycl/accessor2.hpp:12:
In file included from /opt/sycl/lib/clang/9.0.0/include/CL/sycl/buffer.hpp:11:
In file included from /opt/sycl/lib/clang/9.0.0/include/CL/sycl/detail/buffer_impl2.hpp:20:
In file included from /opt/sycl/lib/clang/9.0.0/include/CL/sycl/handler.hpp:10:
/opt/sycl/lib/clang/9.0.0/include/CL/sycl/handler2.hpp:573:14: error: no matching member function for call to 'set'
    MNDRDesc.set(std::move(NumWorkItems), std::move(WorkItemOffset));
    ~~~~~~~~~^~~
./stencil_sycl.hpp:157:7: note: in instantiation of function template specialization
      'cl::sycl::handler::parallel_for<star4_1d<double>, (lambda at ./stencil_sycl.hpp:157:92), 2>' requested here
    h.parallel_for<class star4_1d<T>>(cl::sycl::range<2> {n-8,n-8}, cl::sycl::id<2> {4,4}, [=] (cl::sycl::item<2> it) {
      ^
stencil-sycl.cc:94:29: note: in instantiation of function template specialization 'star4<double>' requested here
          case 4: stencil = star4; break;
                            ^
stencil-sycl.cc:324:9: note: in instantiation of function template specialization 'run<double>' requested here
        run<double>(host, iterations, n, tile_size, star, radius);
        ^
/opt/sycl/lib/clang/9.0.0/include/CL/sycl/detail/cg.hpp:59:29: note: candidate function template not viable: requires single argument 'NumWorkItems', but 2 arguments were
      provided
  template <int Dims_> void set(sycl::range<Dims_> NumWorkItems) {
                            ^
/opt/sycl/lib/clang/9.0.0/include/CL/sycl/detail/cg.hpp:70:29: note: candidate function template not viable: requires single argument 'ExecutionRange', but 2 arguments were
      provided
  template <int Dims_> void set(sycl::nd_range<Dims_> ExecutionRange) {
                            ^
In file included from stencil-sycl.cc:63:
In file included from /opt/sycl/lib/clang/9.0.0/include/CL/sycl.hpp:15:
In file included from /opt/sycl/lib/clang/9.0.0/include/CL/sycl/accessor.hpp:11:
In file included from /opt/sycl/lib/clang/9.0.0/include/CL/sycl/accessor2.hpp:12:
In file included from /opt/sycl/lib/clang/9.0.0/include/CL/sycl/buffer.hpp:11:
In file included from /opt/sycl/lib/clang/9.0.0/include/CL/sycl/detail/buffer_impl2.hpp:20:
In file included from /opt/sycl/lib/clang/9.0.0/include/CL/sycl/handler.hpp:10:
/opt/sycl/lib/clang/9.0.0/include/CL/sycl/handler2.hpp:573:14: error: no matching member function for call to 'set'
    MNDRDesc.set(std::move(NumWorkItems), std::move(WorkItemOffset));
    ~~~~~~~~~^~~
./stencil_sycl.hpp:226:7: note: in instantiation of function template specialization
      'cl::sycl::handler::parallel_for<star5_1d<double>, (lambda at ./stencil_sycl.hpp:226:94), 2>' requested here
    h.parallel_for<class star5_1d<T>>(cl::sycl::range<2> {n-10,n-10}, cl::sycl::id<2> {5,5}, [=] (cl::sycl::item<2> it) {
      ^
stencil-sycl.cc:95:29: note: in instantiation of function template specialization 'star5<double>' requested here
          case 5: stencil = star5; break;
                            ^
stencil-sycl.cc:324:9: note: in instantiation of function template specialization 'run<double>' requested here
        run<double>(host, iterations, n, tile_size, star, radius);
        ^
/opt/sycl/lib/clang/9.0.0/include/CL/sycl/detail/cg.hpp:59:29: note: candidate function template not viable: requires single argument 'NumWorkItems', but 2 arguments were
      provided
  template <int Dims_> void set(sycl::range<Dims_> NumWorkItems) {
                            ^
/opt/sycl/lib/clang/9.0.0/include/CL/sycl/detail/cg.hpp:70:29: note: candidate function template not viable: requires single argument 'ExecutionRange', but 2 arguments were
      provided
  template <int Dims_> void set(sycl::nd_range<Dims_> ExecutionRange) {
                            ^
In file included from stencil-sycl.cc:63:
In file included from /opt/sycl/lib/clang/9.0.0/include/CL/sycl.hpp:15:
In file included from /opt/sycl/lib/clang/9.0.0/include/CL/sycl/accessor.hpp:11:
In file included from /opt/sycl/lib/clang/9.0.0/include/CL/sycl/accessor2.hpp:12:
In file included from /opt/sycl/lib/clang/9.0.0/include/CL/sycl/buffer.hpp:11:
In file included from /opt/sycl/lib/clang/9.0.0/include/CL/sycl/detail/buffer_impl2.hpp:20:
In file included from /opt/sycl/lib/clang/9.0.0/include/CL/sycl/handler.hpp:10:
/opt/sycl/lib/clang/9.0.0/include/CL/sycl/handler2.hpp:573:14: error: no matching member function for call to 'set'
    MNDRDesc.set(std::move(NumWorkItems), std::move(WorkItemOffset));
    ~~~~~~~~~^~~
stencil-sycl.cc:167:11: note: in instantiation of function template specialization 'cl::sycl::handler::parallel_for<add<double>, (lambda at stencil-sycl.cc:168:35), 2>'
      requested here
        h.parallel_for<class add<T>>(cl::sycl::range<2> {n, n}, cl::sycl::id<2> {0, 0},
          ^
stencil-sycl.cc:324:9: note: in instantiation of function template specialization 'run<double>' requested here
        run<double>(host, iterations, n, tile_size, star, radius);
        ^
/opt/sycl/lib/clang/9.0.0/include/CL/sycl/detail/cg.hpp:59:29: note: candidate function template not viable: requires single argument 'NumWorkItems', but 2 arguments were
      provided
  template <int Dims_> void set(sycl::range<Dims_> NumWorkItems) {
                            ^
/opt/sycl/lib/clang/9.0.0/include/CL/sycl/detail/cg.hpp:70:29: note: candidate function template not viable: requires single argument 'ExecutionRange', but 2 arguments were
      provided
  template <int Dims_> void set(sycl::nd_range<Dims_> ExecutionRange) {
                            ^
12 errors generated.
make: *** [Makefile:156: stencil-sycl] Error 1
```

**Comment by againull** [comment] 2019-05-29 18:43
@jeffhammond thank you for reporting the bug. 
  There is no set method in NDRDescTc class that corresponds to
`void parallel_for(range<Dims> NumWorkItems, id<Dims> WorkItemOffset, KernelType KernelFunc)`  
@romanovvlad Could you please take a look.

**Comment by bader** [comment] 2019-05-30 20:19
Might be a regression introduced by new scheduler.
Did you check if it works with the old scheduler?

**Comment by againull** [comment] 2019-05-30 23:55
Yes it is a regression. It works with old scheduler.
Small test:
#include <CL/sycl.hpp>

int main() {
  cl::sycl::default_selector selector;

  cl::sycl::queue myQueue(selector);
  std::cout << "Running on "
            << myQueue.get_device().get_info<cl::sycl::info::device::name>()
            << "\n";
  myQueue.submit([&](cl::sycl::handler& cgh) {
    cgh.parallel_for<class kernel>(cl::sycl::range<1>(10), cl::sycl::id<1>(0),[=](cl::sycl::id<1> i) {
    });
  });
  myQueue.wait();
  return 0;
}

**Comment by romanovvlad** [comment] 2019-05-31 10:34
The patch which solves the problem is in progress.

**Comment by jeffhammond** [comment] 2019-06-26 21:39
Any updates?

**Comment by keryell** [comment] 2019-06-26 21:57
We need this on some devices that does not use buffer accessors, for example an FPGA kernel acting on some specific pipes or functions and other weird devices.

**Comment by jeffhammond** [comment] 2019-07-25 21:14
@romanovvlad what is the status of this?

**Comment by keryell** [comment] 2019-07-25 22:46
Add a rule in the scheduler to just schedule any kernel that does not have any input dependency?
Also required for FPGA with pipe-only kernels, which landed recently...

**Comment by romanovvlad** [comment] 2019-07-26 08:57
@jeffhammond The bug should be fixed already. The small reproducer from @againull  successfully compiles as well as your original one(PRK). 

@keryell I'm not sure how the original problem is related to scheduling kernels without input dependency, could you, please, clarify?

**Comment by jeffhammond** [comment] 2019-07-26 13:58
@romanovvlad Is it safe to close the ticket then?

**Comment by keryell** [comment] 2019-07-27 01:38
@romanovvlad good question! I am still asking why I wrote this... :-( Not enough sleep perhaps...

**Comment by romanovvlad** [comment] 2019-07-28 07:36
Ok, then I'm closing the ticket.

**Closed by romanovvlad** 2019-07-28 07:36 UTC
Labels: bug
