### ISSUE TITLE
CPU opencl backend crashing application on windows

### ISSUE THREAD

**Issue by jzidia** [intel/llvm#6283] opened 2022-06-09 18:47 UTC
**Description**
I use a private build of the compiler (DPC++/sycl) that was built using MSVC v142 (VS 2019) with CUDA support (CUDA 11.7). 
I wrote a simple, single-file application that reports basic info on the devices detected by the Sycl/DPC++ runtime and then runs a simple kernel (vector addition) on a CUDA GPU, Intel's iGPU (HD P630), the host device, and CPU device (OpenCL backend).
When attempting to run Kernel on CPU (CPU selector with OpenCL backend)

**To Reproduce**
1. Use a Windows build of the compiler with CUDA support (per build instructions use CUDA 11.6 or later - I used 11.7).
2. Compile the attached code file (or just create a simple console app that creates a context from/for a cpu device) with: 'clang++.exe -fsycl -fsycl-targets=spir64,nvptx64-nvidia-cuda SyclConsoleApplication.cpp'
4. Run with 'a.exe'
5. The last message printed with the application should be:
    'Message: Native API failed. Native API returns: -6 (CL_OUT_OF_HOST_MEMORY) -6 (CL_OUT_OF_HOST_MEMORY)'

The exception comes when trying to create a context for an OpenCL-CPU device. You can try to create that context directly with no Kernels involved and still get the same error message.

**Environment:**

- OS: Windows10
- Target device and vendor: 
1. Intel(R) Xeon(R) CPU E3-1505M v6 @ 3.00GHz
2. Intel(R) HD Graphics P630 (iGPU)
3. Intel(R) FPGA Emulation Device (virtual)
4. Nvidia's Quadro P3000

- DPC++ version: As of 6/9/2022 the latest Official release (CODE->Download.zip on github)
- Dependencies version: During DPC++ build CUDA toolkit 11.7 and MSVC 2019 (v142) were used. (VS version 16.11.15)

**Additional context**
Intel's oneAPI (2022.2) is also installed and integrated with VS2019 but (AFAIK) is not related in any way to the open-source build of DPC++. Additionally, oneAPI was installed after the build of DPC++ was completed.

Attachments: Code (with txt extension), Console output of the application
[SyclConsoleApplication.txt](https://github.com/intel/llvm/files/8873019/SyclConsoleApplication.txt)
[ConsoleOutput.txt](https://github.com/intel/llvm/files/8873077/ConsoleOutput.txt)

**Comment by jzidia** [comment] 2022-06-11 20:03
I was able to find a way to fix the issue. It seems that Intel's OpenCL runtime for the CPU is built on top of TBB. Thus TBB DLLs need to be accessible at run time to the executable. Adding TBBs bin path (by default C:\Program Files (x86)\Intel\oneAPI\tbb\latest\redist\intel64\vc_mt) to the PATH environment variable seems to solve the problem.

Apologies for tagging as a bug something that was not really a bug. I believe the topic will be useful to others though.

**Comment by AlexeySachkov** [comment] 2022-08-19 08:04
Hi @jzidia,

Glad to hear you were able to figure out what was the problem and resolve it.

> 'Message: Native API failed. Native API returns: -6 (CL_OUT_OF_HOST_MEMORY) -6 (CL_OUT_OF_HOST_MEMORY)'

I would expect a different error code here, something like `CL_DEVICE_NOT_AVAILABLE` (don't remember a number associated with it), but that won't be of great help either. Standard OpenCL API only provides us with functionality to return a single error code, without explaining much.

> I believe the topic will be useful to others though.

Yes, indeed, errors with misconfiguring library search paths happen regularly. I will still close it, because the issue is resolved, but it should be anyway searchable through GitHub UI

**Closed by AlexeySachkov** 2022-08-19 08:04 UTC
Labels: bug, OCL CPU Experimental RT, confirmed
