### ISSUE TITLE
Crash in sycl::event::get_backend for default-constructed event

### ISSUE THREAD

**Issue by oleksandr-pavlyk** [intel/llvm#9264] opened 2023-05-01 03:09 UTC
**Describe the bug**
A crash during ``sycl::event::get_backend()`` for default-constructed event.

**To Reproduce**

```c++
#include <sycl/sycl.hpp>
#include <iostream>

int main(void) {
  sycl::event def_ev {};

  std::cout << "Querying default event backend: " << std::endl;
  auto def_ev_be = def_ev.get_backend();

  std::cout << "Default-constructed event's backend: " << def_ev_be << std::endl;

  return 0;
}
```

Used nightly sycl bundle

```
clang version 17.0.0 (/netbatch/donb644462_00/runDir/jenkins-dir/workspace/Tools_SH/SYCLOS_Nightly/RHEL/llvm.src/clang 5b52ebaacd430b69e8fd2a6ff255261f02731d01)
Target: x86_64-unknown-linux-gnu
Thread model: posix
InstalledDir: /home/opavlyk/repos/dpctl/tmp/dpcpp_compiler/bin
```

compiled using {{clang++ -fsycl default_event.cpp -o a.out}}.  Running the application I get SIGSEV with the following backtrace:

```
Querying default event backend:

Program received signal SIGSEGV, Segmentation fault.
0x00007ffff46e0a38 in sycl::_V1::event::get_backend() const () from /home/opavlyk/repos/dpctl/tmp/dpcpp_compiler/lib/libsycl.so.7
(gdb) bt
#0  0x00007ffff46e0a38 in sycl::_V1::event::get_backend() const () from /home/opavlyk/repos/dpctl/tmp/dpcpp_compiler/lib/libsycl.so.7
#1  0x00000000004013ed in main ()
```

```
(ossb) opavlyk@opavlyk-mobl:~/repos/dpctl/tmp$ OCL_ICD_VENDORS= OCL_ICD_FILENAMES=$HOME/repos/dpctl/tmp/oclcpuexp/x64/libintelocl.so:$HOME/repos/dpctl/tmp/fpgaemu/x64/libintelocl_emu.so ONEAPI_DEVICE_SELECTOR=opencl:cpu sycl-ls
Warning: ONEAPI_DEVICE_SELECTOR environment variable is set to opencl:cpu.
To see the correct device id, please unset ONEAPI_DEVICE_SELECTOR.

[opencl:cpu:0] Intel(R) OpenCL, 11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz OpenCL 3.0 (Build 0) [2023.15.3.0.20_160000]
(ossb) opavlyk@opavlyk-mobl:~/repos/dpctl/tmp$ OCL_ICD_VENDORS= OCL_ICD_FILENAMES=$HOME/repos/dpctl/tmp/oclcpuexp/x64/libintelocl.so:$HOME/repos/dpctl/tmp/fpgaemu/x64/libintelocl_emu.so ONEAPI_DEVICE_SELECTOR=opencl:cpu ./a.out
Querying default event backend:
Segmentation fault
```

**Environment (please complete the following information):**

- OS: Ubuntu 20.04 (by way of WSL)
- Target device and vendor: CPU

The issue was flagged by test suite of DPC++-based Python project [IntelPython/dpctl](https://github.com/IntelPython/dpctl.git).

**Comment by oleksandr-pavlyk** [comment] 2023-05-01 03:12
Reproduce used to behave as expected in "clang version 17.0.0 (/netbatch/donb1293070_00/runDir/jenkins-dir/workspace/Tools_SH/SYCLOS_Nightly/RHEL/llvm.src/clang f24a0bb343b25fa78a35247ed6f6e4b84b6d5908)".

**Comment by AlexeySachkov** [comment] 2023-06-23 19:20
Hi @oleksandr-pavlyk, thanks for the report. Have you tried any more recent versions of the compiler?

I've just tried local build (`clang version 17.0.0 (https://github.com/intel/llvm.git 9ac8d813c4b88d4a4a8c4a4b1a91569c731f2df3)`) and don't see the crash.

**Comment by AlexeySachkov** [comment] 2023-07-12 13:06
Discussed offline, the issue is not reproducible anymore by the reporter, closing it.

**Closed by AlexeySachkov** 2023-07-12 13:06 UTC
Labels: bug
