### ISSUE TITLE
CUDA_ERROR_OUT_OF_MEMORY in PI CUDA

### ISSUE THREAD

**Issue by mmeterel** [intel/llvm#1850] opened 2020-06-09 19:31 UTC
I have tested oneMKL open source interfaces (https://github.com/oneapi-src/oneMKL) with two compiler versions:

20200527: This version was causing CUDA_ERROR_NOT_PERMITTED error as mentioned in this issue (https://github.com/intel/llvm/issues/1569)

To solve this error, I built compiler from latest (20200608). The "CUDA_ERROR_NOT_PERMITTED" error is gone, however, I see memory leak issue now. 
We have a list of tests in oneMKL open source run with single gtest executable, and I start seeing the below error after a few tests.

PI CUDA ERROR:
        Value:           2
        Name:            CUDA_ERROR_OUT_OF_MEMORY
        Description:     out of memory
        Function:        cuda_piContextCreate
        Source Location: /nfs/pdx/disks/mkl_project/mmeterel/tools/dpcpp/llvm/sycl/plugins/cuda/pi_cuda.cpp:1395

Interestingly, all tests pass with ctest.

**Comment by bjoernknafla** [comment] 2020-06-10 11:16
This is very likely related to #1520

**Comment by hiaselhans** [comment] 2021-10-21 20:55
I have updated my build-chain to the most recent dpc++ and i am also seeing memory leaks now.

I used `queue.wait_and_throw()` as a workaround but that doesn't seem to do the job anymore.
It did work 6 months ago.

**Comment by hiaselhans** [comment] 2021-11-01 19:37
I share your view on this matter.

After some investigation sometime earlier, i discovered that while `sycl::event`s are properly destructed, `event_impl` instances are kept alive because the refcount would still be >=2 in `event::~event`

the same thing is happening to me using the level_zero backend.

**Comment by romanovvlad** [comment] 2021-11-02 15:24
@hiaselhans
Could you please add `delete runner` in the main and try again?

So main looks like:

```
int main() {
    int num = 10;
    auto runner = new Runner(num);
    runner->reset();
    runner->run();
    runner->print();
    delete runner;
    return 0;
}
```

**Comment by AidanBeltonS** [comment] 2021-11-09 13:53
> @hiaselhans Could you please add `delete runner` in the main and try again?
> 

I have ran it with and without the delete. Though there are some differences, I am not seeing any additional calls to destroy events when deleting the variable.
The nvprof results are below. Let me know if you want any more information. 
Many thanks.

With `delete runner`

```
            Type  Time(%)      Time     Calls       Avg       Min       Max  Name
 GPU activities:  100.00%  1.65302s   1163363  1.4200us  1.3750us  11.968us  _ZTSZZN6Runner3runEvENKUlRN2cl4sycl7handlerEE_clES3_E4test
                    0.00%  1.5680us         1  1.5680us  1.5680us  1.5680us  [CUDA memcpy HtoD]
      API calls:   66.41%  5.11529s   1163363  4.3960us  3.9010us  3.7709ms  cuLaunchKernel
                    7.97%  613.81ms   1163363     527ns     441ns  320.93us  cuStreamWaitEvent
                    7.41%  570.76ms   1163365     490ns     278ns  1.0945ms  cuEventCreate
                    6.34%  488.51ms   1163365     419ns     349ns  995.08us  cuEventRecord
                    4.94%  380.66ms   1163363     327ns     254ns  1.0932ms  cuOccupancyMaxPotentialBlockSize
                    4.55%  350.15ms   2327898     150ns     100ns  643.11us  cuCtxGetCurrent
                    1.77%  136.50ms         1  136.50ms  136.50ms  136.50ms  cuCtxCreate
                    0.55%  42.657ms         1  42.657ms  42.657ms  42.657ms  cuModuleLoadDataEx
                    0.04%  3.4065ms      1164  2.9260us  1.3570us  6.3270us  cuStreamSynchronize
                    0.00%  190.45us         1  190.45us  190.45us  190.45us  cuMemAlloc
                    0.00%  77.706us         4  19.426us  12.066us  33.827us  cuDeviceGetName
                    0.00%  20.756us         1  20.756us  20.756us  20.756us  cuDeviceGetPCIBusId
                    0.00%  9.9810us         1  9.9810us  9.9810us  9.9810us  cuStreamCreate
                    0.00%  8.4600us         1  8.4600us  8.4600us  8.4600us  cuMemcpyHtoDAsync
                    0.00%  3.1440us        16     196ns     122ns     653ns  cuDeviceGetAttribute
                    0.00%  1.1900us         3     396ns     122ns     893ns  cuDeviceGetCount
                    0.00%  1.0630us         2     531ns     288ns     775ns  cuModuleGetFunction
                    0.00%     822ns         4     205ns     130ns     318ns  cuDriverGetVersion
                    0.00%     543ns         2     271ns     123ns     420ns  cuDeviceGet
```

Without `delete runner`

```
 GPU activities:  100.00%  2.84121s   2000000  1.4200us  1.3750us  12.416us  _ZTSZZN6Runner3runEvENKUlRN2cl4sycl7handlerEE_clES3_E4test
                    0.00%  1.9840us         1  1.9840us  1.9840us  1.9840us  [CUDA memcpy DtoH]
                    0.00%  1.6000us         1  1.6000us  1.6000us  1.6000us  [CUDA memcpy HtoD]
      API calls:   66.85%  9.26991s   2000000  4.6340us  4.1030us  4.2057ms  cuLaunchKernel
                    9.02%  1.25099s   2000001     625ns     510ns  375.85us  cuStreamWaitEvent
                    7.40%  1.02594s   2000003     512ns     299ns  1.0367ms  cuEventCreate
                    6.39%  886.65ms   2000003     443ns     362ns  1.1016ms  cuEventRecord
                    4.92%  682.57ms   2000000     341ns     264ns  2.2115ms  cuOccupancyMaxPotentialBlockSize
                    4.28%  593.16ms   4002010     148ns     100ns  1.0945ms  cuCtxGetCurrent
                    1.07%  148.90ms         1  148.90ms  148.90ms  148.90ms  cuCtxCreate
                    0.05%  7.3254ms      2000  3.6620us  1.4500us  16.297us  cuStreamSynchronize
                    0.00%  239.64us         1  239.64us  239.64us  239.64us  cuModuleLoadDataEx
                    0.00%  189.80us         1  189.80us  189.80us  189.80us  cuMemAlloc
                    0.00%  61.451us         4  15.362us  12.308us  19.105us  cuDeviceGetName
                    0.00%  24.235us         1  24.235us  24.235us  24.235us  cuMemcpyDtoHAsync
                    0.00%  10.413us         1  10.413us  10.413us  10.413us  cuStreamCreate
                    0.00%  9.4340us         1  9.4340us  9.4340us  9.4340us  cuMemcpyHtoDAsync
                    0.00%  4.4940us         1  4.4940us  4.4940us  4.4940us  cuDeviceGetPCIBusId
                    0.00%  3.0040us        16     187ns     124ns     495ns  cuDeviceGetAttribute
                    0.00%  1.2430us         3     414ns     147ns     933ns  cuDeviceGetCount
                    0.00%  1.1750us         1  1.1750us  1.1750us  1.1750us  cuEventSynchronize
                    0.00%     934ns         2     467ns     277ns     657ns  cuModuleGetFunction
                    0.00%     717ns         4     179ns     114ns     276ns  cuDriverGetVersion
                    0.00%     502ns         2     251ns     136ns     366ns  cuDeviceGet
```

**Comment by romanovvlad** [comment] 2021-11-10 11:28
Looking at `SYCL_PI_TRACE` output with `delete runner` I do not see any imbalance in events creation and releasing - for all events we have calls to `piEventRelease`. Please, let me know if you see a different picture.

The `nvproj` output above shows a huge number of calls to `cuEventCreate`, which is suspicious, have this results been obtained using reproducer from this comment https://github.com/intel/llvm/issues/1850#issuecomment-956335991 ?

**Comment by AidanBeltonS** [comment] 2021-11-11 10:48
I do not see an imbalance in `piEventRelease` with `piEventRetain/Create`. I believe this is to be expected. Also yes, this is the output of the reproducer above.

The events are created when a `piEnqueueX` is called with a non-nullptr event. The new event is created with the plugin function, and the event's constructor calls `cuEventCreate`. So this means that an event is created without a call to `piEventCreate` or `piEventRetain`, so nothing will appear in the trace. This implementation matches the OpenCL plugin, where functions like `clEnqueueReadBufferRect` create an event. See https://www.khronos.org/registry/OpenCL/specs/2.2/html/OpenCL_API.html#clEnqueueReadBufferRect for details.

As a result, `piEnqueueX` correctly returns an event to match OpenCL. So this leads me to think that it is the caller of these functions' responsibility to clean up the returned event. Maybe there are other approaches to cleaning up the returned event that I have not thought of.

**Comment by bader** [comment] 2021-11-16 11:03
@romanovvlad, what is your opinion on the ownership responsibility? Is the runtime library responsible for releasing events created by `piEnqueue*` or plug-ins?

**Comment by romanovvlad** [comment] 2021-11-17 11:15
>> @romanovvlad, what is your opinion on the ownership responsibility? Is the runtime library responsible for releasing events created by piEnqueue* or plug-ins?

Yes, SYCL RT is responsible for releasing events and from what I see it does release them in this case.

>> Also yes, this is the output of the reproducer above.

Any idea why it shows so big number of calls to CUDA API? It's hard to imagine how one `queue::submit` could lead to `2000000  ` calls of `cuLaunchKernel` .


>> The events are created when a piEnqueueX is called with a non-nullptr event.

That's correct, in the output of SYCL_PI_TRACE we should see something like:
Ev1 = piEnqueue.*
piEventRetain(Ev1); // called N times
piEventRelease(Ev1); // called N + 1 times

Could you please check if this matches the output of SYCL_PI_TRACE for the reproducer from this comment https://github.com/intel/llvm/issues/1850#issuecomment-956335991 + `delete runner;` added?

**Comment by AidanBeltonS** [comment] 2021-11-18 10:18
> Any idea why it shows so big number of calls to CUDA API? It's hard to imagine how one `queue::submit` could lead to `2000000 ` calls of `cuLaunchKernel` .

The number of calls the to CUDA API is large as the reproducer loops over the submit 2e6 times. This is to try triggering the CUDA memory error.

> Could you please check if this matches the output of SYCL_PI_TRACE for the reproducer from this comment [#1850 (comment)](https://github.com/intel/llvm/issues/1850#issuecomment-956335991) + `delete runner;` added?

When changing the number of kernels the reproducer submits, to get the SYCL_PI_TRACE, nvprof produced the correct results. If the number of kernels submitted is between 1 and 10000 and the runner is deleted, nvprof does produce the correct number of `cuEventDestroy` calls. I think the issue is with nvprof not being able to store the very large number of calls the reproducer creates. Which would then indicate that events destruction is not an issue. 

@hiaselhans, is the CUDA memory error still an issue for you, do you have another reproducer of the issue?

**Comment by hiaselhans** [comment] 2021-11-18 10:22
hi @AidanBeltonS ,

i've been using hipsycl in the meantime. I had this issue with cuda and level_zero backend. My Memory was filling after a few thousand kernel deploys. With the said reproducer.
It's been a while but i think i got to a point where i realized that the sycl::events are properly destroyed, but the refcount of event_impl was stil >= 2 in the destructor of sycl::event.

i will try to test again with the latest upstream.

**Comment by AidanBeltonS** [comment] 2021-11-22 17:45
> i will try to test again with the latest upstream.

Have you had the chance to try with the upstream?

> i've been using hipsycl in the meantime. I had this issue with cuda and level_zero backend. My Memory was filling after a few thousand kernel deploys. With the said reproducer. It's been a while but i think i got to a point where i realized that the sycl::events are properly destroyed, but the refcount of event_impl was stil >= 2 in the destructor of sycl::event.

How are you measuring the memory usage? As if you are still having the issue I can investigate if I can try reproduce it. As I am currently not able to see any issue. 
Thanks

**Comment by AerialMantis** [comment] 2021-12-06 17:41
As we're not able to reproduce this issues described in here we believe it's like the issue has been solved by a prior change, so we would like to close this ticket. However, if the issue still appears please comment and we can re-open the ticket.

**Closed by AerialMantis** 2021-12-06 17:41 UTC
Labels: bug, cuda, runtime
