### ISSUE TITLE
PTX tests don't seem to be running during PR checks

### ISSUE THREAD

**Issue by Alexander-Johnston** [intel/llvm#3002] opened 2021-01-08 15:10 UTC
I've recently been running ptx sycl tests and found a number of failures. From some investigation it seems that the sycl tests aren't run for ptx during the PR checks.

From what I can tell the following testing is currently run on PRs

`buildbot/Lit_With_Cuda`
This seems to be running `check-sycl-cuda` which has been running the on-device tests since https://github.com/intel/llvm/commit/f1ab47c1e05c99ebea7b3a6ec44529ccc8b136a8
Notably the stage in which this is run is called `check-sycl`. As the cuda backend is built, the `check-sycl` or the new `check-sycl-ptx` testsuite (introduced in the commit above) would run the sycl tests for ptx. I believe this stage is currently mislabelled.

`buildbot/sycl-ubu-x64-pr` and `buildbot/sycl-win-x64-pr`
Neither of these build with cuda enabled, so when `check-sycl` is run the sycl tests aren't tested with ptx.

I suspect what has happened is the `Lit_With_Cuda` was running the ptx tests through the `check-sycl-cuda` testsuite, but hasn't been updated to match the new commit above. I can't see the scripts invoking the CI though so can't be sure.

Crucially, at the moment it seems that `check-sycl-ptx` isn't run during any PR checks.

As a result we get the following test results from `check-sycl` on the ptx backend, which matches the results of `check-sycl-ptx`
```
  Unsupported:   5
  Passed     : 191
  Failed     :  86
```

`basic_tests/built-ins.cpp` fails at ptx assembly:
```
ptxas /tmp/built-ins-c5cedf.s, line 35; error   : Call has wrong number of parameters
ptxas fatal   : Ptx assembly aborted due to errors
```
The test shouldn't be running though, as it is marked UNSUPPORTED for cuda. Something a bit weird is going on there.

It seems the other failures are all from PiCudaTests failing to find the cuda PI plugin. 
```
terminate called after throwing an instance of 'std::runtime_error'
  what():  cuda PI plugin not found!
```
Has something changed recently in how plugins are detected and/or loaded?

**Comment by vladimirlaz** [comment] 2021-01-09 13:52
Fix for the issue is under https://github.com/intel/llvm/pull/3007

**Comment by vladimirlaz** [comment] 2021-01-11 10:48
@Alexander-Johnston , the fix has been submitted (both for missing in CI and failing tests)

**Closed** 2021-01-11 10:48 UTC
