### ISSUE TITLE
sycl::info::context:: atomic_fence_scope_capabilities and atomic_fence_order_capabilities are not implemented

### ISSUE THREAD

**Issue by aleksmesh** [intel/llvm#8323] opened 2023-02-13 10:27 UTC
In SYCL 2020 sycl::info::context::atomic_fence_scope_capabilities and sycl::info::context::atomic_fence_order_capabilities are introduced [4.6.3.2. Context information descriptors](https://registry.khronos.org/SYCL/specs/sycl-2020/html/sycl-2020.html#_context_information_descriptors) but not implemented.

**To Reproduce**
```
#include <sycl.hpp>

int main() {
  auto scope_capabilities = sycl::info::context::atomic_fence_scope_capabilities;
  auto order_capabilities = sycl::info::ontext::atomic_fence_order_capabilities;
}

```

**To build:**
`clang++ -fsycl context_fence_order_scope_capabilities.cpp -o sample`

**Output:**
```
/context_fence_order_scope_capabilities.cpp:4:50: error: no member named 'atomic_fence_order_capabilities' in namespace 'sycl::info::context'
  auto order_capabilities = sycl::info::context::atomic_fence_order_capabilities;
                            ~~~~~~~~~~~~~~~~~~~~~^
./context_fence_order_scope_capabilities.cpp:5:50: error: no member named 'atomic_fence_scope_capabilities' in namespace 'sycl::info::context'
  auto scope_capabilities = sycl::info::context::atomic_fence_scope_capabilities;
                            ~~~~~~~~~~~~~~~~~~~~~^
2 errors generated.
```

**Environment details**
Compiler version: from container [14bf9d9a9a456f665f2d5c26cf586bc56b4e06f7](https://github.com/intel/llvm/pkgs/container/llvm%2Fsycl_ubuntu2004_nightly/70049542?tag=14bf9d9a9a456f665f2d5c26cf586bc56b4e06f7)

**Comment by maarquitos14** [comment] 2023-02-23 15:37
Closing issue as it is a duplicate of #8293.

**Closed by maarquitos14** 2023-02-23 15:37 UTC
Labels: bug, duplicate, CTS
