### ISSUE TITLE
Build failure - at configure step with --native_cpu "undefined reference to `spvtools::SpirvTools::SpirvTools(spv_target_env)"

### ISSUE THREAD

**Issue by vidyalathabadde** [intel/llvm#12423] opened 2024-01-17 17:34 UTC
Could someone help me out with the successful installation of open-source dpcpp compiler?

Here is the error log after `python $DPCPP_HOME/llvm/buildbot/configure.py --native_cpu` step

[errorlog.txt](https://github.com/intel/llvm/files/13966568/errorlog.txt)

The build failure occurs at this point

[3312/3633] Linking CXX executable bin/llvm-spirv
FAILED: bin/llvm-spirv

Did I miss some environment set-up?

Thanks,
Vidya

**Comment by vidyalathabadde** [comment] 2024-01-22 11:50
Could someone please help me out with this issue?

**Comment by PietroGhg** [comment] 2024-01-24 16:07
Hi @vidyalathabadde, sorry for the late reply. Which branch/commit are you on? Do you get the same error if you try to configure without `--native_cpu` ?

**Comment by vidyalathabadde** [comment] 2024-01-27 07:00
Hi @PietroGhg ,
Thanks for your reply.
Yes, i get the same error without `--native_cpu` option as well.
 I followed the steps from the [guide](https://intel.github.io/llvm-docs/GetStartedGuide.html). I think i cloned it from sycl branch
 `git clone https://github.com/intel/llvm -b sycl`

**Comment by PietroGhg** [comment] 2024-01-30 09:53
Hi, I've never run into the error you are experiencing, I need a bit more details to help you out, can you make sure that you are on a recent commit and post the full output of the configure and build steps? 
Thank you

**Comment by vidyalathabadde** [comment] 2024-01-31 12:43
>>can you make sure that you are on a recent commit
Could you please give me the link to the recent commit so that i can try to configure with the same so that we are on the same page?
I attached the complete build log in my first post. Please check it.

**Comment by PietroGhg** [comment] 2024-01-31 12:58
I see that your build is picking up `/opt/intel/oneapi/intelpython/latest/lib/libSPIRV-Tools-shared.so`, I'm not sure why that's happening but it could be that this leads to the linker errors you are seeing, try doing a fresh clone of the repo in a fresh environment (e.g. a new terminal session)

**Comment by dm-vodopyanov** [comment] 2024-02-05 13:39
The failure reproduced locally today when building intel/llvm from scratch on the latest available commit (https://github.com/intel/llvm/commit/b781e6ca1fae2fe0b7bbf5be406119c0f1261257).

**Comment by bwlodarcz** [comment] 2024-02-05 15:26
@dm-vodopyanov Are you sure that in you don't have external spirv-tools in your `PATH` when you run buildbot scripts?
It happened to me to have this error before and it was exactly this.
E.g. 
```
/usr/bin/ld: tools/llvm-spirv/tools/llvm-spirv/CMakeFiles/llvm-spirv.dir/llvm-spirv.cpp.o: in function `convertLLVMToSPIRV(SPIRV::TranslatorOpts const&)':
llvm-spirv.cpp:(.text._ZL18convertLLVMToSPIRVRKN5SPIRV14TranslatorOptsE+0x345): undefined reference to `spvtools::SpirvTools::SpirvTools(spv_target_env)'
/usr/bin/ld: llvm-spirv.cpp:(.text._ZL18convertLLVMToSPIRVRKN5SPIRV14TranslatorOptsE+0x380): undefined reference to `spvtools::SpirvTools::SetMessageConsumer(std::function<void (spv_message_level_t, char const*, spv_position_t const&, char const*)>)'
/usr/bin/ld: llvm-spirv.cpp:(.text._ZL18convertLLVMToSPIRVRKN5SPIRV14TranslatorOptsE+0x4e1): undefined reference to `spvtools::SpirvTools::Disassemble(unsigned int const*, unsigned long, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >*, unsigned int) const'
/usr/bin/ld: llvm-spirv.cpp:(.text._ZL18convertLLVMToSPIRVRKN5SPIRV14TranslatorOptsE+0x5b0): undefined reference to `spvtools::SpirvTools::~SpirvTools()'
collect2: error: ld returned 1 exit status
```
Without visible spirv-tools - everything builds for me correctly.

**Comment by vidyalathabadde** [comment] 2024-02-05 16:44
Could you please let me know how to build the compiler successfully without any errors?
How to check if we have any external spirv-tools? I'm just sourcing setvars script from oneapi.

**Comment by PietroGhg** [comment] 2024-02-05 16:50
Can you try building without sourcing the setvars script from oneAPI? That's what I meant when I said using a "fresh environment", sorry if I wasn't clear. Open a new terminal session, clone the repo and run the `configure.py` and `compile.py` scripts

**Comment by maarquitos14** [comment] 2024-04-09 17:36
@vidyalathabadde I am unable to reproduce this just by following the steps provided in the guide. Also, judging by the comments in this issue, it seems like it was env issue, so I'm closing the issue. Please, feel free to reopen if you find this issue again.

**Closed by maarquitos14** 2024-04-09 17:36 UTC
Labels: bug, confirmed
