### ISSUE TITLE
Suspected bug on beta4 devcloud

### ISSUE THREAD

**Issue by paboyle** [intel/llvm#1171] opened 2020-02-25 13:18 UTC
Hi, 

I reproduced a problem with only a subset of threads getting the correct answer on dpcpp on the Intel devcloud.

This depends on the layout for local work group. If the local workgroup is working on consecutive data the problem occurs (I was targeting read/write coalescence), but mapping them to work on work items corresponding to well separated data worked.

All cases worked on CPU target, failed on Gen9 target on devcloud.

When it fails 1 SIMD lane is correct, but other lanes in the same local group are not written.
(i.e. looks like only 1/N of the threads actually do their work).

Code is at www.github.com/paboyle/GridBench/ 

Current develop branch.

Just 

git clone https://www.github.com/paboyle/GridBench

make -j

./bench.rrii.sycl.cpu          PASS
./bench.rrii.sycl.gpu          PASS
./bench.rrii.sycl.cpu           PASS
./bench.rrii.sycl.cpu           FAIL - runs on GPU with attempt at read coalescing

196 ref -1.89885 result -1.89885
197 ref -1.54196 result 0 
198 ref -0.693205 result 0
199 ref -1.35408 result 0

Example of output with compare ok on SIMD lane 0, but miscompare on "SIMD" lanes 123

The mapping of workgroup is controlled in 

WilsonKernelsHandCpu.h line 489.

        cl::sycl::range<3> local {Nsimd,1,1};

Kernel is invoked as:

        cgh.parallel_for<class dslash>(cl::sycl::nd_range<3>(global,local), [=] (cl::sycl::nd_item<3> item) {

The "Nsimd" is the intended coalescing index.

If I change this to:

        cl::sycl::range<3> local {2,1,1};

It changes the pattern to 1/2 being incorrect.

If I change this to:

        cl::sycl::range<3> local {1,1,1};

OR

        cl::sycl::range<3> local {1,Ls,1};

The code works on GPU.

I don't have a massively cut down example; this is much smaller than my 200k LOC application already.

**Comment by Pennycook** [comment] 2020-02-25 14:33
I haven't been able to reproduce the error on my local machine, but I think I might see the problem. 
 The fastest-moving index in a SYCL ND-range is the rightmost, so you want your local range to be `{1, 1, Nsimd}`, and you need to use `get_global_id(2)` to query the SIMD lane.

**Comment by paboyle** [comment] 2020-02-27 13:35
Reordered the indexing but still fails. I think I had already tried both
Advice appreciated.

Diff is:

 #ifdef GRID_SYCL_SIMT
-       cl::sycl::range<3> global{Nsimd,Ls,nsite};
-       cl::sycl::range<3> local {Nsimd,1,1};
+       //      cl::sycl::range<3> global{Nsimd,Ls,nsite};
+       //      cl::sycl::range<3> local {Nsimd,1,1};
+       cl::sycl::range<3> global{nsite,Ls,Nsimd};
+       cl::sycl::range<3> local {1,1,Nsimd};
 #else
-       cl::sycl::range<3> global{1,Ls,nsite};
+       //      cl::sycl::range<3> global{1,Ls,nsite};
+       //      cl::sycl::range<3> local {1,Ls,1};
+       cl::sycl::range<3> global{nsite,Ls,1};
        cl::sycl::range<3> local {1,Ls,1};
 #endif
        cgh.parallel_for<class dslash>(cl::sycl::nd_range<3>(global,local), [=] (cl::sycl::nd_item<3> item) {
 
-           auto mylane = item.get_global_id(0);
+           auto mylane = item.get_global_id(2);
            auto    s   = item.get_global_id(1);
-           auto   sU   = item.get_global_id(2);
+           auto   sU   = item.get_global_id(0);
            auto    ss  = s+Ls*sU;

**Comment by Pennycook** [comment] 2020-02-27 18:27
Thanks for checking.  I've managed to reproduce the error now on my local machine, and I think I might have identified a workaround in arch/rrii/Simd_rrii_vec.h:
```c++
+#if 0
 typedef float     vfloat  __attribute__ ((vector_size (4*sizeof(float))));
 typedef double    vdouble __attribute__ ((vector_size (4*sizeof(double))));
 typedef Integer vinteger  __attribute__ ((vector_size (4*sizeof(uint32_t))));
+#else
+#include <CL/sycl.hpp>
+typedef cl::sycl::vec<float,4> vfloat;
+typedef cl::sycl::vec<double,4> vdouble;
+typedef cl::sycl::vec<uint32_t,4> vinteger;
+#endif
```

Does this fix things for you, and does it align with what you're trying to do?  If so, it looks like there may be some issue with the vector attribute that we need to investigate further.

**Comment by paboyle** [comment] 2020-02-27 21:05
I confirm that I also get this behaviour. It works with the SYCL vec. 

I get 20GF/s double precision from SIMT  read coalesced version, and 5 GF's from the non-SIMT version.

I get 35GF/s single precision.

The four cores on same code give 125GF/s single precision, and 93 in double, but I have an artificially short vector length in single so not surprising the ratio is not 2x.

Personally, I'd really like the vector attribute to work - I'm seeking a way of cross platform single source.

Thanks !

**Comment by keryell** [comment] 2020-02-28 19:42
> Personally, I'd really like the vector attribute to work - I'm seeking a way of cross platform single source.

Is there a way to avoid this vector attribute? It is non standard C++, so I do not know if it can really be named "cross platform" then...
Do you think there is something missing in the SYCL standard?

**Comment by paboyle** [comment] 2020-03-10 13:03
There's always ways to get rid of things, it just increases the volume of code and test coverage cases, but that is a significant penalty. Currently, I cannot combine host vectorisation with GPU acceleration (x86 intrinsics don't run on an Nvidia thread) but this is a route to do so.

I'm trying to minimise the difference between SyCL GPU code and vectorisable CPU code that is compiled with non-SYCL compilers. I have to also support CUDA Nvidia systems, and the ARM SVE system in Japan as well as standard legacy x86 compilers for clusters by containing Intel and AMD CPUs.

Vector attributes are more portable than sycl::vec on account of them not needing SYCL, and working on the systems above that won't use SYCL. Whatever you say, SYCL is not a universal platform that will run everywhere in future, and if asked you to start supporting the Fujitsu system I bet you wouldn't like it!

Vector extensions are more architecture portable than intrinsics which Intel has been suggesting to us for years, because they are not tied to any one architecture. 
That way I could target SSE, AVX, AVX512, ARM SVE etc.. all from a single source, and have host code SIMD vectorise while GPU coded coalesces.

The gcc attributes are supported by multiple (gcc, clang, icc, armclang) compilers, and give me a shot at single source for many architectures, with dropping to architecture specific vector instructions.

**Comment by keryell** [comment] 2020-03-10 22:39
> Vector attributes are more portable than sycl::vec on account of them not needing SYCL, and working on the systems above that won't use SYCL.
> Whatever you say, SYCL is not a universal platform that will run everywhere in future,

There is always a design issue, either to put more and more things into SYCL or to just use SYCL as a pure C++ component to target some accelerators in a bigger picture.

> and if asked you to start supporting the Fujitsu system I bet you wouldn't like it!

Anyone can contribute to the SYCL open-source implementations. Why not people from Fujitsu? :-)
 
> Vector extensions are more architecture portable than intrinsics which Intel has been suggesting to us for years, because they are not tied to any one architecture.
> That way I could target SSE, AVX, AVX512, ARM SVE etc.. all from a single source, and have host code SIMD vectorise while GPU coded coalesces.
> 
> The gcc attributes are supported by multiple (gcc, clang, icc, armclang) compilers, and give me a shot at single source for many architectures, with dropping to architecture specific vector instructions.

What prevents you for example you to use SYCL with vector extensions if you want at least inside host kernels or more generally host code?

You can use the following macro to decide whether some code can be considered on the device side or not:
```c++
#ifdef __SYCL_DEVICE_ONLY__
// Some specific things in the case it is compiled for the device
#else
// Insert a lot of Fujitsu & NEC inline assembly
#endif
```
You can use also some higher-level SIMD frameworks, such as https://github.com/xtensor-stack/xsimd or some preliminary implementation of www.open-std.org/jtc1/sc22/wg21/docs/papers/2018/p0214r8.pdf and so on.

**Comment by Pennycook** [comment] 2022-03-02 16:48
I can no longer compile the reproducer with the latest compiler (because it more strictly enforces `SYCL_EXTERNAL` behavior) so I'm not sure if the original problem still exists.

But I still recommend that we close this issue, for the following reasons:
- `vector_size` is a compiler extension, and its behavior inside of SYCL kernels is not defined.  I don't think we should encourage the usage of `vector_size` and other Clang vector extensions within SPMD kernels, because the mental models are incompatible -- we want developers to reason about vectorization as happening across the work-items in a sub-group.
- The existing `sycl::vec` or `sycl::marray` classes work for this example, and have clearly defined behavior (specifically, each work-item gets its own vector/math array in the private address space, irrespective of any SIMD vectorization that an implementation may employ).
- We're working on several extensions (e.g. [sycl_ext_intel_esimd](https://github.com/intel/llvm/blob/sycl/sycl/doc/extensions/experimental/sycl_ext_intel_esimd/sycl_ext_intel_esimd.md) and [sycl_ext_oneapi_invoke_simd](https://github.com/intel/llvm/blob/sycl/sycl/doc/extensions/proposed/sycl_ext_oneapi_invoke_simd.asciidoc)) for cases where developers do not just want a convenience struct storing multiple elements but actually want to write code in terms of SIMD vectors.

I'm closing this for now; @paboyle, please reopen if there is more to discuss here.

**Closed by Pennycook** 2022-03-02 16:48 UTC
