### ISSUE TITLE
[E2E] Basic/kernel_info.cpp and GroupAlgorithm/root_group.cpp XPASS'd on OCL CPU in SYCL Nightly

### ISSUE THREAD

**Issue by uditagarwal97** [intel/llvm#13735] opened 2024-05-10 03:35 UTC
### Describe the bug

Run: https://github.com/intel/llvm/actions/runs/9019645870/job/24786062097
```
024-05-09T17:42:25.8702355Z XPASS: SYCL :: Basic/kernel_info.cpp (274 of 2025)
2024-05-09T17:42:25.8702739Z ******************** TEST 'SYCL :: Basic/kernel_info.cpp' FAILED ********************
2024-05-09T17:42:25.8702998Z Exit Code: 0
2024-05-09T17:42:25.8703080Z 
2024-05-09T17:42:25.8703144Z Command Output (stdout):
2024-05-09T17:42:25.8703305Z --
2024-05-09T17:42:25.8703422Z # RUN: at line 1
2024-05-09T17:42:25.8704031Z /__w/llvm/llvm/toolchain/bin//clang++   -fsycl -fsycl-targets=spir64  /__w/llvm/llvm/llvm/sycl/test-e2e/Basic/kernel_info.cpp -o /__w/llvm/llvm/build-e2e/Basic/Output/kernel_info.cpp.tmp.out
2024-05-09T17:42:25.8705068Z # executed command: /__w/llvm/llvm/toolchain/bin//clang++ -fsycl -fsycl-targets=spir64 /__w/llvm/llvm/llvm/sycl/test-e2e/Basic/kernel_info.cpp -o /__w/llvm/llvm/build-e2e/Basic/Output/kernel_info.cpp.tmp.out
2024-05-09T17:42:25.8705683Z # note: command had no output on stdout or stderr
2024-05-09T17:42:25.8705895Z # RUN: at line 2
2024-05-09T17:42:25.8706376Z env ONEAPI_DEVICE_SELECTOR=opencl:cpu  /__w/llvm/llvm/build-e2e/Basic/Output/kernel_info.cpp.tmp.out
2024-05-09T17:42:25.8706940Z # executed command: env ONEAPI_DEVICE_SELECTOR=opencl:cpu /__w/llvm/llvm/build-e2e/Basic/Output/kernel_info.cpp.tmp.out
2024-05-09T17:42:25.8707335Z # note: command had no output on stdout or stderr
2024-05-09T17:42:25.8707493Z 
2024-05-09T17:42:25.8707553Z --
2024-05-09T17:42:25.8707618Z 
2024-05-09T17:42:25.8707667Z ********************
2024-05-09T17:42:25.8707877Z XPASS: SYCL :: GroupAlgorithm/root_group.cpp (1177 of 2025)
2024-05-09T17:42:25.8712295Z ******************** TEST 'SYCL :: GroupAlgorithm/root_group.cpp' FAILED ********************
2024-05-09T17:42:25.8712641Z Exit Code: 0
2024-05-09T17:42:25.8712755Z 
2024-05-09T17:42:25.8712817Z Command Output (stdout):
2024-05-09T17:42:25.8712987Z --
2024-05-09T17:42:25.8713119Z # RUN: at line 3
2024-05-09T17:42:25.8713802Z /__w/llvm/llvm/toolchain/bin//clang++   -fsycl -fsycl-targets=spir64  /__w/llvm/llvm/llvm/sycl/test-e2e/GroupAlgorithm/root_group.cpp -I . -o /__w/llvm/llvm/build-e2e/GroupAlgorithm/Output/root_group.cpp.tmp.out
2024-05-09T17:42:25.8714971Z # executed command: /__w/llvm/llvm/toolchain/bin//clang++ -fsycl -fsycl-targets=spir64 /__w/llvm/llvm/llvm/sycl/test-e2e/GroupAlgorithm/root_group.cpp -I . -o /__w/llvm/llvm/build-e2e/GroupAlgorithm/Output/root_group.cpp.tmp.out
2024-05-09T17:42:25.8715788Z # note: command had no output on stdout or stderr
2024-05-09T17:42:25.8716028Z # RUN: at line 4
2024-05-09T17:42:25.8716468Z env ONEAPI_DEVICE_SELECTOR=opencl:cpu  /__w/llvm/llvm/build-e2e/GroupAlgorithm/Output/root_group.cpp.tmp.out
2024-05-09T17:42:25.8717092Z # executed command: env ONEAPI_DEVICE_SELECTOR=opencl:cpu /__w/llvm/llvm/build-e2e/GroupAlgorithm/Output/root_group.cpp.tmp.out
2024-05-09T17:42:25.8717520Z # note: command had no output on stdout or stderr
```

### To reproduce

DPC++ commit: 4b9819f0b6bf50da03ddc9987918c8d6e09ee757

### Environment

Backend and Device:  OpenCL CPU

**Comment by uditagarwal97** [comment] 2024-05-10 04:04
@sarnex @JackAKirk FYI.

**Comment by JackAKirk** [comment] 2024-05-10 13:52
It might just be a coincidence that this is a amd cpu, but for 22.04 amd also requires gcc12 for rocm: https://github.com/ROCm/ROCm/issues/2949.
In any case the timing suggests it was caused by the uplift to build with gcc12: https://github.com/intel/llvm/pull/13619

**Comment by sarnex** [comment] 2024-05-10 15:32
Thanks, I'll fix this.

**Comment by sarnex** [comment] 2024-05-10 15:42
@JackAKirk Assigning to you for now, if it still fails after reverting gcc12 please assign back to me.

**Comment by JackAKirk** [comment] 2024-05-13 09:35
> @JackAKirk Assigning to you for now, if it still fails after reverting gcc12 please assign back to me.

@sarnex I've signed it back to you. Everything is now working except the Xpasses so I think it is safe to merge your PR.

**Comment by sarnex** [comment] 2024-05-13 14:46
Got it, thx

**Closed** 2024-05-13 18:02 UTC
Labels: bug
