### ISSUE TITLE
[CUDA] Reduce run verification fail on CUDA backend

### ISSUE THREAD

**Issue by skosnits** [intel/llvm#5971] opened 2022-04-05 21:11 UTC
**Describe the bug**
[CUDA] Reduce run verification fail on CUDA backend

**To Reproduce**
1. Get SYCL with CUDA support ([GSG](https://intel.github.io/llvm-docs/GetStartedGuide.html)) 
2. Build and run attached source file: [reduce_for_external.cpp.txt](https://github.com/intel/llvm/files/8421856/reduce_for_external.cpp.txt)

```
clang++ -fsycl -fsycl-unnamed-lambda -fsycl-targets=nvptx64-nvidia-cuda-sycldevice reduce_for_external.cpp -o reduce.run  -lOpenCL
SYCL_DEVICE_FILTER="CUDA:GPU" SYCL_ENABLE_HOST_DEVICE="1" ./reduce.run
```

Error message:
```
Calculate failed: 1

out_c = 16777216.000000, out_g = 8422041.000000

input size : row = 8192, col = 8192

output size: row = 1, col = 1

allBytes = 268435460.000000(bit)

duration = 0.450085(ms)

BandWidth = 596.409939(GB/s)
```

**Environment**

- OS: Linux
- Target device and vendor: Nvidia GPU
- DPC++ version: https://github.com/intel/llvm.git 8ec97550b7a84e5d2483f4891059f80abd8db39c
- CUDA version: 
```
nvidia-smi
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 470.57.02    Driver Version: 470.57.02    CUDA Version: 11.4     |
|-------------------------------+----------------------+----------------------+
```

**Comment by zjin-lcf** [comment] 2022-04-06 02:52
Verification also fails on HIP backend.

**Comment by JackAKirk** [comment] 2022-04-14 10:38
@skosnits 
If this code sample does not give correct results for HIP and CUDA backends, could you clarify which backends it passes for?

I'm still working this out but I have a hunch it could be related to the fact this program appears to be assuming that the number of work_items per subgroup is 16, whereas in the CUDA backend it is always 32. This is why I think it would be useful to clarify that it is behaving as expected on a different backend and which backend that is?
It is noteworthy that there does not appear to be any test coverage for `subgroup.shuffle_down` and this should be added. However the generated machine code appears sensible to me.

**Comment by pengzhao-intel** [comment] 2022-04-15 13:22
@JackAKirk This code can get the correct results in Intel hardware.
It makes sense for the subgroup number. I don't know how sycl mapping this between different hardware and guarantee the correctness. 

 _this program appears to be assuming that the number of work_items per subgroup is 16, whereas in the CUDA backend it is always 32._

**Comment by zjin-lcf** [comment] 2022-04-15 15:24
Which Intel GPU was the program running on ?

  what():  Non-uniform work-groups are not supported by the target device -54 (CL_INVALID_WORK_GROUP_SIZE)

In the program, the work-group size is 1024.

**Comment by pengzhao-intel** [comment] 2022-04-16 02:57
@zjin-lcf sorry for the inconvenience and I forgot to change this number to a small one.  

Yes, the small workgroup makes sense as your experiments, like changing the size to half of  GroupSize with "4* SIMD" (or "2 * SIMD, or GroupRow to 1, 2, 4).

And this code shows 3 different reduction algorithms, you can switch it by changing "STATUS" to 0, 1, 2.

Feel free to let me know if any further questions.

**Comment by JackAKirk** [comment] 2022-04-27 14:32
It is expected behavior that this code will fail for the CUDA backend since it is not portable:

**More details** 

Firstly the usage of the decorator `[[intel::reqd_sub_group_size(SIMD)]]` which requests a subgroup size `SIMD` is commented out. Even if this decorator was used it would not lead to portable behavior using the CUDA backend because the only supported subgroup size is 32, and the CUDA backend simply ignores the decorator.  The proposed "named subgroup" extension would be a portable way to select a subgroup size which is guaranteed to be compatible with all core language features can be found here : https://github.com/intel/llvm/blob/sycl/sycl/doc/extensions/proposed/sycl_ext_oneapi_named_sub_group_sizes.asciidoc.  

A specific example where this code is not portable is on line 256 in the `reduce_by_row` function:

`int sg_id = sg.get_group_linear_id();`

Later use of sg_id within the kernel implies that the subgroup size equals `SIMD`.The test can be "fixed" If we set `STATUS = 1` (to use reduce_by_row) and we set `SIMD=32`: Then the test passes on CUDA backend.

For the HIP AMD backend I believe the same issue will arise because the supported subgroup sizes are {32, 64} (I think). Also note that `sub_group.shuffle_down` is marked as unsupported in the shuffle tests (I was wrong they do exist.. but shuffle_down is deprecated: see later comment) in [intel/llvm-test-suite](https://github.com/intel/llvm-test-suite/tree/intel/SYCL/SubGroup), so there may be further problems in that backend. Also note that sub_group.shuffle_down is part of a deprecated oneapi extension: see https://github.com/intel/llvm/pull/4943. `shuffle_down` has been replaced by `sub_group.shift_group_left` in the SYCL 2020 specification.

A final note: There is very limited mention of subgroups in this official DPC++ documentation: https://oneapi-src.github.io/DPCPP_Reference/index.html. I think it would be a good idea to introduce a section on subgroups that expands to some degree on the following:

_subgroups have vendor specific sizes that prevents code performing subgroup operations being fully portable. User code employing subgroup operations should have this in mind._

Similarly to issues of work-group size selection for a given GPU/vendor, it could also be good to mention that even if a code is portable it may not be optimal on other backends, providing some details of concepts to be aware of in guarenteeing good performance for such portable codes etc.

**Comment by pengzhao-intel** [comment] 2022-04-27 15:43
@JackAKirk  thanks for the detailed analysis and answers. I totally agree with you that the subgroup usage is not portable across the HW. 

Yes, we need to add some explanations to the DPCPP documentation.  Let me try to if I can PR some improvements in doc.

I think we can close this issue now @skosnits .

**Comment by AerialMantis** [comment] 2022-05-02 23:12
We believe this issue to be resolved now so I will close the ticket, if there is further work to do we can re-open it.

**Closed by AerialMantis** 2022-05-02 23:12 UTC
Labels: bug, cuda, hip, compiler
