### ISSUE TITLE
[SYCL] Clang Driver ICE when no input file found

### ISSUE THREAD

**Issue by agozillon** [intel/llvm#70] opened 2019-04-09 20:13 UTC
I get an ICE at the moment when I compile using the following command and the file is not found:

``$ISYCL_BIN_DIR/clang++ -std=c++11 -fsycl no_file.cpp -o no_file -lOpenCL``

I've added the stack dump at the bottom if that's of any use.

If I remove the -lOpenCL component, I do not recieve a stack dump and get the desired output:

``$ISYCL_BIN_DIR/clang++ -std=c++11 -fsycl no_file.cpp -o no_file``

**clang-9: error: no such file or directory: 'no_file.cpp'**
**clang-9: error: no input files**

This may be something you guys have already noticed unless it's an environment or understanding problem on my end? Hopefully it's not a user error on my part in this case, if it is I apologize. 

------------------------
```
**clang-9: error: no such file or directory: 'no_file.cpp'**
Stack dump:
0.	Program arguments: /storage/ogozillo/intel-sycl/no-mod/sycl/build/bin/clang++ -std=c++11 -fsycl no_file.cpp -o no_file -lOpenCL 
1.	Compilation construction
2.	Building compilation jobs
3.	Building compilation jobs
4.	Building compilation jobs
5.	Building compilation jobs
6.	Computing output path
 #0 0x000055b529dd325a llvm::sys::PrintStackTrace(llvm::raw_ostream&) (/storage/ogozillo/intel-sycl/no-mod/sycl/build/bin/clang+++0x240f25a)
 #1 0x000055b529dd1134 llvm::sys::RunSignalHandlers() (/storage/ogozillo/intel-sycl/no-mod/sycl/build/bin/clang+++0x240d134)
 #2 0x000055b529dd12b5 SignalHandler(int) (/storage/ogozillo/intel-sycl/no-mod/sycl/build/bin/clang+++0x240d2b5)
 #3 0x00007fa8319dcdd0 __restore_rt (/lib/x86_64-linux-gnu/libpthread.so.0+0x12dd0)
 #4 0x00007fa8311e2f11 /build/glibc-B9XfQf/glibc-2.28/string/../sysdeps/x86_64/multiarch/strlen-avx2.S:62:0
 #5 0x000055b52a304747 clang::driver::Driver::GetNamedOutputPath(clang::driver::Compilation&, clang::driver::JobAction const&, char const*, llvm::StringRef, bool, bool, llvm::StringRef) const (/storage/ogozillo/intel-sycl/no-mod/sycl/build/bin/clang+++0x2940747)
 #6 0x000055b52a3149e5 clang::driver::Driver::BuildJobsForActionNoCache(clang::driver::Compilation&, clang::driver::Action const*, clang::driver::ToolChain const*, llvm::StringRef, bool, bool, char const*, std::map<std::pair<clang::driver::Action const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, clang::driver::InputInfo, std::less<std::pair<clang::driver::Action const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >, std::allocator<std::pair<std::pair<clang::driver::Action const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > const, clang::driver::InputInfo> > >&, clang::driver::Action::OffloadKind) const (/storage/ogozillo/intel-sycl/no-mod/sycl/build/bin/clang+++0x29509e5)
 #7 0x000055b52a3155c7 clang::driver::Driver::BuildJobsForAction(clang::driver::Compilation&, clang::driver::Action const*, clang::driver::ToolChain const*, llvm::StringRef, bool, bool, char const*, std::map<std::pair<clang::driver::Action const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, clang::driver::InputInfo, std::less<std::pair<clang::driver::Action const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >, std::allocator<std::pair<std::pair<clang::driver::Action const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > const, clang::driver::InputInfo> > >&, clang::driver::Action::OffloadKind) const (/storage/ogozillo/intel-sycl/no-mod/sycl/build/bin/clang+++0x29515c7)
 #8 0x000055b52a313666 clang::driver::Driver::BuildJobsForActionNoCache(clang::driver::Compilation&, clang::driver::Action const*, clang::driver::ToolChain const*, llvm::StringRef, bool, bool, char const*, std::map<std::pair<clang::driver::Action const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, clang::driver::InputInfo, std::less<std::pair<clang::driver::Action const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >, std::allocator<std::pair<std::pair<clang::driver::Action const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > const, clang::driver::InputInfo> > >&, clang::driver::Action::OffloadKind) const (/storage/ogozillo/intel-sycl/no-mod/sycl/build/bin/clang+++0x294f666)
 #9 0x000055b52a3155c7 clang::driver::Driver::BuildJobsForAction(clang::driver::Compilation&, clang::driver::Action const*, clang::driver::ToolChain const*, llvm::StringRef, bool, bool, char const*, std::map<std::pair<clang::driver::Action const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, clang::driver::InputInfo, std::less<std::pair<clang::driver::Action const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >, std::allocator<std::pair<std::pair<clang::driver::Action const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > const, clang::driver::InputInfo> > >&, clang::driver::Action::OffloadKind) const (/storage/ogozillo/intel-sycl/no-mod/sycl/build/bin/clang+++0x29515c7)
#10 0x000055b52a3179c4 void llvm::function_ref<void (clang::driver::Action*, clang::driver::ToolChain const*, char const*)>::callback_fn<clang::driver::Driver::BuildJobsForActionNoCache(clang::driver::Compilation&, clang::driver::Action const*, clang::driver::ToolChain const*, llvm::StringRef, bool, bool, char const*, std::map<std::pair<clang::driver::Action const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, clang::driver::InputInfo, std::less<std::pair<clang::driver::Action const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >, std::allocator<std::pair<std::pair<clang::driver::Action const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > const, clang::driver::InputInfo> > >&, clang::driver::Action::OffloadKind) const::'lambda0'(clang::driver::Action*, clang::driver::ToolChain const*, char const*)>(long, clang::driver::Action*, clang::driver::ToolChain const*, char const*) (/storage/ogozillo/intel-sycl/no-mod/sycl/build/bin/clang+++0x29539c4)
#11 0x000055b52a401404 clang::driver::OffloadAction::doOnEachDeviceDependence(llvm::function_ref<void (clang::driver::Action*, clang::driver::ToolChain const*, char const*)> const&) const (/storage/ogozillo/intel-sycl/no-mod/sycl/build/bin/clang+++0x2a3d404)
#12 0x000055b52a312e8a clang::driver::Driver::BuildJobsForActionNoCache(clang::driver::Compilation&, clang::driver::Action const*, clang::driver::ToolChain const*, llvm::StringRef, bool, bool, char const*, std::map<std::pair<clang::driver::Action const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, clang::driver::InputInfo, std::less<std::pair<clang::driver::Action const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >, std::allocator<std::pair<std::pair<clang::driver::Action const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > const, clang::driver::InputInfo> > >&, clang::driver::Action::OffloadKind) const (/storage/ogozillo/intel-sycl/no-mod/sycl/build/bin/clang+++0x294ee8a)
#13 0x000055b52a3155c7 clang::driver::Driver::BuildJobsForAction(clang::driver::Compilation&, clang::driver::Action const*, clang::driver::ToolChain const*, llvm::StringRef, bool, bool, char const*, std::map<std::pair<clang::driver::Action const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, clang::driver::InputInfo, std::less<std::pair<clang::driver::Action const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >, std::allocator<std::pair<std::pair<clang::driver::Action const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > const, clang::driver::InputInfo> > >&, clang::driver::Action::OffloadKind) const (/storage/ogozillo/intel-sycl/no-mod/sycl/build/bin/clang+++0x29515c7)
#14 0x000055b52a315aab clang::driver::Driver::BuildJobs(clang::driver::Compilation&) const (/storage/ogozillo/intel-sycl/no-mod/sycl/build/bin/clang+++0x2951aab)
#15 0x000055b52a317475 clang::driver::Driver::BuildCompilation(llvm::ArrayRef<char const*>) (/storage/ogozillo/intel-sycl/no-mod/sycl/build/bin/clang+++0x2953475)
#16 0x000055b528479875 main (/storage/ogozillo/intel-sycl/no-mod/sycl/build/bin/clang+++0xab5875)
#17 0x00007fa83108309b __libc_start_main /build/glibc-B9XfQf/glibc-2.28/csu/../csu/libc-start.c:308:16
#18 0x000055b52850c2ea _start (/storage/ogozillo/intel-sycl/no-mod/sycl/build/bin/clang+++0xb482ea)
Segmentation fault
```

**Comment by bader** [comment] 2019-06-20 14:52
@agozillon, I can't reproduce this issue using the latest version of the compiler.
Could you confirm that it's fixed on your side too, please?

**Comment by agozillon** [comment] 2019-06-20 19:18
Works fine on my end as well, happy to close the issue

**Closed** 2019-06-20 20:31 UTC
Labels: bug
