### ISSUE TITLE
clang/test/SemaSYCL/loop_unroll.cpp test is failing after LLVM pulldown

### ISSUE THREAD

**Issue by vladimirlaz** [intel/llvm#1893] opened 2020-06-15 11:46 UTC
During pulldown #1842
I have disabled the tests to unblock pulldown

```
$ bin/llvm-lit -a ../clang/test/SemaSYCL/loop_unroll.cpp
llvm-lit: /localdisk2/vladimirlaz_llvm/build/bin/../../llvm/utils/lit/lit/llvm/config.py:343: note: using clang: /localdisk2/vladimirlaz_llvm/build/bin/clang
-- Testing: 1 tests, 1 workers --
FAIL: Clang :: SemaSYCL/loop_unroll.cpp (1 of 1)
******************** TEST 'Clang :: SemaSYCL/loop_unroll.cpp' FAILED ********************
Script:
--
: 'RUN: at line 1';   /localdisk2/vladimirlaz_llvm/build/bin/clang -cc1 -internal-isystem /localdisk2/vladimirlaz_llvm/build/lib/clang/11.0.0/include -nostdsysteminc -fsycl -fsycl-is-device -fsyntax-only -verify -pedantic /localdisk2/vladimirlaz_llvm/clang/test/SemaSYCL/loop_unroll.cpp
--
Exit Code: 134

Command Output (stderr):
--
clang: /localdisk2/vladimirlaz_llvm/clang/lib/Parse/ParseStmt.cpp:2200: clang::StmtResult clang::Parser::ParsePragmaLoopHint(clang::Parser::StmtVector&, clang::Parser::ParsedStmtContext, clang::SourceLocation*, clang::Parser::ParsedAttributesWithRange&): Assertion `Attrs.Range.getBegin().isInvalid() && "start of attribute range already set"' failed.
PLEASE submit a bug report to https://bugs.llvm.org/ and include the crash backtrace, preprocessed source, and associated run script.
Stack dump:
0.      Program arguments: /localdisk2/vladimirlaz_llvm/build/bin/clang -cc1 -internal-isystem /localdisk2/vladimirlaz_llvm/build/lib/clang/11.0.0/include -nostdsysteminc -fsycl -fsycl-is-device -fsyntax-only -verify -pedantic /localdisk2/vladimirlaz_llvm/clang/test/SemaSYCL/loop_unroll.cpp
1.      /localdisk2/vladimirlaz_llvm/clang/test/SemaSYCL/loop_unroll.cpp:41:3: current parser token '['
2.      /localdisk2/vladimirlaz_llvm/clang/test/SemaSYCL/loop_unroll.cpp:10:12: parsing function body 'foo'
3.      /localdisk2/vladimirlaz_llvm/clang/test/SemaSYCL/loop_unroll.cpp:10:12: in compound statement ('{}')
 #0 0x00005583bb46a47a llvm::sys::PrintStackTrace(llvm::raw_ostream&) (/localdisk2/vladimirlaz_llvm/build/bin/clang+0x1f0947a)
 #1 0x00005583bb468184 llvm::sys::RunSignalHandlers() (/localdisk2/vladimirlaz_llvm/build/bin/clang+0x1f07184)
 #2 0x00005583bb4682d3 SignalHandler(int) (/localdisk2/vladimirlaz_llvm/build/bin/clang+0x1f072d3)
 #3 0x00007fa8abcd3890 __restore_rt (/lib/x86_64-linux-gnu/libpthread.so.0+0x12890)
 #4 0x00007fa8aa984e97 raise /build/glibc-OTsEL5/glibc-2.27/signal/../sysdeps/unix/sysv/linux/raise.c:51:0
 #5 0x00007fa8aa986801 abort /build/glibc-OTsEL5/glibc-2.27/stdlib/abort.c:81:0
 #6 0x00007fa8aa97639a __assert_fail_base /build/glibc-OTsEL5/glibc-2.27/assert/assert.c:89:0
 #7 0x00007fa8aa976412 (/lib/x86_64-linux-gnu/libc.so.6+0x30412)
 #8 0x00005583bcc8b976 clang::Parser::ParsePragmaLoopHint(llvm::SmallVector<clang::Stmt*, 32u>&, clang::Parser::ParsedStmtContext, clang::SourceLocation*, clang::Parser::ParsedAttributesWithRange&) (/localdisk2/vladimirlaz_llvm/build/bin/clang+0x372a976)
 #9 0x00005583bcc8a9d1 clang::Parser::ParseStatementOrDeclarationAfterAttributes(llvm::SmallVector<clang::Stmt*, 32u>&, clang::Parser::ParsedStmtContext, clang::SourceLocation*, clang::Parser::ParsedAttributesWithRange&) (/localdisk2/vladimirlaz_llvm/build/bin/clang+0x37299d1)
#10 0x00005583bcc8bb37 clang::Parser::ParseStatementOrDeclaration(llvm::SmallVector<clang::Stmt*, 32u>&, clang::Parser::ParsedStmtContext, clang::SourceLocation*) (/localdisk2/vladimirlaz_llvm/build/bin/clang+0x372ab37)
#11 0x00005583bcc8f2e1 clang::Parser::ParseCompoundStatementBody(bool) (/localdisk2/vladimirlaz_llvm/build/bin/clang+0x372e2e1)
#12 0x00005583bcc9153b clang::Parser::ParseFunctionStatementBody(clang::Decl*, clang::Parser::ParseScope&) (/localdisk2/vladimirlaz_llvm/build/bin/clang+0x373053b)
#13 0x00005583bcbfc1f4 clang::Parser::ParseFunctionDefinition(clang::ParsingDeclarator&, clang::Parser::ParsedTemplateInfo const&, clang::Parser::LateParsedAttrList*) (/localdisk2/vladimirlaz_llvm/build/bin/clang+0x369b1f4)
#14 0x00005583bcc2050e clang::Parser::ParseDeclGroup(clang::ParsingDeclSpec&, clang::DeclaratorContext, clang::SourceLocation*, clang::Parser::ForRangeInit*) (/localdisk2/vladimirlaz_llvm/build/bin/clang+0x36bf50e)
#15 0x00005583bcbf8ed1 clang::Parser::ParseDeclOrFunctionDefInternal(clang::Parser::ParsedAttributesWithRange&, clang::ParsingDeclSpec&, clang::AccessSpecifier) (/localdisk2/vladimirlaz_llvm/build/bin/clang+0x3697ed1)
#16 0x00005583bcbf9631 clang::Parser::ParseDeclarationOrFunctionDefinition(clang::Parser::ParsedAttributesWithRange&, clang::ParsingDeclSpec*, clang::AccessSpecifier) (.part.238) (/localdisk2/vladimirlaz_llvm/build/bin/clang+0x3698631)
#17 0x00005583bcbfd450 clang::Parser::ParseExternalDeclaration(clang::Parser::ParsedAttributesWithRange&, clang::ParsingDeclSpec*) (/localdisk2/vladimirlaz_llvm/build/bin/clang+0x369c450)
#18 0x00005583bcbfe809 clang::Parser::ParseTopLevelDecl(clang::OpaquePtr<clang::DeclGroupRef>&, bool) (/localdisk2/vladimirlaz_llvm/build/bin/clang+0x369d809)
#19 0x00005583bcbf47e9 clang::ParseAST(clang::Sema&, bool, bool) (/localdisk2/vladimirlaz_llvm/build/bin/clang+0x36937e9)
#20 0x00005583bbc7bfe9 clang::FrontendAction::Execute() (/localdisk2/vladimirlaz_llvm/build/bin/clang+0x271afe9)
#21 0x00005583bbc37d12 clang::CompilerInstance::ExecuteAction(clang::FrontendAction&) (/localdisk2/vladimirlaz_llvm/build/bin/clang+0x26d6d12)
#22 0x00005583bbd2bbf1 clang::ExecuteCompilerInvocation(clang::CompilerInstance*) (/localdisk2/vladimirlaz_llvm/build/bin/clang+0x27cabf1)
#23 0x00005583ba37cdb4 cc1_main(llvm::ArrayRef<char const*>, char const*, void*) (/localdisk2/vladimirlaz_llvm/build/bin/clang+0xe1bdb4)
#24 0x00005583ba3791f9 ExecuteCC1Tool(llvm::SmallVectorImpl<char const*>&) (/localdisk2/vladimirlaz_llvm/build/bin/clang+0xe181f9)
#25 0x00005583ba2fd943 main (/localdisk2/vladimirlaz_llvm/build/bin/clang+0xd9c943)
#26 0x00007fa8aa967b97 __libc_start_main /build/glibc-OTsEL5/glibc-2.27/csu/../csu/libc-start.c:344:0
#27 0x00005583ba378d5a _start (/localdisk2/vladimirlaz_llvm/build/bin/clang+0xe17d5a)
/localdisk2/vladimirlaz_llvm/build/tools/clang/test/SemaSYCL/Output/loop_unroll.cpp.script: line 1: 18768 Aborted                 (core dumped) /localdisk2/vladimirlaz_llvm/build/bin/clang -cc1 -internal-isystem /localdisk2/vladimirlaz_llvm/build/lib/clang/11.0.0/include -nostdsysteminc -fsycl -fsycl-is-device -fsyntax-only -verify -pedantic /localdisk2/vladimirlaz_llvm/clang/test/SemaSYCL/loop_unroll.cpp

--

********************
********************
Failed Tests (1):
  Clang :: SemaSYCL/loop_unroll.cpp


Testing Time: 0.61s
  Failed: 1

```

**Comment by vmaksimo** [comment] 2020-06-15 19:15
Here is the test case that fails: https://github.com/intel/llvm/blob/sycl/clang/test/SemaSYCL/loop_unroll.cpp#L35-L38
The regression is caused by this commit from community https://github.com/intel/llvm/commit/9c2e770034d04a0966b84cac14a9e3fb3b0d4ab7, it introduces modifications to `pragma unroll` handling. With this change, the compiler doesn't allow to use pragma unroll and loop attribute together on the same loop. 
As this test case checked that the user should not use `pragma unroll` and `[[clang::unroll]]` together in one loop, and now it's clearly prohibited by compiler, this case can be simply removed.
TODO: to remove this case handling from semantic check in clang.

**Comment by vladimirlaz** [comment] 2020-06-16 08:26
I have removed the test case https://github.com/intel/llvm/pull/1890/commits/415f19de7217f0769bfdd00a4e66d1faa8b09619

Disabling semantic check should be done in scope of the issue

**Comment by vmaksimo** [comment] 2020-06-17 10:33
This issue has been fixed in community https://github.com/llvm/llvm-project/commit/4676cf444ea2678660ee48279be99efde4bf60e9
So, we should just revert this change https://github.com/intel/llvm/pull/1890/commits/9947ba90421ce458181133376be6172128f8dfbd after next pulldown.

**Closed** 2020-06-18 06:44 UTC
