### ISSUE TITLE
[CUDA] 'named symbol not found' error at runtime in cuda_piKernelCreate if static library with kernel is linked on Windows

### ISSUE THREAD

**Issue by yuxianch** [intel/llvm#4873] opened 2021-11-02 08:27 UTC
**Describe the bug**
'named symbol not found' error at runtime in cuda_piKernelCreate if static library with kernel is linked on Windows with CUDA backend. This issue is similar to https://github.com/intel/llvm/issues/4307 but it happens on Windows platform.
It affects almost all of the accessor tests from CTS.

**To Reproduce**
1. Get SYCL with CUDA support ([GSG](https://intel.github.io/llvm-docs/GetStartedGuide.html)) and [SYCL-CTS](https://github.com/KhronosGroup/SYCL-CTS https://github.com/KhronosGroup/SYCL-CTS/commit/14fac446f4454d4889a6b0e7bf5eab83bbe4cf26)
2. Build CTS tests
```
cd SYCL-CTS
mkdir build && cd build
cmake -GNinja  -DSYCL_IMPLEMENTATION=Intel_SYCL -DINTEL_SYCL_ROOT=<path to built sycl> -Dopencl_platform_name=nvidia -Dopencl_device_name=opencl_gpu -DCMAKE_BUILD_TYPE=Release -DCMAKE_CXX_FLAGS_RELEASE="-fsycl -fsycl-unnamed-lambda /EHsc /EHsc /MD -Wno-deprecated-declarations" -DINTEL_SYCL_FLAGS="-Xsycl-target-backend;--cuda-gpu-arch=sm_50" -DCMAKE_EXE_LINKER_FLAGS=" -Wl,-no-relax " -DINTEL_SYCL_TRIPLE=nvptx64-nvidia-cuda-sycldevice -DSYCL_CTS_ENABLE_OPENCL_INTEROP_TESTS=Off -DSYCL_CTS_ENABLE_DOUBLE_TESTS=On -DSYCL_CTS_ENABLE_HALF_TESTS=On ..
ninja test_accessor
```
3. Run test
```
export SYCL_DEVICE_FILTER="cuda:gpu:0"
export SYCL_ENABLE_HOST_DEVICE="1"
bin/test_address_space -p nvidia -d opencl_gpu  --test accessor_api_buffer_fp64
```
Error message:
```
PI CUDA ERROR:
        Value:           500
        Name:            CUDA_ERROR_NOT_FOUND
        Description:     named symbol not found
        Function:        cuda_piKernelCreate
        Source Location: \path\to\build\sycl\plugins\cuda\pi_cuda.cpp:2428

  . sycl exception caught
  . what - Native API failed. Native API returns: -999 (Unknown OpenCL error code) -999 (Unknown OpenCL error code)
  . line: 42
  . a SYCL exception was caught: Native API failed. Native API returns: -999 (Unknown OpenCL error code) -999 (Unknown OpenCL error code)
  - fail

  . Passed 0/1 tests (0%)
```
The issue can also be reproduced with the small reproducer in https://github.com/intel/llvm/issues/4307. 
```
//main.cpp:
void func();
int main() {
  func();
  return 0;
}
```
```
// sycl_lib.cpp:
#include<CL/sycl.hpp>
using namespace sycl;
void func() {
  queue q;
  q.submit([&](sycl::handler &h) {
      sycl::stream os(1024, 768, h);
      h.parallel_for(32, [=](sycl::id<1> i) {
          os<<i<<"\n";
        });
    });
}
```
```
# Commands:
clang-cl -fsycl -fsycl-targets=nvptx64-nvidia-cuda -fsycl-unnamed-lambda -c sycl_lib.cpp
lib /out:sycl_lib.lib sycl_lib.obj
clang-cl -fsycl -fsycl-targets=nvptx64-nvidia-cuda -fsycl-unnamed-lambda -o test.exe main.cpp /link sycl_lib.lib
export SYCL_DEVICE_FILTER="cuda:gpu:0"
export SYCL_ENABLE_HOST_DEVICE="1"
./test.exe ; echo $?
# Output:
PI CUDA ERROR:
        Value:           500
        Name:            CUDA_ERROR_NOT_FOUND
        Description:     named symbol not found
        Function:        cuda_piKernelCreate
        Source Location: \path\to\build\sycl\plugins\cuda\pi_cuda.cpp:2428

9
```

**Environment**

- OS: Windows
- Target device and vendor: Nvidia GPU
- DPC++ version: https://github.com/intel/llvm.git a0342b313592143345ab3367e2ed6f6926a79a98
- CUDA version: 
```
Cuda compilation tools, release 11.4, V11.4.120
Build cuda_11.4.r11.4/compiler.30300941_0
```

**Additional context**

**Comment by npmiller** [comment] 2021-11-22 14:33
Hello, so I had a look and I found the issue in the small sample, the problem is how the linking is done:
```
clang-cl -fsycl -fsycl-targets=nvptx64-nvidia-cuda -fsycl-unnamed-lambda -o test.exe main.cpp /link sycl_lib.lib
```

With `/link` the `sycl_lib.lib` argument is just forwarded to the linker and `clang` doesn't know about it, this is a problem because `sycl_lib.lib` contains the kernel code bundled in the object file, and so it requires a bit of specific work when linking to make sure the kernel code is properly present in the final binary. And obviously this is not something the system linker knows how to do. And so this is why you're seeing the `named symbol not found` error, because the kernel code wasn't setup properly in the final binary and couldn't be properly loaded either.

So as a workaround using the following command, without `/link`, for linking works perfectly fine:
```
clang-cl -fsycl -fsycl-targets=nvptx64-nvidia-cuda -fsycl-unnamed-lambda -o test.exe main.cpp sycl_lib.lib
```

Because in that case `clang` knows about `sycl_lib.lib` and can properly include the kernel code while handling the linking.

So this should be fine for the small reproducer.

However for the SYCL-CTS if it's CMake using `/link` when building then I'm a little unsure on how to approach this, `/link` is supposed to just forward the arguments to the system linker, but if it is commonly used to also pass in static libraries then it will not work for SYCL, and we may need to have clang inspect these arguments before passing them through.

**Comment by bader** [comment] 2021-11-22 14:38
@mdtoguchi, do you think we can change the compiler to handle libraries specified via how `/link` handles libraries in SYCL mode (i.e. when `-fsycl` is set)?

**Comment by AerialMantis** [comment] 2021-12-20 17:22
We believe the issue here and the proposed solution is more generic and not CUDA-specific, so I will remove the CUDA label, if there is CUDA-specific issues involved here after all please re-add the label and we can look into it again.

**Comment by AlessandroFasse** [comment] 2022-01-24 10:59
Any news on this?

**Comment by mdtoguchi** [comment] 2022-03-09 21:45
Modifications to improve `/link` processing for archives on Windows is in review:  https://github.com/intel/llvm/pull/5768

**Comment by romanovvlad** [comment] 2022-07-22 12:46
@mdtoguchi Could you please tell if the issue is fixed now?

**Comment by mdtoguchi** [comment] 2022-07-22 13:54
@romanovvlad, the ability to scan and pick up fat static libraries which are placed after the `/link` command has been added.

**Closed by mdtoguchi** 2022-07-22 13:54 UTC
Labels: bug, CTS, runtime, confirmed
