### ISSUE TITLE
DeviceGlobal/device_global_device_image_scope_unused.cpp reached timeout

### ISSUE THREAD

**Issue by KseniyaTikhomirova** [intel/llvm#9456] opened 2023-05-15 09:39 UTC
OS: Linux
Platform: OCL x64
Failed in pre-commit for https://github.com/intel/llvm/pull/9437.

TIMEOUT: SYCL :: DeviceGlobal/device_global_device_image_scope_unused.cpp (1267 of 1343)
******************** TEST 'SYCL :: DeviceGlobal/device_global_device_image_scope_unused.cpp' FAILED ********************
Script:
--
: 'RUN: at line 4';    /__w/llvm/llvm/toolchain/bin/clang++   -fsycl -fsycl-targets=spir64 /__w/llvm/llvm/llvm/sycl/test-e2e/DeviceGlobal/device_global_device_image_scope_unused.cpp -fsycl-device-code-split=per_source -DUSE_DEVICE_IMAGE_SCOPE -o /__w/llvm/llvm/build-e2e/DeviceGlobal/Output/device_global_device_image_scope_unused.cpp.tmp_dev_img_scope.out
: 'RUN: at line 5';   env ONEAPI_DEVICE_SELECTOR=opencl:cpu  /__w/llvm/llvm/build-e2e/DeviceGlobal/Output/device_global_device_image_scope_unused.cpp.tmp_dev_img_scope.out
--
Exit Code: -9
Timeout: Reached timeout of 600 seconds

**Comment by steffenlarsen** [comment] 2023-12-04 10:55
This has not been reproduced since May. Closing this as unreproducible.

**Closed by steffenlarsen** 2023-12-04 10:55 UTC
Labels: bug, confirmed
