### ISSUE TITLE
is_device_copyable use case from E3SM+YAKL

### ISSUE THREAD

**Issue by naromero77** [intel/llvm#3537] opened 2021-04-12 19:57 UTC
**Is your feature request related to a problem? Please describe**
This may be redundant with other requests that you already have from Argonne. (I think the Intel compiler team is aware of this request, but perhaps not.) I have a DOE science code, E3SM (Fortran) that makes use of a Kokkos-like performance portability layer called YAKL (C++).  YAKL needs the `is_device_copyable` type trait. We have a reduced test case that shows how it will get used if you are interested.

**Describe the solution you would like**
We believe that our code will compile once `is_device_copyable` type trait is supported. So no additional modifications to our code should be necessary.... but we are not 100% sure.

**Comment by AlexeySachkov** [comment] 2021-09-02 10:04
@naromero77, we have introduced `is_device_copyable` in #3905. Could you please check if that works for you and close the issue/add more details about what is missing?

**Comment by naromero77intel** [comment] 2021-09-03 15:49
@AlexeySachkov I am no longer at Argonne, but work at Intel on the Fortran Compiler team.

I am hoping my colleague who took over this aspect of the project can continue this work @abagusetty

**Comment by abagusetty** [comment] 2021-09-03 16:09
@AlexeySachkov , @naromero77 I'll check on this one we get access to the new compiler in the next few days

**Comment by AlexeySachkov** [comment] 2022-01-31 20:27
@abagusetty, any updates here?

**Comment by abagusetty** [comment] 2022-01-31 20:33
> @abagusetty, any updates here?

Hey @AlexeySachkov We've received the compiler with this feature. The `is_device_copyable` was working partly to figure out if the object is device copyable/constructable etc. We were expecting that the compiler would copy the objects to the  device if they are not copyable/constructable instead.

**Comment by bader** [comment] 2022-02-01 07:53
> We were expecting that the compiler would copy the objects to the device if they are not copyable/constructable instead.

It looks like https://github.com/intel/llvm/issues/5320 is proposing something like that. Tagging @Naghasan.

> the compiler would copy the objects to the device if they are not copyable/constructable

Doesn't it sound strange? I have a concern that this might lead to bugs which are hard to detect/debug. If object type is not "device copyable", it means that we can't just re-create bitwise copy of the object on the device and keep object's semantics.
I think developers must (explicitly!) promise to the compiler that copying "not copyable/constructable" object doesn't break program semantics. In addition to that (or instead) it would be great to have some tooling to find all the places where "is_device_copyable" rule is bent.

**Comment by sarats** [comment] 2022-09-28 19:44
Thanks for the pointer @naromero77. cc @mrnorman

**Comment by KornevNikita** [comment] 2024-05-17 11:36
Hi! There have been no updates for at least the last 60 days, though the ticket has assignee(s).

      @naromero77 @v-klochkov, could I ask you to take one of the following actions? :)
      - Please provide an update if you have any (or just a small comment if you don't have any yet).
      - OR mark this issue with the 'confirmed' label if you have confirmed the problem/request and our team should work on it.
      - OR close the issue if it has been resolved.
      - OR take any other suitable action.

      Thanks!

**Comment by naromero77amd** [comment] 2024-05-20 00:13
I filed this issue 3 jobs ago :) 

I am going to close it, @abagusetty can re-open or open something more specific if needed.

**Comment by v-klochkov** [comment] 2024-05-20 13:20
The very first version of is_device_copyable was added by be several years ago. It could get extra changes after I left SYCL squad.

Adding @stdale-intel and @aelovikov-intel , who perhaps can answer the question about the current status and some TODOs/missed-corner-cases if there are any.

**Comment by aelovikov-intel** [comment] 2024-05-20 14:20
Closing per the agreement above. Also https://github.com/intel/llvm/issues/5320 (mentioned earlier) looks like a duplicate as well.

**Closed by aelovikov-intel** 2024-05-20 14:20 UTC
Labels: enhancement
