### ISSUE TITLE
[SYCL][CUDA] Comping SYCL code with subgroups failing

### ISSUE THREAD

**Issue by pvelesko** [intel/llvm#1767] opened 2020-05-28 07:29 UTC
`ptxas fatal   : Unresolved extern function '_Z17__spirv_GroupFAddjjd`

Are there plans to add sub-group support for CUDA? If possible? 
If not, compiler should throw an error during compilation.

**Comment by pvelesko** [comment] 2020-06-03 09:41
@Pennycook Can you share your fix please

**Comment by bader** [comment] 2020-10-02 16:07
Related PR: https://github.com/intel/llvm/pull/2587

**Comment by bader** [comment] 2020-10-05 11:24
@pvelesko, #2587 is merged. Does it address your request or anything else is required?

**Comment by bader** [comment] 2020-10-11 15:26
Closing this issue. @pvelesko, feel free to re-open or leave a comment if the issue is not resolved on your side.

NOTE: https://github.com/intel/llvm/pull/2623 adds `shuffle` support.

**Closed by bader** 2020-10-11 15:26 UTC
Labels: cuda
