### ISSUE TITLE
NVIDIA Backend not able to launch kernels on NVIDIA A100 GPU

### ISSUE THREAD

**Issue by jgtong** [intel/llvm#6051] opened 2022-04-22 21:39 UTC
**Describe the bug**
SYCL-OS with NVIDIA backend support is not launching DPC++ kernels on NVIDIA A100. Causes program to hang just before kernel s ubmission.

**To Reproduce**

Below is a simple program of just assigning a vector of 8 integer elements with the `get_global_id()` value.

```
#include <iostream>
#include <CL/sycl.hpp>

static void DisplayDeviceProperties(sycl::device const &Device)
{
    std::cout << "Device Properties" << std::endl;
    std::cout << "\t Using SYCL device         : " << Device.get_info<cl::sycl::info::device::name>() << " (Driver version " << Device.get_info<cl::sycl::info::device::driver_version>() << ")" << std::endl;;
    std::cout << "\t Platform                  : " << Device.get_platform().get_info<cl::sycl::info::platform::name>() << std::endl;
    std::cout << "\t Vendor                    : " << Device.get_info<cl::sycl::info::device::vendor>() << std::endl;
    std::cout << "\t Max compute units         : " << Device.get_info<cl::sycl::info::device::max_compute_units>() << std::endl;
}

int main()
{
    std::vector<int>       vOutput(8, -1);
    sycl::queue syQueue(sycl::device({sycl::gpu_selector()}));
    DisplayDeviceProperties(syQueue.get_device());

    try {
        std::cout << "Entering SYCL kernel scope" << std::endl;

        {// Begin sycl
            sycl::buffer<int, 1> syclBufOutput(vOutput.data(), cl::sycl::range<1>(vOutput.size()));

            syQueue.submit([&](cl::sycl::handler &cgh) {
                auto accgOutput = syclBufOutput.get_access<cl::sycl::access::mode::write>(cgh);
                auto syclWorkGroupAndItemsSettings(sycl::nd_range<1>(sycl::range<1>(8), sycl::range<1>(8)));
                cgh.parallel_for<class cross_correlation>(
                    syclWorkGroupAndItemsSettings, [=](sycl::nd_item<1> idx) {
                    accgOutput[idx.get_global_id()] = idx.get_global_id();
                 });

            });

            std::cout << "Kernel execution was successful" << std::endl;
        }
        std::cout << "Left SYCL kernel scope" << std::endl;
    } catch (cl::sycl::exception const &e) {
        std::cerr << "SYCL exception caught \'" << e.what() << "\'" << std::endl;
    }

    for (int iElem = 0; iElem < 8; ++iElem)
        std::cout << iElem << ":: " << vOutput[iElem] << std::endl;

    std::cout << "Program successful" << std::endl;
}
```
To build and the above program:

```
clang++ test_case.cpp -O3 -fsycl -fsycl-targets=nvptx64-nvidia-cuda -o ./test_case
./test_case
```
The expected behaviour is the program outputs values from 0-7. The problem that I am seeing on the NV A100 GPU is the kernel is not launching and causes the program to hang indefinitely.

**Environment (please complete the following information):**
- OS: [e.g Windows/Linux] Ubuntu 20.04
- Target device and vendor: NVIDIA A100, Driver: 510.47.03
- DPC++ version: clang version 15.0.0 (https://github.com/intel/llvm.git 8ec97550b7a84e5d2483f4891059f80abd8db39c)
- Dependencies version: None

**Comment by pvchupin** [comment] 2022-04-22 22:04
@AerialMantis, fyi

**Comment by pgorlani** [comment] 2022-04-25 16:18
Hi,
   it is not possible to reproduce the error on our side.

The provided code runs as intended on our A100 / Titan RTX with the 8ec9755/latest commit.

E.g.,
```
Device Properties
         Using SYCL device         : A100-PCIE-40GB (Driver version CUDA 11.5)
         Platform                  : NVIDIA CUDA BACKEND
         Vendor                    : NVIDIA Corporation
         Max compute units         : 108
Entering SYCL kernel scope
Kernel execution was successful
Left SYCL kernel scope
0:: 0
1:: 1
2:: 2
3:: 3
4:: 4
5:: 5
6:: 6
7:: 7
Program successful
```

```
Device Properties
         Using SYCL device         : NVIDIA TITAN RTX (Driver version CUDA 11.6)
         Platform                  : NVIDIA CUDA BACKEND
         Vendor                    : NVIDIA Corporation
         Max compute units         : 72
Entering SYCL kernel scope
Kernel execution was successful
Left SYCL kernel scope
0:: 0
1:: 1
2:: 2
3:: 3
4:: 4
5:: 5
6:: 6
7:: 7
Program successful
```

Is this issue present just for the provided code? Or this applies to every kernel as suggested by the title.
What CUDA Toolkit version are you using?

**Comment by jgtong** [comment] 2022-04-25 16:41
Dear @pgorlani 

We are using the CUDA SDK 11.6; however, I have also tried this using CUDA SDK 11.4 and 11.5 with the same result. We never encountered this hang problem in all of our workloads until a few days ago.

I noticed that the test_case exe is waiting on an object in my `.nv/ComputeCache/index` . So I am not sure what is preventing the runtime to (maybe?) compile the kernel?

**Comment by pgorlani** [comment] 2022-04-25 16:54
You can try to disable the kernel caching with
```
export CUDA_CACHE_DISABLE=1
```
and see if it changes something.

**Comment by jgtong** [comment] 2022-04-25 17:02
Dear @pgorlani 

👍 👍 👍 👍 👍  Wow, it worked! I was not aware of this environment variable. Thank you!

```
─▶ $ CUDA_CACHE_DISABLE=1 ./test_case 
Device Properties
	 Using SYCL device         : NVIDIA A100-PCIE-40GB (Driver version CUDA 11.6)
	 Platform                  : NVIDIA CUDA BACKEND
	 Vendor                    : NVIDIA Corporation
	 Max compute units         : 108
Entering SYCL kernel scope
Kernel execution was successful
Left SYCL kernel scope
0:: 0
1:: 1
2:: 2
3:: 3
4:: 4
5:: 5
6:: 6
7:: 7
Program successful
```

**Comment by pgorlani** [comment] 2022-04-25 17:06
Perfect!

Thank you for the feedback, @jgtong.

If you are happy, fell free to close the issue.

**Closed** 2022-04-25 17:59 UTC
Labels: bug, cuda, blocker, runtime
