### ISSUE TITLE
Definitions in ESIMD headers conflict with user macros

### ISSUE THREAD

**Issue by Pennycook** [intel/llvm#6879] opened 2022-09-26 18:42 UTC
The ESIMD math headers define several constants using names in all caps, e.g.:
https://github.com/intel/llvm/blob/55bf1a0d627aae6d914d23ccf405f912ab304acd/sycl/include/sycl/ext/intel/experimental/esimd/math.hpp#L1314-L1317

All of these variables need to be renamed.  `CONST_PI` is currently preventing me from using esimd in a project I'm working on, because there's already a macro with that name.

This has happened before with a different header (see https://github.com/intel/llvm/issues/5479) so I'm going to repeat the suggestion I made there; it might also be a good idea to add some sort of check for variable names in caps to prevent this sort of thing.

**Comment by bader** [comment] 2024-07-31 21:05
This issue seems to be addressed in https://github.com/intel/llvm/commit/818682e75b716a713b0f2d024d40824621244a25.

@intel/dpcpp-esimd-reviewers, considering that the fix landed in 2022, but the issue is still open, I recommend going over all other open issues to see if they should be updated/closed.

**Comment by sarnex** [comment] 2024-07-31 21:08
Closing this and will do

**Closed by sarnex** 2024-07-31 21:08 UTC
Labels: bug, good first issue, esimd, confirmed
