### ISSUE TITLE
SYCL :: ESIMD/dword_local_accessor_atomic_smoke.cpp failed on Linux

### ISSUE THREAD

**Issue by dm-vodopyanov** [intel/llvm#12942] opened 2024-03-07 15:22 UTC
### Describe the bug

Flaky issue on Linux Gen12:
```
FAIL: SYCL :: ESIMD/dword_local_accessor_atomic_smoke.cpp (565 of 1923)
******************** TEST 'SYCL :: ESIMD/dword_local_accessor_atomic_smoke.cpp' FAILED ********************
Exit Code: 1

Command Output (stdout):
--
# RUN: at line 13
/__w/llvm/llvm/toolchain/bin//clang++   -fsycl -fsycl-targets=spir64 /__w/llvm/llvm/llvm/sycl/test-e2e/ESIMD/dword_local_accessor_atomic_smoke.cpp -o /__w/llvm/llvm/build-e2e/ESIMD/Output/dword_local_accessor_atomic_smoke.cpp.tmp.out
# executed command: /__w/llvm/llvm/toolchain/bin//clang++ -fsycl -fsycl-targets=spir64 /__w/llvm/llvm/llvm/sycl/test-e2e/ESIMD/dword_local_accessor_atomic_smoke.cpp -o /__w/llvm/llvm/build-e2e/ESIMD/Output/dword_local_accessor_atomic_smoke.cpp.tmp.out
# note: command had no output on stdout or stderr
# RUN: at line 14
env ONEAPI_DEVICE_SELECTOR=level_zero:gpu  /__w/llvm/llvm/build-e2e/ESIMD/Output/dword_local_accessor_atomic_smoke.cpp.tmp.out
# executed command: env ONEAPI_DEVICE_SELECTOR=level_zero:gpu /__w/llvm/llvm/build-e2e/ESIMD/Output/dword_local_accessor_atomic_smoke.cpp.tmp.out
# .---command stdout------------
# | Running on Intel(R) Iris(R) Xe Graphics
# |  Local accessor Testing mode=DWORD op=inc T=int[32](https://github.com/intel/llvm/actions/runs/8173967169/job/22348045487?pr=12866#step:21:33)_t N=1
# | 	{ thr_per_group=8 n_groups=1 start_ind=0 masked_lane=1 repeat=1 stride=1 }... passed
# |  Local accessor Testing mode=DWORD op=inc T=uint32_t N=1
# | 	{ thr_per_group=8 n_groups=1 start_ind=0 masked_lane=1 repeat=1 stride=1 }... passed
# |  Local accessor Testing mode=DWORD op=inc T=int32_t N=8
# | 	{ thr_per_group=8 n_groups=1 start_ind=0 masked_lane=1 repeat=1 stride=1 }... passed
# |  Local accessor Testing mode=DWORD op=inc T=uint32_t N=8
# | 	{ thr_per_group=8 n_groups=1 start_ind=0 masked_lane=1 repeat=1 stride=1 }... passed
# |  Local accessor Testing mode=DWORD op=dec T=int32_t N=1
# | 	{ thr_per_group=8 n_groups=1 start_ind=0 masked_lane=1 repeat=1 stride=1 }... passed
# |  Local accessor Testing mode=DWORD op=dec T=uint32_t N=1
# | 	{ thr_per_group=8 n_groups=1 start_ind=0 masked_lane=1 repeat=1 stride=1 }... passed
# |  Local accessor Testing mode=DWORD op=dec T=int32_t N=8
# | 	{ thr_per_group=8 n_groups=1 start_ind=0 masked_lane=1 repeat=1 stride=1 }... passed
# |  Local accessor Testing mode=DWORD op=dec T=uint32_t N=8
# | 	{ thr_per_group=8 n_groups=1 start_ind=0 masked_lane=1 repeat=1 stride=1 }... passed
# |  Local accessor Testing mode=DWORD op=add T=int32_t N=1
# | 	{ thr_per_group=8 n_groups=1 start_ind=0 masked_lane=1 repeat=1 stride=1 }... passed
# |  Local accessor Testing mode=DWORD op=add T=uint32_t N=1
# | 	{ thr_per_group=8 n_groups=1 start_ind=0 masked_lane=1 repeat=1 stride=1 }... passed
# |  Local accessor Testing mode=DWORD op=add T=int32_t N=8
# | 	{ thr_per_group=8 n_groups=1 start_ind=0 masked_lane=1 repeat=1 stride=1 }... passed
# |  Local accessor Testing mode=DWORD op=add T=uint32_t N=8
# | 	{ thr_per_group=8 n_groups=1 start_ind=0 masked_lane=1 repeat=1 stride=1 }... passed
# |  Local accessor Testing mode=DWORD op=sub T=int32_t N=1
# | 	{ thr_per_group=8 n_groups=1 start_ind=0 masked_lane=1 repeat=1 stride=1 }... passed
# |  Local accessor Testing mode=DWORD op=sub T=uint32_t N=1
# | 	{ thr_per_group=8 n_groups=1 start_ind=0 masked_lane=1 repeat=1 stride=1 }... passed
# |  Local accessor Testing mode=DWORD op=sub T=int32_t N=8
# | 	{ thr_per_group=8 n_groups=1 start_ind=0 masked_lane=1 repeat=1 stride=1 }... passed
# |  Local accessor Testing mode=DWORD op=sub T=uint32_t N=8
# | 	{ thr_per_group=8 n_groups=1 start_ind=0 masked_lane=1 repeat=1 stride=1 }... passed
# |  Local accessor Testing mode=DWORD op=smax T=int32_t N=1
# | 	{ thr_per_group=8 n_groups=1 start_ind=0 masked_lane=1 repeat=1 stride=1 }... passed
# |  Local accessor Testing mode=DWORD op=smax T=int32_t N=8
# | 	{ thr_per_group=8 n_groups=1 start_ind=0 masked_lane=1 repeat=1 stride=1 }... passed
# |  Local accessor Testing mode=DWORD op=smin T=int32_t N=1
# | 	{ thr_per_group=8 n_groups=1 start_ind=0 masked_lane=1 repeat=1 stride=1 }... passed
# |  Local accessor Testing mode=DWORD op=smin T=int32_t N=8
# | 	{ thr_per_group=8 n_groups=1 start_ind=0 masked_lane=1 repeat=1 stride=1 }... passed
# |  Local accessor Testing mode=DWORD op=umax T=uint32_t N=1
# | 	{ thr_per_group=8 n_groups=1 start_ind=0 masked_lane=1 repeat=1 stride=1 }... passed
# |  Local accessor Testing mode=DWORD op=umax T=uint32_t N=8
# | 	{ thr_per_group=8 n_groups=1 start_ind=0 masked_lane=1 repeat=1 stride=1 }... passed
# |  Local accessor Testing mode=DWORD op=umin T=uint32_t N=1
# | 	{ thr_per_group=8 n_groups=1 start_ind=0 masked_lane=1 repeat=1 stride=1 }...
# |   failed at index 0: 2 != 0(gold)
# |   FAILED
# |   pass rate: 0% (0/1)
# |  Local accessor Testing mode=DWORD op=umin T=uint32_t N=8
# | 	{ thr_per_group=8 n_groups=1 start_ind=0 masked_lane=1 repeat=1 stride=1 }... passed
# |  Local accessor Testing mode=DWORD op=load T=int32_t N=1
# | 	{ thr_per_group=8 n_groups=1 start_ind=0 masked_lane=1 repeat=1 stride=1 }... passed
# |  Local accessor Testing mode=DWORD op=load T=uint32_t N=1
# | 	{ thr_per_group=8 n_groups=1 start_ind=0 masked_lane=1 repeat=1 stride=1 }... passed
# |  Local accessor Testing mode=DWORD op=load T=int32_t N=8
# | 	{ thr_per_group=8 n_groups=1 start_ind=0 masked_lane=1 repeat=1 stride=1 }... passed
# |  Local accessor Testing mode=DWORD op=load T=uint32_t N=8
# | 	{ thr_per_group=8 n_groups=1 start_ind=0 masked_lane=1 repeat=1 stride=1 }... passed
# |  Local accessor Testing mode=DWORD op=load T=float N=1
# | 	{ thr_per_group=8 n_groups=1 start_ind=0 masked_lane=1 repeat=1 stride=1 }... passed
# |  Local accessor Testing mode=DWORD op=load T=float N=8
# | 	{ thr_per_group=8 n_groups=1 start_ind=0 masked_lane=1 repeat=1 stride=1 }... passed
# |  Local accessor Testing mode=DWORD op=store T=int32_t N=1
# | 	{ thr_per_group=8 n_groups=1 start_ind=0 masked_lane=1 repeat=1 stride=1 }... passed
# |  Local accessor Testing mode=DWORD op=store T=uint32_t N=1
# | 	{ thr_per_group=8 n_groups=1 start_ind=0 masked_lane=1 repeat=1 stride=1 }... passed
# |  Local accessor Testing mode=DWORD op=store T=int32_t N=8
# | 	{ thr_per_group=8 n_groups=1 start_ind=0 masked_lane=1 repeat=1 stride=1 }... passed
# |  Local accessor Testing mode=DWORD op=store T=uint32_t N=8
# | 	{ thr_per_group=8 n_groups=1 start_ind=0 masked_lane=1 repeat=1 stride=1 }... passed
# |  Local accessor Testing mode=DWORD op=store T=float N=1
# | 	{ thr_per_group=8 n_groups=1 start_ind=0 masked_lane=1 repeat=1 stride=1 }... passed
# |  Local accessor Testing mode=DWORD op=store T=float N=8
# | 	{ thr_per_group=8 n_groups=1 start_ind=0 masked_lane=1 repeat=1 stride=1 }... passed
# | FAILED
# `-----------------------------
# error: command failed with exit status: 1
```

[logs_21444921620.zip](https://github.com/intel/llvm/files/14526414/logs_21444921620.zip)

**Comment by uditagarwal97** [comment] 2024-03-07 17:10
Same as https://github.com/intel/llvm/issues/12896. The failure seems to happen on Windows as well: https://github.com/intel/llvm/actions/runs/8141362435/job/22250625992

**Comment by sarnex** [comment] 2024-08-01 15:44
Linux failure dupe of https://github.com/intel/llvm/issues/12896, tried it on Windows and did not fail for me after 5 runs. No reports since March. Closing.

**Closed by sarnex** 2024-08-01 15:44 UTC
Labels: bug, esimd, confirmed
