### ISSUE TITLE
generated SPIRV contains mangled get_global_id

### ISSUE THREAD

**Issue by airlied** [intel/llvm#21] opened 2019-02-06 03:58 UTC
The SPIR-V generated here using the suggested command line contains a function call out to get_global_id.

This should be lowered by the llvm-spirv code, but isn't and I'm not sure how to fix it.

the llvm-spirv code has an OCL20ToSPIRV lowering code for OpenCL C 2.0, and OCL21toSPIRV lowering for OpenCL C++ 2.1 code.

Now we generate OpenCL C++ 1.0 source version, so neither of these gets hit.

However the OpenCL C++ interface to get_global_id is cl::get_global_id in the CL namespace, so the current SYCL runtime gets this wrong.

I'm not sure what best solution is?

Move to CL C++ 2.1 version (maybe this is a bug in the llvm-spirv, since it's probably meant to be C++ 1.0) and use cl:: for the device only code?

**Comment by airlied** [comment] 2019-02-06 04:07
hmm looks like the OclCxxBifNameReflower pass is also involved here, I'll keep digging a bit more

**Comment by bader** [comment] 2019-02-06 08:53
I think @vladimirlaz has a fix for this problem.
@vladimirlaz, could you commit your fix, please?

**Comment by vladimirlaz** [comment] 2019-02-06 09:04
I will take care of that.

**Comment by bader** [comment] 2019-02-12 12:08
Should be fixed by #23.
@airlied, feel free to re-open if fix doesn't work for you.

**Comment by airlied** [comment] 2019-02-18 04:24
Okay the latest code makes things different, but doesn't fix it unfortunately.
OpDecorate %5 LinkageAttributes "_ZN2cl7__spirv21VarGlobalInvocationIdE" Import
OpDecorate %91 LinkageAttributes "_ZN2cl4sycl6detail29InitSizesSTGlobalInvocationIdILi1ENS0_2idILi1EEEE8initSizeERS4_" Export

This still doesn't contain what the SPIR-V spec says it should which is a variable decorated with the GlobalInvocationID builtin.

**Comment by airlied** [comment] 2019-02-18 04:25
(can we reopen this?, I don't have the permissions.)

**Comment by vladimirlaz** [comment] 2019-02-19 08:09
I was able to reproduce the issue.

**Comment by bader** [comment] 2019-02-19 12:01
> Okay the latest code makes things different, but doesn't fix it unfortunately.
> OpDecorate %5 LinkageAttributes "_ZN2cl7__spirv21VarGlobalInvocationIdE" Import
> OpDecorate %91 LinkageAttributes "_ZN2cl4sycl6detail29InitSizesSTGlobalInvocationIdILi1ENS0_2idILi1EEEE8initSizeERS4_" Export
> 
> This still doesn't contain what the SPIR-V spec says it should which is a variable decorated with the GlobalInvocationID builtin.

@airlied thanks for reporting this.
It's surprising... I would expect OpenCL driver to discard invalid SPIR-V.
@vladimirlaz, will you be able to investigate?

**Comment by bader** [comment] 2019-02-19 13:30
I can't reproduce it.
Could @airlied or @vladimirlaz provide command lines you used to get it, please?

**Comment by bader** [comment] 2019-02-19 16:20
[simple-vector-add.zip](https://github.com/intel/llvm/files/2880867/simple-vector-add.zip)

I attached files I get by compiling https://github.com/codeplaysoftware/computecpp-sdk/raw/master/samples/simple-vector-add/simple-vector-add.cpp

To get SPIR-V binary:
```console
clang --sycl -c simple-vector-add.cpp -fno-sycl-use-bitcode
```
Convert binary to text:
```console
llvm-spirv --to-text simple-vector-add.spv
```
Line 101 of text file has required decoration.

**Comment by vladimirlaz** [comment] 2019-02-20 08:11
Hi, I have retest and it looks like @bader is right. We have both variable __spirv namespace (you mentioned) used to access actual builtin value which is present in numeric form:
In my case it looks like:
. . .
11 Name 5 "__spirv_BuiltInGlobalInvocationId"
. . .
Decorate 5 BuiltIn 28
. . .

I suggest to close issue as fixed

**Closed by vladimirlaz** 2019-02-20 08:11 UTC

**Comment by airlied** [comment] 2019-02-20 09:00
Oops my bad, thanks for making me taking another look, another patch I'd left in my tree to get the previous code working was interfereing, now the kernel I got has the decorations.

Sorry again and thanks for the fix.
