### ISSUE TITLE
Build options are ignored when compile/link is done as separate commands

### ISSUE THREAD

**Issue by vladimirlaz** [intel/llvm#3862] opened 2021-06-02 07:37 UTC
**Describe the bug**
When JIT compile/link is done as separate command both for program and kernel bundle build options passed in device image API and environment variables are missed.
Use tests from https://github.com/intel/llvm-test-suite/pull/302/commits/274a06cb96ab5cd2019e3d436775c74b636f85bf

**To Reproduce**
Build/Run programs from the link above with SYCL_PI_TRACE=2. Make sure that options set in API, environment variables, device code image  are passed to compile and link PI calls.

**Environment (please complete the following information):**

- OS: Windows/Linux
- Target device and vendor: DPC++ RT
- DPC++ version: all
- Dependencies version: N/A

**Comment by romanovvlad** [comment] 2022-03-23 13:05
@HabKaffee Could you please confirm that https://github.com/intel/llvm/pull/5476 fixes the problem?

**Comment by HabKaffee** [comment] 2022-03-23 13:11
According to testing coverage sycl::link(), sycl::build() and sycl::compile() works properly and https://github.com/intel/llvm/pull/5476 fixes problem.

**Comment by romanovvlad** [comment] 2022-07-22 12:51
Closing then. Please feel free to reopen if the issue is still there.

**Closed by romanovvlad** 2022-07-22 12:51 UTC
Labels: bug
