### ISSUE TITLE
Wrong results with sycl::ctz for unsigned char with SYCL+Cuda

### ISSUE THREAD

**Issue by masterleinad** [intel/llvm#8426] opened 2023-02-22 16:46 UTC
**Describe the bug**
@dalg24 noticed in https://github.com/kokkos/kokkos/pull/4577#discussion_r1114409188 that `sycl::ctz` compiling for NVIDIA GPUs is off by 248 for `unsigned char`.

**To Reproduce**
```C++
#include <sycl/sycl.hpp>

int main()
{
  sycl::queue q;
  q.single_task([](){
    for (unsigned char test = 0; test<=10; ++ test) {             
      sycl::ext::oneapi::experimental::printf("char ctz(%d): %d\n", int(test), sycl::ctz(test));
      sycl::ext::oneapi::experimental::printf("int ctz(%d): %d\n", int(test), sycl::ctz(unsigned(test)));
    }
  });
  q.wait();
}
```
prints
```
char ctz(0): 8
int ctz(0): 32
char ctz(1): 248
int ctz(1): 0
char ctz(2): 249
int ctz(2): 1
char ctz(3): 248
int ctz(3): 0
char ctz(4): 250
int ctz(4): 2
char ctz(5): 248
int ctz(5): 0
char ctz(6): 249
int ctz(6): 1
char ctz(7): 248
int ctz(7): 0
char ctz(8): 251
int ctz(8): 3
char ctz(9): 248
int ctz(9): 0
char ctz(10): 249
int ctz(10): 1
```
when compiling via
```
clang++ -fsycl -fsycl-targets=nvptx64-nvidia-cuda -Xsycl-target-backend=nvptx64-nvidia-cuda --cuda-gpu-arch=sm_70  ctz-reproducer.cc
```
but
```
char ctz(0): 8
int ctz(0): 32
char ctz(1): 0
int ctz(1): 0
char ctz(2): 1
int ctz(2): 1
char ctz(3): 0
int ctz(3): 0
char ctz(4): 2
int ctz(4): 2
char ctz(5): 0
int ctz(5): 0
char ctz(6): 1
int ctz(6): 1
char ctz(7): 0
int ctz(7): 0
char ctz(8): 3
int ctz(8): 3
char ctz(9): 0
int ctz(9): 0
char ctz(10): 1
int ctz(10): 1
```
with
```
clang++ -fsycl ctz-reproducer.cc
```
The output for `unsigned char` and `unsigned int` should be the same for values other than zero like in the latter case.

**Environment (please complete the following information):**

- OS: Linux
- Target device and vendor: NVIDIA GPU
- DPC++ version: Intel(R) oneAPI DPC++/C++ Compiler 2023.0.0 (2023.0.0.20221201)
- Dependencies version: Using Codeplay's plugin (https://developer.codeplay.com/products/oneapi/nvidia/2023.0.0/guides/index)

**Comment by zjin-lcf** [comment] 2023-02-22 21:43
I am not familiar with Clang; could Clang add the 8-bit built-in ctz function?

```
__builtin_ctz
__builtin_ctzl
__builtin_ctzll
__builtin_ctzs
```

**Comment by npmiller** [comment] 2023-04-17 08:40
@masterleinad I believe @zjin-lcf 's patch fixed this issue, I can't reproduce with the sample, could you confirm?

**Comment by npmiller** [comment] 2023-05-02 11:20
I'll just close this, feel free to re-open if the issue persists, but it should hopefully be fixed, thanks for the report!

**Closed by npmiller** 2023-05-02 11:20 UTC
Labels: bug, cuda
