### ISSUE TITLE
SYCL atomics are slow on MI250

### ISSUE THREAD

**Issue by mgrabban** [intel/llvm#7179] opened 2022-10-25 19:30 UTC
SYCL atomics run slow on AMD MI250.
Multiple workloads show performance degradation compared to MI100, and after looking into details, we find that the reason for slower performance is kernels that have atomics.

Can you please test SYCL atomics on AMD MI250?

FYI I tested in -
- Ubuntu 20.04.4 LTS
- rocm-5.2.3
- 
```
$ clang++ --version
clang version 16.0.0 (https://github.com/intel/llvm 10d978425267ea8543587048606c4d8550dbff95)
Target: x86_64-unknown-linux-gnu
...
```
Note that I have been seeing slow performance on MI250 ever since I started using it, which was at least 4 months back. So it is probably not due to open source sycl version or rocm version.

Please let me know if you need more information. Thanks.

**Comment by zjin-lcf** [comment] 2022-10-26 15:57
Are the HIP assembly codes for the atomics the same ?

**Comment by al42and** [comment] 2022-10-28 15:00
Are you using `-munsafe-fp-atomics` flag and/or `unsafeAtomicAdd`/`atomicAddNoRet` intrinsics?

**Comment by mgrabban** [comment] 2022-10-28 15:06
> Are the HIP assembly codes for the atomics the same ?

Can you please tell me how to generate the HIP assembly code from either SYCL source or clang++ compiled exe?

**Comment by mgrabban** [comment] 2022-10-28 15:08
> Are you using `-munsafe-fp-atomics` flag and/or `unsafeAtomicAdd`/`atomicAddNoRet` intrinsics?

No, I am not using any of these flags in either MI100 or MI250. I did not know about them. Can you link to their docs?

**Comment by al42and** [comment] 2022-10-28 15:28
> Can you link to their docs?

https://github.com/ROCm-Developer-Tools/HIP/blob/develop/docs/markdown/hip_kernel_language.md#unsafe-floating-point-atomic-rmw-operations

And ORNL website has a good description of what exactly is "safe"/"unsafe" in the context of MI250X: https://docs.olcf.ornl.gov/systems/crusher_quick_start_guide.html, search for "unsafe-fp-atomics".

Setting `-munsafe-fp-atomics` should, theoretically, use the appropriate intrinsic automatically.

**Comment by mgrabban** [comment] 2022-10-28 15:58
Ok I want to add more details here

- We have HIP versions of our workloads and do not see them running slower on MI250 compared to MI100.
- Only for SYCL versions, kernels with atomics run slower on MI250. So for some reason, clang++ is generating slower machine code. Note that we have atomics involving uint32_t, float as well as double and all runs slower so data type is probably not the reason for performance issue.

I tried using `-munsafe-fp-atomics` on MI250 and `-mno-unsafe-fp-atomics` on MI100: I do not see any impact on performance but I do see these warnings

MI250
`clang-16: warning: argument unused during compilation: '-munsafe-fp-atomics' [-Wunused-command-line-argument]`

MI100
`clang-16: warning: argument unused during compilation: '-mno-unsafe-fp-atomics' [-Wunused-command-line-argument]`

For my test, I am using this code
```
#include <sycl/sycl.hpp>

#include <iostream>
#include <chrono>

#define atomicAdd(x, y) (sycl::atomic_ref<float, sycl::memory_order::relaxed, sycl::memory_scope::work_group, sycl::access::address_space::global_space>(*(x)) +=(y))

const int factor     = 4;
const int num_points = 10240 * 1 * 256;
const int num_wgs    = 10240 * factor;
const int wg_size    = 256 / factor;

const int tm_size    = 32;
const int num_iters  = 1;

// add 1.0f to array element if it is in my 'team'
void kernel(float* data, sycl::nd_item<1> item)
{
    size_t tid = item.get_global_linear_id();
    size_t sid = tid / tm_size;

    for (size_t i = 0; i < tm_size; i++) {
        atomicAdd(data + (sid * tm_size + i), 1.0f);
    }
}

int main()
{
    try {
    sycl::device dev = sycl::device(sycl::default_selector_v);
    sycl::queue q(dev);

    float* data_d = sycl::malloc_device<float>(num_points, q);
    float* data_h = sycl::malloc_host<float>(  num_points, q);

    // warm-up run:
    for (int iter = 0; iter < 1; iter++) {
        q.memset(data_d, 0.0, num_points * sizeof(float));
        q.wait();

        q.parallel_for(
            sycl::nd_range<1>(num_points, wg_size),
            [=](sycl::nd_item<1> item) {
                kernel(data_d, item);
            }
        );
        q.wait_and_throw();
    }

    // timed run:
    std::chrono::time_point<std::chrono::steady_clock> time11;
    std::chrono::time_point<std::chrono::steady_clock> time12;
    double duration = 0.0;

    for (int iter = 0; iter < num_iters; iter++) {
        q.memset(data_d, 0.0, num_points * sizeof(float));
        q.wait();

        time11 = std::chrono::steady_clock::now();
        q.parallel_for(
            sycl::nd_range<1>(num_points, wg_size),
            [=](sycl::nd_item<1> item) {
                kernel(data_d, item);
            }
        );
        q.wait_and_throw();
        time12 = std::chrono::steady_clock::now();
        duration += std::chrono::duration<double, std::micro>(time12 - time11).count();
    }

    q.memcpy(data_h, data_d, num_points * sizeof(float));
    q.wait();

    for (size_t i = 0; i < num_points; i++) {
        if (data_h[i] != (float)tm_size) {
            std::cerr << "mismatch found at index " << i << std::endl;
            return 3;
        }
    }
    std::cout << "Success!\n";
    std::cout << "num_points: " << num_points << std::endl;
    std::cout << "num_wgs: " << num_wgs << std::endl;
    std::cout << "wg_size: " << wg_size << std::endl;
    std::cout << "tm_size: " << tm_size << std::endl;
    std::cout << "Total time for " << num_iters << " iterations: " << duration << " us\n";

    } catch (sycl::exception const &exc) {
		std::cerr << exc.what() << "Exception caught at file:" << __FILE__
				  << ", line:" << __LINE__ << std::endl;
		return 1;
	} catch (std::exception& e) {
		std::cerr << "Uncaught exception: " << e.what() << std::endl;
        return 2;
	}

    return 0;
}

```
This code runs 136 times faster on MI100 compared to MI250. The work-group size is optimized for MI250 and I see MI100 performance can be increased further by tuning the work-group size.

**Comment by al42and** [comment] 2022-10-28 16:15
Interesting. When I compile your code for both MI100 and MI250 (`$ clang++ -fsycl -O3 -fsycl-targets=amdgcn-amd-amdhsa -Xsycl-target-backend --offload-arch=gfx908 test.cpp  -save-temps`), I get almost identical code in both cases. But the gfx90a version has additional `buffer_wbl2`/`buffer_invl2` instructions around the `global_atomic_cmpswap`.

**Comment by al42and** [comment] 2022-10-28 16:25
Ah, my bad. It seems in the HIP backend, the native floating point atomics are not implemented at all, so it will always be a CAS loop. Then indeed, no effect is to be had from `-munsafe-fp-atomics` and the like.

**Comment by mgrabban** [comment] 2022-10-28 16:36
> Interesting. When I compile your code for both MI100 and MI250 (`$ clang++ -fsycl -O3 -fsycl-targets=amdgcn-amd-amdhsa -Xsycl-target-backend --offload-arch=gfx908 test.cpp -save-temps`), I get almost identical code in both cases. But the gfx90a version has additional `buffer_wbl2`/`buffer_invl2` instructions around the `global_atomic_cmpswap`.

So this could be a reason for slow performance?

**Comment by mgrabban** [comment] 2022-10-28 16:38
> Ah, my bad. It seems in the HIP backend, the native floating point atomics are not implemented at all, so it will always be a CAS loop. Then indeed, no effect is to be had from `-munsafe-fp-atomics` and the like.
> 
> Upd: BTW, I'd expect that your MI100 HIP code can benefit from `-munsafe-fp-atomics` if it's not somehow already enabled. Will only affect `float` atomics, but still something.

Yes we will use `-munsafe-fp-atomics` for HIP versions of our workloads. Thanks for the suggestion.

**Comment by al42and** [comment] 2022-10-28 16:44
> So this could be a reason for slow performance?

No idea. But that's the only difference I see in the generated assembly between gfx908 and gfx90a. Can't find any documentation either (I'm not affiliated with AMD), but it looks like a cache invalidation.

A somewhat bigger problem, performance-wise, is that CAS-loops are used for `float` atomics of MI250 at all. I don't know whether oneAPI/libclc team has any timeline for lifting this restriction.

**Comment by mgrabban** [comment] 2022-10-28 17:05
Ok I will keep pursuing this.
Thanks again for all the help :-)

**Comment by zjin-lcf** [comment] 2022-10-29 12:39
https://github.com/intel/llvm/issues/4471

**Comment by mgrabban** [comment] 2023-01-12 16:21
Hello, is there any updates on this issue (SYCL atomics slow on MI250)? We need urgent support on this.

**Comment by hdelan** [comment] 2023-01-13 12:27
Adding some basic atomics for HIP here https://github.com/intel/llvm-test-suite/pull/1510 . More to be rolled out soon

**Comment by arghdos** [comment] 2023-01-16 15:46
Hi @mgrabban -- I suspect the issue is that the `-munsafe-fp-atomics` flag looks like it's only defined if LLVM sees that the target is an AMDGPU triple: https://reviews.llvm.org/D125909?id=430713, which triggers use of the `unsafeAtomicAdd` (and friends) in the [HIP APIs](https://github.com/ROCm-Developer-Tools/hipamd/blob/develop/include/hip/amd_detail/amd_hip_atomic.h#L189)

Perhaps the `-fsycl-targets` option is not triggering that?

From @al42and's description of the ISA (haven't tried it myself), you are indeed emitting 'safe' atomics, which will map down to a CAS loop in this case.  I suspect to get fast atomic support, I suspect you would need to implement some version of `unsafeAtomicAdd` in the SYCL headers / the compiler to teach it to emit the desired instructions (global_atomic_add_f32, in this case).

**Comment by hdelan** [comment] 2023-01-18 15:23
Hi @mgrabban can you see if there is any performance improvement by using the branch here #8003

**Comment by hdelan** [comment] 2023-01-18 16:12
On my machine I have seen a marginal speedup using branch #8003 . But cannot test for sure on MI250. 

```
$ sycl-ls
[ext_oneapi_hip:gpu:0] AMD HIP BACKEND, AMD Radeon VII 0.0 [HIP 40421.43]

# Using sycl branch of DPC++ 
$ clang++ --version 
clang version 16.0.0 (https://github.com/hdelan/llvm 81ca1dcacc5b6ef60ed9a2a3c662611f5e1cb0cf)
Target: x86_64-unknown-linux-gnu
Thread model: posix
InstalledDir: /home/hugh/llvm/build/bin
$ clang++ -fsycl -fsycl-targets=amd_gpu_gfx906 mytest.cpp && ./a.out
Success!
num_points: 2621440
num_wgs: 40960
wg_size: 64
tm_size: 32
Total time for 100 iterations: 1.29576e+07 us

# Using #8003
$ clang++ --version 
clang version 16.0.0 (https://github.com/hdelan/llvm 89fb7e66f8e0d3b770ebbe6a58848a95be426fe8)
Target: x86_64-unknown-linux-gnu
Thread model: posix
InstalledDir: /home/hugh/llvm/build/bin
$ clang++ -fsycl -fsycl-targets=amd_gpu_gfx906 mytest.cpp && ./a.out
Success!
num_points: 2621440
num_wgs: 40960
wg_size: 64
tm_size: 32
Total time for 100 iterations: 1.24168e+07 us
```
 
I can also confirm @al42and 's observation of extra `buffer_wbl2`, `buffer_invl2` instructions. This could be the cause of perf difference between the two.

There are MI250 specific atomic builtins that we will be adding to DPC++ soon (see here https://github.com/intel/llvm/blob/sycl/clang/include/clang/Basic/BuiltinsAMDGPU.def#L198). I would imagine that these native atomic builtins are much faster than the current CAS implementations, so using the MI250 atomic builtins in DPC++ will most likely solve this performance regression.

**Comment by mgrabban** [comment] 2023-01-18 16:19
> Hi @mgrabban can you see if there is any performance improvement by using the branch here #8003

@hdelan I will try to test this soon on an workload. Thanks.

**Comment by arghdos** [comment] 2023-02-01 20:27
>  Is the hypothesis that the extra buffer_wbl2, buffer_invl2 instructions were the problem?

Indeed:

![image](https://user-images.githubusercontent.com/6463881/216155841-56b2259d-4697-4205-a9b9-d44e0190e645.png)

See pg ~185 of https://developer.amd.com/wp-content/resources/CDNA2_Shader_ISA_4February2022.pdf

**Comment by mgrabban** [comment] 2023-02-01 20:35
> > Hi @mgrabban can you see if there is any performance improvement by using the branch here #8003
> 
> @hdelan I will try to test this soon on an workload. Thanks.

All, except one, of our workloads seem to run at least as fast as in MI100. So thank you for #8003! I am trying to get details on the remaining one workload.

What does #8003 make into the main sycl branch?

**Comment by al42and** [comment] 2023-02-01 20:36
> Also, -munsafe-fp-atomics won't have any effect on the MI100 (gfx908) since the hardware has no support for unsafe atomics. They are only useful on the MI200s (gfx90a) and above.

Not quite. Besides "unsafe atomics", there are also "no return atomics", controlled by the same `-munsafe-fp-atomics` flag and available on gfx908: https://github.com/intel/llvm/blob/sycl/llvm/lib/Target/AMDGPU/SIISelLowering.cpp#L12932

**Comment by nmnobre** [comment] 2023-02-01 20:41
> > > Hi @mgrabban can you see if there is any performance improvement by using the branch here #8003
> > 
> > 
> > @hdelan I will try to test this soon on an workload. Thanks.
> 
> All, except one, of our workloads seem to run at least as fast as in MI100. So thank you for #8003! I am trying to get details on the remaining one workload.
> 
> What does #8003 make into the main sycl branch?

It already did! Just yesterday!

**Comment by mgrabban** [comment] 2023-02-01 20:44
> > > > Hi @mgrabban can you see if there is any performance improvement by using the branch here #8003
> > > 
> > > 
> > > @hdelan I will try to test this soon on an workload. Thanks.
> > 
> > 
> > All, except one, of our workloads seem to run at least as fast as in MI100. So thank you for #8003! I am trying to get details on the remaining one workload.
> > What does #8003 make into the main sycl branch?
> 
> It already did! Just yesterday!

Thanks again!

**Comment by nmnobre** [comment] 2023-02-01 21:00
> > Also, -munsafe-fp-atomics won't have any effect on the MI100 (gfx908) since the hardware has no support for unsafe atomics. They are only useful on the MI200s (gfx90a) and above.
> 
> Not quite. Besides "unsafe atomics", there are also "no return atomics", controlled by the same `-munsafe-fp-atomics` flag and available on gfx908: https://github.com/intel/llvm/blob/sycl/llvm/lib/Target/AMDGPU/SIISelLowering.cpp#L12932

Uh, oops, I stand corrected! Interesting and... just a tiny bit evil...?
So, this is just for single-precision floating-point? And I get no control from the source-code, meaning, e.g. `unsafeAtomicAdd`, will do me no good and I do need the compiler flag?

**Comment by al42and** [comment] 2023-02-01 21:27
> And I get no control from the source-code, meaning, e.g. unsafeAtomicAdd, will do me no good and I do need the compiler flag?

There is `atomicAddNoRet`, which maps to `__ockl_atomic_add_noret_f32` in HIP headers, which works on [gfx908 and gfx90a](https://github.com/RadeonOpenCompute/ROCm-Device-Libs/blob/66a1c5bdca86ef8108263f0a3e2e21a6a343b643/ockl/src/gaaf.cl#L36). But it's not quite a drop-in replacement, since it returns `void`.

**Comment by hdelan** [comment] 2023-02-01 21:37
This may also be of interest for newer gfx90a atomics https://github.com/intel/llvm/pull/8170

**Comment by hdelan** [comment] 2023-02-02 19:41
Using the test above.

SYCL branch:
```
$ clang++ -fsycl -fsycl-targets=amd_gpu_gfx90a mytest.cpp && ./a.out
Success!
num_points: 2621440
num_wgs: 40960
wg_size: 64
tm_size: 32
Total time for 1000 iterations: 4.88058e+07 us
```

https://github.com/intel/llvm/pull/8170 branch:
```
$ clang++ -fsycl -fsycl-targets=amd_gpu_gfx90a mytest.cpp && ./a.out
Success!
num_points: 2621440
num_wgs: 40960
wg_size: 64
tm_size: 32
Total time for 1000 iterations: 3.36497e+06 us
```

**Comment by zjin-lcf** [comment] 2023-02-02 19:51
@mgrabban 
> All, except one, of our workloads seem to run at least as fast as in MI100. So thank you for #8003! I am trying to get details on the remaining one workload.

I read your post. What about the remaining one workload ?

**Comment by mgrabban** [comment] 2023-02-02 20:11
> @mgrabban
> 
> > All, except one, of our workloads seem to run at least as fast as in MI100. So thank you for #8003! I am trying to get details on the remaining one workload.
> 
> I read your post. What about the remaining one workload ?

I asked the owner of that workload and they said that that workload has atomics and was seeing issues but it turned out the issues were not due to atomics. So we are good :-)

**Comment by hdelan** [comment] 2023-02-03 11:19
OK great I will go ahead and close this issue then. If you have any further issues with HIP atomics feel free to reopen this ticket

**Closed by hdelan** 2023-02-03 11:19 UTC
Labels: bug, hip
