### ISSUE TITLE
Assert/assert_in_multiple_tus.cpp failing on Arc in postcommit

### ISSUE THREAD

**Issue by sarnex** [intel/llvm#14557] opened 2024-07-12 14:46 UTC
### Describe the bug

https://github.com/intel/llvm/actions/runs/9909045579/job/27377061306

```
******************** TEST 'SYCL :: Assert/assert_in_multiple_tus.cpp' FAILED ********************
Exit Code: 1

Command Output (stdout):
--
# RUN: at line 12
/__w/llvm/llvm/toolchain/bin//clang++   -fsycl -fsycl-targets=spir64  /__w/llvm/llvm/llvm/sycl/test-e2e/Assert/assert_in_multiple_tus.cpp -DSYCL_FALLBACK_ASSERT=1 -I /__w/llvm/llvm/llvm/sycl/test-e2e/Assert/Inputs /__w/llvm/llvm/llvm/sycl/test-e2e/Assert/Inputs/kernels_in_file2.cpp -o /__w/llvm/llvm/build-e2e/Assert/Output/assert_in_multiple_tus.cpp.tmp.out
# executed command: /__w/llvm/llvm/toolchain/bin//clang++ -fsycl -fsycl-targets=spir64 /__w/llvm/llvm/llvm/sycl/test-e2e/Assert/assert_in_multiple_tus.cpp -DSYCL_FALLBACK_ASSERT=1 -I /__w/llvm/llvm/llvm/sycl/test-e2e/Assert/Inputs /__w/llvm/llvm/llvm/sycl/test-e2e/Assert/Inputs/kernels_in_file2.cpp -o /__w/llvm/llvm/build-e2e/Assert/Output/assert_in_multiple_tus.cpp.tmp.out
# note: command had no output on stdout or stderr
# RUN: at line 13
env ONEAPI_DEVICE_SELECTOR=level_zero:gpu  /__w/llvm/llvm/build-e2e/Assert/Output/assert_in_multiple_tus.cpp.tmp.out &> /__w/llvm/llvm/build-e2e/Assert/Output/assert_in_multiple_tus.cpp.tmp.txt ; /__w/llvm/llvm/toolchain/bin/FileCheck /__w/llvm/llvm/llvm/sycl/test-e2e/Assert/assert_in_multiple_tus.cpp --input-file /__w/llvm/llvm/build-e2e/Assert/Output/assert_in_multiple_tus.cpp.tmp.txt
# executed command: env ONEAPI_DEVICE_SELECTOR=level_zero:gpu /__w/llvm/llvm/build-e2e/Assert/Output/assert_in_multiple_tus.cpp.tmp.out
# .---redirected output from '/__w/llvm/llvm/build-e2e/Assert/Output/assert_in_multiple_tus.cpp.tmp.txt'
# | AssertHandler::printMessage
# | /__w/llvm/llvm/llvm/sycl/test-e2e/Assert/Inputs/kernels_in_file2.cpp:15: int calculus(int): global id: [5,0,0], local id: [1,0,0] Assertion `X && "this message from calculus"` failed.
# | /__w/llvm/llvm/llvm/sycl/test-e2e/Assert/assert_in_multiple_tus.hpp:22: int checkFunction(): global id: [5,0,0], local id: [1,0,0] Assertion `X && "Nil in result"` failed.
# | /__w/llvm/llvm/llvm/sycl/test-e2e/Assert/Inputs/kernels_in_file2.cpp:19: void check_nil(int): global id: [0,0,0], local id: [0,0,0] Assertion `value && "this message from file2"` failed.
# | /__w/llvm/llvm/llvm/sycl/test-e2e/Assert/Inputs/kernels_in_file2.cpp:19: void check_nil(int): global id: [1,0,0], local id: [1,0,0] Assertion `value && "this message from file2"` failed.
# | /__w/llvm/llvm/llvm/sycl/test-e2e/Assert/Inputs/kernels_in_file2.cpp:19: void check_nil(int): global id: [2,0,0], local id: [2,0,0] Assertion `value && "this message from file2"` failed.
# | /__w/llvm/llvm/llvm/sycl/test-e2e/Assert/Inputs/kernels_in_file2.cpp:19: void c
# | ...
# `---data was truncated--------
# note: command had no output on stdout or stderr
# error: command failed with exit status: -6
# executed command: /__w/llvm/llvm/toolchain/bin/FileCheck /__w/llvm/llvm/llvm/sycl/test-e2e/Assert/assert_in_multiple_tus.cpp --input-file /__w/llvm/llvm/build-e2e/Assert/Output/assert_in_multiple_tus.cpp.tmp.txt
# .---command stderr------------
# | /__w/llvm/llvm/llvm/sycl/test-e2e/Assert/assert_in_multiple_tus.cpp:20:15: error: CHECK-NOT: excluded string found in input
# | // CHECK-NOT: this message from file2
# |               ^
# | /__w/llvm/llvm/build-e2e/Assert/Output/assert_in_multiple_tus.cpp.tmp.txt:4:154: note: found here
# | /__w/llvm/llvm/llvm/sycl/test-e2e/Assert/Inputs/kernels_in_file2.cpp:19: void check_nil(int): global id: [0,0,0], local id: [0,0,0] Assertion `value && "this message from file2"` failed.
# |                                                                                                                                                          ^~~~~~~~~~~~~~~~~~~~~~~
# | 
# | Input file: /__w/llvm/llvm/build-e2e/Assert/Output/assert_in_multiple_tus.cpp.tmp.txt
# | Check file: /__w/llvm/llvm/llvm/sycl/test-e2e/Assert/assert_in_multiple_tus.cpp
# | 
# | -dump-input=help explains the following input dump.
# | 
# | Input was:
# | <<<<<<
# |         1: AssertHandler::printMessage 
# |         2: /__w/llvm/llvm/llvm/sycl/test-e2e/Assert/Inputs/kernels_in_file2.cpp:15: int calculus(int): global id: [5,0,0], local id: [1,0,0] Assertion `X && "this message from calculus"` failed. 
# |         3: /__w/llvm/llvm/llvm/sycl/test-e2e/Assert/assert_in_multiple_tus.hpp:22: int checkFunction(): global id: [5,0,0], local id: [1,0,0] Assertion `X && "Nil in result"` failed. 
# |         4: /__w/llvm/llvm/llvm/sycl/test-e2e/Assert/Inputs/kernels_in_file2.cpp:19: void check_nil(int): global id: [0,0,0], local id: [0,0,0] Assertion `value && "this message from file2"` failed. 
# | not:20                                                                                                                                                              !~~~~~~~~~~~~~~~~~~~~~~            error: no match expected
# |         5: /__w/llvm/llvm/llvm/sycl/test-e2e/Assert/Inputs/kernels_in_file2.cpp:19: void check_nil(int): global id: [1,0,0], local id: [1,0,0] Assertion `value && "this message from file2"` failed. 
# |         6: /__w/llvm/llvm/llvm/sycl/test-e2e/Assert/Inputs/kernels_in_file2.cpp:19: void check_nil(int): global id: [2,0,0], local id: [2,0,0] Assertion `value && "this message from file2"` failed. 
# |         7: /__w/llvm/llvm/llvm/sycl/test-e2e/Assert/Inputs/kernels_in_file2.cpp:19: void check_nil(int): global id: [3,0,0], local id: [3,0,0] Assertion `value && "this message from file2"` failed. 
# | >>>>>>
# `-----------------------------
# error: command failed with exit status: 1
```

**Comment by bader** [comment] 2024-08-01 04:35
Another instance - https://github.com/intel/llvm/actions/runs/10189443105/job/28187745437#step:22:2279.

Seems to be related to https://github.com/intel/llvm/issues/11364.
Maybe https://github.com/intel/llvm/issues/8832 is related as well.

**Comment by againull** [comment] 2024-12-26 19:41
I have reproduced this issue on Arc  and it seems to depend on version of the GPU driver and is fixed in the latest drivers.

So, using the latest compiler (20241226) and different versions of gpu driver I've got the following results:
24.22.29735.20 - fail
24.31.30508.7 - fail
24.39.31294.12 - pass
24.45.31740.9 - pass

So I am going to reenable the test and close this issue.

**Closed** 2024-12-26 21:38 UTC
Labels: bug, confirmed
