### ISSUE TITLE
[CUDA] q.wait() causes CUDA_ERROR_NOT_PERMITTED error

### ISSUE THREAD

**Issue by pvelesko** [intel/llvm#1569] opened 2020-04-22 10:00 UTC
capturing the event `auto e = q.submit...`  followed by `e.wait()` works but doing `q.wait()` causes the following error:

````
PI CUDA ERROR:
        Value:           800
        Name:            CUDA_ERROR_NOT_PERMITTED
        Description:     operation not permitted
        Function:        ScopedContext
        Source Location: /home/bhomerding/repo/sycl_usm/llvm/sycl/plugins/cuda/pi_cuda.cpp:147

````

**Comment by Ruyk** [comment] 2020-04-27 09:03
This is a known issue, related to the implementation of events, we are working on a fix

**Comment by mmeterel** [comment] 2020-06-03 19:25
@Ruyk Do you have an estimate for the fix? We are seeing this problem on oneMKL interfaces side as well.

**Comment by StuartDAdams** [comment] 2020-06-08 14:43
Hello! This is fixed in the sycl branch. Event implementation has been improved a lot since this issue was opened. Updating to the latest should resolve this.

**Comment by Ruyk** [comment] 2020-06-08 19:43
The issue cannot be reproduced, this can be closed. @mmeterel  / @pvelesko  , feel free to open a new ticket if it reappears.

**Closed by Ruyk** 2020-06-08 19:43 UTC
Labels: cuda

**Comment by mmeterel** [comment] 2020-06-08 21:36
Hi @StuartDAdams I tested with 20200527 build and see the same issue. Do you know when was the fix integrated?

**Comment by StuartDAdams** [comment] 2020-06-09 09:53
[It was fixed 11 days ago.](https://github.com/intel/llvm/pull/1735) The release you've linked seems a few days older than that. The compiler build you are using will need these changes and to have CUDA backend support.
