### ISSUE TITLE
Clang tests use tools, but they are not built.

### ISSUE THREAD

**Issue by bader** [intel/llvm#4132] opened 2021-07-18 17:57 UTC
**Describe the bug**
Following clang lit tests use `append-file` tool.
  Clang :: Driver/print-internal-defines-for-sycl.c
  Clang :: Driver/sycl-int-footer.cpp
  Clang :: Driver/sycl-intelfpga-aoco-win.cpp
  Clang :: Driver/sycl-intelfpga-aoco.cpp
  Clang :: Driver/sycl-intelfpga-return-check.cpp
  Clang :: Driver/sycl-intelfpga-static-lib.cpp
  Clang :: Driver/sycl-offload-static-lib-2.cpp
  Clang :: Driver/sycl-offload-static-lib.cpp
  Clang :: Driver/sycl-offload-win.c

  Clang :: Driver/sycl-intelfpga-return-check.cpp requires following tools to exist: `llvm-link`, `sycl-post-link`, `file-table-tform`, `llmv-spirv`, `llvm-foreach`. The test is looking for an error message from the linker, but if the tools I listed doesn't exist, the compilation aborted before the linker step.

I think the tests should be refactored to remove dependencies on external tools.

**To Reproduce**
Run `check-clang` immediately after running configure.py script.

**Environment (please complete the following information):**

- OS: I reproduced this issue on Linux.
- DPC++ version: ea4b8a945b80c4e7f10cc98a92a8e4815dcb99d6

**Comment by vladimirlaz** [comment] 2022-02-07 08:11
The issue is resolved in the scope of: https://github.com/intel/llvm/pull/4890 and https://github.com/intel/llvm/pull/4249.

**Closed by vladimirlaz** 2022-02-07 08:11 UTC
Labels: bug
