### ISSUE TITLE
[SYCL] 11 tests are failing on Ubuntu 18.10 and GCC 8.2.0

### ISSUE THREAD

**Issue by keryell** [intel/llvm#29] opened 2019-02-13 18:03 UTC
Current version https://github.com/intel/llvm/commit/bae2b751d83aab3bc819796350fcc086c14ba92a
has some failing tests on Ubuntu 18.10 and GCC 8.2.0:

```
********************
Failing Tests (11):
    SYCLUnitTests :: aot/with-llvm-bc.cpp
    SYCLUnitTests :: sub_group/barrier.cpp
    SYCLUnitTests :: sub_group/broadcast.cpp
    SYCLUnitTests :: sub_group/common.cpp
    SYCLUnitTests :: sub_group/common_ocl.cpp
    SYCLUnitTests :: sub_group/info.cpp
    SYCLUnitTests :: sub_group/load_store.cpp
    SYCLUnitTests :: sub_group/reduce.cpp
    SYCLUnitTests :: sub_group/scan.cpp
    SYCLUnitTests :: sub_group/shuffle.cpp
    SYCLUnitTests :: sub_group/vote.cpp

  Expected Passes    : 43607
  Expected Failures  : 172
  Unsupported Tests  : 1292
  Unexpected Failures: 11
make[3]: *** [CMakeFiles/check-all.dir/build.make:58: CMakeFiles/check-all] Error 1
make[2]: *** [CMakeFiles/Makefile2:211: CMakeFiles/check-all.dir/all] Error 2
make[1]: *** [CMakeFiles/Makefile2:218: CMakeFiles/check-all.dir/rule] Error 2
make: *** [Makefile:199: check-all] Error 2
```

Actually it is also mentionned by @Ruyk in https://github.com/intel/llvm/pull/9

Among the 11, it looks like there are 2 kinds of failures:
```
FAIL: SYCLUnitTests :: aot/with-llvm-bc.cpp (45019 of 45082)
******************** TEST 'SYCLUnitTests :: aot/with-llvm-bc.cpp' FAILED ********************
Script:
--
: 'RUN: at line 1';    /home/rkeryell/Xilinx/Projects/LLVM/worktrees/intel/sycl/build/bin/clang -I/home/rkeryell/Xilinx/Projects/OpenCL/Khronos/OpenCL-Headers -fsycl -fsycl-targets=spir64-unknown-linux-sycldevice -c /home/rkeryell/Xilinx/Projects/LLVM/worktrees/intel/sycl/sycl/test/aot/with-llvm-bc.cpp -o /home/rkeryell/Xilinx/Projects/LLVM/worktrees/intel/sycl/build/projects/sycl/test/aot/Output/with-llvm-bc.cpp.tmp.o
: 'RUN: at line 2';    /home/rkeryell/Xilinx/Projects/LLVM/worktrees/intel/sycl/build/bin/clang -I/home/rkeryell/Xilinx/Projects/OpenCL/Khronos/OpenCL-Headers -fsycl -fsycl-link-targets=spir64-unknown-linux-sycldevice /home/rkeryell/Xilinx/Projects/LLVM/worktrees/intel/sycl/build/projects/sycl/test/aot/Output/with-llvm-bc.cpp.tmp.o -o /home/rkeryell/Xilinx/Projects/LLVM/worktrees/intel/sycl/build/projects/sycl/test/aot/Output/with-llvm-bc.cpp.tmp.spv
: 'RUN: at line 3';   /home/rkeryell/Xilinx/Projects/LLVM/worktrees/intel/sycl/build/bin/llvm-spirv -r /home/rkeryell/Xilinx/Projects/LLVM/worktrees/intel/sycl/build/projects/sycl/test/aot/Output/with-llvm-bc.cpp.tmp.spv -o /home/rkeryell/Xilinx/Projects/LLVM/worktrees/intel/sycl/build/projects/sycl/test/aot/Output/with-llvm-bc.cpp.tmp.bc
: 'RUN: at line 4';    /home/rkeryell/Xilinx/Projects/LLVM/worktrees/intel/sycl/build/bin/clang -I/home/rkeryell/Xilinx/Projects/OpenCL/Khronos/OpenCL-Headers -fsycl -fsycl-add-targets=binary:/home/rkeryell/Xilinx/Projects/LLVM/worktrees/intel/sycl/build/projects/sycl/test/aot/Output/with-llvm-bc.cpp.tmp.bc /home/rkeryell/Xilinx/Projects/LLVM/worktrees/intel/sycl/build/projects/sycl/test/aot/Output/with-llvm-bc.cpp.tmp.o -o /home/rkeryell/Xilinx/Projects/LLVM/worktrees/intel/sycl/build/projects/sycl/test/aot/Output/with-llvm-bc.cpp.tmp.out -lOpenCL -lsycl -lstdc++
: 'RUN: at line 7';   env SYCL_DEVICE_TYPE=CPU  /home/rkeryell/Xilinx/Projects/LLVM/worktrees/intel/sycl/build/projects/sycl/test/aot/Output/with-llvm-bc.cpp.tmp.out
--
Exit Code: -11

Command Output (stdout):
--
$ ":" "RUN: at line 1"
$ "/home/rkeryell/Xilinx/Projects/LLVM/worktrees/intel/sycl/build/bin/clang" "-I/home/rkeryell/Xilinx/Projects/OpenCL/Khronos/OpenCL-Headers" "-fsycl" "-fsycl-targets=spir64-unknown-linux-sycldevice" "-c" "/home/rkeryell/Xilinx/Projects/LLVM/worktrees/intel/sycl/sycl/test/aot/with-llvm-bc.cpp" "-o" "/home/rkeryell/Xilinx/Projects/LLVM/worktrees/intel/sycl/build/projects/sycl/test/aot/Output/with-llvm-bc.cpp.tmp.o"
$ ":" "RUN: at line 2"
$ "/home/rkeryell/Xilinx/Projects/LLVM/worktrees/intel/sycl/build/bin/clang" "-I/home/rkeryell/Xilinx/Projects/OpenCL/Khronos/OpenCL-Headers" "-fsycl" "-fsycl-link-targets=spir64-unknown-linux-sycldevice" "/home/rkeryell/Xilinx/Projects/LLVM/worktrees/intel/sycl/build/projects/sycl/test/aot/Output/with-llvm-bc.cpp.tmp.o" "-o" "/home/rkeryell/Xilinx/Projects/LLVM/worktrees/intel/sycl/build/projects/sycl/test/aot/Output/with-llvm-bc.cpp.tmp.spv"
$ ":" "RUN: at line 3"
$ "/home/rkeryell/Xilinx/Projects/LLVM/worktrees/intel/sycl/build/bin/llvm-spirv" "-r" "/home/rkeryell/Xilinx/Projects/LLVM/worktrees/intel/sycl/build/projects/sycl/test/aot/Output/with-llvm-bc.cpp.tmp.spv" "-o" "/home/rkeryell/Xilinx/Projects/LLVM/worktrees/intel/sycl/build/projects/sycl/test/aot/Output/with-llvm-bc.cpp.tmp.bc"
$ ":" "RUN: at line 4"
$ "/home/rkeryell/Xilinx/Projects/LLVM/worktrees/intel/sycl/build/bin/clang" "-I/home/rkeryell/Xilinx/Projects/OpenCL/Khronos/OpenCL-Headers" "-fsycl" "-fsycl-add-targets=binary:/home/rkeryell/Xilinx/Projects/LLVM/worktrees/intel/sycl/build/projects/sycl/test/aot/Output/with-llvm-bc.cpp.tmp.bc" "/home/rkeryell/Xilinx/Projects/LLVM/worktrees/intel/sycl/build/projects/sycl/test/aot/Output/with-llvm-bc.cpp.tmp.o" "-o" "/home/rkeryell/Xilinx/Projects/LLVM/worktrees/intel/sycl/build/projects/sycl/test/aot/Output/with-llvm-bc.cpp.tmp.out" "-lOpenCL" "-lsycl" "-lstdc++"
$ ":" "RUN: at line 7"
$ "/home/rkeryell/Xilinx/Projects/LLVM/worktrees/intel/sycl/build/projects/sycl/test/aot/Output/with-llvm-bc.cpp.tmp.out"
# command stderr:
Stack dump:
0.	Running pass 'Intel OpenCL Vectorizer' on module 'main'.
1.	Running pass 'Intel OpenCL VectorizerCore' on function ''
2.	Running pass 'OCL Builtin Pre Vectorization Pass' on function ''

error: command failed with exit status: -11

--

********************
FAIL: SYCLUnitTests :: sub_group/broadcast.cpp (45042 of 45082)
******************** TEST 'SYCLUnitTests :: sub_group/broadcast.cpp' FAILED ********************
Script:
--
: 'RUN: at line 1';    /home/rkeryell/Xilinx/Projects/LLVM/worktrees/intel/sycl/build/bin/clang -I/home/rkeryell/Xilinx/Projects/OpenCL/Khronos/OpenCL-Headers -std=c++11 -fsycl /home/rkeryell/Xilinx/Projects/LLVM/worktrees/intel/sycl/sycl/test/sub_group/broadcast.cpp -o /home/rkeryell/Xilinx/Projects/LLVM/worktrees/intel/sycl/build/projects/sycl/test/sub_group/Output/broadcast.cpp.tmp.out -lstdc++ -lOpenCL -lsycl
: 'RUN: at line 2';   env SYCL_DEVICE_TYPE=HOST /home/rkeryell/Xilinx/Projects/LLVM/worktrees/intel/sycl/build/projects/sycl/test/sub_group/Output/broadcast.cpp.tmp.out
: 'RUN: at line 3';   env SYCL_DEVICE_TYPE=CPU  /home/rkeryell/Xilinx/Projects/LLVM/worktrees/intel/sycl/build/projects/sycl/test/sub_group/Output/broadcast.cpp.tmp.out
: 'RUN: at line 4';    env SYCL_DEVICE_TYPE=GPU  /home/rkeryell/Xilinx/Projects/LLVM/worktrees/intel/sycl/build/projects/sycl/test/sub_group/Output/broadcast.cpp.tmp.out
: 'RUN: at line 5';   echo /home/rkeryell/Xilinx/Projects/LLVM/worktrees/intel/sycl/build/projects/sycl/test/sub_group/Output/broadcast.cpp.tmp.out
--
Exit Code: 1

Command Output (stdout):
--
$ ":" "RUN: at line 1"
$ "/home/rkeryell/Xilinx/Projects/LLVM/worktrees/intel/sycl/build/bin/clang" "-I/home/rkeryell/Xilinx/Projects/OpenCL/Khronos/OpenCL-Headers" "-std=c++11" "-fsycl" "/home/rkeryell/Xilinx/Projects/LLVM/worktrees/intel/sycl/sycl/test/sub_group/broadcast.cpp" "-o" "/home/rkeryell/Xilinx/Projects/LLVM/worktrees/intel/sycl/build/projects/sycl/test/sub_group/Output/broadcast.cpp.tmp.out" "-lstdc++" "-lOpenCL" "-lsycl"
# command stderr:
In file included from /home/rkeryell/Xilinx/Projects/LLVM/worktrees/intel/sycl/sycl/test/sub_group/broadcast.cpp:14:
/home/rkeryell/Xilinx/Projects/LLVM/worktrees/intel/sycl/sycl/test/sub_group/helper.hpp:105:9: error: call to 'abs' is ambiguous
    if (std::abs(val - ref) != 0) {
        ^~~~~~~~
/home/rkeryell/Xilinx/Projects/LLVM/worktrees/intel/sycl/sycl/test/sub_group/broadcast.cpp:50:7: note: in instantiation of function template specialization 'exit_if_not_equal<unsigned int>' requested here
      exit_if_not_equal<T>(syclacc[j], L * WGid + SGid + SGid * sg_size,
      ^
/home/rkeryell/Xilinx/Projects/LLVM/worktrees/intel/sycl/sycl/test/sub_group/broadcast.cpp:65:3: note: in instantiation of function template specialization 'check<unsigned int>' requested here
  check<unsigned int>(Queue);
  ^
/usr/include/stdlib.h:837:12: note: candidate function
extern int abs (int __x) __THROW __attribute__ ((__const__)) __wur;
           ^
/usr/lib/gcc/x86_64-linux-gnu/8/../../../../include/c++/8/bits/std_abs.h:56:3: note: candidate function
  abs(long __i) { return __builtin_labs(__i); }
  ^
/usr/lib/gcc/x86_64-linux-gnu/8/../../../../include/c++/8/bits/std_abs.h:61:3: note: candidate function
  abs(long long __x) { return __builtin_llabs (__x); }
  ^
/usr/lib/gcc/x86_64-linux-gnu/8/../../../../include/c++/8/bits/std_abs.h:70:3: note: candidate function
  abs(double __x)
  ^
/usr/lib/gcc/x86_64-linux-gnu/8/../../../../include/c++/8/bits/std_abs.h:74:3: note: candidate function
  abs(float __x)
  ^
/usr/lib/gcc/x86_64-linux-gnu/8/../../../../include/c++/8/bits/std_abs.h:78:3: note: candidate function
  abs(long double __x)
  ^
In file included from /home/rkeryell/Xilinx/Projects/LLVM/worktrees/intel/sycl/sycl/test/sub_group/broadcast.cpp:14:
/home/rkeryell/Xilinx/Projects/LLVM/worktrees/intel/sycl/sycl/test/sub_group/helper.hpp:105:9: error: call to 'abs' is ambiguous
    if (std::abs(val - ref) != 0) {
        ^~~~~~~~
/home/rkeryell/Xilinx/Projects/LLVM/worktrees/intel/sycl/sycl/test/sub_group/broadcast.cpp:50:7: note: in instantiation of function template specialization 'exit_if_not_equal<unsigned long>' requested here
      exit_if_not_equal<T>(syclacc[j], L * WGid + SGid + SGid * sg_size,
      ^
/home/rkeryell/Xilinx/Projects/LLVM/worktrees/intel/sycl/sycl/test/sub_group/broadcast.cpp:67:3: note: in instantiation of function template specialization 'check<unsigned long>' requested here
  check<unsigned long>(Queue);
  ^
/usr/include/stdlib.h:837:12: note: candidate function
extern int abs (int __x) __THROW __attribute__ ((__const__)) __wur;
           ^
/usr/lib/gcc/x86_64-linux-gnu/8/../../../../include/c++/8/bits/std_abs.h:56:3: note: candidate function
  abs(long __i) { return __builtin_labs(__i); }
  ^
/usr/lib/gcc/x86_64-linux-gnu/8/../../../../include/c++/8/bits/std_abs.h:61:3: note: candidate function
  abs(long long __x) { return __builtin_llabs (__x); }
  ^
/usr/lib/gcc/x86_64-linux-gnu/8/../../../../include/c++/8/bits/std_abs.h:70:3: note: candidate function
  abs(double __x)
  ^
/usr/lib/gcc/x86_64-linux-gnu/8/../../../../include/c++/8/bits/std_abs.h:74:3: note: candidate function
  abs(float __x)
  ^
/usr/lib/gcc/x86_64-linux-gnu/8/../../../../include/c++/8/bits/std_abs.h:78:3: note: candidate function
  abs(long double __x)
  ^
2 errors generated.
In file included from /home/rkeryell/Xilinx/Projects/LLVM/worktrees/intel/sycl/sycl/test/sub_group/broadcast.cpp:14:
/home/rkeryell/Xilinx/Projects/LLVM/worktrees/intel/sycl/sycl/test/sub_group/helper.hpp:105:9: error: call to 'abs' is ambiguous
    if (std::abs(val - ref) != 0) {
        ^~~~~~~~
/home/rkeryell/Xilinx/Projects/LLVM/worktrees/intel/sycl/sycl/test/sub_group/broadcast.cpp:50:7: note: in instantiation of function template specialization 'exit_if_not_equal<unsigned int>' requested here
      exit_if_not_equal<T>(syclacc[j], L * WGid + SGid + SGid * sg_size,
      ^
/home/rkeryell/Xilinx/Projects/LLVM/worktrees/intel/sycl/sycl/test/sub_group/broadcast.cpp:65:3: note: in instantiation of function template specialization 'check<unsigned int>' requested here
  check<unsigned int>(Queue);
  ^
/usr/include/stdlib.h:837:12: note: candidate function
extern int abs (int __x) __THROW __attribute__ ((__const__)) __wur;
           ^
/usr/lib/gcc/x86_64-linux-gnu/8/../../../../include/c++/8/bits/std_abs.h:56:3: note: candidate function
  abs(long __i) { return __builtin_labs(__i); }
  ^
/usr/lib/gcc/x86_64-linux-gnu/8/../../../../include/c++/8/bits/std_abs.h:61:3: note: candidate function
  abs(long long __x) { return __builtin_llabs (__x); }
  ^
/usr/lib/gcc/x86_64-linux-gnu/8/../../../../include/c++/8/bits/std_abs.h:70:3: note: candidate function
  abs(double __x)
  ^
/usr/lib/gcc/x86_64-linux-gnu/8/../../../../include/c++/8/bits/std_abs.h:74:3: note: candidate function
  abs(float __x)
  ^
/usr/lib/gcc/x86_64-linux-gnu/8/../../../../include/c++/8/bits/std_abs.h:78:3: note: candidate function
  abs(long double __x)
  ^
In file included from /home/rkeryell/Xilinx/Projects/LLVM/worktrees/intel/sycl/sycl/test/sub_group/broadcast.cpp:14:
/home/rkeryell/Xilinx/Projects/LLVM/worktrees/intel/sycl/sycl/test/sub_group/helper.hpp:105:9: error: call to 'abs' is ambiguous
    if (std::abs(val - ref) != 0) {
        ^~~~~~~~
/home/rkeryell/Xilinx/Projects/LLVM/worktrees/intel/sycl/sycl/test/sub_group/broadcast.cpp:50:7: note: in instantiation of function template specialization 'exit_if_not_equal<unsigned long>' requested here
      exit_if_not_equal<T>(syclacc[j], L * WGid + SGid + SGid * sg_size,
      ^
/home/rkeryell/Xilinx/Projects/LLVM/worktrees/intel/sycl/sycl/test/sub_group/broadcast.cpp:67:3: note: in instantiation of function template specialization 'check<unsigned long>' requested here
  check<unsigned long>(Queue);
  ^
/usr/include/stdlib.h:837:12: note: candidate function
extern int abs (int __x) __THROW __attribute__ ((__const__)) __wur;
           ^
/usr/lib/gcc/x86_64-linux-gnu/8/../../../../include/c++/8/bits/std_abs.h:56:3: note: candidate function
  abs(long __i) { return __builtin_labs(__i); }
  ^
/usr/lib/gcc/x86_64-linux-gnu/8/../../../../include/c++/8/bits/std_abs.h:61:3: note: candidate function
  abs(long long __x) { return __builtin_llabs (__x); }
  ^
/usr/lib/gcc/x86_64-linux-gnu/8/../../../../include/c++/8/bits/std_abs.h:70:3: note: candidate function
  abs(double __x)
  ^
/usr/lib/gcc/x86_64-linux-gnu/8/../../../../include/c++/8/bits/std_abs.h:74:3: note: candidate function
  abs(float __x)
  ^
/usr/lib/gcc/x86_64-linux-gnu/8/../../../../include/c++/8/bits/std_abs.h:78:3: note: candidate function
  abs(long double __x)
  ^
2 errors generated.

error: command failed with exit status: 1
--
********************
```

**Comment by bader** [comment] 2019-02-13 18:06
@vladimirlaz, could you take a look at these, please?

**Comment by Ruyk** [comment] 2019-02-27 16:45
In case it helps, when using Ubuntu 18.04, GCC 7.3 and Intel CPU OpenCL 1.2.0.10, aot/with-llvm-bc.cpp  deadlocks for me on clBuildProgram.

When I disable execution of that test, output is as below:

```
$ninja check-sycl
(.......)
********************
Testing Time: 44.30s
********************
Failing Tests (7):
    SYCLUnitTests :: sub_group/barrier.cpp
    SYCLUnitTests :: sub_group/broadcast.cpp
    SYCLUnitTests :: sub_group/common.cpp
    SYCLUnitTests :: sub_group/common_ocl.cpp
    SYCLUnitTests :: sub_group/reduce.cpp
    SYCLUnitTests :: sub_group/scan.cpp
    SYCLUnitTests :: sub_group/vote.cpp

  Expected Passes    : 43
  Expected Failures  : 1
  Unexpected Failures: 7
```

**Comment by pvchupin** [comment] 2019-02-28 04:46
This seems to be an issue in version older (but the latest publicly available) of OpenCL CPU RT which is fixed now. We are working towards making a new OpenCL CPU RT release available soon and going to have more frequent updates going forward.

**Comment by bader** [comment] 2019-02-28 10:41
There is a workaround for this issue: the problem is that SYCL device compiler saves information about source language as "OpenCL C++ 1.0" and OpenCL CPU runtime does not support C++ language yet, so it assumes that SPIR-V will require only OpenCL C 1.0 features.
The workaround could be raise the version in OpenCL language metadata to 2.1(?).

**Comment by bader** [comment] 2019-05-15 14:02
@keryell, @Ruyk, could you check if [Experimental Intel® CPU Runtime](https://github.com/intel/llvm/releases/tag/expoclcpu-1.0.0) fixes these LIT test failures in your environment, please?

**Comment by keryell** [comment] 2019-05-17 00:30
Since now I already switched on Ubuntu 19.04 and I am investigating some other failures there, perhaps @agozillon can test on his machine...

**Comment by agozillon** [comment] 2019-05-17 02:16
I haven't had any failing tests in a long while with the cookie cutter GetStartedWithSYCLCompiler.md compile command, with either the experimental runtime or standard CPU runtime (I had some failing sub_group tests for a while as well, but they disappeared at some point). I am using GCC 8.3 though, I could probably downgrade to test this tomorrow.

**Comment by bader** [comment] 2019-05-17 14:14
Okay, it seems like you can't reproduce the issues @Ruyk experienced.
The issues reported by @keryell were fixed in February by #34, so if you don't have any failing LIT tests anymore - it's great, but a little bit puzzling... If you could share more information about your environment it would be great (e.g. what version of OpenCL CPU do you use).
To close this issue, I'll wait for a confirmation from @Ruyk, that no tests are failing in his environment.

**Comment by agozillon** [comment] 2019-05-20 17:45
I am currently using Ubuntu 18.10, GCC 8.3.0 and the OpenCL/SYCL experimental runtime (the one linked in the GetStarted doc). I also have Xilinx's runtime installed and POCL. I should probably restate the previous sentence as no more failing tests than occur during the pull request verification. e.g:

********************
Testing Time: 51.31s
********************
Failing Tests (3):
    SYCLUnitTests :: kernel_from_file/hw.cpp
    SYCLUnitTests :: scheduler/MultipleDevices.cpp
    SYCLUnitTests :: separate-compile/test.cpp

  Expected Passes    : 62
  Unexpected Failures: 3 

Although your recent revert aims to fix these I think. When using the previous runtime I get 10 unexpected failures: 

********************
Testing Time: 75.04s
********************
Failing Tests (10):
    SYCLUnitTests :: basic_tests/boolean.cpp
    SYCLUnitTests :: basic_tests/handler/handler_mem_op.cpp
    SYCLUnitTests :: built-ins/vector_common.cpp
    SYCLUnitTests :: built-ins/vector_geometric.cpp
    SYCLUnitTests :: built-ins/vector_integer.cpp
    SYCLUnitTests :: built-ins/vector_math.cpp
    SYCLUnitTests :: built-ins/vector_relational.cpp
    SYCLUnitTests :: multi_ptr/multi_ptr.cpp
    SYCLUnitTests :: struct_param/struct_kernel_param.cpp
    SYCLUnitTests :: sub_group/shuffle.cpp

  Expected Passes    : 55
  Unexpected Failures: 10

This was from a build on Friday, so prior to the revert but the most recent merge I think. So I believe the SYCL/OpenCL CPU experimental runtime is doing it's job in this case.

As for prior LIT tests I've run via the standard Intel OpenCL CPU Runtime I don't recall any failures (at least up to the point https://github.com/triSYCL/sycl is currently synced to which is a little old at the moment), I could be mistaken though.

**Comment by agozillon** [comment] 2019-05-21 04:01
So I believe I fixed the problem I was having and I now pass all the tests with Ubuntu 18.10, GCC 8.3.0 and the OpenCL/SYCL experimental CPU runtime. I am also currently using the Debian ICD loader packages (ocl-icd-opencl-dev/ocl-icd-libopencl1 ) in conjunction with the experimental runtime, seems to be working fine (tested without the packages installed as well, same result).  Output:

Testing Time: 51.50s
  Expected Passes    : 65

Although, I've noticed that the pull requests have:
  Expected Passes    : 64
  Expected Failures  : 1 

But the dockers is also testing with a GPU runtime so perhaps the expected failure comes from this?

As a possibly irrelevant aside, the problem seems to be that as I'm using an old machine it seems that I had inherited some old ICD loaders that were interfering with certain runtime functionality and giving unusual results from the LIT tests. So thanks @bader for indicating there may be some environment issues!

**Comment by bader** [comment] 2019-05-21 11:40
> Although, I've noticed that the pull requests have:
> Expected Passes : 64
> Expected Failures : 1
> 
> But the travis ci docker is also testing with a GPU runtime so perhaps the expected failure comes from this?

See to be the case:
```
grep -rni xfail sycl/test/
sycl/test/sub_group/load_store.cpp:14:// XFAIL: gpu
```
@vladimirlaz, were we can find information about the OpenCL runtimes versions used in CI?

**Comment by bader** [comment] 2019-05-21 12:00
> I am also currently using the Debian ICD loader packages (ocl-icd-opencl-dev/ocl-icd-libopencl1 ) in conjunction with the experimental runtime, seems to be working fine (tested without the packages installed as well, same result), although perhaps they shouldn't be installed alongside the experimental runtime?

I think current implementation of LIT tests doesn't provide controls to choose specific device among multiple devices of the same type (e.g. always prefer Intel's CPU runtime over Debian ICD loader). Probably this is something we can improve.

ATM, Intel team validates SYCL implementation in specific environment (i.e. Intel HW + Intel's OpenCL implementations), so assume that the environment is configured according to [the get started guide](https://github.com/intel/llvm/blob/sycl/sycl/doc/GetStartedWithSYCLCompiler.md#before-you-begin).

It would be great if someone can analyze the issues and send patches to either Debian ICD loader or SYCL compiler/runtime implementation.

**Comment by vladimirlaz** [comment] 2019-05-21 12:05
This information is not available in logs now.  Currently we have internal CPU RT (moving to experimantal now) and https://github.com/intel/compute-runtime/releases/tag/19.15.12831 for GPU.

**Comment by bader** [comment] 2019-06-20 14:48
AFAIK, all LIT tests pass now, so I'm closing this issue.

**Closed by bader** 2019-06-20 14:48 UTC
Labels: bug
