### ISSUE TITLE
[CUDA] CTS math_builtin_api tests are failed with no kernel named _ZTS6kernelILi1000078EE on Windows

### ISSUE THREAD

**Issue by yuxianch** [intel/llvm#4882] opened 2021-11-03 07:50 UTC
**Describe the bug**
CTS math_builtin_api tests are failed with no kernel named _ZTS6kernelILi1000078EE with CUDA backend on Windows.

**To Reproduce**
1. Get SYCL with CUDA support ([GSG](https://intel.github.io/llvm-docs/GetStartedGuide.html)) and [SYCL-CTS](https://github.com/KhronosGroup/SYCL-CTS https://github.com/KhronosGroup/SYCL-CTS/commit/14fac446f4454d4889a6b0e7bf5eab83bbe4cf26)
2. Build CTS tests
```
cd SYCL-CTS
mkdir build && cd build
cmake -GNinja  -DSYCL_IMPLEMENTATION=Intel_SYCL -DINTEL_SYCL_ROOT=<path to built sycl> -Dopencl_platform_name=nvidia -Dopencl_device_name=opencl_gpu -DCMAKE_BUILD_TYPE=Release -DCMAKE_CXX_FLAGS_RELEASE="-fsycl -fsycl-unnamed-lambda /EHsc /EHsc /MD -Wno-deprecated-declarations" -DINTEL_SYCL_FLAGS="-Xsycl-target-backend;--cuda-gpu-arch=sm_50" -DCMAKE_EXE_LINKER_FLAGS=" -Wl,-no-relax " -DINTEL_SYCL_TRIPLE=nvptx64-nvidia-cuda-sycldevice -DSYCL_CTS_ENABLE_OPENCL_INTEROP_TESTS=Off -DSYCL_CTS_ENABLE_DOUBLE_TESTS=On -DSYCL_CTS_ENABLE_HALF_TESTS=On ..
ninja test_math_builtin_api
```
3. Run test
```
export SYCL_DEVICE_FILTER="cuda:gpu:0"
export SYCL_ENABLE_HOST_DEVICE="1"
bin/test_math_builtin_api -p nvidia -d opencl_gpu  --test math_builtin_common_base
```
Error message(all the test cases are failed with the same exception):
```
--- math_builtin_common_base
  . sycl exception caught
  . what - No kernel named _ZTS6kernelILi1000000EE was found -46 (CL_INVALID_KERNEL_NAME)
  . line: 143
  . tests case: 1000000 a SYCL exception was caught: No kernel named _ZTS6kernelILi1000000EE was found -46 (CL_INVALID_KERNEL_NAME)
  . sycl exception caught
  . what - No kernel named _ZTS6kernelILi1000001EE was found -46 (CL_INVALID_KERNEL_NAME)
  . line: 143
  . tests case: 1000001 a SYCL exception was caught: No kernel named _ZTS6kernelILi1000001EE was found -46 (CL_INVALID_KERNEL_NAME)
...
```
The error comes from [math_builtin.h](https://github.com/KhronosGroup/SYCL-CTS/blob/ccb228e527c148b134c9cf69299169be971549f6/tests/math_builtin_api/math_builtin.h#L125-L144):
```
    sycl::buffer<returnT, 1> buffer(&kernelResult, ndRng);
    testQueue.submit([&](sycl::handler &h) {
      auto resultPtr =
          buffer.template get_access<sycl::access_mode::write>(h);
      h.single_task<kernel<N>>([=]() { resultPtr[0] = fun(); });  //<-- ERROR
    });
```

**Environment**

- OS: Windows
- Target device and vendor: Nvidia GPU
- DPC++ version: https://github.com/intel/llvm.git 1d8cebacb2306b4112a8e82c5f9b5d6a2274b9d8
- CUDA version: 
```
Cuda compilation tools, release 11.4, V11.4.120
Build cuda_11.4.r11.4/compiler.30300941_0
```

**Comment by AerialMantis** [comment] 2021-12-06 23:31
We believe this is the same issue as seen in https://github.com/intel/llvm/issues/4873.

**Comment by AerialMantis** [comment] 2021-12-20 17:24
We believe the issue here to the same as that in https://github.com/intel/llvm/issues/4873 and the proposed solution there more generic and not CUDA-specific, so I will remove the CUDA label, if there is CUDA-specific issues involved here after all please re-add the label and we can look into it again.

**Comment by romanovvlad** [comment] 2022-02-08 11:01
Closing the issue as a duplicate of #4873. Please, reopen if there are some concerns?

**Closed by romanovvlad** 2022-02-08 11:01 UTC
Labels: bug, runtime
