### ISSUE TITLE
Unit test failure after https://github.com/intel/llvm/pull/7778.

### ISSUE THREAD

**Issue by bader** [intel/llvm#7788] opened 2022-12-14 22:01 UTC
@smaslov-intel, post-commit has failed, which is a bit surprising.
https://github.com/intel/llvm/actions/runs/3697810699/jobs/6263246783

I think Scheduler unittests are executed in pre-commit as well, so it's possible that failure is sporadic.
Could you take a look and check if the failure caused by the changes from https://github.com/intel/llvm/pull/7778, please?

**Comment by smaslov-intel** [comment] 2022-12-14 22:21
@Bader: Reported failure is this:

> Failed Tests (1):
  SYCL-Unit :: scheduler/./SchedulerTests/DependsOnTests/EnqueueNoMemObjDoubleKernelDepHostBlocked
Testing Time: 168.36s
  Unsupported:  19
  Passed     : 481
  Failed     :   1

The "check-sycl" passes locally but the number of Passed tests is different:

> Testing Time: 152.48s
  Unsupported:  19
  Passed     : 468

How to run that specific test locally?

**Comment by bader** [comment] 2022-12-14 22:39
> How to run that specific test locally?

I think you can use the command from the log:

/__w/llvm/llvm/build/tools/sycl/unittests/scheduler/./SchedulerTests --gtest_filter=DependsOnTests.EnqueueNoMemObjDoubleKernelDepHostBlocked

**Comment by smaslov-intel** [comment] 2022-12-14 22:45
It doesn't seem to run it:

> $ build/tools/sycl/unittests/scheduler/./SchedulerTests --gtest_filter=DependsOnTests.EnqueueNoMemObjDoubleKernelDepHostBlocked
Note: Google Test filter = DependsOnTests.EnqueueNoMemObjDoubleKernelDepHostBlocked
[==========] Running 0 tests from 0 test suites.
[==========] 0 tests from 0 test suites ran. (0 ms total)
[  PASSED  ] 0 tests.

**Comment by smaslov-intel** [comment] 2022-12-14 22:47
Also it looks it is no longer reported in post-commit after re-run: https://github.com/intel/llvm/actions/runs/3697810699

**Comment by bader** [comment] 2022-12-15 00:46
> It doesn't seem to run it:
> 
> > $ build/tools/sycl/unittests/scheduler/./SchedulerTests --gtest_filter=DependsOnTests.EnqueueNoMemObjDoubleKernelDepHostBlocked
> > Note: Google Test filter = DependsOnTests.EnqueueNoMemObjDoubleKernelDepHostBlocked
> > [==========] Running 0 tests from 0 test suites.
> > [==========] 0 tests from 0 test suites ran. (0 ms total)
> > [  PASSED  ] 0 tests.

I think your local sources are outdated. This test has been added yesterday by @KseniyaTikhomirova - #6995.
@aelovikov-intel, FYI.

**Comment by bader** [comment] 2022-12-15 00:47
> Also it looks it is no longer reported in post-commit after re-run: https://github.com/intel/llvm/actions/runs/3697810699

That confirms my guess that the issue is sporadic. It passed in pre-commit before the merge.

**Comment by smaslov-intel** [comment] 2022-12-15 01:15
Is anything still needed on my side?
I am pretty sure that the stylistic changes in L0 Plugin should not have caused real issues in SYCL RT

**Comment by bader** [comment] 2022-12-15 01:19
> Is anything still needed on my side? I am pretty sure that the stylistic changes in L0 Plugin should not have caused real issues in SYCL RT

I don't think so.

@KseniyaTikhomirova, could you check what might go wrong with a new test, please?

**Comment by KseniyaTikhomirova** [comment] 2022-12-15 09:57
@bader sure, will work on this

**Comment by KseniyaTikhomirova** [comment] 2022-12-15 10:51
root cause is in test (I had two merged PRs for scheduler, both were updating those tests and the second uploaded was not changed appropriately)
this PR should fix observed unpredictable behavior https://github.com/intel/llvm/pull/7793

**Comment by KseniyaTikhomirova** [comment] 2022-12-21 15:57
hi folks, could we close it now?

**Comment by smaslov-intel** [comment] 2022-12-21 16:02
I think so, yes

**Closed by smaslov-intel** 2022-12-21 16:02 UTC
Labels: bug, confirmed
