### ISSUE TITLE
Flaky failure in ESIMD/mask_expand_load.cpp on Windows Gen12

### ISSUE THREAD

**Issue by steffenlarsen** [intel/llvm#15088] opened 2024-08-15 06:28 UTC
### Describe the bug

The ESIMD/mask_expand_load.cpp test has been observed to fail on unrelated changes (https://github.com/intel/llvm/pull/13817) in Gen12 Windows pre-commit CI:

```
******************** TEST 'SYCL :: ESIMD/mask_expand_load.cpp' FAILED ********************
Exit Code: 1

Command Output (stdout):
--
# RUN: at line 9
.../llvm/install/bin/clang++.exe  -Werror  -Wno-error=deprecated-declarations -fsycl -fsycl-targets=spir64  ...\llvm\llvm\sycl\test-e2e\ESIMD\mask_expand_load.cpp -fsycl-device-code-split=per_kernel -o ...\llvm\build-e2e\ESIMD\Output\mask_expand_load.cpp.tmp.out
# executed command: .../llvm/install/bin/clang++.exe -Werror -Wno-error=deprecated-declarations -fsycl -fsycl-targets=spir64 '...\llvm\llvm\sycl\test-e2e\ESIMD\mask_expand_load.cpp' -fsycl-device-code-split=per_kernel -o '...\llvm\build-e2e\ESIMD\Output\mask_expand_load.cpp.tmp.out'
# note: command had no output on stdout or stderr
# RUN: at line 10
env ONEAPI_DEVICE_SELECTOR=level_zero:gpu  ...\llvm\build-e2e\ESIMD\Output\mask_expand_load.cpp.tmp.out
# executed command: env ONEAPI_DEVICE_SELECTOR=level_zero:gpu '...\llvm\build-e2e\ESIMD\Output\mask_expand_load.cpp.tmp.out'
# .---command stdout------------
# | Running on Intel(R) Iris(R) Xe Graphics, driver=[1.3.29803]
# | mask_compress_load: error at I = 1: 0 != 681 != 681
# | mask_compress_load: error at I = 1: 0 != 681 != 0
# `-----------------------------
# error: command failed with exit status: 1

--
```

### To reproduce

1. Include a code snippet that is as short as possible
2. Specify the command which should be used to compile the program
3. Specify the command which should be used to launch the program
4. Indicate what is wrong and what was expected

### Environment

- OS: [e.g Windows/Linux]
- Target device and vendor: [e.g. Intel GPU]
- DPC++ version: [e.g. commit hash or output of `clang++ --version`]
- Dependencies version: [e.g. the output of `sycl-ls --verbose`]

**Comment by sarnex** [comment] 2024-09-11 15:29
Dupe of https://github.com/intel/llvm/issues/15257

**Closed by sarnex** 2024-09-11 15:29 UTC
Labels: bug, esimd, confirmed
