### ISSUE TITLE
[SYCL][CUDA] OneDNN fails to compile sources designated for cuda backend support

### ISSUE THREAD

**Issue by dzarukin** [intel/llvm#3084] opened 2021-01-23 00:07 UTC
Hi!

OneDNN has a problem when compiling sources containing cuda backend support. The problem happens if to rely on compiler identifying path to `<CL/cl.h>` header file. Consider the following source containing both sycl-specific and cuda-specific code:
```
#include <CL/sycl.hpp>
#include <cuda.h>

int main() {
    cl::sycl::device adevice;
    cl::sycl::context acontext;
    for (auto &plat : cl::sycl::platform::get_platforms()) {
        for (auto &dev : plat.get_devices()) {
            if (dev.is_gpu()) {
                adevice = cl::sycl::device(dev);
                acontext = cl::sycl::context(adevice);
                constexpr int nvidia_vendor_id = 0x10DE;
                if (dev.get_info<cl::sycl::info::device::vendor_id>() == nvidia_vendor_id) {
                    printf("This is Nvidia GPU\n");
                    struct cudaDeviceProp prop;
                    auto status = cudaGetDeviceProperties(&prop, 0);
                    if (status == cudaSuccess)
                        printf("prop.name=%s\n", prop.name);
                }
            }
        }
    }
    return 0;
}
```

To compile it, one uses the following command line:
```
(export LLVM=/path/to/intel-llvm/build; export PATH=${LLVM}/bin:$PATH; export LD_LIBRARY_PATH=$LLVM/lib:$LD_LIBRARY_PATH; $LLVM/bin/clang++ -I/usr/local/cuda/include -std=c++11 -fsycl -g -o a.out a.cpp)
```

This result in the following error:
```
In file included from a.cpp:1:
In file included from /path/to/intel-llvm/build/include/sycl/CL/sycl.hpp:11:
In file included from /path/to/intel-llvm/build/include/sycl/CL/sycl/ONEAPI/atomic.hpp:11:
In file included from /path/to/intel-llvm/build/include/sycl/CL/sycl/ONEAPI/atomic_accessor.hpp:11:
In file included from /path/to/intel-llvm/build/include/sycl/CL/sycl/ONEAPI/atomic_enums.hpp:12:
In file included from /path/to/intel-llvm/build/include/sycl/CL/sycl/access/access.hpp:10:
In file included from /path/to/intel-llvm/build/include/sycl/CL/sycl/detail/common.hpp:11:
/path/to/intel-llvm/build/include/sycl/CL/cl_ext_intel.h:431:9: error: unknown type name 'cl_properties'
typedef cl_properties cl_mem_properties_intel;
        ^
```

This is happening due to the fact that cuda headers are obsolete, incompatible with sycl and have to be specified explicitly for a compile line:
```
#include <...> search starts here:
 /usr/local/cuda/include
 /path/to/intel-llvm/build/include/sycl
 /usr/lib/gcc/x86_64-linux-gnu/8/../../../../include/c++/8
 /usr/lib/gcc/x86_64-linux-gnu/8/../../../../include/x86_64-linux-gnu/c++/8
 /usr/lib/gcc/x86_64-linux-gnu/8/../../../../include/c++/8/backward
 /usr/local/include
 /lpath/to/intel-llvm/build/lib/clang/12.0.0/include
 /usr/include/x86_64-linux-gnu
 /usr/include
End of search list.
```

If path to cuda headers is not specified, one sees:
```
a.cpp:2:10: fatal error: 'cuda.h' file not found
```

One could imaging that directly specifying ` /path/to/intel-llvm/build/include/sycl` in front of cuda headers could solve the problem, but it doesn't happen due to the fact that:

```
(export LLVM=/path/to/intel-llvm/build; export PATH=${LLVM}/bin:$PATH; export LD_LIBRARY_PATH=$LLVM/lib:$LD_LIBRARY_PATH; $LLVM/bin/clang++ -I/$LLVM/include/sycl -I/usr/local/cuda/include -std=c++11 -fsycl -g -o a.out a.cpp)

ignoring duplicate directory "/path/to/intel-llvm/build/include/sycl"
  as it is a non-system directory that duplicates a system directory
#include <...> search starts here:
 /usr/local/cuda/include
 /path/to/intel-llvm/build/include/sycl
...
```

So now the question is: what should we do?

Sorry for too long issue description and thank you for reading.

**Comment by zjin-lcf** [comment] 2021-02-03 19:29
May a user replace cuda-specific codes with sycl-specific codes ?

```
                    struct cudaDeviceProp prop;
                    auto status = cudaGetDeviceProperties(&prop, 0);
                    if (status == cudaSuccess)
                        printf("prop.name=%s\n", prop.name);
````

**Comment by dzarukin** [comment] 2021-02-05 21:00
> May a user replace cuda-specific codes with sycl-specific codes ?
> 
> ```
>                     struct cudaDeviceProp prop;
>                     auto status = cudaGetDeviceProperties(&prop, 0);
>                     if (status == cudaSuccess)
>                         printf("prop.name=%s\n", prop.name);
> ```

Hi @zjin-lcf, not sure this is possible due to the final goal is to utilize cuda optimizations from libraries they ship with specific APIs they provide from cuDNN or cuBLAS. This is just a small reproducer for show-case. Thanks.

**Comment by dzarukin** [comment] 2021-04-17 05:43
Hi! Any progress here?

**Comment by JackAKirk** [comment] 2021-10-07 14:43
In your example code (a.cpp) the compilation invocation requires adding the CUDA include directory via -I/usr/local/cuda/include. This places the cuda include directory at the head of include directories that the compiler sees. This means that when the compiler searches for openCL headers it looks first in /usr/local/cuda/include and finds the obsolete headers. Unless these out of date headers are updated by Nvidia the only solution is to make sure that the correct headers are found before the obsolete ones. This can be achieved by manually specifying the correct include directory in front of the CUDA include, as:
```
$ $DPCPP_HOME/bin/clang++ -I/$DPCPP_HOME/build/_deps/ocl-headers-src -I/usr/local/cuda/include -fsycl -g -o a.out
```
For solving the corresponding issue of building oneDNN with DPC++ the cmake variable setting the correct openCL include directory is OpenCL_INCLUDE_DIR. This needs to be manually set at the correct place when invoking cmake as:
```
$ cmake .. -GNinja -DCMAKE_C_COMPILER=$DPCPP_HOME/build/bin/clang -DCMAKE_CXX_COMPILER=$DPCPP_HOME/build/bin/clang++ -DDNNL_CPU_RUNTIME=DPCPP -DDNNL_GPU_RUNTIME=DPCPP -DDNNL_GPU_VENDOR=NVIDIA -DOpenCL_INCLUDE_DIR=$DPCPP_HOME/build/_deps/ocl-headers-src  -DCMAKE_CXX_FLAGS=-I\ $DPCPP_HOME/sycl/include
```

Here are the full instructions for building oneDNN with DPC++ for CUDA backend:

## Prerequisites

    * DPC++ (assuming it is cloned in $DPCPP_HOME and built in $DPCPP_HOME/build)

    * CMake 2.8.12 or later

    * Intel Thread Building Blocks (TBB)

    * OpenCL

    * NVIDIA CUDA driver

    * cuBLAS 10.1 or later

    * cuDNN 7.6 or later

## Building

Clone the library:

`git clone https://github.com/oneapi-src/oneDNN.git`

### Configure using CMake:
```
cmake .. -GNinja -DCMAKE_C_COMPILER=$DPCPP_HOME/build/bin/clang -DCMAKE_CXX_COMPILER=$DPCPP_HOME/build/bin/clang++ -DDNNL_CPU_RUNTIME=DPCPP -DDNNL_GPU_RUNTIME=DPCPP -DDNNL_GPU_VENDOR=NVIDIA -DOpenCL_INCLUDE_DIR=$DPCPP_HOME/build/_deps/ocl-headers-src  -DCMAKE_CXX_FLAGS=-I\ $DPCPP_HOME/sycl/include
```
OpenCL_INCLUDE_DIR can be detected automatically, but letting it do so will likely cause errors. The issue is that oneDNN needs both CUDA and OpenCL and CUDA include folder contains OpenCL headers that are too old for oneDNN. So the path to OpenCL headers must be before the path to CUDA on the list of include directories. Automatically detected include path for OpenCL will likely be a system include path or duplicate of some other include path. Compiler will deduplicate paths, leaving in only the last entry, resulting in CUDA and OpenCL paths in the wrong order.

### Build using ninja:

`ninja`

### Running Tests

Add path to dynamic libraries from DPC++ to path:

`export LD_LIBRARY_PATH=$DPCPP_HOME/build/lib/:$LD_LIBRARY_PATH`

Run tests:

`ctest`

All tests are expected to pass.

**Comment by densamoilov** [comment] 2021-10-24 02:18
Hi @JackAKirk, I'm not sure about the statement below.
> This can be achieved by manually specifying the correct include directory in front of the CUDA include
The compiler still searches `CL/cl.h` in  `/usr/local/cuda/include` first.

I used [2021-07 release](https://github.com/intel/llvm/releases/tag/2021-07) to make experiments.
Suppose we have a simple program:
```cpp
// main.cpp
#include <CL/sycl.hpp>
#include <cuda.h>
int main() { return 0; }
```
```bash
# run.sh
CMPLRROOT=/path/to/lnx/cuda
${CMPLRROOT}/compiler/bin/clang++ -fsycl -v \
    -I${CMPLRROOT}/compiler/include \
    -I/usr/local/cuda/include \
    -c main.cpp
```
The order of directories for searching is the follow:
```none
ignoring duplicate directory "/path/to/lnx/cuda/compiler/include"
  as it is a non-system directory that duplicates a system directory
. . .
#include "..." search starts here:
#include <...> search starts here:
 /usr/local/cuda/include
 /path/to/lnx/cuda/compiler/bin/../include/sycl
 /path/to/lnx/cuda/compiler/include
 . . .
End of search list.
```
The order of passing the paths via `-I` option doesn't affect the order in which the compiler goes through the paths in this particular case. The compiler also gives a note that the `/path/to/lnx/cuda/compiler/include` is ignored because ` it is a non-system directory that duplicates a system directory`.

I think what's happening here is that the compiler receives two paths (via `-I) that contain the same header file and one of the path is system. In this case, the compiler prefers the system path over the other one.
 
The only way to make this work is to use `-idirafter` to lower priority of `/usrl/local/cuda/include` directory (or any other directory where CUDA is installed) so that the compiler picks up `CL/cl.h` from `/path/to/lnx/cuda/compiler/include`, though this is not an ideal solution.

The ideal solution would be making the compiler to use the OpenCL headers from the path that we explicitly specify rather than lowering priority of the other paths where the other OpenCL headers can be located. The downside of the `-idirafter` approach is that it may not work for all cases, but I think it will work for most of them.

**Comment by densamoilov** [comment] 2021-11-05 04:31
@JackAKirk, I guess the behavior can be summarized in a table:

| H1   |  H2    |  H1 first    | H2 first |
|------|-------|------------|----------|
| system      | non-system    |  H1           | H1         |
| non-system   | system       | H2            | H2         |
| system      | system       | H1           | H2          |
|  non-system  |  non-system    | H1           | H2          |

- system/non-system is where the headers are located
- H1/H2 is different OpenCL headers
- H1 first/H2 first is the place in the command line

So if we want to H1 always to have a higher priority than H2 then we should lower H2's priority. This can be done via `-idirafter` option. We (oneDNN) implemented the workaround and it seems to be working fine. You can find it [here](https://github.com/oneapi-src/oneDNN/blob/3025f80fa59384c06c5ec2a3a4792e57be3f8107/cmake/SYCL.cmake#L68).

**Comment by AerialMantis** [comment] 2021-12-06 17:17
Discussion of this was continued on the pull request for the oneDNN project (https://github.com/oneapi-src/oneDNN/pull/1172) to update the documentation, the issue has been resolved by a patch to oneDNN (https://github.com/oneapi-src/oneDNN/blob/3025f80fa59384c06c5ec2a3a4792e57be3f8107/cmake/SYCL.cmake#L68) and the documentation pull request has been updated accordingly.

As the patch to correct this issue has been merged and all that is remaining is for the documentation update to be approved, we believe this ticket to be resolved, and are therefore closing it. If this issue appears again or there is further work to do please comment and we can re-open the ticket.

**Closed by AerialMantis** 2021-12-06 17:17 UTC
Labels: bug, cuda, compiler
