### ISSUE TITLE
failing SYCL tests

### ISSUE THREAD

**Issue by ce107** [intel/llvm#1412] opened 2020-03-27 20:45 UTC
I built following the instructions on an Ubuntu 18.04LTS system with CUDA 10.2 (I did get a compilation giving a warning about that), V100 Nvidia GPUs (as well as Fiji class AMD ones). Various OpenCL versions included in the system configuration (including AMD ROCm and Intel Studio 2019 CPU one) but the only way I could get things to build was to ask the build system to download and install its own OpenCL. I did have to tinker with cmake a bit before the compile step but compilation proceeded fine. However ninja check-all was a disaster when it came to testing - I am showing a characteristic error towards the end:

```
********************
FAIL: SYCL :: basic_tests/handler/handler_mem_op.cpp (54614 of 54614)
******************** TEST 'SYCL :: basic_tests/handler/handler_mem_op.cpp' FAILED ********************
Script:
--
: 'RUN: at line 1';   /root/build/dpcpp/build/bin/clang --driver-mode=g++ -fsycl -fsycl-targets=spir64-unknown-linux-sycldevice /home/root/build/dpcpp/llvm/sycl/test/basic_tests/handler/handler_mem_op.cpp -o /home/root/build/dpcpp/build/tools/sycl/test/basic_tests/handler/Output/handler_mem_op.cpp.tmp.out
: 'RUN: at line 2';   env SYCL_DEVICE_TYPE=HOST /home/root/build/dpcpp/build/tools/sycl/test/basic_tests/handler/Output/handler_mem_op.cpp.tmp.out
: 'RUN: at line 3';   env SYCL_DEVICE_TYPE=CPU  /home/root/build/dpcpp/build/tools/sycl/test/basic_tests/handler/Output/handler_mem_op.cpp.tmp.out
: 'RUN: at line 4';    env SYCL_DEVICE_TYPE=GPU  /home/root/build/dpcpp/build/tools/sycl/test/basic_tests/handler/Output/handler_mem_op.cpp.tmp.out
--
Exit Code: -6

Command Output (stdout):
--
$ ":" "RUN: at line 1"
note: command had no output on stdout or stderr
$ "/root/build/dpcpp/build/bin/clang" "--driver-mode=g++" "-fsycl" "-fsycl-targets=spir64-unknown-linux-sycldevice" "/home/root/build/dpcpp/llvm/sycl/test/basic_tests/handler/handler_mem_op.cpp" "-o" "/home/root/build/dpcpp/build/tools/sycl/test/basic_tests/handler/Output/handler_mem_op.cpp.tmp.out"
note: command had no output on stdout or stderr
$ ":" "RUN: at line 2"
note: command had no output on stdout or stderr
$ "env" "SYCL_DEVICE_TYPE=HOST" "/home/root/build/dpcpp/build/tools/sycl/test/basic_tests/handler/Output/handler_mem_op.cpp.tmp.out"
# command output:
finish

$ ":" "RUN: at line 3"
note: command had no output on stdout or stderr
$ "env" "SYCL_DEVICE_TYPE=CPU" "/home/root/build/dpcpp/build/tools/sycl/test/basic_tests/handler/Output/handler_mem_op.cpp.tmp.out"
# command output:
finish

$ ":" "RUN: at line 4"
note: command had no output on stdout or stderr
$ "env" "SYCL_DEVICE_TYPE=GPU" "/home/root/build/dpcpp/build/tools/sycl/test/basic_tests/handler/Output/handler_mem_op.cpp.tmp.out"
# command stderr:
terminate called after throwing an instance of 'cl::sycl::runtime_error'
  what():  OpenCL API failed. OpenCL API returns: -30 (CL_INVALID_VALUE) -30 (CL_INVALID_VALUE)

error: command failed with exit status: -6

--

********************

Testing Time: 190.64s
********************
Failing Tests (269):
    Clang :: Driver/cuda-simple.cu
    SYCL :: aot/with-llvm-bc.cpp
    SYCL :: aot/with-llvm-bc.cpp
    SYCL :: basic_tests/access_to_subset.cpp
    SYCL :: basic_tests/access_to_subset.cpp
    SYCL :: basic_tests/accessor/accessor.cpp
    SYCL :: basic_tests/accessor/accessor.cpp
    SYCL :: basic_tests/boolean.cpp
    SYCL :: basic_tests/boolean.cpp
    SYCL :: basic_tests/buffer/buffer.cpp
    SYCL :: basic_tests/buffer/buffer.cpp
    SYCL :: basic_tests/buffer/buffer_dev_to_dev.cpp
    SYCL :: basic_tests/buffer/buffer_dev_to_dev.cpp
    SYCL :: basic_tests/buffer/buffer_full_copy.cpp
    SYCL :: basic_tests/buffer/buffer_interop.cpp
    SYCL :: basic_tests/buffer/buffer_interop.cpp
    SYCL :: basic_tests/buffer/reinterpret.cpp
    SYCL :: basic_tests/buffer/reinterpret.cpp
    SYCL :: basic_tests/buffer/subbuffer.cpp
    SYCL :: basic_tests/buffer/subbuffer.cpp
    SYCL :: basic_tests/buffer/subbuffer_interop.cpp
    SYCL :: basic_tests/buffer/subbuffer_interop.cpp
    SYCL :: basic_tests/compare_exchange_strong.cpp
    SYCL :: basic_tests/compare_exchange_strong.cpp
    SYCL :: basic_tests/device.cpp
    SYCL :: basic_tests/device_event.cpp
    SYCL :: basic_tests/device_event.cpp
    SYCL :: basic_tests/diagnostics/device-check.cpp
    SYCL :: basic_tests/diagnostics/device-check.cpp
    SYCL :: basic_tests/diagnostics/handler.cpp
    SYCL :: basic_tests/diagnostics/handler.cpp
    SYCL :: basic_tests/event_profiling_info.cpp
    SYCL :: basic_tests/event_profiling_info.cpp
    SYCL :: basic_tests/get_nonhost_devices.cpp
    SYCL :: basic_tests/get_nonhost_devices.cpp
    SYCL :: basic_tests/handler/handler_copy_with_offset.cpp
    SYCL :: basic_tests/handler/handler_copy_with_offset.cpp
    SYCL :: basic_tests/handler/handler_mem_op.cpp
    SYCL :: basic_tests/handler/handler_mem_op.cpp
    SYCL :: basic_tests/handler/interop_task.cpp
    SYCL :: basic_tests/handler/interop_task.cpp
    SYCL :: basic_tests/handler/run_on_host_intel.cpp
    SYCL :: basic_tests/image.cpp
    SYCL :: basic_tests/image.cpp
    SYCL :: basic_tests/image_accessor_readsampler.cpp
    SYCL :: basic_tests/image_accessor_readsampler.cpp
    SYCL :: basic_tests/image_accessor_readwrite.cpp
    SYCL :: basic_tests/image_accessor_readwrite.cpp
    SYCL :: basic_tests/image_array.cpp
    SYCL :: basic_tests/image_array.cpp
    SYCL :: basic_tests/image_constructors.cpp
    SYCL :: basic_tests/info.cpp
    SYCL :: basic_tests/info.cpp
    SYCL :: basic_tests/kernel_info.cpp
    SYCL :: basic_tests/kernel_info.cpp
    SYCL :: basic_tests/kernel_interop.cpp
    SYCL :: basic_tests/kernel_interop.cpp
    SYCL :: basic_tests/parallel_for_indexers.cpp
    SYCL :: basic_tests/parallel_for_indexers.cpp
    SYCL :: basic_tests/parallel_for_range.cpp
    SYCL :: basic_tests/parallel_for_range.cpp
    SYCL :: basic_tests/property_list.cpp
    SYCL :: basic_tests/queue.cpp
    SYCL :: basic_tests/queue.cpp
    SYCL :: basic_tests/sampler/sampler.cpp
    SYCL :: basic_tests/sampler/sampler.cpp
    SYCL :: basic_tests/scalar_vec_access.cpp
    SYCL :: basic_tests/scalar_vec_access.cpp
    SYCL :: basic_tests/set_arg_interop.cpp
    SYCL :: basic_tests/set_arg_interop.cpp
    SYCL :: basic_tests/stream/auto_flush.cpp
    SYCL :: basic_tests/stream/auto_flush.cpp
    SYCL :: basic_tests/stream/stream.cpp
    SYCL :: basic_tests/stream/stream.cpp
    SYCL :: basic_tests/subdevice.cpp
    SYCL :: basic_tests/swizzle_op.cpp
    SYCL :: basic_tests/swizzle_op.cpp
    SYCL :: basic_tests/sycl-namespace.cpp
    SYCL :: basic_tests/sycl-namespace.cpp
    SYCL :: basic_tests/vec_op.cpp
    SYCL :: basic_tests/vec_op.cpp
    SYCL :: basic_tests/vectors/vector_operators.cpp
    SYCL :: basic_tests/vectors/vector_operators.cpp
    SYCL :: basic_tests/vectors/vectors.cpp
    SYCL :: built-ins/nan.cpp
    SYCL :: built-ins/nan.cpp
    SYCL :: built-ins/printf.cpp
    SYCL :: built-ins/printf.cpp
    SYCL :: built-ins/scalar_common.cpp
    SYCL :: built-ins/scalar_common.cpp
    SYCL :: built-ins/scalar_geometric.cpp
    SYCL :: built-ins/scalar_geometric.cpp
    SYCL :: built-ins/scalar_integer.cpp
    SYCL :: built-ins/scalar_integer.cpp
    SYCL :: built-ins/scalar_math.cpp
    SYCL :: built-ins/scalar_math.cpp
    SYCL :: built-ins/scalar_relational.cpp
    SYCL :: built-ins/scalar_relational.cpp
    SYCL :: built-ins/vector_common.cpp
    SYCL :: built-ins/vector_common.cpp
    SYCL :: built-ins/vector_geometric.cpp
    SYCL :: built-ins/vector_geometric.cpp
    SYCL :: built-ins/vector_integer.cpp
    SYCL :: built-ins/vector_integer.cpp
    SYCL :: built-ins/vector_math.cpp
    SYCL :: built-ins/vector_math.cpp
    SYCL :: built-ins/vector_relational.cpp
    SYCL :: built-ins/vector_relational.cpp
    SYCL :: device-code-split/aot-cpu.cpp
    SYCL :: device-code-split/split-per-kernel.cpp
    SYCL :: device-code-split/split-per-kernel.cpp
    SYCL :: device-code-split/split-per-source-main.cpp
    SYCL :: device-code-split/split-per-source-main.cpp
    SYCL :: fpga_tests/fpga_pipes.cpp
    SYCL :: fpga_tests/fpga_pipes.cpp
    SYCL :: fpga_tests/fpga_queue.cpp
    SYCL :: fpga_tests/fpga_queue.cpp
    SYCL :: fpga_tests/pipes_info.cpp
    SYCL :: fpga_tests/pipes_info.cpp
    SYCL :: function-pointers/fp-as-kernel-arg.cpp
    SYCL :: function-pointers/fp-as-kernel-arg.cpp
    SYCL :: function-pointers/pass-fp-through-buffer.cpp
    SYCL :: function-pointers/pass-fp-through-buffer.cpp
    SYCL :: functor/kernel_functor.cpp
    SYCL :: functor/kernel_functor.cpp
    SYCL :: group-algorithm/all_of.cpp
    SYCL :: group-algorithm/all_of.cpp
    SYCL :: group-algorithm/any_of.cpp
    SYCL :: group-algorithm/any_of.cpp
    SYCL :: group-algorithm/broadcast.cpp
    SYCL :: group-algorithm/broadcast.cpp
    SYCL :: group-algorithm/exclusive_scan.cpp
    SYCL :: group-algorithm/exclusive_scan.cpp
    SYCL :: group-algorithm/inclusive_scan.cpp
    SYCL :: group-algorithm/inclusive_scan.cpp
    SYCL :: group-algorithm/leader.cpp
    SYCL :: group-algorithm/leader.cpp
    SYCL :: group-algorithm/none_of.cpp
    SYCL :: group-algorithm/none_of.cpp
    SYCL :: group-algorithm/reduce.cpp
    SYCL :: group-algorithm/reduce.cpp
    SYCL :: hier_par/hier_par_basic.cpp
    SYCL :: hier_par/hier_par_basic.cpp
    SYCL :: hier_par/hier_par_wgscope.cpp
    SYCL :: hier_par/hier_par_wgscope.cpp
    SYCL :: kernel-and-program/kernel-and-program.cpp
    SYCL :: kernel-and-program/kernel-and-program.cpp
    SYCL :: kernel_from_file/hw.cpp
    SYCL :: kernel_from_file/hw.cpp
    SYCL :: linear_id/linear-sub_group.cpp
    SYCL :: linear_id/linear-sub_group.cpp
    SYCL :: linear_id/opencl-interop.cpp
    SYCL :: linear_id/opencl-interop.cpp
    SYCL :: multi_ptr/multi_ptr.cpp
    SYCL :: multi_ptr/multi_ptr.cpp
    SYCL :: multisource/multisource.cpp
    SYCL :: multisource/multisource.cpp
    SYCL :: ordered_queue/oq_kernels.cpp
    SYCL :: ordered_queue/oq_kernels.cpp
    SYCL :: ordered_queue/ordered_buffs.cpp
    SYCL :: ordered_queue/ordered_buffs.cpp
    SYCL :: ordered_queue/ordered_dmemll.cpp
    SYCL :: ordered_queue/ordered_dmemll.cpp
    SYCL :: ordered_queue/prop.cpp
    SYCL :: ordered_queue/prop.cpp
    SYCL :: program_manager/env_vars.cpp
    SYCL :: program_manager/env_vars.cpp
    SYCL :: program_manager/program_manager.cpp
    SYCL :: program_manager/program_manager.cpp
    SYCL :: regression/fp16-with-unnamed-lambda.cpp
    SYCL :: regression/fp16-with-unnamed-lambda.cpp
    SYCL :: regression/group.cpp
    SYCL :: regression/group.cpp
    SYCL :: regression/image_access.cpp
    SYCL :: regression/image_access.cpp
    SYCL :: regression/kernel_name_class.cpp
    SYCL :: regression/kernel_name_class.cpp
    SYCL :: regression/kernel_name_inside_sycl_namespace.cpp
    SYCL :: regression/kernel_name_inside_sycl_namespace.cpp
    SYCL :: regression/kernel_unnamed.cpp
    SYCL :: regression/kernel_unnamed.cpp
    SYCL :: regression/same_unnamed_kernels.cpp
    SYCL :: regression/same_unnamed_kernels.cpp
    SYCL :: regression/static-buffer-dtor.cpp
    SYCL :: regression/static-buffer-dtor.cpp
    SYCL :: regression/usm_malloc_shared.cpp
    SYCL :: regression/usm_malloc_shared.cpp
    SYCL :: scheduler/BasicSchedulerTests.cpp
    SYCL :: scheduler/BasicSchedulerTests.cpp
    SYCL :: scheduler/DataMovement.cpp
    SYCL :: scheduler/DataMovement.cpp
    SYCL :: scheduler/ReleaseResourcesTest.cpp
    SYCL :: scheduler/ReleaseResourcesTest.cpp
    SYCL :: separate-compile/same-kernel.cpp
    SYCL :: separate-compile/same-kernel.cpp
    SYCL :: separate-compile/sycl-external.cpp
    SYCL :: separate-compile/sycl-external.cpp
    SYCL :: separate-compile/test.cpp
    SYCL :: separate-compile/test.cpp
    SYCL :: struct_param/non-standard-layout.cpp
    SYCL :: struct_param/non-standard-layout.cpp
    SYCL :: sub_group/barrier.cpp
    SYCL :: sub_group/barrier.cpp
    SYCL :: sub_group/broadcast.cpp
    SYCL :: sub_group/broadcast.cpp
    SYCL :: sub_group/common.cpp
    SYCL :: sub_group/common.cpp
    SYCL :: sub_group/common_ocl.cpp
    SYCL :: sub_group/common_ocl.cpp
    SYCL :: sub_group/info.cpp
    SYCL :: sub_group/info.cpp
    SYCL :: sub_group/load_store.cpp
    SYCL :: sub_group/load_store.cpp
    SYCL :: sub_group/reduce.cpp
    SYCL :: sub_group/reduce.cpp
    SYCL :: sub_group/scan.cpp
    SYCL :: sub_group/scan.cpp
    SYCL :: sub_group/vote.cpp
    SYCL :: sub_group/vote.cpp
    SYCL :: usm/allocator_vector.cpp
    SYCL :: usm/allocator_vector.cpp
    SYCL :: usm/allocator_vector_fail.cpp
    SYCL :: usm/allocator_vector_fail.cpp
    SYCL :: usm/allocatorll.cpp
    SYCL :: usm/allocatorll.cpp
    SYCL :: usm/badmalloc.cpp
    SYCL :: usm/badmalloc.cpp
    SYCL :: usm/depends_on.cpp
    SYCL :: usm/depends_on.cpp
    SYCL :: usm/dmemll.cpp
    SYCL :: usm/dmemll.cpp
    SYCL :: usm/dmemllaligned.cpp
    SYCL :: usm/dmemllaligned.cpp
    SYCL :: usm/hmemll.cpp
    SYCL :: usm/hmemll.cpp
    SYCL :: usm/hmemllaligned.cpp
    SYCL :: usm/hmemllaligned.cpp
    SYCL :: usm/memadvise.cpp
    SYCL :: usm/memadvise.cpp
    SYCL :: usm/memcpy.cpp
    SYCL :: usm/memcpy.cpp
    SYCL :: usm/memset.cpp
    SYCL :: usm/memset.cpp
    SYCL :: usm/mixed.cpp
    SYCL :: usm/mixed.cpp
    SYCL :: usm/mixed2.cpp
    SYCL :: usm/mixed2.cpp
    SYCL :: usm/mixed2template.cpp
    SYCL :: usm/mixed2template.cpp
    SYCL :: usm/mixed_queue.cpp
    SYCL :: usm/mixed_queue.cpp
    SYCL :: usm/multictxt.cpp
    SYCL :: usm/multictxt.cpp
    SYCL :: usm/pfor_flatten.cpp
    SYCL :: usm/pfor_flatten.cpp
    SYCL :: usm/queue_wait.cpp
    SYCL :: usm/queue_wait.cpp
    SYCL :: usm/smemll.cpp
    SYCL :: usm/smemll.cpp
    SYCL :: usm/smemllaligned.cpp
    SYCL :: usm/smemllaligned.cpp
    SYCL-Unit :: scheduler/./SchedulerTests/SchedulerTest.BlockedCommands
    SYCL-Unit :: scheduler/./SchedulerTests/SchedulerTest.BlockedCommands
    SYCL-Unit :: scheduler/./SchedulerTests/SchedulerTest.FinishedCmdCleanup
    SYCL-Unit :: scheduler/./SchedulerTests/SchedulerTest.FinishedCmdCleanup
    SYCL-Unit :: scheduler/./SchedulerTests/SchedulerTest.LeafLimit
    SYCL-Unit :: scheduler/./SchedulerTests/SchedulerTest.LeafLimit
    SYCL-Unit :: scheduler/./SchedulerTests/SchedulerTest.MemObjCommandCleanup
    SYCL-Unit :: scheduler/./SchedulerTests/SchedulerTest.MemObjCommandCleanup

  Expected Passes    : 38407
  Expected Failures  : 90
  Unsupported Tests  : 15848
  Unexpected Failures: 269
FAILED: CMakeFiles/check-all 
cd /root/build/dpcpp/build && /usr/bin/python /root/build/dpcpp/build/./bin/llvm-lit -v -v --verbose -sv --param clang_site_config=/root/build/dpcpp/build/tools/clang/test/lit.site.cfg --param USE_Z3_SOLVER=0 --param SYCL_BE=PI_OPENCL --param SYCL_BE=PI_CUDA /root/build/dpcpp/build/tools/clang/test /root/build/dpcpp/build/tools/sycl/test /root/build/dpcpp/build/tools/sycl/test /root/build/dpcpp/build/tools/llvm-spirv/test /root/build/dpcpp/build/utils/lit /root/build/dpcpp/build/test
ninja: build stopped: subcommand failed.
```
I tested things separately:

```
root@css-host-6:/root/build/dpcpp/build# /home/root/build/dpcpp/build/tools/sycl/test/basic_tests/handler/Output/handler_mem_op.cpp.tmp.out
Segmentation fault (core dumped)
root@css-host-6:/root/build/dpcpp/build# env SYCL_DEVICE_TYPE=GPU /home/root/build/dpcpp/build/tools/sycl/test/basic_tests/handler/Output/handler_mem_op.cpp.tmp.out 
Segmentation fault (core dumped)
root@css-host-6:/root/build/dpcpp/build# env SYCL_DEVICE_TYPE=host /home/root/build/dpcpp/build/tools/sycl/test/basic_tests/handler/Output/handler_mem_op.cpp.tmp.out
Segmentation fault (core dumped)
root@css-host-6:/root/build/dpcpp/build# env SYCL_DEVICE_TYPE=CPU /home/root/build/dpcpp/build/tools/sycl/test/basic_tests/handler/Output/handler_mem_op.cpp.tmp.out 
Segmentation fault (core dumped)
```
Just to make sure I was not hitting a problem because of the compilation looking at [issue 1240](https://github.com/intel/llvm/issues/1240)  I proceeded to build 
https://github.com/codeplaysoftware/computecpp-sdk/blob/master/samples/example-sycl-application.cpp
```
ce107@css-host-6:~/projects/SYCL/computecpp-sdk/samples$ /opt/dpcpp/bin/clang++ -O2 -g -Wno-unknown-cuda-version -fsycl -fsycl-targets=nvptx64-nvidia-cuda-sycldevice -Xsycl-target-backend=nvptx64-nvidia-cuda-sycldevice '--cuda-gpu-arch=sm_70' --cuda-path=/usr/local/cuda  example-sycl-application.cpp -o example-sycl-application
ce107@css-host-6:~/projects/SYCL/computecpp-sdk/samples$ LD_LIBRARY_PATH=/opt/dpcpp/lib ./example-sycl-application 
Segmentation fault (core dumped)
ce107@css-host-6:~/projects/SYCL/computecpp-sdk/samples$ LD_LIBRARY_PATH=/opt/dpcpp/lib SYCL_DEVICE_TYPE=GPU ./example-sycl-application 
Segmentation fault (core dumped)
ce107@css-host-6:~/projects/SYCL/computecpp-sdk/samples$ LD_LIBRARY_PATH=/opt/dpcpp/lib SYCL_DEVICE_TYPE=host ./example-sycl-application 
Segmentation fault (core dumped)
ce107@css-host-6:~/projects/SYCL/computecpp-sdk/samples$ LD_LIBRARY_PATH=/opt/dpcpp/lib SYCL_DEVICE_TYPE=CPU ./example-sycl-application 
Segmentation fault (core dumped)
```

**Comment by bader** [comment] 2020-03-30 09:13
I think we should work towards improving two things here:
1. Error diagnostics. The error message like 
```
terminate called after throwing an instance of 'cl::sycl::runtime_error'
  what():  OpenCL API failed. OpenCL API returns: -30 (CL_INVALID_VALUE) -30 (CL_INVALID_VALUE)

error: command failed with exit status: -6
```
 doesn't help much to understand what is the problem and how to fix it. @Ruyk, @romanovvlad, @smaslov-intel, can we improve the error message?
2. We need improve LIT testing infrastructure to make it more predictable i.e. provide developers control over the testing configuration. I think this problem deserves a separate issue.

**Comment by Ruyk** [comment] 2020-04-01 16:04
I think the problem is related to device selection, sometimes it picks up the wrong plugin for a given device. We have hit this problem in some configurations, @ce107  is it possible for you to disable the NVIDIA OpenCL from the system and try again? Removing the nvidia.icd from `/etc/OpenCL/vendors` should be enough.

Also, I think we need some mechanism that ensures the plugin used for a certain PI function matches the expected plugin where the arguments are used. This may be as simple as an assert on all functions, but adding it manually could be cumbersome, maybe some helper function?

**Comment by hiaselhans** [comment] 2020-04-02 11:12
I experienced the same with an NVIDIA and non-intel cpu.
setting `static constexpr int DbgProgMgr` in `program_manager.cpp` reveals that when compiling for spirv- and nptx-target it always picks the spirv-pi-plugin though the CUDA device was selected:

```
>>> ProgramManager::getOrCreateKernel(-1, 0x23d73e0, _ZTSZZ4mainENK3$_0clERN2cl4sycl7handlerEE10FillBuffer)
>>> ProgramManager::getDeviceImage(-1, "2", 0x23d73e0)
available device images:
  ++++++ Kernel set: 2
  --- Image 0x410f60
    Version  : 2
    Kind     : 4
    Format   : 0
    Target   : spir64
    Bin size : 15400
    Compile options : 
    Link options    : 
    Entries  : _ZTSZZ4mainENK3$_0clERN2cl4sycl7handlerEE10FillBuffer 
    Properties [0x410f20-0x410f38]:
      Category SYCL/specialization constants [0-0]:
    OSModuleHandle=-1
  ++++++ Kernel set: 1
  --- Image 0x410e30
    Version  : 2
    Kind     : 4
    Format   : 0
    Target   : nvptx64
    Bin size : 3024
    Compile options : 
    Link options    : 
    Entries  : 
    Properties [0-0]:
    OSModuleHandle=-1
selected device image: 0x410f60
  --- Image 0x410f60
    Version  : 2
    Kind     : 4
    Format   : 0
    Target   : spir64
    Bin size : 15400
    Compile options : 
    Link options    : 
    Entries  : _ZTSZZ4mainENK3$_0clERN2cl4sycl7handlerEE10FillBuffer 
    Properties [0x410f20-0x410f38]:
      Category SYCL/specialization constants [0-0]:
    OSModuleHandle=-1
>>> ProgramManager::createPIProgram(0x23d6130)
terminate called after throwing an instance of 'cl::sycl::feature_not_supported'
  what():  Online compilation is not supported in this context -59 (CL_INVALID_OPERATION)
```
removing the nvidia.icd doesn't change it.
I will look into it more this afternoon, but it feels like something isn't yet working as it should in my configuration.

**Comment by Ruyk** [comment] 2020-06-08 11:52
Is this still a problem? We have fixed the accidental OpenCl device selection for the CUDA backend, and cleaned up the outcome of lit testing.
Building for multiple targets is not supported, but the outcome of lit test and building the example shouldn't be affected.

**Comment by ce107** [comment] 2020-06-08 14:48
Thanks for working on this. I will try again once I can fix my system which was broken recently due to an update.

**Comment by bader** [comment] 2020-06-29 17:55
@ce107, I suggest we close the issue and re-open if you have encounter any problems with the fix on your side.
Are you okay with that?

**Comment by romanovvlad** [comment] 2020-07-22 12:42
Please, reopen if you still have some issues with the fix.

**Closed by romanovvlad** 2020-07-22 12:42 UTC
Labels: cuda
