### ISSUE TITLE
sycl::ctz seems to be missing from the implementation

### ISSUE THREAD

**Issue by AlexeySachkov** [intel/llvm#4451] opened 2021-09-01 12:56 UTC
### Discussed in https://github.com/intel/llvm/discussions/4450

<div type='discussions-op-text'>

<sup>Originally posted by **zjin-lcf** September  1, 2021</sup>
With the latest build, the compiler shows the message:

error: no member named 'ctz' in namespace 'sycl'; did you mean 'clz'?

Thanks
</div>

Note: the built-in is documented by SYCL 2020 spec in section [4.17.6. Integer functions](https://www.khronos.org/registry/SYCL/specs/sycl-2020/html/sycl-2020.html#_integer_functions)

@yuriykoch, @bader, seems like a gap in SYCL-CTS testing if we haven't found this ourselves

**Comment by bader** [comment] 2021-09-01 13:02
FYI: `ctz` has been introduced with SYCL 2020 version and CTS for this version is still under development.

**Comment by AlexeySachkov** [comment] 2021-09-01 13:13
@zjin-lcf, I've just realized that we have already implemented `ctz`, but only as `sycl::ext::intel::ctz` - you can try using it for now as a workaround

**Comment by zjin-lcf** [comment] 2021-09-01 14:29
Thanks!

**Comment by zjin-lcf** [comment] 2021-09-08 14:31
I find that it is sycl::intel::ctz in the oneAPI toolkit 2021.3

**Comment by vladimirlaz** [comment] 2022-02-07 07:51
Tthe fix for the issue is available in https://github.com/intel/llvm/pull/5223 and https://github.com/intel/llvm/pull/5333.
Close the issue.

**Closed by vladimirlaz** 2022-02-07 07:51 UTC
Labels: bug, good first issue
