### ISSUE TITLE
Definition of Compute Unit

### ISSUE THREAD

**Issue by al42and** [intel/llvm#6313] opened 2022-06-15 16:53 UTC
**Describe the bug**

Per SYCL spec,

> The SYCL work-group (`sycl::group` class) is a representation of a collection of related work items that execute on a single compute unit.

Here are the results of querying `sycl::info::device::max_compute_units` on Intel and NVIDIA devices:

- Intel Xe MAX: 96
- NVIDIA GTX 1660 SUPER: 22

For the NVIDIA device, the number of SMs is returned, which is consistent with the compute unit definition (all threads in a workgroup/block are executed on the same SM),

For Intel, however, the call returns the number of EUs (XVEs in new terminology). That's not right, because usually not all work-items in a workgroup are executed on the same EU.

According to [Intel Iris Xe GPU Architecture page](https://www.intel.com/content/www/us/en/develop/documentation/oneapi-gpu-optimization-guide/top/xe-arch.html), subslice looks like a better fit for the "compute unit' definition.

**Additional context**

I understand that the current behavior is consistent with how Intel OpenCL behaves. However, it seems to violate the spec, so at least a notice should be added to the docs.

**Comment by AlexeySachkov** [comment] 2022-12-12 11:02
Hi @al42and,

We have discussed this internally and decided that we would prefer the spec to be clarified first before updated our implementation and/or documentation.

Once KhronosGroup/SYCL-Docs#329 is resolved, we will proceed with changes on our side (if those would be necessary). Please look for updates there.

I will close this one for now, because there are no changes expected to be done in short-/medium-term. Moreover, the value described in the issue is not produced by SYCL RT, but it is produced by [NEO](https://github.com/intel/compute-runtime). SYCL RT simply propagates whatever it got from low-level runtime. If you are still interested in a clarification, please submit an issue against NEO runtime.

**Closed by AlexeySachkov** 2022-12-12 11:02 UTC
Labels: bug

**Comment by al42and** [comment] 2022-12-12 16:12
> Moreover, the value described in the issue is not produced by SYCL RT, but it is produced by [NEO](https://github.com/intel/compute-runtime). SYCL RT simply propagates whatever it got from low-level runtime.

I don't argue with that. NEO can return whatever it wants, but here, we have the standard which prescribes what `sycl::info::device::max_compute_units` should return.

Updating the definition in the standard is indeed one way to deal with it, so I'm ok with closing this issue.
